//! Codegen for the guest `libcuda.so.1` shim: turn `registry/cuda_driver.manifest` into the complete
//! `#[no_mangle] extern "C"` `cu*` export surface (132 entry points).
//!
//! Every entry point NOT hand-written in `src/driver.rs` (`IMPLEMENTED` below) is emitted here as a
//! spec-faithful default stub: correct C-ABI signature (so the symbol resolves and the guest app links +
//! runs), a `HL_SHIM_DEBUG`-gated once-per-name trace, and a benign `CUDA_SUCCESS` (0) return. Real
//! bodies replace stubs without ever changing the exported surface. Ported from the shipping
//! `hl-shim-cuda/build.rs` (capability-inventory codegen dropped — this is the transport-wired template).
//!
//! Also bakes the shared-object soname `libcuda.so.1` (the CUDA Driver API drop-in name).

use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(BuildEnvironment::get("CARGO_MANIFEST_DIR"))
        .join("registry/cuda_driver.manifest");
    println!("cargo:rerun-if-changed={}", manifest.display());
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rustc-cdylib-link-arg=-Wl,-soname,libcuda.so.1");

    let text = std::fs::read_to_string(&manifest)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest.display()));

    let mut out = String::new();
    out.push_str("// @generated by build.rs from registry/cuda_driver.manifest — DO NOT EDIT.\n\n");

    let mut cu = 0usize;
    let mut stubs = 0usize;
    for (lineno, line) in text.lines().enumerate() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut f = line.split('\t');
        let lib = f.next().unwrap_or("");
        let name = f.next().unwrap_or("");
        let ret = f.next().unwrap_or("void");
        let params = f.next().unwrap_or("");
        if name.is_empty() {
            panic!("manifest line {}: empty name: {line:?}", lineno + 1);
        }
        match lib {
            "CU" => cu += 1,
            other => panic!("manifest line {}: unknown lib {other:?}", lineno + 1),
        }
        if IMPLEMENTED.contains(&name) {
            continue; // hand-written in src/driver.rs; a generated stub would collide.
        }
        stubs += 1;
        Generator::emit_stub(&mut out, name, ret, params);
    }

    writeln!(
        out,
        "\n/// Total CUDA Driver API entry points in the manifest (the exported surface)."
    )
    .unwrap();
    writeln!(out, "pub const CUDA_DRIVER_ENTRYPOINTS: usize = {cu};").unwrap();
    writeln!(
        out,
        "/// Entry points emitted as default stubs (not yet hand-implemented)."
    )
    .unwrap();
    writeln!(out, "pub const GENERATED_STUBS: usize = {stubs};").unwrap();
    writeln!(
        out,
        "/// Entry points with real hand-written bodies in `src/driver.rs`."
    )
    .unwrap();
    writeln!(
        out,
        "pub const IMPLEMENTED_ENTRYPOINTS: usize = {};",
        IMPLEMENTED.len()
    )
    .unwrap();

    let out_path = PathBuf::from(BuildEnvironment::get("OUT_DIR")).join("generated_entrypoints.rs");
    std::fs::write(&out_path, out).unwrap();
}

struct Generator;
impl Generator {
    fn emit_stub(out: &mut String, name: &str, ret: &str, params: &str) {
        let mut sig = String::new();
        let mut argnames = Vec::new();
        if !params.is_empty() {
            for (i, p) in params.split(';').enumerate() {
                let (ty, pname) = p
                    .split_once('|')
                    .unwrap_or_else(|| panic!("bad param {p:?} in {name}"));
                let rty = Binding::new(ty.trim(), name).rust_type();
                let pn = Signature::parameter(pname.trim(), i);
                if i > 0 {
                    sig.push_str(", ");
                }
                write!(sig, "{pn}: {rty}").unwrap();
                argnames.push(pn);
            }
        }
        let rmap = Binding::new(ret.trim(), name).return_type();
        let arrow = rmap
            .as_ref()
            .map(|r| format!(" -> {r}"))
            .unwrap_or_default();
        let touch: String = argnames.iter().map(|a| format!("let _ = {a}; ")).collect();
        let body = match &rmap {
            None => format!("{touch}crate::stub::Stub::hit(\"{name}\");"),
            Some(r) => format!(
                "{touch}crate::stub::Stub::hit(\"{name}\"); {}",
                Binding::default_value(r)
            ),
        };
        writeln!(
            out,
            "#[no_mangle]\npub extern \"C\" fn {name}({sig}){arrow} {{ {body} }}\n"
        )
        .unwrap();
    }
}

struct Binding<'a> {
    c: &'a str,
    context: &'a str,
}
impl<'a> Binding<'a> {
    fn new(c: &'a str, context: &'a str) -> Self {
        Self { c, context }
    }
    fn return_type(&self) -> Option<String> {
        if self.c == "void" {
            return None;
        }
        Some(self.rust_type())
    }

    fn rust_type(&self) -> String {
        let c = self.c.trim();
        if let Some(base) = c.strip_suffix("*const*") {
            return format!("*const *const {}", Self::pointee(base, self.context));
        }
        if let Some(base) = c.strip_suffix("**") {
            return format!("*mut *mut {}", Self::pointee(base, self.context));
        }
        if let Some(base) = c.strip_suffix('*') {
            let is_const = base.trim_start().starts_with("const ");
            let q = if is_const { "*const" } else { "*mut" };
            return format!("{q} {}", Self::pointee(base, self.context));
        }
        Self::scalar(c, self.context).to_string()
    }

    fn pointee(base: &str, context: &str) -> String {
        let b = base.trim();
        let b = b.strip_prefix("const ").unwrap_or(b).trim();
        Self::scalar(b, context).to_string()
    }

    fn scalar(c: &str, context: &str) -> &'static str {
        match c {
            "void" => "core::ffi::c_void",
            "char" => "core::ffi::c_char",
            "float" => "f32",
            "int" => "i32",
            "unsigned char" => "u8",
            "unsigned short" => "u16",
            "unsigned int" | "cuuint32_t" => "u32",
            "unsigned long" => "u64",
            "unsigned long long" | "cuuint64_t" => "u64",
            "size_t" => "usize",
            "CUdeviceptr" => "u64",
            "CUresult"
            | "CUdevice"
            | "CUdevice_attribute"
            | "CUlimit"
            | "CUfunc_cache"
            | "CUsharedconfig"
            | "CUpointer_attribute"
            | "CUfunction_attribute"
            | "CUjit_option"
            | "CUmoduleLoadingMode"
            | "CUdriverProcAddressQueryResult" => "i32",
            "CUcontext" | "CUmodule" | "CUfunction" | "CUstream" | "CUevent" | "CUtexref"
            | "CUsurfref" | "CUhostFn" | "CUstreamCallback" | "CUoccupancyB2DSize" => {
                "*mut core::ffi::c_void"
            }
            "CUdevprop" | "CUuuid" | "CUlaunchConfig" => "core::ffi::c_void",
            other => {
                panic!("unmapped C base type {other:?} (in {context}); extend scalar() in build.rs")
            }
        }
    }

    fn default_value(rust_ty: &str) -> &'static str {
        if rust_ty.starts_with("*const") {
            "core::ptr::null()"
        } else if rust_ty.starts_with("*mut") {
            "core::ptr::null_mut()"
        } else {
            "0" // CUDA_SUCCESS for the CUresult all driver entry points return.
        }
    }
}

struct Signature;
impl Signature {
    fn parameter(name: &str, i: usize) -> String {
        const KW: &[&str] = &[
            "type", "ref", "box", "in", "fn", "let", "match", "move", "mut", "as", "impl", "loop",
            "where", "self", "final", "override", "become",
        ];
        if name.is_empty() {
            return format!("a{i}");
        }
        if KW.contains(&name) {
            return format!("{name}_");
        }
        name.to_string()
    }
}

struct BuildEnvironment;
impl BuildEnvironment {
    fn get(key: &str) -> String {
        std::env::var(key).unwrap_or_else(|_| panic!("env {key} not set"))
    }
}

/// Entry points hand-written in `src/driver.rs` (the generator skips them to avoid duplicate symbols):
/// the bring-up set (init / driver-version / error strings / device presence / context basics) and the
/// IR-wired compute set (memory alloc/copy, PTX module load, kernel launch, stream/event sync) that
/// marshals C args and calls the `hl_cuda` lowering services through the process-global RemoteCommandSink.
const IMPLEMENTED: &[&str] = &[
    // bring-up
    "cuInit",
    "cuDriverGetVersion",
    "cuGetErrorString",
    "cuGetErrorName",
    "cuDeviceGetCount",
    "cuDeviceGet",
    "cuDeviceGetName",
    "cuDeviceTotalMem_v2",
    "cuDeviceGetAttribute",
    "cuDeviceComputeCapability",
    "cuDeviceGetUuid",
    "cuDeviceGetUuid_v2",
    "cuCtxCreate_v2",
    "cuCtxDestroy_v2",
    "cuCtxSetCurrent",
    "cuCtxGetCurrent",
    "cuCtxGetDevice",
    "cuCtxSynchronize",
    // context management: push/pop stack, api version, flags
    "cuCtxPushCurrent_v2",
    "cuCtxPopCurrent_v2",
    "cuCtxGetApiVersion",
    "cuCtxGetFlags",
    "cuCtxSetFlags",
    // primary context (device 0): retain/release/reset ref-counting + state
    "cuDevicePrimaryCtxRetain",
    "cuDevicePrimaryCtxRelease_v2",
    "cuDevicePrimaryCtxReset_v2",
    "cuDevicePrimaryCtxGetState",
    "cuDevicePrimaryCtxSetFlags_v2",
    // memory info + pointer attributes
    "cuMemGetInfo_v2",
    "cuMemGetAddressRange_v2",
    "cuPointerGetAttribute",
    "cuPointerGetAttributes",
    // stream/event query + wait (synchronous-executor semantics)
    "cuEventRecordWithFlags",
    "cuEventQuery",
    "cuEventElapsedTime",
    "cuStreamQuery",
    "cuStreamWaitEvent",
    // IR-wired compute path
    "cuMemAlloc_v2",
    "cuMemFree_v2",
    "cuMemcpyHtoD_v2",
    "cuMemcpyDtoH_v2",
    "cuMemcpyDtoD_v2",
    // memory: host pinned/registered, managed, pitched
    "cuMemAllocHost_v2",
    "cuMemHostAlloc",
    "cuMemFreeHost",
    "cuMemHostRegister_v2",
    "cuMemHostUnregister",
    "cuMemHostGetDevicePointer_v2",
    "cuMemAllocManaged",
    "cuMemAllocPitch_v2",
    // memory: memset (sync + async) — lowers to WriteBuffer of the expanded pattern
    "cuMemsetD8_v2",
    "cuMemsetD16_v2",
    "cuMemsetD32_v2",
    "cuMemsetD8Async",
    "cuMemsetD16Async",
    "cuMemsetD32Async",
    // memory: stream-ordered copies
    "cuMemcpyHtoDAsync_v2",
    "cuMemcpyDtoHAsync_v2",
    "cuMemcpyDtoDAsync_v2",
    "cuModuleLoadData",
    "cuModuleGetFunction",
    // module: load variants, unload, global/texref/surfref, loading mode
    "cuModuleLoad",
    "cuModuleLoadDataEx",
    "cuModuleLoadFatBinary",
    "cuModuleUnload",
    "cuModuleGetGlobal_v2",
    "cuModuleGetLoadingMode",
    "cuModuleGetTexRef",
    "cuModuleGetSurfRef",
    // unified + peer copies (single-device model → device→device)
    "cuMemcpy",
    "cuMemcpyAsync",
    "cuMemcpyPeer",
    "cuMemcpyPeerAsync",
    "cuLaunchKernel",
    "cuLaunchKernelEx",
    "cuStreamCreate",
    "cuStreamDestroy_v2",
    "cuStreamSynchronize",
    "cuEventCreate",
    "cuEventRecord",
    "cuEventSynchronize",
    "cuEventDestroy_v2",
    // function attributes + cache config
    "cuFuncGetAttribute",
    "cuFuncSetAttribute",
    "cuFuncSetCacheConfig",
    // occupancy (computed from the modeled device limits + function resource use)
    "cuOccupancyMaxActiveBlocksPerMultiprocessor",
    "cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags",
    "cuOccupancyMaxPotentialBlockSize",
    "cuOccupancyMaxPotentialBlockSizeWithFlags",
    // stream getters: flags / priority / owning context / id
    "cuStreamGetFlags",
    "cuStreamGetPriority",
    "cuStreamGetCtx",
    "cuStreamGetId",
    // context limits + cache config + stream-priority range
    "cuCtxGetLimit",
    "cuCtxSetLimit",
    "cuCtxGetCacheConfig",
    "cuCtxSetCacheConfig",
    "cuCtxGetStreamPriorityRange",
    // device: peer access, PCI/LUID identity, legacy properties struct
    "cuDeviceCanAccessPeer",
    "cuDeviceGetByPCIBusId",
    "cuDeviceGetPCIBusId",
    "cuDeviceGetLuid", // honest NOT_SUPPORTED (LUID is Windows/TCC-only)
    "cuDeviceGetProperties",
    // context: v3 create, id, shared-mem config, peer access, persisting-L2 reset
    "cuCtxCreate_v3",
    "cuCtxGetId",
    "cuCtxGetSharedMemConfig",
    "cuCtxSetSharedMemConfig",
    "cuCtxEnablePeerAccess",  // honest PEER_ACCESS_UNSUPPORTED (no peers)
    "cuCtxDisablePeerAccess", // honest PEER_ACCESS_NOT_ENABLED
    "cuCtxResetPersistingL2Cache",
    // function: owning module, entry name, shared-mem config
    "cuFuncGetModule",
    "cuFuncGetName",
    "cuFuncSetSharedMemConfig",
    // entry-point dispatch (dlsym over this object's own cu* surface)
    "cuGetProcAddress",
    "cuGetProcAddress_v2",
    // launch: cooperative kernel + host callbacks
    "cuLaunchCooperativeKernel",
    "cuLaunchHostFunc",
    "cuStreamAddCallback",
    // memory: stream-ordered alloc/free, unified-memory hints, host flags, pointer set-attr
    "cuMemAllocAsync",
    "cuMemFreeAsync",
    "cuMemAdvise",
    "cuMemPrefetchAsync",
    "cuStreamAttachMemAsync",
    "cuMemHostGetFlags",
    "cuPointerSetAttribute",
    "cuOccupancyAvailableDynamicSMemPerBlock",
    // stream: priority create + capture status (capture unsupported → honest NONE)
    "cuStreamCreateWithPriority",
    "cuStreamIsCapturing",
    "cuThreadExchangeStreamCaptureMode",
    // profiler: deprecated collection controls (no host profiler → benign no-ops)
    "cuProfilerInitialize",
    "cuProfilerStart",
    "cuProfilerStop",
];
