//! dd-shim-gl codegen: turn the Khronos-registry-derived entry-point manifest into the complete set
//! of `#[no_mangle] extern "C"` GLES2+EGL exports the shim must provide.
//!
//! Input:  `registry/gles2_egl.manifest` (generated from gl.xml/egl.xml — see `registry/`).
//! Output: `$OUT_DIR/generated_entrypoints.rs`, `include!`d by `src/lib.rs`.
//!
//! For every entry point NOT hand-implemented in `src/` (`IMPLEMENTED` below), we emit a spec-faithful
//! *default* stub: correct C-ABI signature (so the symbol resolves and the app links + runs), a
//! debug-gated "unimplemented entry point" trace, and a benign default return. Real bodies replace
//! stubs incrementally without ever changing the exported surface.
//!
//! Also sets the shared-object soname to `libEGL.so.1` (the canonical GLES drop-in name).

use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env("CARGO_MANIFEST_DIR")).join("registry/gles2_egl.manifest");
    println!("cargo:rerun-if-changed={}", manifest.display());
    println!("cargo:rerun-if-changed=build.rs");

    // The shim is deployed as libEGL.so.1; bake that soname so the guest dynamic linker binds it under
    // the name apps `DT_NEEDED`. (libGLESv2.so.2 / libwayland-egl.so.1 are thin DT_NEEDED->libEGL
    // stubs created at deploy time; see docs/rendering/SHIM_RUST_ARCHITECTURE.md.)
    println!("cargo:rustc-cdylib-link-arg=-Wl,-soname,libEGL.so.1");

    let text = std::fs::read_to_string(&manifest)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest.display()));

    let mut out = String::new();
    out.push_str("// @generated by build.rs from registry/gles2_egl.manifest — DO NOT EDIT.\n");
    out.push_str("// (crate-level `#![allow(non_snake_case, ...)]` lives in src/lib.rs.)\n\n");

    let mut gl = 0usize;
    let mut egl = 0usize;
    let mut stubs = 0usize;
    for (lineno, line) in text.lines().enumerate() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut f = line.split('\t');
        let lib = f.next().unwrap_or("");
        let name = f.next().unwrap_or("");
        let ret = f.next().unwrap_or("void");
        let params = f.next().unwrap_or("");
        if name.is_empty() {
            panic!("manifest line {}: empty name: {line:?}", lineno + 1);
        }
        match lib {
            "GL" => gl += 1,
            "EGL" => egl += 1,
            other => panic!("manifest line {}: unknown lib {other:?}", lineno + 1),
        }
        if IMPLEMENTED.contains(&name) {
            continue; // hand-written in src/; a generated stub would collide.
        }
        stubs += 1;
        emit_stub(&mut out, name, ret, params);
    }

    // A compile-time census the crate can assert against (the completeness gate).
    writeln!(out, "\n/// Total GLES2 entry points in the manifest.").unwrap();
    writeln!(out, "pub const GLES2_ENTRYPOINTS: usize = {gl};").unwrap();
    writeln!(out, "/// Total EGL entry points in the manifest.").unwrap();
    writeln!(out, "pub const EGL_ENTRYPOINTS: usize = {egl};").unwrap();
    writeln!(out, "/// Entry points emitted as default stubs (not yet hand-implemented).").unwrap();
    writeln!(out, "pub const GENERATED_STUBS: usize = {stubs};").unwrap();

    let out_path = PathBuf::from(env("OUT_DIR")).join("generated_entrypoints.rs");
    std::fs::write(&out_path, out).unwrap();
}

fn emit_stub(out: &mut String, name: &str, ret: &str, params: &str) {
    let mut sig = String::new();
    let mut argnames = Vec::new();
    if !params.is_empty() {
        for (i, p) in params.split(';').enumerate() {
            let (ty, pname) = p.split_once('|').unwrap_or_else(|| panic!("bad param {p:?} in {name}"));
            let rty = map_type(ty.trim(), name);
            // Sanitize the param name (avoid Rust keywords / empties).
            let pn = sanitize(pname.trim(), i);
            if i > 0 {
                sig.push_str(", ");
            }
            write!(sig, "{pn}: {rty}").unwrap();
            argnames.push(pn);
        }
    }
    let rmap = map_ret(ret.trim(), name);
    let arrow = rmap.as_ref().map(|r| format!(" -> {r}")).unwrap_or_default();
    // Reference every argument so `unused_variables` stays quiet even without the allow (belt+braces).
    let touch: String = argnames.iter().map(|a| format!("let _ = {a}; ")).collect();
    let body = match &rmap {
        None => format!("{touch}crate::stub::hit(\"{name}\");"),
        Some(r) => {
            let dflt = default_for(r);
            format!("{touch}crate::stub::hit(\"{name}\"); {dflt}")
        }
    };
    writeln!(out, "#[no_mangle]\npub extern \"C\" fn {name}({sig}){arrow} {{ {body} }}\n").unwrap();
}

/// C return type -> Rust type (None == `void`/unit). Panics on an unknown type so an API bump surfaces
/// at build time rather than silently mis-typing the ABI.
fn map_ret(c: &str, ctx: &str) -> Option<String> {
    if c == "void" {
        return None;
    }
    Some(map_type(c, ctx))
}

/// C type string -> Rust C-ABI type. Handles the pointer forms generally (single/double, const/mut,
/// `*const*`) so an API bump only ever surprises us on a genuinely new *base scalar*, which panics
/// (fail-loud ABI generator) rather than silently mis-typing.
fn map_type(c: &str, ctx: &str) -> String {
    let c = c.trim();
    // pointer forms, longest suffix first
    if let Some(base) = c.strip_suffix("*const*") {
        return format!("*const *const {}", pointee(base, ctx));
    }
    if let Some(base) = c.strip_suffix("**") {
        // outer const-ness of `X **` params is not expressed in the registry surface; treat as mut.
        return format!("*mut *mut {}", pointee(base, ctx));
    }
    if let Some(base) = c.strip_suffix('*') {
        let is_const = base.trim_start().starts_with("const ");
        let q = if is_const { "*const" } else { "*mut" };
        return format!("{q} {}", pointee(base, ctx));
    }
    scalar(c, ctx).to_string()
}

/// The Rust type of a pointer's pointee (the base with any leading `const` stripped).
fn pointee(base: &str, ctx: &str) -> String {
    let b = base.trim();
    let b = b.strip_prefix("const ").unwrap_or(b).trim();
    scalar(b, ctx).to_string()
}

/// A bare (by-value) scalar / opaque-handle C type -> Rust. Opaque handles (`EGLDisplay`, `GLsync`,
/// EGLConfig, …) are `void*`-shaped, so a value-of-that-type is a `*mut c_void`.
fn scalar(c: &str, ctx: &str) -> &'static str {
    match c {
        "void" => "core::ffi::c_void", // only meaningful as a pointee; bare `void` -> map_ret == None
        "char" | "GLchar" => "core::ffi::c_char",
        "GLbyte" => "i8",
        "GLubyte" | "GLboolean" => "u8",
        "GLshort" => "i16",
        "GLushort" => "u16",
        "GLenum" | "GLbitfield" | "GLuint" | "EGLenum" | "EGLBoolean" => "u32",
        "GLint" | "GLsizei" | "GLfixed" | "EGLint" => "i32",
        "GLfloat" | "GLclampf" => "f32",
        "GLdouble" => "f64",
        "GLint64" => "i64",
        "GLuint64" | "EGLTime" | "EGLTimeKHR" | "EGLuint64KHR" => "u64",
        "GLintptr" | "GLsizeiptr" | "EGLAttrib" => "isize",
        // opaque handles (all `void*`-shaped)
        "GLsync" | "GLDEBUGPROC" | "EGLClientBuffer" | "EGLContext" | "EGLDisplay" | "EGLImage"
        | "EGLImageKHR" | "EGLSurface" | "EGLSync" | "EGLSyncKHR" | "EGLConfig"
        | "EGLNativeDisplayType" | "EGLNativeWindowType" | "EGLNativePixmapType"
        | "__eglMustCastToProperFunctionPointerType" => "*mut core::ffi::c_void",
        other => panic!("unmapped C base type {other:?} (in {ctx}); extend scalar() in build.rs"),
    }
}

fn default_for(rust_ty: &str) -> &'static str {
    if rust_ty.starts_with("*const") {
        "core::ptr::null()"
    } else if rust_ty.starts_with("*mut") {
        "core::ptr::null_mut()"
    } else {
        "0"
    }
}

fn sanitize(name: &str, i: usize) -> String {
    const KW: &[&str] = &[
        "type", "ref", "box", "in", "fn", "let", "match", "move", "mut", "as", "impl", "loop",
        "where", "self", "final", "override", "become",
    ];
    if name.is_empty() {
        return format!("a{i}");
    }
    if KW.contains(&name) {
        return format!("{name}_");
    }
    name.to_string()
}

fn env(k: &str) -> String {
    std::env::var(k).unwrap_or_else(|_| panic!("env {k} not set"))
}

/// Entry points hand-implemented in `src/` (so the generator skips them to avoid duplicate symbols).
/// Grows as bodies are ported from the C shim; the generated surface shrinks correspondingly.
const IMPLEMENTED: &[&str] = &[
    // EGL: display/config/query bring-up (real bodies in src/egl.rs).
    "eglGetError",
    "eglQueryString",
    "eglGetDisplay",
    "eglInitialize",
    "eglGetProcAddress",
    // GLES: string/error queries (real bodies in src/gles.rs).
    "glGetError",
    "glGetString",
];
