//! dd-shim-gl codegen: turn the Khronos-registry-derived entry-point manifest into the complete set
//! of `#[no_mangle] extern "C"` GLES2+EGL exports the shim must provide, PLUS a generated capability
//! inventory that tags every exported symbol.
//!
//! Input:  `registry/gles2_egl.manifest` (generated from gl.xml/egl.xml — see `registry/`).
//! Output: `$OUT_DIR/generated_entrypoints.rs`, `include!`d by `src/lib.rs`.
//!
//! Every entry point is classified into one of three capability levels:
//!   - **full**    — hand-implemented in `src/` (`IMPLEMENTED` below): a real body at gl_shim.c parity.
//!   - **partial** — generated, but a spec-legitimate no-op / default-return (`PARTIAL` below): matches
//!     gl_shim.c's degraded behavior (queries return zeros/empty, optional state no-ops). Reports NO
//!     error, but ALWAYS initializes its output parameters.
//!   - **stub**    — generated, an operation a conforming driver performs and the shim does NOT: sets
//!     the API-correct GL/EGL error, zero-initializes every output, returns the spec failure value, and
//!     (under `DD_SHIM_STRICT`) aborts. NEVER a success-by-default.
//!
//! The classification and its per-symbol records are emitted as [`crate::CAPABILITIES`], the machine-
//! checkable inventory that keeps the exported surface and the completeness census in sync.
//!
//! Also sets the shared-object soname to `libEGL.so.1` (the canonical GLES drop-in name).

use std::fmt::Write as _;
use std::path::PathBuf;

/// Backed GL extensions the shim advertises via `glGetString(GL_EXTENSIONS)` / `glGetStringi` — the
/// exact set the gl_shim.c oracle advertises, each backed by a real body: BGRA8888 texture upload
/// (`tex_store_pixels`), immutable texture storage (`glTexStorage2D`, now full), RGBA8 renderbuffer
/// storage, NPOT textures, and multisample renderbuffers (`glRenderbufferStorageMultisample`). Driving
/// both string queries from this one list keeps `glGetString`/`glGetStringi`/`GL_NUM_EXTENSIONS`
/// mutually consistent (capability honesty; the audit flagged ad-hoc extension reporting).
const BACKED_GL_EXTENSIONS: &[&str] = &[
    "GL_EXT_texture_format_BGRA8888",
    "GL_APPLE_texture_format_BGRA8888",
    "GL_EXT_texture_storage",
    "GL_OES_rgb8_rgba8",
    "GL_OES_texture_npot",
    "GL_EXT_sRGB",
    "GL_EXT_sRGB_write_control",
    "GL_ANGLE_framebuffer_multisample",
    "GL_ANGLE_texture_usage",
];

/// The lowest coherent GLES profile the real bodies back. NOT ES3: the ES3 core additions (UBO
/// binding, transform feedback, fence sync, sampler objects, immutable/3D textures, MRT) are all
/// `stub`s, so advertising ES3 would be a false claim. ES3 stays an explicit `DD_SHIM_ES3` opt-in.
const ADVERTISED_GL_VERSION: &str = "OpenGL ES 2.0 dd-shim";
const ADVERTISED_GLSL_VERSION: &str = "OpenGL ES GLSL ES 1.00";
const ADVERTISED_GL_MAJOR: i32 = 2;
const ADVERTISED_GL_MINOR: i32 = 0;

fn main() {
    let manifest = PathBuf::from(env("CARGO_MANIFEST_DIR")).join("registry/gles2_egl.manifest");
    println!("cargo:rerun-if-changed={}", manifest.display());
    println!("cargo:rerun-if-changed=build.rs");

    // The shim is deployed as libEGL.so.1; bake that soname so the guest dynamic linker binds it under
    // the name apps `DT_NEEDED`. (libGLESv2.so.2 / libwayland-egl.so.1 are thin DT_NEEDED->libEGL
    // stubs created at deploy time; see docs/rendering/SHIM_RUST_ARCHITECTURE.md.)
    println!("cargo:rustc-cdylib-link-arg=-Wl,-soname,libEGL.so.1");

    let text = std::fs::read_to_string(&manifest)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest.display()));

    let mut out = String::new();
    out.push_str("// @generated by build.rs from registry/gles2_egl.manifest — DO NOT EDIT.\n");
    out.push_str("// (crate-level `#![allow(non_snake_case, ...)]` lives in src/lib.rs.)\n\n");

    let mut gl = 0usize;
    let mut egl = 0usize;
    let mut full = 0usize;
    let mut partial = 0usize;
    let mut stub = 0usize;
    let mut caps = String::new();

    for (lineno, line) in text.lines().enumerate() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut f = line.split('\t');
        let lib = f.next().unwrap_or("");
        let name = f.next().unwrap_or("");
        let ret = f.next().unwrap_or("void");
        let params = f.next().unwrap_or("");
        if name.is_empty() {
            panic!("manifest line {}: empty name: {line:?}", lineno + 1);
        }
        match lib {
            "GL" => gl += 1,
            "EGL" => egl += 1,
            other => panic!("manifest line {}: unknown lib {other:?}", lineno + 1),
        }

        let level = classify(name);
        match level {
            Level::Full => full += 1,
            Level::Partial => partial += 1,
            Level::Stub => stub += 1,
        }

        // Emit a body only for generated (non-full) entry points; full ones live in src/.
        if level != Level::Full {
            emit_entry(&mut out, lib, name, ret, params, level);
        }

        // Every exported symbol gets a capability record (the inventory is total — 402 rows).
        let gl_error = stub_error(lib, name, level);
        writeln!(
            caps,
            "    Capability {{ name: {name:?}, lib: {}, level: {}, since: {:?}, requirement: {:?}, gl_error: {gl_error:#06x} }},",
            cap_lib(lib),
            cap_level(level),
            since(lib, name, level),
            requirement(lib, name, level),
        )
        .unwrap();
    }

    // ---- the generated capability inventory (machine-checkable completeness census) ----
    out.push_str(CAP_TYPES);
    writeln!(out, "\n/// The generated capability inventory: one record per exported GLES2/EGL entry point,").unwrap();
    writeln!(out, "/// classifying it as `full` / `partial` / `stub` (see [`CapLevel`]). Generated by build.rs").unwrap();
    writeln!(out, "/// from registry/gles2_egl.manifest + the IMPLEMENTED/PARTIAL sets, so it can never drift").unwrap();
    writeln!(out, "/// from the exported surface. The `surface_is_complete_and_large` test asserts every").unwrap();
    writeln!(out, "/// exported symbol has exactly one record.").unwrap();
    writeln!(out, "pub const CAPABILITIES: &[Capability] = &[").unwrap();
    out.push_str(&caps);
    writeln!(out, "];").unwrap();

    // A compile-time census the crate can assert against (the completeness gate).
    writeln!(out, "\n/// Total GLES2 entry points in the manifest.").unwrap();
    writeln!(out, "pub const GLES2_ENTRYPOINTS: usize = {gl};").unwrap();
    writeln!(out, "/// Total EGL entry points in the manifest.").unwrap();
    writeln!(out, "pub const EGL_ENTRYPOINTS: usize = {egl};").unwrap();
    writeln!(out, "/// Entry points with a hand-written real body (`full`).").unwrap();
    writeln!(out, "pub const CAP_FULL: usize = {full};").unwrap();
    writeln!(out, "/// Entry points that are a spec-legitimate no-op / default query (`partial`).").unwrap();
    writeln!(out, "pub const CAP_PARTIAL: usize = {partial};").unwrap();
    writeln!(out, "/// Entry points that are unsupported truthful-failure stubs (`stub`).").unwrap();
    writeln!(out, "pub const CAP_STUB: usize = {stub};").unwrap();
    writeln!(out, "/// Entry points emitted by the generator (partial + stub) — everything not `full`.").unwrap();
    writeln!(out, "pub const GENERATED_STUBS: usize = {};", partial + stub).unwrap();

    // ---- inventory-driven advertisement (Phase 1.1): the lowest coherent GLES profile ----
    let ext_join = BACKED_GL_EXTENSIONS.join(" ");
    writeln!(out, "\n/// Advertised `glGetString(GL_VERSION)` — NUL-terminated for the C ABI.").unwrap();
    writeln!(out, "pub const ADVERTISED_GL_VERSION: &[u8] = b\"{ADVERTISED_GL_VERSION}\\0\";").unwrap();
    writeln!(out, "/// Advertised GL_VERSION as a Rust str (no NUL) — for tests/inventory.").unwrap();
    writeln!(out, "pub const ADVERTISED_GL_VERSION_STR: &str = {ADVERTISED_GL_VERSION:?};").unwrap();
    writeln!(out, "/// Advertised `glGetString(GL_SHADING_LANGUAGE_VERSION)` — NUL-terminated.").unwrap();
    writeln!(out, "pub const ADVERTISED_GLSL_VERSION: &[u8] = b\"{ADVERTISED_GLSL_VERSION}\\0\";").unwrap();
    writeln!(out, "/// Advertised GLSL version as a Rust str (no NUL).").unwrap();
    writeln!(out, "pub const ADVERTISED_GLSL_VERSION_STR: &str = {ADVERTISED_GLSL_VERSION:?};").unwrap();
    writeln!(out, "/// Advertised `glGetString(GL_EXTENSIONS)` — only host-backed extensions, NUL-terminated.").unwrap();
    writeln!(out, "pub const ADVERTISED_GL_EXTENSIONS: &[u8] = b\"{ext_join}\\0\";").unwrap();
    writeln!(out, "/// Advertised extension string as a Rust str (no NUL).").unwrap();
    writeln!(out, "pub const ADVERTISED_GL_EXTENSIONS_STR: &str = {ext_join:?};").unwrap();
    writeln!(out, "/// Number of advertised extensions (`glGetIntegerv(GL_NUM_EXTENSIONS)`).").unwrap();
    writeln!(out, "pub const ADVERTISED_GL_EXTENSION_COUNT: usize = {};", BACKED_GL_EXTENSIONS.len()).unwrap();
    writeln!(out, "/// The advertised extensions as individual NUL-terminated byte strings, for the indexed").unwrap();
    writeln!(out, "/// `glGetStringi(GL_EXTENSIONS, i)` query (kept in lockstep with the space-joined string above).").unwrap();
    write!(out, "pub const ADVERTISED_GL_EXTENSIONS_LIST: &[&[u8]] = &[").unwrap();
    for e in BACKED_GL_EXTENSIONS {
        write!(out, "b\"{e}\\0\", ").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out, "/// Advertised GLES major version (the coherent profile).").unwrap();
    writeln!(out, "pub const ADVERTISED_GL_MAJOR: i32 = {ADVERTISED_GL_MAJOR};").unwrap();
    writeln!(out, "/// Advertised GLES minor version.").unwrap();
    writeln!(out, "pub const ADVERTISED_GL_MINOR: i32 = {ADVERTISED_GL_MINOR};").unwrap();

    let out_path = PathBuf::from(env("OUT_DIR")).join("generated_entrypoints.rs");
    std::fs::write(&out_path, out).unwrap();
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Level {
    Full,
    Partial,
    Stub,
}

fn classify(name: &str) -> Level {
    if IMPLEMENTED.contains(&name) {
        Level::Full
    } else if PARTIAL.contains(&name) {
        Level::Partial
    } else {
        Level::Stub
    }
}

fn cap_level(l: Level) -> &'static str {
    match l {
        Level::Full => "CapLevel::Full",
        Level::Partial => "CapLevel::Partial",
        Level::Stub => "CapLevel::Stub",
    }
}

fn cap_lib(lib: &str) -> &'static str {
    match lib {
        "EGL" => "CapLib::Egl",
        _ => "CapLib::Gl",
    }
}

/// The GL/EGL error a `stub` raises (0 for full/partial). Default is the generic "operation could not
/// be performed"; a few entry points get a more specific error where the spec clearly dictates one.
fn stub_error(lib: &str, name: &str, level: Level) -> u32 {
    if level != Level::Stub {
        return 0;
    }
    let _ = name;
    if lib == "EGL" {
        0x3002 // EGL_BAD_ACCESS
    } else {
        0x0502 // GL_INVALID_OPERATION
    }
}

fn since(lib: &str, name: &str, level: Level) -> String {
    if level != Level::Full {
        return String::new();
    }
    if lib == "EGL" {
        return "EGL 1.4".into();
    }
    if ES3_FULL.contains(&name) {
        "GLES 3.0".into()
    } else {
        "GLES 2.0".into()
    }
}

fn requirement(lib: &str, name: &str, level: Level) -> String {
    match level {
        Level::Partial => "spec-default no-op / degraded query (gl_shim.c parity)".into(),
        Level::Stub => {
            if lib == "EGL" {
                "unsupported (raises eglGetError)".into()
            } else {
                "unsupported (raises glGetError)".into()
            }
        }
        Level::Full => {
            if lib == "EGL" {
                "EGL lifecycle / present".into()
            } else if name.starts_with("glClear") || name.starts_with("glDraw") {
                "draw-list IR (lowered at swap)".into()
            } else if name.starts_with("glGet") || name.starts_with("glIs") {
                "state query (no IR)".into()
            } else {
                "state / resource (lowered at swap)".into()
            }
        }
    }
}

/// Emit a generated (partial | stub) entry point with truthful-failure semantics.
fn emit_entry(out: &mut String, lib: &str, name: &str, ret: &str, params: &str, level: Level) {
    let mut sig = String::new();
    let mut plist: Vec<(String, String, bool)> = Vec::new(); // (rust_ty, name, is_out_ptr)
    if !params.is_empty() {
        for (i, p) in params.split(';').enumerate() {
            let (ty, pname) = p.split_once('|').unwrap_or_else(|| panic!("bad param {p:?} in {name}"));
            let cty = ty.trim();
            let rty = map_type(cty, name);
            let pn = sanitize(pname.trim(), i);
            if i > 0 {
                sig.push_str(", ");
            }
            write!(sig, "{pn}: {rty}").unwrap();
            plist.push((rty, pn, is_out_ptr(cty)));
        }
    }
    let rmap = map_ret(ret.trim(), name);
    let arrow = rmap.as_ref().map(|r| format!(" -> {r}")).unwrap_or_default();

    // `glGen*(GLsizei n, T* out)` array contract: `n` is the length of `out`, so it is safe (and
    // truthful) to zero all `n` handles. Every other out param zeroes a single element.
    let gen_array = plist.len() == 2
        && (plist[0].0 == "i32" || plist[0].0 == "u32")
        && plist[0].1 == "n"
        && plist[1].2;

    let mut body = String::new();
    // Reference every argument so `unused_variables` stays quiet (belt + braces).
    for (_, pn, _) in &plist {
        write!(body, "let _ = {pn}; ").unwrap();
    }
    // Record / debug-log / strict-abort.
    match level {
        Level::Stub => write!(body, "crate::stub::stub_call(\"{name}\"); ").unwrap(),
        Level::Partial => write!(body, "crate::stub::partial_call(\"{name}\"); ").unwrap(),
        Level::Full => unreachable!(),
    }
    // Deterministically initialize every genuine output pointer (a mutable C pointer parameter — NOT
    // an opaque handle passed by value, which also maps to a Rust raw pointer but must not be written).
    for (idx, (_, pn, is_out)) in plist.iter().enumerate() {
        if *is_out {
            let count = if gen_array && idx == 1 {
                format!("({}).max(0) as usize", plist[0].1)
            } else {
                "1".to_string()
            };
            write!(body, "unsafe {{ crate::stub::out_zero({pn}, {count}); }} ").unwrap();
        }
    }
    // Truthful failure: a stub raises the API-correct error; a partial no-op raises nothing.
    if level == Level::Stub {
        let err = stub_error(lib, name, level);
        if lib == "EGL" {
            write!(body, "crate::stub::fail_egl({err:#06x}); ").unwrap();
        } else {
            write!(body, "crate::stub::fail_gl({err:#06x}); ").unwrap();
        }
    }
    // Return value: a sentinel for the "not found" queries, else the spec default.
    if let Some(r) = &rmap {
        let ret_expr = SENTINEL_RETURN
            .iter()
            .find(|(n, _)| *n == name)
            .map(|(_, e)| (*e).to_string())
            .unwrap_or_else(|| default_for(r).to_string());
        write!(body, "{ret_expr}").unwrap();
    }

    writeln!(out, "#[no_mangle]\npub extern \"C\" fn {name}({sig}){arrow} {{ {body} }}\n").unwrap();
}

/// Whether a C parameter type is a genuine *mutable output pointer* — i.e. the caller passes storage
/// for us to write. This is decided from the C type (not the Rust type): an opaque handle like
/// `EGLDisplay` is passed *by value* yet also maps to a Rust `*mut c_void`, and must NEVER be written
/// through. Only a real pointer form (`GLint *`, `void **`, …) with a non-const base is an output.
fn is_out_ptr(c: &str) -> bool {
    let c = c.trim();
    if c.ends_with("*const*") {
        return false; // pointer-to-const-pointer: input
    }
    if c.ends_with("**") {
        return true; // `X **` (e.g. `void **params`): output pointer-to-pointer
    }
    if let Some(base) = c.strip_suffix('*') {
        return !base.trim_start().starts_with("const ");
    }
    false // by-value scalar or opaque handle
}

/// C return type -> Rust type (None == `void`/unit). Panics on an unknown type so an API bump surfaces
/// at build time rather than silently mis-typing the ABI.
fn map_ret(c: &str, ctx: &str) -> Option<String> {
    if c == "void" {
        return None;
    }
    Some(map_type(c, ctx))
}

/// C type string -> Rust C-ABI type. Handles the pointer forms generally (single/double, const/mut,
/// `*const*`) so an API bump only ever surprises us on a genuinely new *base scalar*, which panics
/// (fail-loud ABI generator) rather than silently mis-typing.
fn map_type(c: &str, ctx: &str) -> String {
    let c = c.trim();
    // pointer forms, longest suffix first
    if let Some(base) = c.strip_suffix("*const*") {
        return format!("*const *const {}", pointee(base, ctx));
    }
    if let Some(base) = c.strip_suffix("**") {
        // outer const-ness of `X **` params is not expressed in the registry surface; treat as mut.
        return format!("*mut *mut {}", pointee(base, ctx));
    }
    if let Some(base) = c.strip_suffix('*') {
        let is_const = base.trim_start().starts_with("const ");
        let q = if is_const { "*const" } else { "*mut" };
        return format!("{q} {}", pointee(base, ctx));
    }
    scalar(c, ctx).to_string()
}

/// The Rust type of a pointer's pointee (the base with any leading `const` stripped).
fn pointee(base: &str, ctx: &str) -> String {
    let b = base.trim();
    let b = b.strip_prefix("const ").unwrap_or(b).trim();
    scalar(b, ctx).to_string()
}

/// A bare (by-value) scalar / opaque-handle C type -> Rust. Opaque handles (`EGLDisplay`, `GLsync`,
/// EGLConfig, …) are `void*`-shaped, so a value-of-that-type is a `*mut c_void`.
fn scalar(c: &str, ctx: &str) -> &'static str {
    match c {
        "void" => "core::ffi::c_void", // only meaningful as a pointee; bare `void` -> map_ret == None
        "char" | "GLchar" => "core::ffi::c_char",
        "GLbyte" => "i8",
        "GLubyte" | "GLboolean" => "u8",
        "GLshort" => "i16",
        "GLushort" => "u16",
        "GLenum" | "GLbitfield" | "GLuint" | "EGLenum" | "EGLBoolean" => "u32",
        "GLint" | "GLsizei" | "GLfixed" | "EGLint" => "i32",
        "GLfloat" | "GLclampf" => "f32",
        "GLdouble" => "f64",
        "GLint64" => "i64",
        "GLuint64" | "EGLTime" | "EGLTimeKHR" | "EGLuint64KHR" => "u64",
        "GLintptr" | "GLsizeiptr" | "EGLAttrib" => "isize",
        // opaque handles (all `void*`-shaped)
        "GLsync" | "GLDEBUGPROC" | "EGLClientBuffer" | "EGLContext" | "EGLDisplay" | "EGLImage"
        | "EGLImageKHR" | "EGLSurface" | "EGLSync" | "EGLSyncKHR" | "EGLConfig"
        | "EGLNativeDisplayType" | "EGLNativeWindowType" | "EGLNativePixmapType"
        | "__eglMustCastToProperFunctionPointerType" => "*mut core::ffi::c_void",
        other => panic!("unmapped C base type {other:?} (in {ctx}); extend scalar() in build.rs"),
    }
}

fn default_for(rust_ty: &str) -> &'static str {
    if rust_ty.starts_with("*const") {
        "core::ptr::null()"
    } else if rust_ty.starts_with("*mut") {
        "core::ptr::null_mut()"
    } else {
        "0"
    }
}

fn sanitize(name: &str, i: usize) -> String {
    const KW: &[&str] = &[
        "type", "ref", "box", "in", "fn", "let", "match", "move", "mut", "as", "impl", "loop",
        "where", "self", "final", "override", "become",
    ];
    if name.is_empty() {
        return format!("a{i}");
    }
    if KW.contains(&name) {
        return format!("{name}_");
    }
    name.to_string()
}

fn env(k: &str) -> String {
    std::env::var(k).unwrap_or_else(|_| panic!("env {k} not set"))
}

/// The Rust source for the inventory's public types (prepended to the generated file).
const CAP_TYPES: &str = r#"
/// Which shared library an entry point belongs to.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum CapLib { Gl, Egl }

/// Behavioral completeness of an exported entry point.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum CapLevel {
    /// Hand-written real body at gl_shim.c parity.
    Full,
    /// Spec-legitimate no-op / default-return (matches gl_shim.c); initializes outputs, raises no error.
    Partial,
    /// Unsupported operation: raises the API-correct error, zeroes outputs, returns the failure value.
    Stub,
}

/// One row of the generated capability inventory (see [`CAPABILITIES`]).
#[derive(Clone, Copy, Debug)]
pub struct Capability {
    /// The exported C symbol name (e.g. "glTexStorage2D").
    pub name: &'static str,
    /// GLES2 (`Gl`) or EGL (`Egl`).
    pub lib: CapLib,
    /// full / partial / stub.
    pub level: CapLevel,
    /// For `full`: the core version / extension the real body targets. Empty for partial/stub.
    pub since: &'static str,
    /// For `full`: the IR/backend path it drives. For partial/stub: the reason it is degraded.
    pub requirement: &'static str,
    /// For `stub`: the GL error (or EGL error, as u32) raised on call. 0 for full/partial.
    pub gl_error: u32,
}
"#;

// ================================================================================================
// Classification tables
// ================================================================================================

/// Entry points hand-implemented in `src/` (`full`) — the generator skips their bodies to avoid a
/// duplicate symbol. Grows as bodies are ported from the C shim; the generated surface shrinks.
const IMPLEMENTED: &[&str] = &[
    // ---- EGL: display/config/context/surface query + lifecycle (src/egl.rs) ----
    "eglGetError",
    "eglQueryString",
    "eglGetDisplay",
    "eglInitialize",
    "eglTerminate",
    "eglReleaseThread",
    "eglGetProcAddress",
    "eglChooseConfig",
    "eglGetConfigs",
    "eglGetConfigAttrib",
    "eglCreateContext",
    "eglDestroyContext",
    "eglMakeCurrent",
    "eglQueryContext",
    "eglQuerySurface",
    "eglDestroySurface",
    "eglBindAPI",
    "eglQueryAPI",
    "eglSwapInterval",
    "eglGetCurrentSurface",
    "eglGetCurrentDisplay",
    "eglGetCurrentContext",
    "eglWaitClient",
    "eglWaitGL",
    "eglWaitNative",
    // present / surface bring-up (frame boundary; clear-path IR is byte-identical to gl_shim.c)
    "eglCreateWindowSurface",
    "eglCreatePbufferSurface",
    "eglSwapBuffers",
    // ---- GLES: error/string ----
    "glGetError",
    "glGetString",
    // ---- GLES: scalar state + queries ----
    "glClearColor",
    "glViewport",
    "glScissor",
    "glEnable",
    "glDisable",
    "glIsEnabled",
    "glBlendFunc",
    "glBlendFuncSeparate",
    "glBlendEquation",
    "glBlendEquationSeparate",
    "glBlendFunci",
    "glBlendFuncSeparatei",
    "glBlendEquationi",
    "glBlendEquationSeparatei",
    "glBlendColor",
    "glCullFace",
    "glFrontFace",
    "glColorMask",
    "glDepthFunc",
    "glDepthMask",
    "glDepthRangef",
    "glClearDepthf",
    "glClearStencil",
    "glStencilFunc",
    "glStencilOp",
    "glStencilMask",
    "glLineWidth",
    "glHint",
    "glPolygonOffset",
    "glSampleCoverage",
    "glFinish",
    "glFlush",
    "glGenerateMipmap",
    "glPixelStorei",
    "glGetIntegerv",
    "glGetFloatv",
    "glGetBooleanv",
    // ---- GLES: buffers ----
    "glGenBuffers",
    "glDeleteBuffers",
    "glBindBuffer",
    "glBufferData",
    "glBufferSubData",
    "glIsBuffer",
    // ---- GLES: textures ----
    "glGenTextures",
    "glDeleteTextures",
    "glActiveTexture",
    "glBindTexture",
    "glTexImage2D",
    "glTexSubImage2D",
    "glTexParameteri",
    "glTexParameterf",
    "glTexParameteriv",
    "glTexParameterfv",
    "glIsTexture",
    // ---- GLES: shaders + programs (object state; translation deferred) ----
    "glCreateShader",
    "glShaderSource",
    "glCompileShader",
    "glGetShaderiv",
    "glGetShaderInfoLog",
    "glDeleteShader",
    "glIsShader",
    "glCreateProgram",
    "glAttachShader",
    "glDetachShader",
    "glLinkProgram",
    "glUseProgram",
    "glGetProgramiv",
    "glGetProgramInfoLog",
    "glDeleteProgram",
    "glIsProgram",
    "glGetUniformLocation",
    "glGetAttribLocation",
    "glUniform1f",
    "glUniform2f",
    "glUniform3f",
    "glUniform4f",
    "glUniform1fv",
    "glUniform2fv",
    "glUniform3fv",
    "glUniform4fv",
    "glUniform1i",
    "glUniform2i",
    "glUniform3i",
    "glUniform4i",
    "glUniform1iv",
    "glUniform2iv",
    "glUniform3iv",
    "glUniform4iv",
    "glUniform1ui",
    "glUniform2ui",
    "glUniform3ui",
    "glUniform4ui",
    "glUniform1uiv",
    "glUniform2uiv",
    "glUniform3uiv",
    "glUniform4uiv",
    "glUniformMatrix4fv",
    "glUniformMatrix2fv",
    "glUniformMatrix3fv",
    "glUniformMatrix2x3fv",
    "glUniformMatrix3x2fv",
    "glUniformMatrix2x4fv",
    "glUniformMatrix4x2fv",
    "glUniformMatrix3x4fv",
    "glUniformMatrix4x3fv",
    // ---- GLES: vertex attributes ----
    "glVertexAttribPointer",
    "glEnableVertexAttribArray",
    "glDisableVertexAttribArray",
    // ---- GLES: draw recording (frame draw-list; IR lowered at eglSwapBuffers) ----
    "glClear",
    "glDrawArrays",
    "glDrawElements",
    "glDrawArraysInstanced",
    "glDrawElementsInstanced",
    "glCheckFramebufferStatus",
    // ---- GLES: vertex array objects ----
    "glGenVertexArrays",
    "glBindVertexArray",
    "glDeleteVertexArrays",
    "glIsVertexArray",
    // ---- GLES: framebuffer + renderbuffer objects (offscreen render targets) ----
    "glGenFramebuffers",
    "glBindFramebuffer",
    "glDeleteFramebuffers",
    "glIsFramebuffer",
    "glFramebufferTexture2D",
    "glFramebufferTextureLayer",
    "glFramebufferRenderbuffer",
    "glGetFramebufferAttachmentParameteriv",
    "glGenRenderbuffers",
    "glBindRenderbuffer",
    "glDeleteRenderbuffers",
    "glIsRenderbuffer",
    "glRenderbufferStorage",
    "glRenderbufferStorageMultisample",
    "glGetRenderbufferParameteriv",
    "glBlitFramebuffer",
    "glReadPixels",
    "glClearBufferfv",
    // ---- Phase 4.1: coherent-GLES2 promotions (real bodies ported from gl_shim.c) ----
    // texture: immutable storage + 3D/array upload + copy-from-framebuffer
    "glTexStorage2D",
    "glTexStorage3D",
    "glTexImage3D",
    "glTexSubImage3D",
    "glCopyTexImage2D",
    "glCopyTexSubImage2D",
    // buffer: mapping (functional pointer into buffer storage) + copy
    "glMapBufferRange",
    "glUnmapBuffer",
    "glCopyBufferSubData",
    // vertex: integer attribute arrays
    "glVertexAttribIPointer",
    // strings: indexed extension enumeration (served from the same inventory list)
    "glGetStringi",
    // draw: range-elements delegates to glDrawElements
    "glDrawRangeElements",
    // ES3 object-name allocators (monotonic ids; objects are documented partial no-ops)
    "glGenQueries",
    "glGenSamplers",
    "glGenTransformFeedbacks",
    // EGL: modern platform-display open (delegates to the eglGetDisplay lifecycle)
    "eglGetPlatformDisplay",

    // ---- Phase 11b: GLES2 mandatory-command completeness (ported from gl_shim.c oracle) ----
    "glBindAttribLocation",
    "glCompressedTexImage2D",
    "glCompressedTexSubImage2D",
    "glGetActiveAttrib",
    "glGetActiveUniform",
    "glGetAttachedShaders",
    "glGetBufferParameteriv",
    "glGetShaderPrecisionFormat",
    "glGetShaderSource",
    "glGetTexParameterfv",
    "glGetTexParameteriv",
    "glGetUniformfv",
    "glGetUniformiv",
    "glGetVertexAttribPointerv",
    "glGetVertexAttribfv",
    "glGetVertexAttribiv",
    "glReleaseShaderCompiler",
    "glShaderBinary",
    "glStencilFuncSeparate",
    "glStencilMaskSeparate",
    "glStencilOpSeparate",
    "glValidateProgram",
    "glVertexAttrib1f",
    "glVertexAttrib1fv",
    "glVertexAttrib2f",
    "glVertexAttrib2fv",
    "glVertexAttrib3f",
    "glVertexAttrib3fv",
    "glVertexAttrib4f",
    "glVertexAttrib4fv",

    // ---- Phase 11c: EGL 1.4 mandatory tail (real bodies; truthful for unsupported paths) ----
    "eglBindTexImage",
    "eglCopyBuffers",
    "eglCreatePbufferFromClientBuffer",
    "eglCreatePixmapSurface",
    "eglReleaseTexImage",
    "eglSurfaceAttrib",
];

/// Subset of `IMPLEMENTED` whose real body targets an ES 3.0 core feature (for the inventory's `since`
/// field). Everything else in `IMPLEMENTED` is ES 2.0.
const ES3_FULL: &[&str] = &[
    "glDrawArraysInstanced",
    "glDrawElementsInstanced",
    "glGenVertexArrays",
    "glBindVertexArray",
    "glDeleteVertexArrays",
    "glIsVertexArray",
    "glFramebufferTextureLayer",
    "glRenderbufferStorageMultisample",
    "glBlitFramebuffer",
    "glClearBufferfv",
    "glUniform1ui",
    "glUniform2ui",
    "glUniform3ui",
    "glUniform4ui",
    "glUniform1uiv",
    "glUniform2uiv",
    "glUniform3uiv",
    "glUniform4uiv",
    "glUniformMatrix2x3fv",
    "glUniformMatrix3x2fv",
    "glUniformMatrix2x4fv",
    "glUniformMatrix4x2fv",
    "glUniformMatrix3x4fv",
    "glUniformMatrix4x3fv",
    // Phase 4.1 ES3-core promotions (glTexStorage2D/glCopyTex*2D are ES2-reachable via extensions).
    "glTexStorage3D",
    "glTexImage3D",
    "glTexSubImage3D",
    "glMapBufferRange",
    "glUnmapBuffer",
    "glCopyBufferSubData",
    "glVertexAttribIPointer",
    "glGetStringi",
    "glDrawRangeElements",
    "glGenQueries",
    "glGenSamplers",
    "glGenTransformFeedbacks",
];

/// Generated entry points that are a `partial`: a spec-legitimate no-op or default-return that matches
/// gl_shim.c's own degraded behavior. These initialize their outputs but raise NO error — a no-op is
/// the correct answer (introspection queries that return the spec default; optional state the shim
/// doesn't need for its IR; "not found"/"is-object" queries returning the correct sentinel). Everything
/// NOT in `IMPLEMENTED` and NOT here is a `stub` (an unsupported operation that raises an error).
const PARTIAL: &[&str] = &[
    // --- introspection queries: return spec default (0 / empty), like gl_shim.c ---
    "glGetActiveUniformBlockName",
    "glGetActiveUniformBlockiv",
    "glGetActiveUniformsiv",
    "glGetBooleani_v",
    "glGetBufferParameteri64v",
    "glGetBufferPointerv",
    "glGetDebugMessageLog",
    "glGetFramebufferParameteriv",
    "glGetGraphicsResetStatus",
    "glGetInteger64i_v",
    "glGetInteger64v",
    "glGetIntegeri_v",
    "glGetInternalformativ",
    "glGetMultisamplefv",
    "glGetObjectLabel",
    "glGetObjectPtrLabel",
    "glGetPointerv",
    "glGetProgramBinary",
    "glGetProgramInterfaceiv",
    "glGetProgramPipelineInfoLog",
    "glGetProgramPipelineiv",
    "glGetProgramResourceName",
    "glGetProgramResourceiv",
    "glGetQueryObjectuiv",
    "glGetQueryiv",
    "glGetSamplerParameterIiv",
    "glGetSamplerParameterIuiv",
    "glGetSamplerParameterfv",
    "glGetSamplerParameteriv",
    "glGetSynciv",
    "glGetTexLevelParameterfv",
    "glGetTexLevelParameteriv",
    "glGetTexParameterIiv",
    "glGetTexParameterIuiv",
    "glGetTransformFeedbackVarying",
    "glGetUniformIndices",
    "glGetUniformuiv",
    "glGetVertexAttribIiv",
    "glGetVertexAttribIuiv",
    "glGetnUniformfv",
    "glGetnUniformiv",
    "glGetnUniformuiv",
    // --- "not found" / "is-object" queries: return the correct sentinel (see SENTINEL_RETURN) ---
    "glGetFragDataLocation",
    "glGetProgramResourceIndex",
    "glGetProgramResourceLocation",
    "glGetUniformBlockIndex",
    "glIsEnabledi",
    "glIsProgramPipeline",
    "glIsQuery",
    "glIsSampler",
    "glIsSync",
    "glIsTransformFeedback",
    // --- optional state / hints the shim legitimately no-ops (gl_shim.c also no-ops) ---
    "glBlendBarrier",
    "glColorMaski",
    "glDebugMessageCallback",
    "glDebugMessageControl",
    "glDebugMessageInsert",
    "glDisablei",
    "glEnablei",
    "glInvalidateFramebuffer",
    "glInvalidateSubFramebuffer",
    "glMemoryBarrier",
    "glMemoryBarrierByRegion",
    "glMinSampleShading",
    "glObjectLabel",
    "glObjectPtrLabel",
    "glPatchParameteri",
    "glPopDebugGroup",
    "glPrimitiveBoundingBox",
    "glProgramParameteri",
    "glPushDebugGroup",
    "glSampleMaski",
    "glValidateProgramPipeline",
    "glVertexAttribI4i",
    "glVertexAttribI4iv",
    "glVertexAttribI4ui",
    "glVertexAttribI4uiv",
    // --- deletes of objects the shim never hands out: GL silently ignores unknown names ---
    "glDeleteProgramPipelines",
    "glDeleteQueries",
    "glDeleteSamplers",
    "glDeleteSync",
    "glDeleteTransformFeedbacks",
    // --- EGL: benign attribute set (swap behavior / mip hint) ---
    // --- Phase 4.1: reclassified stub->partial to match gl_shim.c's deliberate no-ops (byte-parity;
    //     these raise no error because the oracle performs no work either — an error would DIVERGE) ---
    // UBO binding: uniforms flow through the translator's default `[[buffer(1)]]` block, so the explicit
    // binding calls are correct no-ops (gl_shim.c).
    "glBindBufferBase",
    "glBindBufferRange",
    "glUniformBlockBinding",
    "glFlushMappedBufferRange",
    // single color target / no MRT: draw-buffer + integer/depth-stencil clears no-op (glClearBufferfv is full)
    "glDrawBuffers",
    "glReadBuffer",
    "glClearBufferiv",
    "glClearBufferuiv",
    "glClearBufferfi",
    // instancing collapses to one instance, so the per-attribute divisor is a no-op (as in gl_shim.c)
    "glVertexAttribDivisor",
    // compressed / 3D-copy texture upload is not decoded (gl_shim.c no-ops; leaves the RGBA8 plane)
    "glCompressedTexImage3D",
    "glCompressedTexSubImage3D",
    "glCopyTexSubImage3D",
    // sampler objects carry no state; filtering uses the texture's own params (gl_shim.c no-ops these)
    "glBindSampler",
    "glSamplerParameteri",
    "glSamplerParameterf",
    "glSamplerParameteriv",
    "glSamplerParameterfv",
    // queries / transform feedback: begin/end/bind are no-ops (the object names come from the full glGen*)
    "glBeginQuery",
    "glEndQuery",
    "glBindTransformFeedback",
    "glBeginTransformFeedback",
    "glEndTransformFeedback",
    // program binary + shader binary: no binary formats advertised, so load is a no-op (gl_shim.c)
    "glProgramBinary",
];

/// `partial` queries whose "not found" answer is a non-zero sentinel (returning 0 would be a false
/// "found at slot 0"). Mapped to the exact Rust return expression.
const SENTINEL_RETURN: &[(&str, &str)] = &[
    ("glGetFragDataLocation", "-1"),
    ("glGetProgramResourceLocation", "-1"),
    ("glGetUniformBlockIndex", "crate::glconst::GL_INVALID_INDEX"),
    ("glGetProgramResourceIndex", "crate::glconst::GL_INVALID_INDEX"),
];
