// Writes the TypeScript declarations for this package from the component
// catalogue the Rust library emits.
//
// The declarations are generated rather than written because the library is
// where a component's contract lives: which properties a Button means something
// by, and which interactions it can report, are declared beside the component
// in src/workspaces/hl-gui/src/node/tag.rs. A hand-kept .d.ts would describe
// last month's library and nobody would notice — the same reason the catalogue
// itself is emitted from the library rather than transcribed.
//
// Run through `npm run types`, which regenerates the catalogue first.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const CATALOGUE = process.env.HUSKLET_CATALOGUE ?? path.resolve(here, '../catalogue.json');
const DECLARATIONS = process.env.HUSKLET_DECLARATIONS ?? path.resolve(here, '../src/index.d.ts');

/** The value shapes a property accepts, as the TypeScript that describes them. */
const SHAPES = {
  Text: 'string',
  Number: 'number',
  Integer: 'number',
  Flag: 'boolean',
  Length: 'Length',
  Edges: 'Edges',
  Bounds: 'Bounds',
  Choices: 'Choice[]',
  Schema: 'readonly ColumnSpec[]',
  Source: 'number',
};

/** `Label` is the wire spelling; `label` is what a component is given. */
function camel(name) {
  return name[0].toLowerCase() + name.slice(1);
}

/**
 * The type of one property.
 *
 * Read from the value shapes the catalogue publishes for it, so a property that
 * gains a shape gains it here too. The enumerations are unions of both
 * spellings the wire accepts: `"accent"` as the stylesheet names it and
 * `"Accent"` as the wire carries it.
 */
function typed(entry, enums) {
  const written = entry.values.map((shape) => (shape in SHAPES ? SHAPES[shape] : union(enums[shape])));
  // A growth factor is written as a weight by some and as a switch by others,
  // and the host compares either against zero.
  if (entry.name === 'Grow') written.push('boolean');
  return [...new Set(written)].join(' | ');
}

function union(members) {
  if (!members) return 'unknown';
  const spellings = members.flatMap((member) => [member.style, member.wire]);
  return [...new Set(spellings)].map((spelling) => JSON.stringify(spelling)).join(' | ');
}

/** The hand-written part: the shapes no single property owns. */
function preamble() {
  return `// Generated by tools/types.js from catalogue.json. Do not edit.
//
// One interface per component, carrying the properties that component declares
// and the handlers for the interactions it can report. A property no component
// declares is a type error, which is the whole point of generating this.

import type { ComponentType, ReactNode } from 'react';
import type { SurfaceBootstrap } from '@husklet/client';

export interface CommandPaletteItem {
  id: string;
  title: string;
  group?: string;
  detail?: string;
  shortcut?: string;
  keywords?: readonly string[];
  disabled?: boolean;
  destructive?: boolean;
  tone?: 'neutral' | 'accent' | 'positive' | 'warning' | 'danger';
  onInvoke?: (command: CommandPaletteItem) => void;
}
export interface CommandPaletteViewProps extends NodeProps {
  commands?: readonly CommandPaletteItem[];
  initialQuery?: string;
  placeholder?: string;
  emptyLabel?: string;
  onQueryChange?: (query: string) => void;
  onSelect?: (command: CommandPaletteItem) => void;
}
export const CommandPaletteView: ComponentType<CommandPaletteViewProps>;
export function filterCommands(commands: readonly CommandPaletteItem[], query: string): CommandPaletteItem[];
export const COMMAND_PALETTE_ITEM_LIMIT: 256;
export const COMMAND_PALETTE_QUERY_BYTE_LIMIT: 128;
export const COMMAND_PALETTE_TEXT_BYTE_LIMIT: 256;

export interface TerminalTranscriptLine {
  id?: string | number;
  number?: number;
  text: string;
  timestamp?: string;
  stream?: 'stdout' | 'stderr' | 'system';
  tone?: 'neutral' | 'accent' | 'positive' | 'warning' | 'danger';
}

export interface TerminalTranscriptAction {
  id?: string;
  label: string;
  tone?: 'neutral' | 'accent' | 'positive' | 'warning' | 'danger';
  variant?: 'solid' | 'outline' | 'ghost' | 'text';
  destructive?: boolean;
  enabled?: boolean;
  onInvoke?: () => void;
}

export interface TerminalTranscriptProps extends NodeProps {
  lines?: readonly (string | TerminalTranscriptLine)[];
  cursor?: { line: number; column: number };
  lineNumbers?: boolean;
  timestamps?: boolean;
  selected?: string | number;
  truncated?: boolean;
  droppedLines?: number;
  actions?: readonly TerminalTranscriptAction[];
  onSelect?: (line: TerminalTranscriptLine, sourceIndex: number) => void;
  emptyLabel?: string;
}

export const TerminalTranscript: ComponentType<TerminalTranscriptProps>;
export const TERMINAL_TRANSCRIPT_LINE_LIMIT: 256;
export const TERMINAL_TRANSCRIPT_LINE_BYTE_LIMIT: 2048;
export const TERMINAL_TRANSCRIPT_BYTE_LIMIT: 65536;
export const TERMINAL_TRANSCRIPT_ACTION_LIMIT: 8;

/** A spacing or sizing quantity: steps on the 4px scale unless named. */
export type Length = number | 'fill' | 'content' | { chars: number } | { step: number };

/** Space inside a component's own edges, per side or all at once. */
export type Edges = Length | { top?: Length; end?: Length; bottom?: Length; start?: Length };

/** An exact extent, or a floor and a ceiling. */
export type Bounds = Length | { minimum?: Length; maximum?: Length };

export interface JsonTreeEvent { path: string; type: string; value?: unknown; text?: string; }
export interface JsonTreeProps {
  value: unknown;
  maxDepth?: number;
  maxNodes?: number;
  maxStringLength?: number;
  initiallyExpanded?: string[];
  height?: Length | Bounds;
  grow?: number | boolean;
  onSelect?: (event: JsonTreeEvent) => void;
  onCopy?: (event: JsonTreeEvent) => void;
}
export const JsonTree: import('react').ComponentType<JsonTreeProps>;
export const ObjectInspector: typeof JsonTree;
export function inspectJson(value: unknown, options?: Pick<JsonTreeProps, 'maxDepth' | 'maxNodes' | 'maxStringLength'>): { rows: Array<Record<string, unknown>>; limits: Record<string, number>; truncated: boolean };

/** One selectable option offered by a choice control. */
export interface Choice {
  value: string;
  label: string;
}

/** One declared column of a table. */
export interface ColumnSpec {
  key: string;
  title?: string;
  width?: Length;
  align?: ${union(catalogue().enums.Align)};
  sortable?: boolean;
  editable?: boolean;
}
export const TABLE_COLUMN_LIMIT: 64;
export const COLUMN_KEY_BYTE_LIMIT: 128;
export const COLUMN_TITLE_BYTE_LIMIT: 256;

/** One interaction, as the host reports it. */
export interface Report {
  trigger: string;
  node: number;
  id: string;
  value: unknown;
}

export interface SelectedCollectionRow { index: number; id: string; }
export interface CollectionSelection { source: number; version: number; rows: SelectedCollectionRow[]; }
export interface SelectionReport extends Report { rows: number[]; collection?: CollectionSelection | null; }
export interface EditReport extends Report { source: number; version: number; row: SelectedCollectionRow; column: string; value: string; }
export interface SortReport extends Report { source: number; version: number; column: string; descending: boolean; }

/** What every component takes, whatever it is. */
export interface NodeProps {
  key?: string | number | null;
}
`;
}

let held = null;
function catalogue() {
  held ??= JSON.parse(fs.readFileSync(CATALOGUE, 'utf8'));
  return held;
}

/** One component's interface: its own properties, then its handlers. */
function component(tag, props, enums) {
  const lines = [`export interface ${tag.name}Props extends NodeProps {`];
  if (tag.acceptsChildren) lines.push('  children?: ReactNode;');
  for (const name of tag.props) {
    const entry = props.get(name);
    lines.push(`  /** ${entry.note} */`);
    lines.push(`  ${camel(name)}?: ${typed(entry, enums)};`);
  }
  for (const trigger of tag.triggers) {
    lines.push(`  on${trigger}?: (report: ${trigger === 'Select' ? 'SelectionReport' : trigger === 'Edit' ? 'EditReport' : trigger === 'Sort' ? 'SortReport' : 'Report'}) => void;`);
  }
  lines.push('}');
  return lines.join('\n');
}

/** The rest of the public API, which the catalogue says nothing about. */
function api(tags) {
  const components = tags.map((tag) => `export const ${tag.name}: ComponentType<${tag.name}Props>;`);
  return `
${components.join('\n')}

export interface ConfirmActionProps {
  authorityKey: string;
  label: string;
  confirmLabel: string;
  question: string;
  onConfirm: (authorityKey: string) => void | Promise<void>;
  enabled?: boolean;
  cancelLabel?: string;
  pendingLabel?: string;
  onCancel?: (authorityKey: string) => void;
}
export const ConfirmAction: ComponentType<ConfirmActionProps>;
export const CONFIRM_ACTION_TEXT_BYTE_LIMIT: 1024;

export interface ResourceStateProps extends NodeProps {
  state: 'loading' | 'empty' | 'error' | 'ready';
  loadingLabel?: string;
  emptyLabel?: string;
  emptyDetail?: string;
  error?: string;
  retryLabel?: string;
  onRetry?: () => void;
  children?: ReactNode;
}
export const ResourceState: ComponentType<ResourceStateProps>;
export const RESOURCE_STATE_TEXT_BYTE_LIMIT: 1024;

/** Every tag name, in catalogue order. */
export const tags: string[];

/** Every tag, as a host component React can create. */
export const components: Record<string, string>;

/** Whether a tag accepts child nodes. */
export function acceptsChildren(tag: string): boolean;

/** Every prop and handler name a component accepts. */
export const vocabulary: { props: string[]; handlers: string[] };

import type { ConnectOptions, HostEvent, PaneSelection, Session } from '@husklet/client';
export * from '@husklet/client';

export const LOG_VIEW_CHARACTER_LIMIT: 4096;
export function connect(options?: ConnectOptions): Promise<Session>;
export function useHostEvents(session: Session, listener: (event: HostEvent, channel: number) => void): void;
export function usePaneSelection(session: Session, provider?: string | null): PaneSelection | null;
export type InterfaceSourceMutation =
  | { Open: { source: number; columns: readonly unknown[] } }
  | { Length: { source: number; version: number; rows: number } }
  | { Window: { source: number; version: number; request: number; range: { start: number; count: number }; rows: readonly unknown[] } }
  | { Invalidate: { source: number; version: number; range: { start: number; count: number } | null } }
  | { Close: { source: number } };

export interface RenderHandle {
  readonly ready: Promise<string>;
  readonly slot: string | null;
  update(next: ReactNode): void;
  /** Waits until every reconciliation frame queued so far is acknowledged by the host. */
  flush(): Promise<void>;
  source(mutation: InterfaceSourceMutation): Promise<void>;
  close(): void;
}

export function render(
  element: ReactNode,
  session: Session,
  options?: {
    title?: string;
    split?: { slot: string; division: 'beside' | 'below' };
    bootstrap?: SurfaceBootstrap;
  },
): RenderHandle;

export function deliver(session: Session, payload: unknown): boolean;
`;
}

function main() {
  const { tags, props, enums } = catalogue();
  const described = new Map(props.map((entry) => [entry.name, entry]));
  const written = [preamble(), ...tags.map((tag) => component(tag, described, enums)), api(tags)];
  fs.writeFileSync(DECLARATIONS, `${written.join('\n\n').trimEnd()}\n`);
  process.stdout.write(`${DECLARATIONS}: ${tags.length} components\n`);
}

main();
