//! Codegen for the guest `libcudart.so.1` shim: turn `registry/cudart.manifest` into the complete
//! `#[no_mangle] extern "C"` `cuda*`/`__cuda*` export surface (49 entry points).
//!
//! Same mechanism as the cuda shim's build.rs (a spec-faithful default stub for every entry not
//! hand-written in `src/runtime.rs`), adapted to the CUDA Runtime API type vocabulary (`cudaError_t`,
//! `dim3` by value, `cudaStream_t`/`cudaEvent_t` handles, `enum cudaMemcpyKind`). Bakes the soname
//! `libcudart.so.1`.

use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env("CARGO_MANIFEST_DIR")).join("registry/cudart.manifest");
    println!("cargo:rerun-if-changed={}", manifest.display());
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rustc-cdylib-link-arg=-Wl,-soname,libcudart.so.1");

    let text = std::fs::read_to_string(&manifest)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest.display()));

    let mut out = String::new();
    out.push_str("// @generated by build.rs from registry/cudart.manifest — DO NOT EDIT.\n\n");

    let mut rt = 0usize;
    let mut stubs = 0usize;
    for (lineno, line) in text.lines().enumerate() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut f = line.split('\t');
        let lib = f.next().unwrap_or("");
        let name = f.next().unwrap_or("");
        let ret = f.next().unwrap_or("void");
        let params = f.next().unwrap_or("");
        if name.is_empty() {
            panic!("manifest line {}: empty name: {line:?}", lineno + 1);
        }
        match lib {
            "RT" => rt += 1,
            other => panic!("manifest line {}: unknown lib {other:?}", lineno + 1),
        }
        if IMPLEMENTED.contains(&name) {
            continue;
        }
        stubs += 1;
        emit_stub(&mut out, name, ret, params);
    }

    writeln!(out, "\n/// Total CUDA Runtime API entry points in the manifest (the exported surface).").unwrap();
    writeln!(out, "pub const CUDART_ENTRYPOINTS: usize = {rt};").unwrap();
    writeln!(out, "/// Entry points emitted as default stubs (not yet hand-implemented).").unwrap();
    writeln!(out, "pub const GENERATED_STUBS: usize = {stubs};").unwrap();
    writeln!(out, "/// Entry points with real hand-written bodies in `src/runtime.rs`.").unwrap();
    writeln!(out, "pub const IMPLEMENTED_ENTRYPOINTS: usize = {};", IMPLEMENTED.len()).unwrap();

    let out_path = PathBuf::from(env("OUT_DIR")).join("generated_entrypoints.rs");
    std::fs::write(&out_path, out).unwrap();
}

fn emit_stub(out: &mut String, name: &str, ret: &str, params: &str) {
    let mut sig = String::new();
    let mut argnames = Vec::new();
    if !params.is_empty() {
        for (i, p) in params.split(';').enumerate() {
            let (ty, pname) = p.split_once('|').unwrap_or_else(|| panic!("bad param {p:?} in {name}"));
            let rty = map_type(ty.trim(), name);
            let pn = sanitize(pname.trim(), i);
            if i > 0 {
                sig.push_str(", ");
            }
            write!(sig, "{pn}: {rty}").unwrap();
            argnames.push(pn);
        }
    }
    let rmap = map_ret(ret.trim(), name);
    let arrow = rmap.as_ref().map(|r| format!(" -> {r}")).unwrap_or_default();
    let touch: String = argnames.iter().map(|a| format!("let _ = {a}; ")).collect();
    let body = match &rmap {
        None => format!("{touch}crate::stub::hit(\"{name}\");"),
        Some(r) => format!("{touch}crate::stub::hit(\"{name}\"); {}", default_for(r)),
    };
    writeln!(out, "#[no_mangle]\npub extern \"C\" fn {name}({sig}){arrow} {{ {body} }}\n").unwrap();
}

fn map_ret(c: &str, ctx: &str) -> Option<String> {
    if c == "void" {
        return None;
    }
    Some(map_type(c, ctx))
}

fn map_type(c: &str, ctx: &str) -> String {
    let c = c.trim();
    if let Some(base) = c.strip_suffix("**") {
        return format!("*mut *mut {}", pointee(base, ctx));
    }
    if let Some(base) = c.strip_suffix('*') {
        let is_const = base.trim_start().starts_with("const ");
        let q = if is_const { "*const" } else { "*mut" };
        return format!("{q} {}", pointee(base, ctx));
    }
    scalar(c, ctx).to_string()
}

fn pointee(base: &str, ctx: &str) -> String {
    let b = base.trim();
    let b = b.strip_prefix("const ").unwrap_or(b).trim();
    scalar(b, ctx).to_string()
}

fn scalar(c: &str, ctx: &str) -> &'static str {
    // strip a leading struct/enum tag (`struct cudaDeviceProp` -> `cudaDeviceProp`).
    let c = c.strip_prefix("struct ").or_else(|| c.strip_prefix("enum ")).unwrap_or(c).trim();
    match c {
        "void" => "core::ffi::c_void",
        "char" => "core::ffi::c_char",
        "float" => "f32",
        "int" => "i32",
        "unsigned char" => "u8",
        "unsigned int" => "u32",
        "size_t" => "usize",
        // cudaError_t and the int-sized runtime enums.
        "cudaError_t" | "cudaMemcpyKind" => "i32",
        // opaque handle typedefs (void*-shaped).
        "cudaStream_t" | "cudaEvent_t" => "*mut core::ffi::c_void",
        // dim3 is a by-value {x,y,z} struct.
        "dim3" => "crate::Dim3",
        // opaque structs only ever referenced through a pointer.
        "cudaDeviceProp" | "cudaFuncAttributes" => "core::ffi::c_void",
        other => panic!("unmapped C base type {other:?} (in {ctx}); extend scalar() in cudart build.rs"),
    }
}

fn default_for(rust_ty: &str) -> &'static str {
    if rust_ty.starts_with("*const") {
        "core::ptr::null()"
    } else if rust_ty.starts_with("*mut") {
        "core::ptr::null_mut()"
    } else {
        "0" // cudaSuccess for the cudaError_t / unsigned int the runtime entry points return.
    }
}

fn sanitize(name: &str, i: usize) -> String {
    const KW: &[&str] = &[
        "type", "ref", "box", "in", "fn", "let", "match", "move", "mut", "as", "impl", "loop",
        "where", "self", "final", "override", "become",
    ];
    if name.is_empty() {
        return format!("a{i}");
    }
    if KW.contains(&name) {
        return format!("{name}_");
    }
    name.to_string()
}

fn env(k: &str) -> String {
    std::env::var(k).unwrap_or_else(|_| panic!("env {k} not set"))
}

/// Every entry point is hand-written in `src/runtime.rs` (`GENERATED_STUBS == 0`): the memory + device +
/// stream + event basics that map onto the `hl_cuda` lowering services (alloc/free/memcpy/memset/sync,
/// managed + pinned memory, streams, events), the full device-properties / func-attributes / version /
/// error surface, and the runtime-API launch tail — `__cudaRegisterFatBinary`/`Function`/`FatBinaryEnd`/
/// `Var`/`UnregisterFatBinary` + the `<<<>>>` `__cudaPush/PopCallConfiguration` stack + `cudaLaunchKernel`
/// (resolves a host-fn pointer to its device entry and lowers exactly like the driver-API `cuLaunchKernel`).
const IMPLEMENTED: &[&str] = &[
    // nvcc registration + launch glue
    "__cudaRegisterFatBinary",
    "__cudaRegisterFunction",
    "__cudaRegisterFatBinaryEnd",
    "__cudaRegisterVar",
    "__cudaUnregisterFatBinary",
    "__cudaPushCallConfiguration",
    "__cudaPopCallConfiguration",
    "cudaLaunchKernel",
    // memory (device / managed / pinned)
    "cudaMalloc",
    "cudaFree",
    "cudaMallocManaged",
    "cudaMallocHost",
    "cudaHostAlloc",
    "cudaFreeHost",
    "cudaHostGetDevicePointer",
    "cudaMemcpy",
    "cudaMemcpyAsync",
    "cudaMemset",
    "cudaMemsetAsync",
    "cudaMemGetInfo",
    // synchronization
    "cudaDeviceSynchronize",
    "cudaThreadSynchronize",
    // streams
    "cudaStreamCreate",
    "cudaStreamCreateWithFlags",
    "cudaStreamDestroy",
    "cudaStreamSynchronize",
    "cudaStreamQuery",
    "cudaStreamWaitEvent",
    // events
    "cudaEventCreate",
    "cudaEventCreateWithFlags",
    "cudaEventRecord",
    "cudaEventSynchronize",
    "cudaEventQuery",
    "cudaEventElapsedTime",
    "cudaEventDestroy",
    // device queries + properties
    "cudaGetDeviceCount",
    "cudaGetDevice",
    "cudaSetDevice",
    "cudaGetDeviceProperties",
    "cudaGetDeviceProperties_v2",
    "cudaDeviceGetPCIBusId",
    "cudaFuncGetAttributes",
    // versions + errors
    "cudaDriverGetVersion",
    "cudaRuntimeGetVersion",
    "cudaGetErrorString",
    "cudaGetErrorName",
    "cudaGetLastError",
    "cudaPeekAtLastError",
    "cudaDeviceReset",
];
