use super::*;

mod extra;

/// Resolves a hand-written EGL or GLES entry point to its exported C function address.
#[cfg_attr(not(gles_client), no_mangle)]
pub extern "C" fn eglGetProcAddress(procname: *const c_char) -> *mut c_void {
    if procname.is_null() {
        return core::ptr::null_mut();
    }
    let name = match unsafe { core::ffi::CStr::from_ptr(procname) }.to_str() {
        Ok(s) => s,
        Err(_) => return core::ptr::null_mut(),
    };
    // Map each core entry point name to its address. `f as usize as *mut c_void` erases the specific
    // `extern "C"` fn type to the opaque function pointer EGL hands back.
    macro_rules! p {
        ($f:path) => {
            $f as *const () as *mut c_void
        };
    }
    let address = match name {
        // ---- EGL: display / config / context / surface lifecycle + present ----
        "eglGetError" => p!(eglGetError),
        "eglGetDisplay" => p!(eglGetDisplay),
        "eglInitialize" => p!(eglInitialize),
        "eglTerminate" => p!(eglTerminate),
        "eglQueryString" => p!(eglQueryString),
        "eglGetProcAddress" => p!(eglGetProcAddress),
        "eglBindAPI" => p!(eglBindAPI),
        "eglChooseConfig" => p!(eglChooseConfig),
        "eglGetConfigs" => p!(eglGetConfigs),
        "eglGetConfigAttrib" => p!(eglGetConfigAttrib),
        "eglCreateContext" => p!(eglCreateContext),
        "eglDestroyContext" => p!(eglDestroyContext),
        "eglMakeCurrent" => p!(eglMakeCurrent),
        "eglCreateWindowSurface" => p!(eglCreateWindowSurface),
        "eglDestroySurface" => p!(eglDestroySurface),
        "eglSwapBuffers" => p!(eglSwapBuffers),
        "eglSwapInterval" => p!(eglSwapInterval),
        "eglGetCurrentDisplay" => p!(eglGetCurrentDisplay),
        "eglGetCurrentContext" => p!(eglGetCurrentContext),
        "eglGetCurrentSurface" => p!(eglGetCurrentSurface),
        // ---- GLES: error / string / query ----
        "glGetError" => p!(glGetError),
        "glCopyTextureCHROMIUM" => p!(glCopyTextureCHROMIUM),
        "glCopySubTextureCHROMIUM" => p!(glCopySubTextureCHROMIUM),
        "glRequestExtensionANGLE" => p!(glRequestExtensionANGLE),
        "glGetString" => p!(glGetString),
        "glGetStringi" => p!(glGetStringi),
        "glGetIntegerv" => p!(glGetIntegerv),
        "glGetIntegervRobustANGLE" => p!(glGetIntegervRobustANGLE),
        "glGetFloatv" => p!(glGetFloatv),
        "glGetBooleanv" => p!(glGetBooleanv),
        "glGetBooleanvRobustANGLE" => p!(glGetBooleanvRobustANGLE),
        "glGetActiveUniformBlockivRobustANGLE" => p!(glGetActiveUniformBlockivRobustANGLE),
        "glGetBufferParameteri64vRobustANGLE" => p!(glGetBufferParameteri64vRobustANGLE),
        "glGetBufferParameterivRobustANGLE" => p!(glGetBufferParameterivRobustANGLE),
        "glGetBufferPointervRobustANGLE" => p!(glGetBufferPointervRobustANGLE),
        "glGetFloatvRobustANGLE" => p!(glGetFloatvRobustANGLE),
        "glGetFramebufferAttachmentParameterivRobustANGLE" => {
            p!(glGetFramebufferAttachmentParameterivRobustANGLE)
        }
        "glPixelStorei" => p!(glPixelStorei),
        // ---- GLES: shader / program introspection ----
        "glGetShaderiv" => p!(glGetShaderiv),
        "glGetProgramiv" => p!(glGetProgramiv),
        "glGetProgramivRobustANGLE" => p!(glGetProgramivRobustANGLE),
        "glGetInteger64i_vRobustANGLE" => p!(glGetInteger64i_vRobustANGLE),
        "glGetInteger64vRobustANGLE" => p!(glGetInteger64vRobustANGLE),
        "glGetIntegeri_vRobustANGLE" => p!(glGetIntegeri_vRobustANGLE),
        "glGetInternalformativRobustANGLE" => p!(glGetInternalformativRobustANGLE),
        "glGetMultisamplefvRobustANGLE" => p!(glGetMultisamplefvRobustANGLE),
        "glGetQueryivRobustANGLE" => p!(glGetQueryivRobustANGLE),
        "glGetQueryObjecti64vRobustANGLE" => p!(glGetQueryObjecti64vRobustANGLE),
        "glGetQueryObjectivRobustANGLE" => p!(glGetQueryObjectivRobustANGLE),
        "glGetQueryObjectui64vRobustANGLE" => p!(glGetQueryObjectui64vRobustANGLE),
        "glGetQueryObjectuivRobustANGLE" => p!(glGetQueryObjectuivRobustANGLE),
        "glGetRenderbufferParameterivRobustANGLE" => p!(glGetRenderbufferParameterivRobustANGLE),
        "glGetSamplerParameterfvRobustANGLE" => p!(glGetSamplerParameterfvRobustANGLE),
        "glGetSamplerParameterivRobustANGLE" => p!(glGetSamplerParameterivRobustANGLE),
        "glGetShaderInfoLog" => p!(glGetShaderInfoLog),
        "glGetShaderivRobustANGLE" => p!(glGetShaderivRobustANGLE),
        "glGetProgramInfoLog" => p!(glGetProgramInfoLog),
        "glGetUniformLocation" => p!(glGetUniformLocation),
        "glGetAttribLocation" => p!(glGetAttribLocation),
        "glBindAttribLocation" => p!(glBindAttribLocation),
        "glGetActiveUniform" => p!(glGetActiveUniform),
        "glGetActiveAttrib" => p!(glGetActiveAttrib),
        // ---- GLES: buffers ----
        "glGenBuffers" => p!(glGenBuffers),
        "glBindBuffer" => p!(glBindBuffer),
        "glBufferData" => p!(glBufferData),
        "glBufferSubData" => p!(glBufferSubData),
        "glDeleteBuffers" => p!(glDeleteBuffers),
        // ---- GLES: textures ----
        "glGenTextures" => p!(glGenTextures),
        "glActiveTexture" => p!(glActiveTexture),
        "glBindTexture" => p!(glBindTexture),
        "glTexImage2D" => p!(glTexImage2D),
        "glTexParameteri" => p!(glTexParameteri),
        "glTexParameterf" => p!(glTexParameterf),
        "glTexParameterfv" => p!(glTexParameterfv),
        "glTexParameteriv" => p!(glTexParameteriv),
        "glGetTexParameterfvRobustANGLE" => p!(glGetTexParameterfvRobustANGLE),
        "glGetTexParameterivRobustANGLE" => p!(glGetTexParameterivRobustANGLE),
        "glGetTexLevelParameterfvRobustANGLE" => p!(glGetTexLevelParameterfvRobustANGLE),
        "glGetTexLevelParameterivRobustANGLE" => p!(glGetTexLevelParameterivRobustANGLE),
        "glGetVertexAttribfvRobustANGLE" => p!(glGetVertexAttribfvRobustANGLE),
        "glGetVertexAttribivRobustANGLE" => p!(glGetVertexAttribivRobustANGLE),
        "glGetVertexAttribIivRobustANGLE" => p!(glGetVertexAttribIivRobustANGLE),
        "glGetVertexAttribIuivRobustANGLE" => p!(glGetVertexAttribIuivRobustANGLE),
        "glGetVertexAttribPointervRobustANGLE" => p!(glGetVertexAttribPointervRobustANGLE),
        "glGetUniformfvRobustANGLE" => p!(glGetUniformfvRobustANGLE),
        "glGetUniformivRobustANGLE" => p!(glGetUniformivRobustANGLE),
        "glGetUniformuivRobustANGLE" => p!(glGetUniformuivRobustANGLE),
        "glReadPixelsRobustANGLE" => p!(glReadPixelsRobustANGLE),
        "glSamplerParameterfvRobustANGLE" => p!(glSamplerParameterfvRobustANGLE),
        "glSamplerParameterivRobustANGLE" => p!(glSamplerParameterivRobustANGLE),
        "glTexImage2DRobustANGLE" => p!(glTexImage2DRobustANGLE),
        "glTexImage3DRobustANGLE" => p!(glTexImage3DRobustANGLE),
        "glTexParameterfvRobustANGLE" => p!(glTexParameterfvRobustANGLE),
        "glTexParameterivRobustANGLE" => p!(glTexParameterivRobustANGLE),
        "glTexSubImage2DRobustANGLE" => p!(glTexSubImage2DRobustANGLE),
        "glTexSubImage3DRobustANGLE" => p!(glTexSubImage3DRobustANGLE),
        "glGenerateMipmap" => p!(glGenerateMipmap),
        "glEGLImageTargetTexture2DOES" => p!(glEGLImageTargetTexture2DOES),
        "glEGLImageTargetRenderbufferStorageOES" => {
            p!(glEGLImageTargetRenderbufferStorageOES)
        }
        "glDeleteTextures" => p!(glDeleteTextures),
        // ---- GLES: shaders + programs ----
        "glCreateShader" => p!(glCreateShader),
        "glShaderSource" => p!(glShaderSource),
        "glCompileShader" => p!(glCompileShader),
        "glCreateProgram" => p!(glCreateProgram),
        "glAttachShader" => p!(glAttachShader),
        "glLinkProgram" => p!(glLinkProgram),
        "glUseProgram" => p!(glUseProgram),
        "glUniform1i" => p!(glUniform1i),
        "glUniform2i" => p!(glUniform2i),
        "glUniform3i" => p!(glUniform3i),
        "glUniform4i" => p!(glUniform4i),
        "glUniform1iv" => p!(glUniform1iv),
        "glUniform2iv" => p!(glUniform2iv),
        "glUniform3iv" => p!(glUniform3iv),
        "glUniform4iv" => p!(glUniform4iv),
        "glUniform1f" => p!(glUniform1f),
        "glUniform2f" => p!(glUniform2f),
        "glUniform3f" => p!(glUniform3f),
        "glUniform4f" => p!(glUniform4f),
        "glUniform1fv" => p!(glUniform1fv),
        "glUniform2fv" => p!(glUniform2fv),
        "glUniform3fv" => p!(glUniform3fv),
        "glUniform4fv" => p!(glUniform4fv),
        "glUniformMatrix2fv" => p!(glUniformMatrix2fv),
        "glUniformMatrix3fv" => p!(glUniformMatrix3fv),
        "glUniformMatrix4fv" => p!(glUniformMatrix4fv),
        // ---- GLES: vertex attributes + fixed-function state ----
        "glVertexAttribPointer" => p!(glVertexAttribPointer),
        "glEnableVertexAttribArray" => p!(glEnableVertexAttribArray),
        "glDisableVertexAttribArray" => p!(glDisableVertexAttribArray),
        "glVertexAttribDivisor" => p!(glVertexAttribDivisor),
        "glClearColor" => p!(glClearColor),
        "glClearDepthf" => p!(glClearDepthf),
        "glClearDepth" => p!(glClearDepth),
        "glViewport" => p!(glViewport),
        "glScissor" => p!(glScissor),
        "glEnable" => p!(glEnable),
        "glDisable" => p!(glDisable),
        "glBlendFunc" => p!(glBlendFunc),
        "glBlendFuncSeparate" => p!(glBlendFuncSeparate),
        "glDepthFunc" => p!(glDepthFunc),
        "glDepthMask" => p!(glDepthMask),
        "glCullFace" => p!(glCullFace),
        "glFrontFace" => p!(glFrontFace),
        // ---- GLES: draw recording ----
        "glClear" => p!(glClear),
        "glDrawArrays" => p!(glDrawArrays),
        "glDrawElements" => p!(glDrawElements),
        "glDrawArraysInstanced" => p!(glDrawArraysInstanced),
        "glDrawElementsInstanced" => p!(glDrawElementsInstanced),
        "glReadPixels" => p!(glReadPixels),
        // ---- GLES: vertex array objects ----
        "glGenVertexArrays" => p!(glGenVertexArrays),
        "glBindVertexArray" => p!(glBindVertexArray),
        "glDeleteVertexArrays" => p!(glDeleteVertexArrays),
        "glIsVertexArray" => p!(glIsVertexArray),
        // ---- GLES: framebuffer + renderbuffer objects (offscreen render targets) ----
        "glGenFramebuffers" => p!(glGenFramebuffers),
        "glBindFramebuffer" => p!(glBindFramebuffer),
        "glDeleteFramebuffers" => p!(glDeleteFramebuffers),
        "glIsFramebuffer" => p!(glIsFramebuffer),
        "glCheckFramebufferStatus" => p!(glCheckFramebufferStatus),
        "glFramebufferTexture2D" => p!(glFramebufferTexture2D),
        "glGenRenderbuffers" => p!(glGenRenderbuffers),
        "glBindRenderbuffer" => p!(glBindRenderbuffer),
        "glDeleteRenderbuffers" => p!(glDeleteRenderbuffers),
        "glIsRenderbuffer" => p!(glIsRenderbuffer),
        "glRenderbufferStorage" => p!(glRenderbufferStorage),
        "glFramebufferRenderbuffer" => p!(glFramebufferRenderbuffer),
        "glBlitFramebuffer" => p!(glBlitFramebuffer),
        // ---- GLES3.1: compute dispatch ----
        "glDispatchCompute" => p!(glDispatchCompute),
        "glDispatchComputeIndirect" => p!(glDispatchComputeIndirect),
        // ---- GLES3.0: sync objects (GLsync) ----
        "glFenceSync" => p!(glFenceSync),
        "glClientWaitSync" => p!(glClientWaitSync),
        "glWaitSync" => p!(glWaitSync),
        "glDeleteSync" => p!(glDeleteSync),
        "glIsSync" => p!(glIsSync),
        "glGetSynciv" => p!(glGetSynciv),
        // ---- GLES3.0: indexed buffer bindings (UBO/SSBO) ----
        "glBindBufferBase" => p!(glBindBufferBase),
        "glBindBufferRange" => p!(glBindBufferRange),
        // ---- GLES3.0: PBO-style buffer mapping ----
        "glMapBufferRange" => p!(glMapBufferRange),
        "glUnmapBuffer" => p!(glUnmapBuffer),
        "glFlushMappedBufferRange" => p!(glFlushMappedBufferRange),
        // ---- GLES3.0: MRT draw/read buffer selection ----
        "glDrawBuffers" => p!(glDrawBuffers),
        "glReadBuffer" => p!(glReadBuffer),
        // ---- GLES3.0: sampler objects ----
        "glGenSamplers" => p!(glGenSamplers),
        "glDeleteSamplers" => p!(glDeleteSamplers),
        "glBindSampler" => p!(glBindSampler),
        "glIsSampler" => p!(glIsSampler),
        "glSamplerParameteri" => p!(glSamplerParameteri),
        "glSamplerParameterf" => p!(glSamplerParameterf),
        "glSamplerParameteriv" => p!(glSamplerParameteriv),
        "glSamplerParameterfv" => p!(glSamplerParameterfv),
        "glSamplerParameterIiv" => p!(glSamplerParameterIiv),
        "glSamplerParameterIuiv" => p!(glSamplerParameterIuiv),
        "glGetSamplerParameteriv" => p!(glGetSamplerParameteriv),
        "glGetSamplerParameterfv" => p!(glGetSamplerParameterfv),
        "glGetSamplerParameterIiv" => p!(glGetSamplerParameterIiv),
        "glGetSamplerParameterIuiv" => p!(glGetSamplerParameterIuiv),
        // ---- GLES3.0: query objects ----
        "glGenQueries" => p!(glGenQueries),
        "glDeleteQueries" => p!(glDeleteQueries),
        "glBeginQuery" => p!(glBeginQuery),
        "glEndQuery" => p!(glEndQuery),
        "glIsQuery" => p!(glIsQuery),
        "glGetQueryiv" => p!(glGetQueryiv),
        "glGetQueryObjectuiv" => p!(glGetQueryObjectuiv),
        // ---- GLES3.0: transform-feedback objects ----
        "glGenTransformFeedbacks" => p!(glGenTransformFeedbacks),
        "glDeleteTransformFeedbacks" => p!(glDeleteTransformFeedbacks),
        "glBindTransformFeedback" => p!(glBindTransformFeedback),
        "glIsTransformFeedback" => p!(glIsTransformFeedback),
        "glBeginTransformFeedback" => p!(glBeginTransformFeedback),
        "glEndTransformFeedback" => p!(glEndTransformFeedback),
        "glPauseTransformFeedback" => p!(glPauseTransformFeedback),
        "glResumeTransformFeedback" => p!(glResumeTransformFeedback),
        "glTransformFeedbackVaryings" => p!(glTransformFeedbackVaryings),
        "glGetTransformFeedbackVarying" => p!(glGetTransformFeedbackVarying),
        // ---- GLES3.1: program pipeline objects ----
        "glGenProgramPipelines" => p!(glGenProgramPipelines),
        "glDeleteProgramPipelines" => p!(glDeleteProgramPipelines),
        "glBindProgramPipeline" => p!(glBindProgramPipeline),
        "glIsProgramPipeline" => p!(glIsProgramPipeline),
        "glUseProgramStages" => p!(glUseProgramStages),
        "glActiveShaderProgram" => p!(glActiveShaderProgram),
        "glProgramParameteri" => p!(glProgramParameteri),
        "glGetProgramPipelineiv" => p!(glGetProgramPipelineiv),
        "glGetProgramPipelineInfoLog" => p!(glGetProgramPipelineInfoLog),
        "glValidateProgramPipeline" => p!(glValidateProgramPipeline),
        "glCreateShaderProgramv" => p!(glCreateShaderProgramv),
        // ---- GLES3.0: texture storage / 3D / sub-image / copy ----
        "glTexStorage2D" => p!(glTexStorage2D),
        "glTexStorage3D" => p!(glTexStorage3D),
        "glTexImage3D" => p!(glTexImage3D),
        "glTexSubImage2D" => p!(glTexSubImage2D),
        "glTexSubImage3D" => p!(glTexSubImage3D),
        "glCopyTexSubImage2D" => p!(glCopyTexSubImage2D),
        "glCopyTexSubImage3D" => p!(glCopyTexSubImage3D),
        "glCopyTexImage2D" => p!(glCopyTexImage2D),
        "glCompressedTexImage2D" => p!(glCompressedTexImage2D),
        "glCompressedTexImage3D" => p!(glCompressedTexImage3D),
        "glCompressedTexSubImage2D" => p!(glCompressedTexSubImage2D),
        "glCompressedTexSubImage3D" => p!(glCompressedTexSubImage3D),
        // ---- GLES3.0: buffer / texture / vertex-attribute queries ----
        "glGetBufferParameteriv" => p!(glGetBufferParameteriv),
        "glGetBufferParameteri64v" => p!(glGetBufferParameteri64v),
        "glGetTexParameteriv" => p!(glGetTexParameteriv),
        "glGetTexParameterfv" => p!(glGetTexParameterfv),
        "glGetTexParameterIiv" => p!(glGetTexParameterIiv),
        "glGetTexParameterIuiv" => p!(glGetTexParameterIuiv),
        "glGetVertexAttribfv" => p!(glGetVertexAttribfv),
        "glGetVertexAttribiv" => p!(glGetVertexAttribiv),
        "glGetVertexAttribIiv" => p!(glGetVertexAttribIiv),
        "glGetVertexAttribIuiv" => p!(glGetVertexAttribIuiv),
        "glGetVertexAttribPointerv" => p!(glGetVertexAttribPointerv),
        // ---- GLES3.0: buffer copy + bounded readback ----
        "glCopyBufferSubData" => p!(glCopyBufferSubData),
        "glReadnPixels" => p!(glReadnPixels),
        // ---- GLES3.0: constant + integer vertex attributes ----
        "glVertexAttrib1f" => p!(glVertexAttrib1f),
        "glVertexAttrib2f" => p!(glVertexAttrib2f),
        "glVertexAttrib3f" => p!(glVertexAttrib3f),
        "glVertexAttrib4f" => p!(glVertexAttrib4f),
        "glVertexAttrib1fv" => p!(glVertexAttrib1fv),
        "glVertexAttrib2fv" => p!(glVertexAttrib2fv),
        "glVertexAttrib3fv" => p!(glVertexAttrib3fv),
        "glVertexAttrib4fv" => p!(glVertexAttrib4fv),
        "glVertexAttribI4i" => p!(glVertexAttribI4i),
        "glVertexAttribI4ui" => p!(glVertexAttribI4ui),
        "glVertexAttribI4iv" => p!(glVertexAttribI4iv),
        "glVertexAttribI4uiv" => p!(glVertexAttribI4uiv),
        "glVertexAttribIPointer" => p!(glVertexAttribIPointer),
        "glVertexAttribIFormat" => p!(glVertexAttribIFormat),
        // ---- GLES3.0: invalidation hints + separate-face stencil ----
        "glInvalidateFramebuffer" => p!(glInvalidateFramebuffer),
        "glInvalidateSubFramebuffer" => p!(glInvalidateSubFramebuffer),
        "glStencilFuncSeparate" => p!(glStencilFuncSeparate),
        "glStencilMaskSeparate" => p!(glStencilMaskSeparate),
        "glStencilOpSeparate" => p!(glStencilOpSeparate),
        _ => extra::resolve(name),
    };
    if address.is_null() && std::env::var_os("HL_SHIM_DEBUG").is_some() {
        eprintln!("[hl-gl-shim] eglGetProcAddress unresolved name={name}");
    } else if name.contains("DebugMessage") && std::env::var_os("HL_SHIM_DEBUG").is_some() {
        eprintln!("[hl-gl-shim] eglGetProcAddress resolved name={name}");
    }
    address
}
