use super::*;

/// Resolves a hand-written EGL or GLES entry point to its exported C function address.
#[cfg_attr(not(gles_client), no_mangle)]
pub extern "C" fn eglGetProcAddress(procname: *const c_char) -> *mut c_void {
    if procname.is_null() {
        return core::ptr::null_mut();
    }
    let name = match unsafe { core::ffi::CStr::from_ptr(procname) }.to_str() {
        Ok(s) => s,
        Err(_) => return core::ptr::null_mut(),
    };
    // Map each core entry point name to its address. `f as usize as *mut c_void` erases the specific
    // `extern "C"` fn type to the opaque function pointer EGL hands back.
    macro_rules! p {
        ($f:path) => {
            $f as *const () as *mut c_void
        };
    }
    match name {
        // ---- EGL: display / config / context / surface lifecycle + present ----
        "eglGetError" => p!(eglGetError),
        "eglGetDisplay" => p!(eglGetDisplay),
        "eglInitialize" => p!(eglInitialize),
        "eglTerminate" => p!(eglTerminate),
        "eglQueryString" => p!(eglQueryString),
        "eglGetProcAddress" => p!(eglGetProcAddress),
        "eglBindAPI" => p!(eglBindAPI),
        "eglChooseConfig" => p!(eglChooseConfig),
        "eglGetConfigs" => p!(eglGetConfigs),
        "eglGetConfigAttrib" => p!(eglGetConfigAttrib),
        "eglCreateContext" => p!(eglCreateContext),
        "eglDestroyContext" => p!(eglDestroyContext),
        "eglMakeCurrent" => p!(eglMakeCurrent),
        "eglCreateWindowSurface" => p!(eglCreateWindowSurface),
        "eglDestroySurface" => p!(eglDestroySurface),
        "eglSwapBuffers" => p!(eglSwapBuffers),
        "eglSwapInterval" => p!(eglSwapInterval),
        "eglGetCurrentDisplay" => p!(eglGetCurrentDisplay),
        "eglGetCurrentContext" => p!(eglGetCurrentContext),
        "eglGetCurrentSurface" => p!(eglGetCurrentSurface),
        // ---- GLES: error / string / query ----
        "glGetError" => p!(glGetError),
        "glGetString" => p!(glGetString),
        "glGetStringi" => p!(glGetStringi),
        "glGetIntegerv" => p!(glGetIntegerv),
        "glGetFloatv" => p!(glGetFloatv),
        "glGetBooleanv" => p!(glGetBooleanv),
        "glPixelStorei" => p!(glPixelStorei),
        // ---- GLES: shader / program introspection ----
        "glGetShaderiv" => p!(glGetShaderiv),
        "glGetProgramiv" => p!(glGetProgramiv),
        "glGetShaderInfoLog" => p!(glGetShaderInfoLog),
        "glGetProgramInfoLog" => p!(glGetProgramInfoLog),
        "glGetUniformLocation" => p!(glGetUniformLocation),
        "glGetAttribLocation" => p!(glGetAttribLocation),
        "glBindAttribLocation" => p!(glBindAttribLocation),
        "glGetActiveUniform" => p!(glGetActiveUniform),
        "glGetActiveAttrib" => p!(glGetActiveAttrib),
        // ---- GLES: buffers ----
        "glGenBuffers" => p!(glGenBuffers),
        "glBindBuffer" => p!(glBindBuffer),
        "glBufferData" => p!(glBufferData),
        "glBufferSubData" => p!(glBufferSubData),
        "glDeleteBuffers" => p!(glDeleteBuffers),
        // ---- GLES: textures ----
        "glGenTextures" => p!(glGenTextures),
        "glActiveTexture" => p!(glActiveTexture),
        "glBindTexture" => p!(glBindTexture),
        "glTexImage2D" => p!(glTexImage2D),
        "glTexParameteri" => p!(glTexParameteri),
        "glTexParameterf" => p!(glTexParameterf),
        "glTexParameterfv" => p!(glTexParameterfv),
        "glTexParameteriv" => p!(glTexParameteriv),
        "glGenerateMipmap" => p!(glGenerateMipmap),
        "glDeleteTextures" => p!(glDeleteTextures),
        // ---- GLES: shaders + programs ----
        "glCreateShader" => p!(glCreateShader),
        "glShaderSource" => p!(glShaderSource),
        "glCompileShader" => p!(glCompileShader),
        "glCreateProgram" => p!(glCreateProgram),
        "glAttachShader" => p!(glAttachShader),
        "glLinkProgram" => p!(glLinkProgram),
        "glUseProgram" => p!(glUseProgram),
        "glUniform1i" => p!(glUniform1i),
        "glUniform2i" => p!(glUniform2i),
        "glUniform3i" => p!(glUniform3i),
        "glUniform4i" => p!(glUniform4i),
        "glUniform1iv" => p!(glUniform1iv),
        "glUniform2iv" => p!(glUniform2iv),
        "glUniform3iv" => p!(glUniform3iv),
        "glUniform4iv" => p!(glUniform4iv),
        "glUniform1f" => p!(glUniform1f),
        "glUniform2f" => p!(glUniform2f),
        "glUniform3f" => p!(glUniform3f),
        "glUniform4f" => p!(glUniform4f),
        "glUniform1fv" => p!(glUniform1fv),
        "glUniform2fv" => p!(glUniform2fv),
        "glUniform3fv" => p!(glUniform3fv),
        "glUniform4fv" => p!(glUniform4fv),
        "glUniformMatrix2fv" => p!(glUniformMatrix2fv),
        "glUniformMatrix3fv" => p!(glUniformMatrix3fv),
        "glUniformMatrix4fv" => p!(glUniformMatrix4fv),
        // ---- GLES: vertex attributes + fixed-function state ----
        "glVertexAttribPointer" => p!(glVertexAttribPointer),
        "glEnableVertexAttribArray" => p!(glEnableVertexAttribArray),
        "glDisableVertexAttribArray" => p!(glDisableVertexAttribArray),
        "glVertexAttribDivisor" => p!(glVertexAttribDivisor),
        "glClearColor" => p!(glClearColor),
        "glClearDepthf" => p!(glClearDepthf),
        "glViewport" => p!(glViewport),
        "glScissor" => p!(glScissor),
        "glEnable" => p!(glEnable),
        "glDisable" => p!(glDisable),
        "glBlendFunc" => p!(glBlendFunc),
        "glBlendFuncSeparate" => p!(glBlendFuncSeparate),
        "glDepthFunc" => p!(glDepthFunc),
        "glDepthMask" => p!(glDepthMask),
        "glCullFace" => p!(glCullFace),
        "glFrontFace" => p!(glFrontFace),
        // ---- GLES: draw recording ----
        "glClear" => p!(glClear),
        "glDrawArrays" => p!(glDrawArrays),
        "glDrawElements" => p!(glDrawElements),
        "glDrawArraysInstanced" => p!(glDrawArraysInstanced),
        "glDrawElementsInstanced" => p!(glDrawElementsInstanced),
        "glReadPixels" => p!(glReadPixels),
        // ---- GLES: vertex array objects ----
        "glGenVertexArrays" => p!(glGenVertexArrays),
        "glBindVertexArray" => p!(glBindVertexArray),
        "glDeleteVertexArrays" => p!(glDeleteVertexArrays),
        "glIsVertexArray" => p!(glIsVertexArray),
        // ---- GLES: framebuffer + renderbuffer objects (offscreen render targets) ----
        "glGenFramebuffers" => p!(glGenFramebuffers),
        "glBindFramebuffer" => p!(glBindFramebuffer),
        "glDeleteFramebuffers" => p!(glDeleteFramebuffers),
        "glIsFramebuffer" => p!(glIsFramebuffer),
        "glCheckFramebufferStatus" => p!(glCheckFramebufferStatus),
        "glFramebufferTexture2D" => p!(glFramebufferTexture2D),
        "glGenRenderbuffers" => p!(glGenRenderbuffers),
        "glBindRenderbuffer" => p!(glBindRenderbuffer),
        "glDeleteRenderbuffers" => p!(glDeleteRenderbuffers),
        "glIsRenderbuffer" => p!(glIsRenderbuffer),
        "glRenderbufferStorage" => p!(glRenderbufferStorage),
        "glFramebufferRenderbuffer" => p!(glFramebufferRenderbuffer),
        "glBlitFramebuffer" => p!(glBlitFramebuffer),
        // ---- GLES3.1: compute dispatch ----
        "glDispatchCompute" => p!(glDispatchCompute),
        "glDispatchComputeIndirect" => p!(glDispatchComputeIndirect),
        // ---- GLES3.0: sync objects (GLsync) ----
        "glFenceSync" => p!(glFenceSync),
        "glClientWaitSync" => p!(glClientWaitSync),
        "glWaitSync" => p!(glWaitSync),
        "glDeleteSync" => p!(glDeleteSync),
        "glIsSync" => p!(glIsSync),
        "glGetSynciv" => p!(glGetSynciv),
        // ---- GLES3.0: indexed buffer bindings (UBO/SSBO) ----
        "glBindBufferBase" => p!(glBindBufferBase),
        "glBindBufferRange" => p!(glBindBufferRange),
        // ---- GLES3.0: PBO-style buffer mapping ----
        "glMapBufferRange" => p!(glMapBufferRange),
        "glUnmapBuffer" => p!(glUnmapBuffer),
        "glFlushMappedBufferRange" => p!(glFlushMappedBufferRange),
        // ---- GLES3.0: MRT draw/read buffer selection ----
        "glDrawBuffers" => p!(glDrawBuffers),
        "glReadBuffer" => p!(glReadBuffer),
        // ---- GLES3.0: sampler objects ----
        "glGenSamplers" => p!(glGenSamplers),
        "glDeleteSamplers" => p!(glDeleteSamplers),
        "glBindSampler" => p!(glBindSampler),
        "glIsSampler" => p!(glIsSampler),
        "glSamplerParameteri" => p!(glSamplerParameteri),
        "glSamplerParameterf" => p!(glSamplerParameterf),
        "glSamplerParameteriv" => p!(glSamplerParameteriv),
        "glSamplerParameterfv" => p!(glSamplerParameterfv),
        "glSamplerParameterIiv" => p!(glSamplerParameterIiv),
        "glSamplerParameterIuiv" => p!(glSamplerParameterIuiv),
        "glGetSamplerParameteriv" => p!(glGetSamplerParameteriv),
        "glGetSamplerParameterfv" => p!(glGetSamplerParameterfv),
        "glGetSamplerParameterIiv" => p!(glGetSamplerParameterIiv),
        "glGetSamplerParameterIuiv" => p!(glGetSamplerParameterIuiv),
        // ---- GLES3.0: query objects ----
        "glGenQueries" => p!(glGenQueries),
        "glDeleteQueries" => p!(glDeleteQueries),
        "glBeginQuery" => p!(glBeginQuery),
        "glEndQuery" => p!(glEndQuery),
        "glIsQuery" => p!(glIsQuery),
        "glGetQueryiv" => p!(glGetQueryiv),
        "glGetQueryObjectuiv" => p!(glGetQueryObjectuiv),
        // ---- GLES3.0: transform-feedback objects ----
        "glGenTransformFeedbacks" => p!(glGenTransformFeedbacks),
        "glDeleteTransformFeedbacks" => p!(glDeleteTransformFeedbacks),
        "glBindTransformFeedback" => p!(glBindTransformFeedback),
        "glIsTransformFeedback" => p!(glIsTransformFeedback),
        "glBeginTransformFeedback" => p!(glBeginTransformFeedback),
        "glEndTransformFeedback" => p!(glEndTransformFeedback),
        "glPauseTransformFeedback" => p!(glPauseTransformFeedback),
        "glResumeTransformFeedback" => p!(glResumeTransformFeedback),
        "glTransformFeedbackVaryings" => p!(glTransformFeedbackVaryings),
        "glGetTransformFeedbackVarying" => p!(glGetTransformFeedbackVarying),
        // ---- GLES3.1: program pipeline objects ----
        "glGenProgramPipelines" => p!(glGenProgramPipelines),
        "glDeleteProgramPipelines" => p!(glDeleteProgramPipelines),
        "glBindProgramPipeline" => p!(glBindProgramPipeline),
        "glIsProgramPipeline" => p!(glIsProgramPipeline),
        "glUseProgramStages" => p!(glUseProgramStages),
        "glActiveShaderProgram" => p!(glActiveShaderProgram),
        "glProgramParameteri" => p!(glProgramParameteri),
        "glGetProgramPipelineiv" => p!(glGetProgramPipelineiv),
        "glGetProgramPipelineInfoLog" => p!(glGetProgramPipelineInfoLog),
        "glValidateProgramPipeline" => p!(glValidateProgramPipeline),
        "glCreateShaderProgramv" => p!(glCreateShaderProgramv),
        // ---- GLES3.0: texture storage / 3D / sub-image / copy ----
        "glTexStorage2D" => p!(glTexStorage2D),
        "glTexStorage3D" => p!(glTexStorage3D),
        "glTexImage3D" => p!(glTexImage3D),
        "glTexSubImage2D" => p!(glTexSubImage2D),
        "glTexSubImage3D" => p!(glTexSubImage3D),
        "glCopyTexSubImage2D" => p!(glCopyTexSubImage2D),
        "glCopyTexSubImage3D" => p!(glCopyTexSubImage3D),
        "glCopyTexImage2D" => p!(glCopyTexImage2D),
        "glCompressedTexImage2D" => p!(glCompressedTexImage2D),
        "glCompressedTexImage3D" => p!(glCompressedTexImage3D),
        "glCompressedTexSubImage2D" => p!(glCompressedTexSubImage2D),
        "glCompressedTexSubImage3D" => p!(glCompressedTexSubImage3D),
        // ---- GLES3.0: buffer / texture / vertex-attribute queries ----
        "glGetBufferParameteriv" => p!(glGetBufferParameteriv),
        "glGetBufferParameteri64v" => p!(glGetBufferParameteri64v),
        "glGetTexParameteriv" => p!(glGetTexParameteriv),
        "glGetTexParameterfv" => p!(glGetTexParameterfv),
        "glGetTexParameterIiv" => p!(glGetTexParameterIiv),
        "glGetTexParameterIuiv" => p!(glGetTexParameterIuiv),
        "glGetVertexAttribfv" => p!(glGetVertexAttribfv),
        "glGetVertexAttribiv" => p!(glGetVertexAttribiv),
        "glGetVertexAttribIiv" => p!(glGetVertexAttribIiv),
        "glGetVertexAttribIuiv" => p!(glGetVertexAttribIuiv),
        "glGetVertexAttribPointerv" => p!(glGetVertexAttribPointerv),
        // ---- GLES3.0: buffer copy + bounded readback ----
        "glCopyBufferSubData" => p!(glCopyBufferSubData),
        "glReadnPixels" => p!(glReadnPixels),
        // ---- GLES3.0: constant + integer vertex attributes ----
        "glVertexAttrib1f" => p!(glVertexAttrib1f),
        "glVertexAttrib2f" => p!(glVertexAttrib2f),
        "glVertexAttrib3f" => p!(glVertexAttrib3f),
        "glVertexAttrib4f" => p!(glVertexAttrib4f),
        "glVertexAttrib1fv" => p!(glVertexAttrib1fv),
        "glVertexAttrib2fv" => p!(glVertexAttrib2fv),
        "glVertexAttrib3fv" => p!(glVertexAttrib3fv),
        "glVertexAttrib4fv" => p!(glVertexAttrib4fv),
        "glVertexAttribI4i" => p!(glVertexAttribI4i),
        "glVertexAttribI4ui" => p!(glVertexAttribI4ui),
        "glVertexAttribI4iv" => p!(glVertexAttribI4iv),
        "glVertexAttribI4uiv" => p!(glVertexAttribI4uiv),
        "glVertexAttribIPointer" => p!(glVertexAttribIPointer),
        "glVertexAttribIFormat" => p!(glVertexAttribIFormat),
        // ---- GLES3.0: invalidation hints + separate-face stencil ----
        "glInvalidateFramebuffer" => p!(glInvalidateFramebuffer),
        "glInvalidateSubFramebuffer" => p!(glInvalidateSubFramebuffer),
        "glStencilFuncSeparate" => p!(glStencilFuncSeparate),
        "glStencilMaskSeparate" => p!(glStencilMaskSeparate),
        "glStencilOpSeparate" => p!(glStencilOpSeparate),
        // ---- ES3 / GLES3.1 completeness pass + remaining EGL (real bodies below) ----
        "eglBindTexImage" => p!(eglBindTexImage),
        "eglClientWaitSync" => p!(eglClientWaitSync),
        "eglCopyBuffers" => p!(eglCopyBuffers),
        "eglCreateImage" => p!(eglCreateImage),
        "eglCreatePbufferFromClientBuffer" => p!(eglCreatePbufferFromClientBuffer),
        "eglCreatePbufferSurface" => p!(eglCreatePbufferSurface),
        "eglCreatePixmapSurface" => p!(eglCreatePixmapSurface),
        "eglCreatePlatformPixmapSurface" => p!(eglCreatePlatformPixmapSurface),
        "eglCreatePlatformWindowSurface" => p!(eglCreatePlatformWindowSurface),
        "eglCreateSync" => p!(eglCreateSync),
        "eglDestroyImage" => p!(eglDestroyImage),
        "eglDestroySync" => p!(eglDestroySync),
        "eglGetPlatformDisplay" => p!(eglGetPlatformDisplay),
        // EGL_EXT_platform_base — advertised in the client extension string, so a caller (e.g. the real
        // `eglinfo`) resolves + calls these without a null check. Resolved here only (not exported ABI).
        "eglGetPlatformDisplayEXT" => p!(eglGetPlatformDisplayEXT),
        "eglCreatePlatformWindowSurfaceEXT" => p!(eglCreatePlatformWindowSurfaceEXT),
        "eglCreatePlatformPixmapSurfaceEXT" => p!(eglCreatePlatformPixmapSurfaceEXT),
        // EGL_EXT_device_base / device_query / device_enumeration — advertised in the client + display
        // extension strings (GDK/epoxy require one of the device_* set to find eglQueryDisplayAttribEXT).
        // Resolved here only (extension functions, not exported ABI).
        "eglQueryDisplayAttribEXT" => p!(eglQueryDisplayAttribEXT),
        "eglQueryDeviceAttribEXT" => p!(eglQueryDeviceAttribEXT),
        "eglQueryDeviceStringEXT" => p!(eglQueryDeviceStringEXT),
        "eglQueryDevicesEXT" => p!(eglQueryDevicesEXT),
        "eglGetSyncAttrib" => p!(eglGetSyncAttrib),
        "eglQueryAPI" => p!(eglQueryAPI),
        "eglQueryContext" => p!(eglQueryContext),
        "eglQuerySurface" => p!(eglQuerySurface),
        "eglReleaseTexImage" => p!(eglReleaseTexImage),
        "eglReleaseThread" => p!(eglReleaseThread),
        "eglSurfaceAttrib" => p!(eglSurfaceAttrib),
        "eglWaitClient" => p!(eglWaitClient),
        "eglWaitGL" => p!(eglWaitGL),
        "eglWaitNative" => p!(eglWaitNative),
        "eglWaitSync" => p!(eglWaitSync),
        "glBindImageTexture" => p!(glBindImageTexture),
        "glBindVertexBuffer" => p!(glBindVertexBuffer),
        "glBlendBarrier" => p!(glBlendBarrier),
        "glBlendColor" => p!(glBlendColor),
        "glBlendEquation" => p!(glBlendEquation),
        "glBlendEquationSeparate" => p!(glBlendEquationSeparate),
        "glBlendEquationSeparatei" => p!(glBlendEquationSeparatei),
        "glBlendEquationi" => p!(glBlendEquationi),
        "glBlendFuncSeparatei" => p!(glBlendFuncSeparatei),
        "glBlendFunci" => p!(glBlendFunci),
        "glClearBufferfi" => p!(glClearBufferfi),
        "glClearBufferfv" => p!(glClearBufferfv),
        "glClearBufferiv" => p!(glClearBufferiv),
        "glClearBufferuiv" => p!(glClearBufferuiv),
        "glClearStencil" => p!(glClearStencil),
        "glColorMask" => p!(glColorMask),
        "glColorMaski" => p!(glColorMaski),
        "glCopyImageSubData" => p!(glCopyImageSubData),
        "glDebugMessageCallback" => p!(glDebugMessageCallback),
        "glDebugMessageControl" => p!(glDebugMessageControl),
        "glDebugMessageInsert" => p!(glDebugMessageInsert),
        "glDeleteProgram" => p!(glDeleteProgram),
        "glDeleteShader" => p!(glDeleteShader),
        "glDepthRangef" => p!(glDepthRangef),
        "glDetachShader" => p!(glDetachShader),
        "glDisablei" => p!(glDisablei),
        "glDrawArraysIndirect" => p!(glDrawArraysIndirect),
        "glDrawElementsBaseVertex" => p!(glDrawElementsBaseVertex),
        "glDrawElementsIndirect" => p!(glDrawElementsIndirect),
        "glDrawElementsInstancedBaseVertex" => p!(glDrawElementsInstancedBaseVertex),
        "glDrawRangeElements" => p!(glDrawRangeElements),
        "glDrawRangeElementsBaseVertex" => p!(glDrawRangeElementsBaseVertex),
        "glEnablei" => p!(glEnablei),
        "glFinish" => p!(glFinish),
        "glFlush" => p!(glFlush),
        "glFramebufferParameteri" => p!(glFramebufferParameteri),
        "glFramebufferTexture" => p!(glFramebufferTexture),
        "glFramebufferTextureLayer" => p!(glFramebufferTextureLayer),
        "glGetActiveUniformBlockName" => p!(glGetActiveUniformBlockName),
        "glGetActiveUniformBlockiv" => p!(glGetActiveUniformBlockiv),
        "glGetActiveUniformsiv" => p!(glGetActiveUniformsiv),
        "glGetAttachedShaders" => p!(glGetAttachedShaders),
        "glGetBooleani_v" => p!(glGetBooleani_v),
        "glGetBufferPointerv" => p!(glGetBufferPointerv),
        "glGetDebugMessageLog" => p!(glGetDebugMessageLog),
        "glGetFragDataLocation" => p!(glGetFragDataLocation),
        "glGetFramebufferAttachmentParameteriv" => p!(glGetFramebufferAttachmentParameteriv),
        "glGetFramebufferParameteriv" => p!(glGetFramebufferParameteriv),
        "glGetGraphicsResetStatus" => p!(glGetGraphicsResetStatus),
        "glGetInteger64i_v" => p!(glGetInteger64i_v),
        "glGetInteger64v" => p!(glGetInteger64v),
        "glGetIntegeri_v" => p!(glGetIntegeri_v),
        "glGetInternalformativ" => p!(glGetInternalformativ),
        "glGetMultisamplefv" => p!(glGetMultisamplefv),
        "glGetObjectLabel" => p!(glGetObjectLabel),
        "glGetObjectPtrLabel" => p!(glGetObjectPtrLabel),
        "glGetPointerv" => p!(glGetPointerv),
        "glGetProgramBinary" => p!(glGetProgramBinary),
        "glGetProgramInterfaceiv" => p!(glGetProgramInterfaceiv),
        "glGetProgramResourceIndex" => p!(glGetProgramResourceIndex),
        "glGetProgramResourceLocation" => p!(glGetProgramResourceLocation),
        "glGetProgramResourceName" => p!(glGetProgramResourceName),
        "glGetProgramResourceiv" => p!(glGetProgramResourceiv),
        "glGetRenderbufferParameteriv" => p!(glGetRenderbufferParameteriv),
        "glGetShaderPrecisionFormat" => p!(glGetShaderPrecisionFormat),
        "glGetShaderSource" => p!(glGetShaderSource),
        "glGetTexLevelParameterfv" => p!(glGetTexLevelParameterfv),
        "glGetTexLevelParameteriv" => p!(glGetTexLevelParameteriv),
        "glGetUniformBlockIndex" => p!(glGetUniformBlockIndex),
        "glGetUniformIndices" => p!(glGetUniformIndices),
        "glGetUniformfv" => p!(glGetUniformfv),
        "glGetUniformiv" => p!(glGetUniformiv),
        "glGetUniformuiv" => p!(glGetUniformuiv),
        "glGetnUniformfv" => p!(glGetnUniformfv),
        "glGetnUniformiv" => p!(glGetnUniformiv),
        "glGetnUniformuiv" => p!(glGetnUniformuiv),
        "glHint" => p!(glHint),
        "glIsBuffer" => p!(glIsBuffer),
        "glIsEnabled" => p!(glIsEnabled),
        "glIsEnabledi" => p!(glIsEnabledi),
        "glIsProgram" => p!(glIsProgram),
        "glIsShader" => p!(glIsShader),
        "glIsTexture" => p!(glIsTexture),
        "glLineWidth" => p!(glLineWidth),
        "glMemoryBarrier" => p!(glMemoryBarrier),
        "glMemoryBarrierByRegion" => p!(glMemoryBarrierByRegion),
        "glMinSampleShading" => p!(glMinSampleShading),
        "glObjectLabel" => p!(glObjectLabel),
        "glObjectPtrLabel" => p!(glObjectPtrLabel),
        "glPatchParameteri" => p!(glPatchParameteri),
        "glPolygonOffset" => p!(glPolygonOffset),
        "glPopDebugGroup" => p!(glPopDebugGroup),
        "glPrimitiveBoundingBox" => p!(glPrimitiveBoundingBox),
        "glProgramBinary" => p!(glProgramBinary),
        "glProgramUniform1f" => p!(glProgramUniform1f),
        "glProgramUniform1fv" => p!(glProgramUniform1fv),
        "glProgramUniform1i" => p!(glProgramUniform1i),
        "glProgramUniform1iv" => p!(glProgramUniform1iv),
        "glProgramUniform1ui" => p!(glProgramUniform1ui),
        "glProgramUniform1uiv" => p!(glProgramUniform1uiv),
        "glProgramUniform2f" => p!(glProgramUniform2f),
        "glProgramUniform2fv" => p!(glProgramUniform2fv),
        "glProgramUniform2i" => p!(glProgramUniform2i),
        "glProgramUniform2iv" => p!(glProgramUniform2iv),
        "glProgramUniform2ui" => p!(glProgramUniform2ui),
        "glProgramUniform2uiv" => p!(glProgramUniform2uiv),
        "glProgramUniform3f" => p!(glProgramUniform3f),
        "glProgramUniform3fv" => p!(glProgramUniform3fv),
        "glProgramUniform3i" => p!(glProgramUniform3i),
        "glProgramUniform3iv" => p!(glProgramUniform3iv),
        "glProgramUniform3ui" => p!(glProgramUniform3ui),
        "glProgramUniform3uiv" => p!(glProgramUniform3uiv),
        "glProgramUniform4f" => p!(glProgramUniform4f),
        "glProgramUniform4fv" => p!(glProgramUniform4fv),
        "glProgramUniform4i" => p!(glProgramUniform4i),
        "glProgramUniform4iv" => p!(glProgramUniform4iv),
        "glProgramUniform4ui" => p!(glProgramUniform4ui),
        "glProgramUniform4uiv" => p!(glProgramUniform4uiv),
        "glProgramUniformMatrix2fv" => p!(glProgramUniformMatrix2fv),
        "glProgramUniformMatrix2x3fv" => p!(glProgramUniformMatrix2x3fv),
        "glProgramUniformMatrix2x4fv" => p!(glProgramUniformMatrix2x4fv),
        "glProgramUniformMatrix3fv" => p!(glProgramUniformMatrix3fv),
        "glProgramUniformMatrix3x2fv" => p!(glProgramUniformMatrix3x2fv),
        "glProgramUniformMatrix3x4fv" => p!(glProgramUniformMatrix3x4fv),
        "glProgramUniformMatrix4fv" => p!(glProgramUniformMatrix4fv),
        "glProgramUniformMatrix4x2fv" => p!(glProgramUniformMatrix4x2fv),
        "glProgramUniformMatrix4x3fv" => p!(glProgramUniformMatrix4x3fv),
        "glPushDebugGroup" => p!(glPushDebugGroup),
        "glReleaseShaderCompiler" => p!(glReleaseShaderCompiler),
        "glRenderbufferStorageMultisample" => p!(glRenderbufferStorageMultisample),
        "glSampleCoverage" => p!(glSampleCoverage),
        "glSampleMaski" => p!(glSampleMaski),
        "glShaderBinary" => p!(glShaderBinary),
        "glStencilFunc" => p!(glStencilFunc),
        "glStencilMask" => p!(glStencilMask),
        "glStencilOp" => p!(glStencilOp),
        "glTexBuffer" => p!(glTexBuffer),
        "glTexBufferRange" => p!(glTexBufferRange),
        "glTexParameterIiv" => p!(glTexParameterIiv),
        "glTexParameterIuiv" => p!(glTexParameterIuiv),
        "glTexStorage2DMultisample" => p!(glTexStorage2DMultisample),
        "glTexStorage3DMultisample" => p!(glTexStorage3DMultisample),
        "glUniform1ui" => p!(glUniform1ui),
        "glUniform1uiv" => p!(glUniform1uiv),
        "glUniform2ui" => p!(glUniform2ui),
        "glUniform2uiv" => p!(glUniform2uiv),
        "glUniform3ui" => p!(glUniform3ui),
        "glUniform3uiv" => p!(glUniform3uiv),
        "glUniform4ui" => p!(glUniform4ui),
        "glUniform4uiv" => p!(glUniform4uiv),
        "glUniformBlockBinding" => p!(glUniformBlockBinding),
        "glUniformMatrix2x3fv" => p!(glUniformMatrix2x3fv),
        "glUniformMatrix2x4fv" => p!(glUniformMatrix2x4fv),
        "glUniformMatrix3x2fv" => p!(glUniformMatrix3x2fv),
        "glUniformMatrix3x4fv" => p!(glUniformMatrix3x4fv),
        "glUniformMatrix4x2fv" => p!(glUniformMatrix4x2fv),
        "glUniformMatrix4x3fv" => p!(glUniformMatrix4x3fv),
        "glValidateProgram" => p!(glValidateProgram),
        "glVertexAttribBinding" => p!(glVertexAttribBinding),
        "glVertexAttribFormat" => p!(glVertexAttribFormat),
        "glVertexBindingDivisor" => p!(glVertexBindingDivisor),
        // Unknown / extension name we do not advertise → spec-legal "not found".
        _ => core::ptr::null_mut(),
    }
}
