[package]
name = "hl-native"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
build = "build.rs"
links = "hl_native"

[lints]
workspace = true

[features]
native-test-hooks = []

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.4.0"

[dev-dependencies]
sha2.workspace = true
tempfile.workspace = true

[lib]
name = "hl_native"
path = "src/lib.rs"
