//! The generated CUDA Runtime API **capability inventory** — the machine-checkable census that tags
//! every exported `cuda*`/`__cuda*` entry point as `full`, `partial`, or `unsupported`, and records the
//! exact `cudaError_t` an unsupported (or out-of-supported-domain) path returns.
//!
//! Phase 0's "make completeness measurable" deliverable for the runtime library (see
//! `docs/codex-rendering.md` §2.3 / §6). Generated by `build.rs` from the manifest + a classification
//! table; the crate asserts against it at test time and `docs/rendering/SHIM_RUST_ARCHITECTURE.md` draws
//! the same census. The runtime maps to the SAME shared IR + PTX executor as the driver shim, so its
//! capability boundary is the same bounded PTX subset (see [`hl_gpu::ptx`]).

/// Capability level of an exported entry point.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Cap {
    /// Observable CUDA runtime semantics fully implemented for the modeled device.
    Full,
    /// Works within a bounded supported domain; outside it, returns `cuda_error` (or degrades to a
    /// documented no-op). See the entry's `note` for the domain.
    Partial,
    /// Always returns the defined `cudaError_t` `cuda_error` — the feature is not modeled.
    Unsupported,
}

/// One entry in the capability inventory.
#[derive(Clone, Copy, Debug)]
pub struct Entry {
    /// The exported `cuda*` / `__cuda*` symbol name.
    pub name: &'static str,
    /// full / partial / unsupported.
    pub cap: Cap,
    /// The `cudaError_t` an unsupported (or out-of-domain `partial`) path returns; `0` (`cudaSuccess`)
    /// for `full` entries and for `partial` entries that degrade to a benign no-op rather than erroring.
    pub cuda_error: i32,
    /// Human-readable supported-domain / reason note (empty for plain `full`).
    pub note: &'static str,
}

/// Single source of truth for the advertised CUDA Runtime version (`cudaRuntimeGetVersion`) and the
/// backing driver version (`cudaDriverGetVersion`): 12020 == CUDA 12.2 (ABI). The inventory test asserts
/// both entry points report exactly this, so the library never advertises a version it does not back.
pub const SUPPORTED_RUNTIME_VERSION: i32 = 12020;

/// The compute capability the modeled device advertises (`sm_86`), matching the PTX subset's target.
pub const SUPPORTED_COMPUTE_CAPABILITY: (u32, u32) = (8, 6);

// The generated inventory (`CAPABILITIES`, `CAP_FULL`, `CAP_PARTIAL`, `CAP_UNSUPPORTED`) is emitted by
// build.rs and `include!`d at the crate root (see lib.rs).
