// Writes the TypeScript declarations for this package from the component
// catalogue the Rust library emits.
//
// The declarations are generated rather than written because the library is
// where a component's contract lives: which properties a Button means something
// by, and which interactions it can report, are declared beside the component
// in src/workspaces/hl-gui/src/node/tag.rs. A hand-kept .d.ts would describe
// last month's library and nobody would notice — the same reason the catalogue
// itself is emitted from the library rather than transcribed.
//
// Run through `npm run types`, which regenerates the catalogue first.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const CATALOGUE = process.env.HUSKLET_CATALOGUE ?? path.resolve(here, '../catalogue.json');
const DECLARATIONS = process.env.HUSKLET_DECLARATIONS ?? path.resolve(here, '../src/index.d.ts');

/** The value shapes a property accepts, as the TypeScript that describes them. */
const SHAPES = {
  Text: 'string',
  Number: 'number',
  Integer: 'number',
  Flag: 'boolean',
  Length: 'Length',
  Edges: 'Edges',
  Bounds: 'Bounds',
  Choices: 'Choice[]',
  Schema: 'ColumnSpec[]',
  Source: 'number',
};

/** `Label` is the wire spelling; `label` is what a component is given. */
function camel(name) {
  return name[0].toLowerCase() + name.slice(1);
}

/**
 * The type of one property.
 *
 * Read from the value shapes the catalogue publishes for it, so a property that
 * gains a shape gains it here too. The enumerations are unions of both
 * spellings the wire accepts: `"accent"` as the stylesheet names it and
 * `"Accent"` as the wire carries it.
 */
function typed(entry, enums) {
  const written = entry.values.map((shape) => (shape in SHAPES ? SHAPES[shape] : union(enums[shape])));
  // A growth factor is written as a weight by some and as a switch by others,
  // and the host compares either against zero.
  if (entry.name === 'Grow') written.push('boolean');
  return [...new Set(written)].join(' | ');
}

function union(members) {
  if (!members) return 'unknown';
  const spellings = members.flatMap((member) => [member.style, member.wire]);
  return [...new Set(spellings)].map((spelling) => JSON.stringify(spelling)).join(' | ');
}

/** The hand-written part: the shapes no single property owns. */
function preamble() {
  return `// Generated by tools/types.js from catalogue.json. Do not edit.
//
// One interface per component, carrying the properties that component declares
// and the handlers for the interactions it can report. A property no component
// declares is a type error, which is the whole point of generating this.

import type { ReactNode } from 'react';

/** A spacing or sizing quantity: steps on the 4px scale unless named. */
export type Length = number | 'fill' | 'content' | { chars: number } | { step: number };

/** Space inside a component's own edges, per side or all at once. */
export type Edges = Length | { top?: Length; end?: Length; bottom?: Length; start?: Length };

/** An exact extent, or a floor and a ceiling. */
export type Bounds = Length | { minimum?: Length; maximum?: Length };

/** One selectable option offered by a choice control. */
export interface Choice {
  value: string;
  label: string;
}

/** One declared column of a table. */
export interface ColumnSpec {
  key: string;
  title?: string;
  width?: Length;
  align?: ${union(catalogue().enums.Align)};
  sortable?: boolean;
}

/** One interaction, as the host reports it. */
export interface Report {
  trigger: string;
  node: number;
  id: string;
  value: unknown;
}

/** What every component takes, whatever it is. */
export interface NodeProps {
  key?: string | number | null;
}
`;
}

let held = null;
function catalogue() {
  held ??= JSON.parse(fs.readFileSync(CATALOGUE, 'utf8'));
  return held;
}

/** One component's interface: its own properties, then its handlers. */
function component(tag, props, enums) {
  const lines = [`export interface ${tag.name}Props extends NodeProps {`];
  if (tag.acceptsChildren) lines.push('  children?: ReactNode;');
  for (const name of tag.props) {
    const entry = props.get(name);
    lines.push(`  /** ${entry.note} */`);
    lines.push(`  ${camel(name)}?: ${typed(entry, enums)};`);
  }
  for (const trigger of tag.triggers) {
    lines.push(`  on${trigger}?: (report: Report) => void;`);
  }
  lines.push('}');
  return lines.join('\n');
}

/** The rest of the public API, which the catalogue says nothing about. */
function api(tags) {
  const components = tags.map((tag) => `export const ${tag.name}: ComponentType<${tag.name}Props>;`);
  return `
import type { ComponentType } from 'react';

${components.join('\n')}

/** Every tag name, in catalogue order. */
export const tags: string[];

/** Every tag, as a host component React can create. */
export const components: Record<string, string>;

/** Whether a tag accepts child nodes. */
export function acceptsChildren(tag: string): boolean;

/** Every prop and handler name a component accepts. */
export const vocabulary: { props: string[]; handlers: string[] };

export const SOCKET: string;
export const PROTOCOL: number;
/** Maximum Unicode characters retained by a LogView; Value patches append. */
export const LOG_VIEW_CHARACTER_LIMIT: 4096;

export type Topic = 'containers' | 'images' | 'volumes' | 'networks' | 'terminal' | 'pane-changes' | 'extensions' | 'extension-acquisitions' | 'workspace-events';
export type Division = 'beside' | 'below';
export interface WorkspaceInfo { name: string; architecture: string; image: string }
export interface ExtensionSummary { name: string; image_digest: string; status: string }
export type ExtensionCapability =
  | 'workspace-read' | 'workspace-control' | 'workspace-events'
  | 'container-read' | 'container-control' | 'container-attach' | 'image-read' | 'image-write'
  | 'volume-read' | 'volume-write' | 'network-read' | 'network-write'
  | 'terminal-read' | 'terminal-control' | 'terminal-output' | 'pane-observe'
  | 'pane-semantic-read' | 'pane-semantic-control' | 'extension-read'
  | 'extension-control' | 'extension-install' | 'filesystem-read'
  | 'filesystem-write' | 'interface';
export interface ExtensionCandidate { name: string; version: string; image_digest: string; requested: ExtensionCapability[] }
export interface ExtensionAcquisitionJob { job: string }
export interface ExtensionAcquisitionProgress { status: string; id: string | null; current: number | null; total: number | null }
export interface ExtensionAcquisitionStatus { job: string; reference: string; revision: number; state: string; progress: ExtensionAcquisitionProgress | null; candidate: ExtensionCandidate | null; error: string | null }
export interface ExtensionAcquisitionChange { job: string; revision: number; state: string; coalesced: number }
export interface WorkspaceState extends WorkspaceInfo { running: boolean; current: boolean }
export interface WorkspaceMount { host: string; container: string; read_only: boolean }
export interface WorkspaceTerminal {
  font_family: string | null;
  font_size: number | null;
  foreground: string | null;
  background: string | null;
  cursor_shape: string | null;
  cursor_blink: boolean | null;
}
export interface WorkspaceConfiguration extends WorkspaceInfo {
  generation?: string;
  storage: string | null;
  shell: string | null;
  cpus: number | null;
  memory_mb: number | null;
  environment: [string, string][];
  mounts: WorkspaceMount[];
  docker_socket: boolean;
  scrollback: number | null;
  vpn: string | null;
  execution_lifetime: 'persisted' | 'live' | 'ephemeral';
  terminal: WorkspaceTerminal;
}
export interface ContainerSummary { id: string; name: string; image: string; state: string; created: number }
export interface ProcessList {
  titles: string[]; processes: string[][]; observed_at_ms: number;
  scope: 'initial'; pid_identity: 'snapshot'; truncated: boolean;
}
export interface ContainerOutput {
  stdout: number[]; stderr: number[]; truncated: boolean;
  stdout_truncated: boolean; stderr_truncated: boolean; eof: boolean;
}
export interface ExecutionSummary {
  id: string; container_id: string; running: boolean; exit_code: number; pid: number;
  command: string[]; user: string;
}
export interface ImageSummary { id: string; reference: string; size: number; created: number }
export interface ImageDetails { id: string; references: string[]; created: string; size: number; os: string; architecture: string; entrypoint: string[]; command: string[]; working_directory: string; user: string }
export interface ImagePruneResult { deleted: number; space_reclaimed: number }
export interface VolumeSummary { name: string; driver: string; generation: string }
export interface NetworkSummary { id: string; name: string; driver: string; scope: string }
export interface PaneSummary {
  slot: string;
  working_directory: string | null;
  command: string | null;
  occupant: 'terminal' | 'surface';
  provider: { extension: string; provider: string } | null;
}
export interface TabSummary { id: string; title: string; panes: PaneSummary[] }
export interface PaneText { slot: string; lines: string[]; cursor_column: number; cursor_row: number; truncated: boolean }
export interface PaneChange { slot: string; kind: 'terminal' | 'surface' | 'native'; revision: number; generation: number; coalesced: number }
export interface InspectablePane { slot: string; kind: 'terminal' | 'surface' | 'native'; provider: { extension: string; provider: string } | null; tab: string | null; title: string | null; focused: boolean }
export interface PaneInventory { panes: InspectablePane[]; truncated: boolean }
export type SemanticActionKind = 'invoke' | 'change' | 'submit' | 'toggle' | 'expand' | 'focus';
export interface SemanticNode { id: number; role: string; label: string | null; value: string | null; disabled: boolean; destructive: boolean; actions: SemanticActionKind[]; children: SemanticNode[] }
export interface PaneSemanticTree { slot: string; revision: number; root: SemanticNode; truncated: boolean }
export interface PaneSemanticAction { revision: number; node: number; action: SemanticActionKind; value?: string | null }
export interface GridSize { columns: number; rows: number }
export type LayoutNode =
  | { kind: 'pane'; pane: PaneSummary; grid: GridSize | null; focused: boolean }
  | { kind: 'split'; division: Division; ratio_per_mille: number; first: LayoutNode; second: LayoutNode };
export interface TabTopology { id: string; title: string; root: LayoutNode }
export interface TerminalTopology { active_tab: string | null; tabs: TabTopology[] }
export interface FileEntry { path: string; directory: boolean; size: number }
export type WorkspaceEvent =
  | { event: 'key'; key: string; modifiers: string[]; pressed: boolean }
  | { event: 'focus'; active: boolean }
  | { event: 'pointer'; phase: 'move' | 'enter' | 'leave'; x: number; y: number; button: null };
export interface WorkspaceEventBatch { events: WorkspaceEvent[]; dropped: number }
export interface PaneSelection { pane_provider: string; slot: string }
export interface InterfaceEventBase<I extends string, T extends string> {
  interaction: I; trigger: T; node: number; id: string; slot?: string;
}
export type InterfaceEvent =
  | InterfaceEventBase<'invoke', 'Invoke'>
  | InterfaceEventBase<'submit', 'Submit'>
  | (InterfaceEventBase<'change', 'Change'> & { value?: unknown })
  | (InterfaceEventBase<'select', 'Select'> & { rows: number[] })
  | (InterfaceEventBase<'scroll', 'Scroll'> & { dx: number; dy: number })
  | InterfaceEventBase<'close', 'Close'>
  | (InterfaceEventBase<'context', 'Context'> & { x: number; y: number })
  | (InterfaceEventBase<'key', 'Key'> & { key: string; keycode: number; modifiers: number; pressed: boolean })
  | (InterfaceEventBase<'focus', 'Focus'> & { focused: boolean })
  | (InterfaceEventBase<'pointer', 'Pointer'> & {
      phase: 'enter' | 'motion' | 'leave' | 'press' | 'release';
      x: number | null; y: number | null; button: number; modifiers: number;
    });
/** Protocol-1 interface spellings accepted from older hosts by the event router. */
export type LegacyInterfaceEvent =
  | { slot?: string; event: string; node: number; id: string; value?: unknown }
  | { slot?: string; event: Record<string, { node: number; id: string; value?: unknown }> };
export type SnapshotEvent =
  | { snapshot: 'containers'; of: ContainerSummary[] }
  | { snapshot: 'images'; of: ImageSummary[] }
  | { snapshot: 'volumes'; of: VolumeSummary[] }
  | { snapshot: 'networks'; of: NetworkSummary[] }
  | { snapshot: 'terminal'; of: TabSummary[] }
  | { snapshot: 'pane_changes'; of: PaneChange }
  | { snapshot: 'extensions'; of: ExtensionSummary[] }
  | { snapshot: 'extension_acquisitions'; of: ExtensionAcquisitionChange }
  | { snapshot: 'workspace_events'; of: WorkspaceEventBatch };
export type HostEvent = SnapshotEvent | PaneSelection | InterfaceEvent | LegacyInterfaceEvent;

export class ExtensionError extends Error {
  readonly kind: 'denied' | 'absent' | 'conflict' | 'failed' | 'unsupported';
  readonly capability?: string;
}

export interface ConnectOptions {
  path?: string;
  pendingLimit?: number;
  timeout?: number;
  onRows?: (request: unknown, channel: number) => void;
  onReply?: (reply: unknown) => void;
  onEvent?: (event: HostEvent, channel: number) => void;
  onEventError?: (error: unknown) => void;
}

export class Session {
  static connect(path?: string, handlers?: ConnectOptions): Promise<Session>;
  readonly ready: Promise<void>;
  readonly granted: readonly string[];
  call(method: string, params?: unknown): Promise<unknown>;
  answer(channel: number, window: unknown): void;
  onEvent(listener: (event: HostEvent, channel: number) => void): () => boolean;
  close(): Promise<void>;
}

export function connect(options?: ConnectOptions): Promise<Session>;

/** Observe host events with automatic unmount/session cleanup and a fresh render callback. */
export function useHostEvents(session: Session, listener: (event: HostEvent, channel: number) => void): void;

/** The latest pane chooser selection, optionally restricted to one provider ID. */
export function usePaneSelection(session: Session, provider?: string | null): PaneSelection | null;

export interface WorkspaceApi {
  info(): Promise<WorkspaceInfo>;
  list(): Promise<WorkspaceState[]>;
  inspect(name: string): Promise<WorkspaceConfiguration>;
  create(configuration: WorkspaceConfiguration): Promise<WorkspaceConfiguration>;
  /** Assign identity to the exact still-unchanged generation-less legacy record. */
  adopt(configuration: WorkspaceConfiguration): Promise<WorkspaceConfiguration>;
  update(name: string, generation: string, configuration: WorkspaceConfiguration): Promise<WorkspaceConfiguration>;
  delete(name: string, generation: string): Promise<void>;
  start(name: string): Promise<void>;
  stop(name: string): Promise<void>;
  restart(name: string): Promise<void>;
  extensions: {
    list(): Promise<ExtensionSummary[]>;
    inspect(name: string): Promise<ExtensionSummary>;
    enable(name: string): Promise<void>;
    disable(name: string): Promise<void>;
    remove(name: string, generation: string): Promise<void>;
    startAcquisition(reference: string): Promise<ExtensionAcquisitionJob>;
    acquisition(job: string): Promise<ExtensionAcquisitionStatus>;
    cancelAcquisition(job: string): Promise<void>;
    install(job: string, revision: number, granted: ExtensionCapability[]): Promise<ExtensionSummary>;
    update(job: string, revision: number, granted: ExtensionCapability[]): Promise<ExtensionSummary>;
  };
  containers: {
    list(): Promise<ContainerSummary[]>;
    inspect(id: string): Promise<ContainerSummary>;
    processes(id: string): Promise<ProcessList>;
    logs(id: string, streams?: { stdout?: boolean; stderr?: boolean }): Promise<ContainerOutput>;
    execution(id: string): Promise<ExecutionSummary>;
    signalExecution(id: string, signal: string): Promise<void>;
    create(image: string, name: string): Promise<string>;
    start(id: string): Promise<void>;
    stop(id: string): Promise<void>;
    remove(id: string): Promise<void>;
    pause(id: string): Promise<void>;
    unpause(id: string): Promise<void>;
    restart(id: string): Promise<void>;
    kill(id: string, signal: string): Promise<void>;
    exec(id: string, options: { command: string[]; user?: string; workingDirectory?: string }): Promise<string>;
  };
  images: { list(): Promise<ImageSummary[]>; pull(reference: string): Promise<ImageSummary>; inspect(reference: string): Promise<ImageDetails>; remove(reference: string): Promise<void>; prune(): Promise<ImagePruneResult> };
  volumes: {
    list(): Promise<VolumeSummary[]>;
    inspect(name: string): Promise<VolumeSummary>;
    create(name: string): Promise<VolumeSummary>;
    remove(name: string): Promise<void>;
  };
  networks: {
    list(): Promise<NetworkSummary[]>;
    inspect(reference: string): Promise<NetworkSummary>;
    create(name: string): Promise<string>;
    remove(reference: string): Promise<void>;
    connect(reference: string, container: string): Promise<void>;
    disconnect(reference: string, container: string): Promise<void>;
  };
  terminal: {
    panes(): Promise<PaneInventory>;
    tabs(): Promise<TabSummary[]>;
    topology(): Promise<TerminalTopology>;
    openTab(title: string): Promise<string>;
    split(slot: string, division: Division): Promise<string>;
    spawn(slot: string, command: string[]): Promise<void>;
    read(slot: string, lines?: number): Promise<PaneText>;
    semantics(slot: string): Promise<PaneSemanticTree>;
    act(slot: string, action: PaneSemanticAction): Promise<void>;
    writeInput(slot: string, input: string | Iterable<number>): Promise<void>;
    resizeGrid(slot: string, columns: number, rows: number): Promise<void>;
    close(slot: string): Promise<void>;
    focus(slot: string): Promise<void>;
    ratio(slot: string, ratio: number): Promise<void>;
  };
  files: {
    list(path: string): Promise<FileEntry[]>;
    read(path: string): Promise<number[]>;
    write(path: string, contents: Iterable<number>): Promise<void>;
    mkdir(path: string): Promise<void>;
    rename(from: string, to: string): Promise<void>;
    remove(path: string): Promise<void>;
  };
  subscribe(topic: Topic): Promise<void>;
  unsubscribe(topic: Topic): Promise<void>;
  watchPaneChanges(listener: (change: PaneChange) => void): Promise<() => Promise<void>>;
  watchExtensions(listener: (extensions: ExtensionSummary[]) => void): Promise<() => Promise<void>>;
  watchExtensionAcquisitions(listener: (change: ExtensionAcquisitionChange) => void): Promise<() => Promise<void>>;
}

export function workspace(session: Session): WorkspaceApi;
export const protocolCoverage: Readonly<{
  available: Readonly<Record<string, readonly string[]>>;
  unavailable: Readonly<Record<string, readonly string[]>>;
}>;

export type InterfaceSourceMutation =
  | { Open: { source: number; columns: readonly unknown[] } }
  | { Length: { source: number; version: number; rows: number } }
  | { Window: { source: number; version: number; request: number; range: { start: number; count: number }; rows: readonly unknown[] } }
  | { Invalidate: { source: number; version: number; range: { start: number; count: number } | null } }
  | { Close: { source: number } };

export interface RenderHandle {
  readonly ready: Promise<string>;
  readonly slot: string | null;
  update(next: ReactNode): void;
  source(mutation: InterfaceSourceMutation): Promise<void>;
  close(): void;
}

export function render(
  element: ReactNode,
  session: Session,
  options?: { title?: string; split?: { slot: string; division: 'beside' | 'below' } },
): RenderHandle;

export function deliver(session: Session, payload: unknown): boolean;
`;
}

function main() {
  const { tags, props, enums } = catalogue();
  const described = new Map(props.map((entry) => [entry.name, entry]));
  const written = [preamble(), ...tags.map((tag) => component(tag, described, enums)), api(tags)];
  fs.writeFileSync(DECLARATIONS, `${written.join('\n\n').trimEnd()}\n`);
  process.stdout.write(`${DECLARATIONS}: ${tags.length} components\n`);
}

main();
