// Writes the TypeScript declarations for this package from the component
// catalogue the Rust library emits.
//
// The declarations are generated rather than written because the library is
// where a component's contract lives: which properties a Button means something
// by, and which interactions it can report, are declared beside the component
// in src/workspaces/hl-gui/src/node/tag.rs. A hand-kept .d.ts would describe
// last month's library and nobody would notice — the same reason the catalogue
// itself is emitted from the library rather than transcribed.
//
// Run through `npm run types`, which regenerates the catalogue first.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const CATALOGUE = path.resolve(here, '../catalogue.json');
const DECLARATIONS = path.resolve(here, '../src/index.d.ts');

/** The value shapes a property accepts, as the TypeScript that describes them. */
const SHAPES = {
  Text: 'string',
  Number: 'number',
  Integer: 'number',
  Flag: 'boolean',
  Length: 'Length',
  Edges: 'Edges',
  Bounds: 'Bounds',
  Choices: 'Choice[]',
  Schema: 'ColumnSpec[]',
  Source: 'number',
};

/** `Label` is the wire spelling; `label` is what a component is given. */
function camel(name) {
  return name[0].toLowerCase() + name.slice(1);
}

/**
 * The type of one property.
 *
 * Read from the value shapes the catalogue publishes for it, so a property that
 * gains a shape gains it here too. The enumerations are unions of both
 * spellings the wire accepts: `"accent"` as the stylesheet names it and
 * `"Accent"` as the wire carries it.
 */
function typed(entry, enums) {
  const written = entry.values.map((shape) => (shape in SHAPES ? SHAPES[shape] : union(enums[shape])));
  // A growth factor is written as a weight by some and as a switch by others,
  // and the host compares either against zero.
  if (entry.name === 'Grow') written.push('boolean');
  return [...new Set(written)].join(' | ');
}

function union(members) {
  if (!members) return 'unknown';
  const spellings = members.flatMap((member) => [member.style, member.wire]);
  return [...new Set(spellings)].map((spelling) => JSON.stringify(spelling)).join(' | ');
}

/** The hand-written part: the shapes no single property owns. */
function preamble() {
  return `// Generated by tools/types.js from catalogue.json. Do not edit.
//
// One interface per component, carrying the properties that component declares
// and the handlers for the interactions it can report. A property no component
// declares is a type error, which is the whole point of generating this.

import type { ReactNode } from 'react';

/** A spacing or sizing quantity: steps on the 4px scale unless named. */
export type Length = number | 'fill' | 'content' | { chars: number } | { step: number };

/** Space inside a component's own edges, per side or all at once. */
export type Edges = Length | { top?: Length; end?: Length; bottom?: Length; start?: Length };

/** An exact extent, or a floor and a ceiling. */
export type Bounds = Length | { minimum?: Length; maximum?: Length };

/** One selectable option offered by a choice control. */
export interface Choice {
  value: string;
  label: string;
}

/** One declared column of a table. */
export interface ColumnSpec {
  key: string;
  title?: string;
  width?: Length;
  align?: ${union(catalogue().enums.Align)};
  sortable?: boolean;
}

/** One interaction, as the host reports it. */
export interface Report {
  trigger: string;
  node: number;
  id: string;
  value: unknown;
}

/** What every component takes, whatever it is. */
export interface NodeProps {
  key?: string | number | null;
}
`;
}

let held = null;
function catalogue() {
  held ??= JSON.parse(fs.readFileSync(CATALOGUE, 'utf8'));
  return held;
}

/** One component's interface: its own properties, then its handlers. */
function component(tag, props, enums) {
  const lines = [`export interface ${tag.name}Props extends NodeProps {`];
  if (tag.acceptsChildren) lines.push('  children?: ReactNode;');
  for (const name of tag.props) {
    const entry = props.get(name);
    lines.push(`  /** ${entry.note} */`);
    lines.push(`  ${camel(name)}?: ${typed(entry, enums)};`);
  }
  for (const trigger of tag.triggers) {
    lines.push(`  on${trigger}?: (report: Report) => void;`);
  }
  lines.push('}');
  return lines.join('\n');
}

/** The rest of the public API, which the catalogue says nothing about. */
function api(tags) {
  const components = tags.map((tag) => `export const ${tag.name}: ComponentType<${tag.name}Props>;`);
  return `
import type { ComponentType } from 'react';

${components.join('\n')}

/** Every tag name, in catalogue order. */
export const tags: string[];

/** Every tag, as a host component React can create. */
export const components: Record<string, string>;

/** Whether a tag accepts child nodes. */
export function acceptsChildren(tag: string): boolean;

/** Every prop and handler name a component accepts. */
export const vocabulary: { props: string[]; handlers: string[] };

export const SOCKET: string;
export const PROTOCOL: string;

export class Session {
  static connect(path?: string, handlers?: Record<string, unknown>): Promise<Session>;
  call(method: string, params?: unknown): Promise<unknown>;
  close(): void;
}

export function connect(options?: Record<string, unknown>): Promise<Session>;

export function render(
  element: ReactNode,
  session: Session,
  options?: { title?: string },
): { update(next: ReactNode): void; close(): void };

export function deliver(session: Session, payload: unknown): boolean;
`;
}

function main() {
  const { tags, props, enums } = catalogue();
  const described = new Map(props.map((entry) => [entry.name, entry]));
  const written = [preamble(), ...tags.map((tag) => component(tag, described, enums)), api(tags)];
  fs.writeFileSync(DECLARATIONS, `${written.join('\n\n')}\n`);
  process.stdout.write(`${DECLARATIONS}: ${tags.length} components\n`);
}

main();
