// A robust PRIO_INHERIT mutex whose owner dies while a peer is ALREADY PARKED on it.
//
// pi_robust.c (compat/process) covers the easy half: the next locker arrives after the owner has exited, so
// it reads OWNER_DIED straight out of the word and never blocks -- no wake has to be delivered. This case
// covers the half that needs the kernel-side handoff. The waiter enters FUTEX_LOCK_PI and parks; the owner
// then exits still holding the mutex; the robust-list walk must set OWNER_DIED *and* wake that parked waiter,
// which then returns EOWNERDEAD.
//
// The wake is generated by the exit path, not by a guest futex(2) call, so it carries no FUTEX_PRIVATE_FLAG.
// An emulator that keys private waiters separately from shared ones (as it must, so two aliases of one memfd
// stay distinct futexes) has to notify both key spaces here, or a private PI waiter -- which is what glibc
// creates for a non-pshared mutex -- can never be reached and hangs until its deadline.
//
// Bounded: the waiter uses pthread_mutex_timedlock, so a missing wake reports timedout=1 after 5s instead of
// deadlocking the run.
#define _GNU_SOURCE
#include <errno.h>
#include <pthread.h>
#include <stdatomic.h>
#include <stdio.h>
#include <time.h>

static pthread_mutex_t mutex;
static atomic_int owner_holds;
static int waiter_rc = -1, waiter_consistent = 0;

static void *owner(void *unused) {
    (void)unused;
    if (pthread_mutex_lock(&mutex) != 0) return NULL;
    atomic_store(&owner_holds, 1);
    // Give the waiter time to reach FUTEX_LOCK_PI and park, then exit WITHOUT unlocking.
    struct timespec hold = {0, 300 * 1000 * 1000};
    nanosleep(&hold, NULL);
    return NULL;
}

static void *waiter(void *unused) {
    (void)unused;
    while (!atomic_load(&owner_holds)) {
        struct timespec spin = {0, 1000 * 1000};
        nanosleep(&spin, NULL);
    }
    struct timespec deadline; // pthread_mutex_timedlock takes an absolute CLOCK_REALTIME deadline
    clock_gettime(CLOCK_REALTIME, &deadline);
    deadline.tv_sec += 5;
    waiter_rc = pthread_mutex_timedlock(&mutex, &deadline);
    if (waiter_rc == EOWNERDEAD) {
        waiter_consistent = pthread_mutex_consistent(&mutex) == 0;
        pthread_mutex_unlock(&mutex);
    } else if (waiter_rc == 0) {
        pthread_mutex_unlock(&mutex);
    }
    return NULL;
}

int main(void) {
    pthread_mutexattr_t attribute;
    pthread_mutexattr_init(&attribute);
    pthread_mutexattr_setprotocol(&attribute, PTHREAD_PRIO_INHERIT);
    pthread_mutexattr_setrobust(&attribute, PTHREAD_MUTEX_ROBUST);
    if (pthread_mutex_init(&mutex, &attribute) != 0) {
        printf("robust_pi_handoff init_failed\n");
        return 1;
    }

    pthread_t o, w;
    pthread_create(&o, NULL, owner, NULL);
    pthread_create(&w, NULL, waiter, NULL);
    pthread_join(o, NULL);
    pthread_join(w, NULL);

    printf("robust_pi_handoff eownerdead=%d consistent=%d timedout=%d\n", waiter_rc == EOWNERDEAD,
           waiter_consistent, waiter_rc == ETIMEDOUT);
    return 0;
}
