// One component per tag, so an interface is written in components rather than
// in strings.
//
import catalogue from '../catalogue.json' with { type: 'json' };

/**
 * Every tag, as a host component React can create.
 *
 * The element type is the tag's wire spelling, so there is no lookup table
 * between what someone writes and what the host receives.
 */
export const components = Object.fromEntries(catalogue.tags.map((entry) => [entry.name, entry.name]));

/** Every tag name, in catalogue order. */
export const tags = catalogue.tags.map((entry) => entry.name);

/** Whether a tag accepts child nodes. Leaf tags reject `Insert` on the host. */
export function acceptsChildren(tag) {
  return catalogue.tags.some((entry) => entry.name === tag && entry.acceptsChildren);
}

export const {
  Column,
  Row,
  Grid,
  Scroll,
  Splitter,
  Stack,
  Overlay,
  Container,
  Spacer,
  Separator,
  Card,
  CardHeader,
  CardContent,
  CardActions,
  CardMedia,
  CardActionArea,
  Paper,
  Section,
  Toolbar,
  HeaderBar,
  Sidebar,
  Text,
  Heading,
  Code,
  Link,
  Icon,
  Badge,
  Avatar,
  AvatarGroup,
  Chip,
  Image,
  ImageList,
  ImageListItem,
  Progress,
  Spinner,
  Meter,
  Skeleton,
  EmptyState,
  Stat,
  Toast,
  Banner,
  AlertTitle,
  InlineMessage,
  ValidationSummary,
  Button,
  IconButton,
  ToggleButton,
  ButtonGroup,
  ToggleButtonGroup,
  SplitButton,
  Fab,
  SpeedDial,
  SpeedDialAction,
  Overflow,
  Entry,
  Search,
  CommandPalette,
  TagInput,
  NumberEntry,
  TextArea,
  PasswordEntry,
  Autocomplete,
  TextField,
  InputAdornment,
  Slider,
  DatePicker,
  TimePicker,
  ColorPicker,
  FilePicker,
  Rating,
  FormControl,
  FormLabel,
  FormHelperText,
  FormControlLabel,
  FormGroup,
  Switch,
  Checkbox,
  Radio,
  RadioGroup,
  Select,
  List,
  ListRow,
  ListItemText,
  ListItemIcon,
  ListItemAvatar,
  ListItemButton,
  ListItemAction,
  ListItemSecondaryAction,
  ListSubheader,
  Table,
  TableHead,
  TableBody,
  TableFooter,
  TableRow,
  TableCell,
  TableSortLabel,
  DataTable,
  KeyValueTable,
  TreeTable,
  EventStream,
  FileBrowser,
  TablePagination,
  Tree,
  TreeItem,
  Tabs,
  TabPage,
  Breadcrumb,
  Pagination,
  PaginationItem,
  Stepper,
  Step,
  StepLabel,
  StepContent,
  StepConnector,
  StepIcon,
  NavigationRail,
  NavigationRailItem,
  BottomNavigation,
  BottomNavigationAction,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  AccordionActions,
  Expander,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogContentText,
  DialogActions,
  Popover,
  ContextMenu,
  Menu,
  MenuItem,
  Drawer,
  DrawerPanel,
  CodeView,
  HexView,
  MarkdownView,
  JsonView,
  LogView,
  Video,
  Chart,
  Sparkline,
  FlameGraph,
  MemoryMap,
  DiffViewer,
  DiffLine,
  StackTrace,
  StackFrame,
} = components;
