//! dd-shim-cuda codegen: turn the CUDA-Driver-API entry-point manifest into the complete set of
//! `#[no_mangle] extern "C"` `cu*` exports the shim must provide. Mirrors dd-shim-gl/build.rs.
//!
//! Input:  `registry/cuda_driver.manifest` (extracted from dd's clean-room `dd-gpu/cuda/cuda_shim.c`
//!         driver-API surface — see `registry/extract_cuda_manifest.py`).
//! Output: `$OUT_DIR/generated_entrypoints.rs`, `include!`d by `src/lib.rs`.
//!
//! For every entry point NOT hand-implemented in `src/` (`IMPLEMENTED` below), we emit a spec-faithful
//! *default* stub: correct C-ABI signature (so the symbol resolves and the app links + runs), a
//! debug-gated "unimplemented entry point" trace, and a benign default return (`CUDA_SUCCESS` = 0 for
//! the `CUresult` all driver entry points return). Real bodies replace stubs incrementally without
//! ever changing the exported surface — the shrinking long tail, exactly like dd-shim-gl.
//!
//! Also sets the shared-object soname to `libcuda.so.1` (the CUDA Driver API drop-in name).

use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env("CARGO_MANIFEST_DIR")).join("registry/cuda_driver.manifest");
    println!("cargo:rerun-if-changed={}", manifest.display());
    println!("cargo:rerun-if-changed=build.rs");

    // The shim is deployed as libcuda.so.1 (the CUDA Driver API soname a real app `DT_NEEDED`s);
    // bake that soname. Matches dd-gpu/cuda/build.sh's C shim and dd-shim-gl's libEGL.so.1 pattern.
    println!("cargo:rustc-cdylib-link-arg=-Wl,-soname,libcuda.so.1");

    let text = std::fs::read_to_string(&manifest)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest.display()));

    let mut out = String::new();
    out.push_str("// @generated by build.rs from registry/cuda_driver.manifest — DO NOT EDIT.\n");
    out.push_str("// (crate-level `#![allow(non_snake_case, ...)]` lives in src/lib.rs.)\n\n");

    let mut cu = 0usize;
    let mut stubs = 0usize;
    for (lineno, line) in text.lines().enumerate() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut f = line.split('\t');
        let lib = f.next().unwrap_or("");
        let name = f.next().unwrap_or("");
        let ret = f.next().unwrap_or("void");
        let params = f.next().unwrap_or("");
        if name.is_empty() {
            panic!("manifest line {}: empty name: {line:?}", lineno + 1);
        }
        match lib {
            "CU" => cu += 1,
            other => panic!("manifest line {}: unknown lib {other:?}", lineno + 1),
        }
        if IMPLEMENTED.contains(&name) {
            continue; // hand-written in src/; a generated stub would collide.
        }
        stubs += 1;
        emit_stub(&mut out, name, ret, params);
    }

    // A compile-time census the crate can assert against (the completeness gate).
    writeln!(out, "\n/// Total CUDA Driver API entry points in the manifest.").unwrap();
    writeln!(out, "pub const CUDA_DRIVER_ENTRYPOINTS: usize = {cu};").unwrap();
    writeln!(out, "/// Entry points emitted as default stubs (not yet hand-implemented).").unwrap();
    writeln!(out, "pub const GENERATED_STUBS: usize = {stubs};").unwrap();

    let out_path = PathBuf::from(env("OUT_DIR")).join("generated_entrypoints.rs");
    std::fs::write(&out_path, out).unwrap();
}

fn emit_stub(out: &mut String, name: &str, ret: &str, params: &str) {
    let mut sig = String::new();
    let mut argnames = Vec::new();
    if !params.is_empty() {
        for (i, p) in params.split(';').enumerate() {
            let (ty, pname) = p.split_once('|').unwrap_or_else(|| panic!("bad param {p:?} in {name}"));
            let rty = map_type(ty.trim(), name);
            let pn = sanitize(pname.trim(), i);
            if i > 0 {
                sig.push_str(", ");
            }
            write!(sig, "{pn}: {rty}").unwrap();
            argnames.push(pn);
        }
    }
    let rmap = map_ret(ret.trim(), name);
    let arrow = rmap.as_ref().map(|r| format!(" -> {r}")).unwrap_or_default();
    // Reference every argument so `unused_variables` stays quiet even without the allow (belt+braces).
    let touch: String = argnames.iter().map(|a| format!("let _ = {a}; ")).collect();
    let body = match &rmap {
        None => format!("{touch}crate::stub::hit(\"{name}\");"),
        Some(r) => {
            let dflt = default_for(r);
            format!("{touch}crate::stub::hit(\"{name}\"); {dflt}")
        }
    };
    writeln!(out, "#[no_mangle]\npub extern \"C\" fn {name}({sig}){arrow} {{ {body} }}\n").unwrap();
}

/// C return type -> Rust type (None == `void`/unit). Panics on an unknown type so an API bump surfaces
/// at build time rather than silently mis-typing the ABI. Every CUDA driver entry point returns
/// `CUresult` (an `int`-sized enum), so this is `Some(i32)` in practice.
fn map_ret(c: &str, ctx: &str) -> Option<String> {
    if c == "void" {
        return None;
    }
    Some(map_type(c, ctx))
}

/// C type string -> Rust C-ABI type. Handles the pointer forms generally (single/double, const/mut,
/// `*const*`) so an API bump only ever surprises us on a genuinely new *base scalar*, which panics
/// (fail-loud ABI generator) rather than silently mis-typing. Identical structure to dd-shim-gl.
fn map_type(c: &str, ctx: &str) -> String {
    let c = c.trim();
    if let Some(base) = c.strip_suffix("*const*") {
        return format!("*const *const {}", pointee(base, ctx));
    }
    if let Some(base) = c.strip_suffix("**") {
        // outer const-ness of `X **` params is not expressed in the manifest surface; treat as mut.
        return format!("*mut *mut {}", pointee(base, ctx));
    }
    if let Some(base) = c.strip_suffix('*') {
        let is_const = base.trim_start().starts_with("const ");
        let q = if is_const { "*const" } else { "*mut" };
        return format!("{q} {}", pointee(base, ctx));
    }
    scalar(c, ctx).to_string()
}

/// The Rust type of a pointer's pointee (the base with any leading `const` stripped).
fn pointee(base: &str, ctx: &str) -> String {
    let b = base.trim();
    let b = b.strip_prefix("const ").unwrap_or(b).trim();
    scalar(b, ctx).to_string()
}

/// A bare (by-value) scalar / opaque-handle / enum C type -> Rust.
///
/// CUDA's driver types fall into four buckets:
///   * **opaque handles** (`CUcontext`, `CUmodule`, `CUfunction`, `CUstream`, `CUevent`,
///     `CUtexref`, `CUsurfref`) and **function-pointer typedefs** (`CUhostFn`, `CUstreamCallback`,
///     `CUoccupancyB2DSize`) are all `void*`-shaped → `*mut c_void`;
///   * **`CUdeviceptr`** is a 64-bit device address → `u64`;
///   * **`int`-sized enums** (`CUresult`, `CUdevice`, `CU*_attribute`, `CUlimit`, `CUfunc_cache`,
///     `CUsharedconfig`, `CUpointer_attribute`, `CUjit_option`, `CUmoduleLoadingMode`,
///     `CUdriverProcAddressQueryResult`) → `i32`;
///   * **opaque structs only ever seen behind a pointer** (`CUdevprop`, `CUuuid`, `CUlaunchConfig`)
///     → `c_void` (so `CUuuid*` becomes `*mut c_void`), plus the plain C scalars.
fn scalar(c: &str, ctx: &str) -> &'static str {
    match c {
        "void" => "core::ffi::c_void", // only meaningful as a pointee; bare `void` -> map_ret == None
        "char" => "core::ffi::c_char",
        "float" => "f32",
        "int" => "i32",
        "unsigned char" => "u8",
        "unsigned short" => "u16",
        "unsigned int" | "cuuint32_t" => "u32",
        "unsigned long" => "u64",
        "unsigned long long" | "cuuint64_t" => "u64",
        "size_t" => "usize",
        // 64-bit device address
        "CUdeviceptr" => "u64",
        // int-sized driver enums
        "CUresult" | "CUdevice" | "CUdevice_attribute" | "CUlimit" | "CUfunc_cache"
        | "CUsharedconfig" | "CUpointer_attribute" | "CUfunction_attribute" | "CUjit_option"
        | "CUmoduleLoadingMode" | "CUdriverProcAddressQueryResult" => "i32",
        // opaque handles + function-pointer typedefs (all `void*`-shaped)
        "CUcontext" | "CUmodule" | "CUfunction" | "CUstream" | "CUevent" | "CUtexref"
        | "CUsurfref" | "CUhostFn" | "CUstreamCallback" | "CUoccupancyB2DSize" => {
            "*mut core::ffi::c_void"
        }
        // opaque structs only ever referenced through a pointer -> treat pointee as c_void
        "CUdevprop" | "CUuuid" | "CUlaunchConfig" => "core::ffi::c_void",
        other => panic!("unmapped C base type {other:?} (in {ctx}); extend scalar() in build.rs"),
    }
}

fn default_for(rust_ty: &str) -> &'static str {
    if rust_ty.starts_with("*const") {
        "core::ptr::null()"
    } else if rust_ty.starts_with("*mut") {
        "core::ptr::null_mut()"
    } else {
        // For the `CUresult`/`i32` return this is `CUDA_SUCCESS` (0) — a benign "did nothing, ok"
        // default so an app keeps running while the entry point is still a stub (matches gl_shim's 0).
        "0"
    }
}

fn sanitize(name: &str, i: usize) -> String {
    const KW: &[&str] = &[
        "type", "ref", "box", "in", "fn", "let", "match", "move", "mut", "as", "impl", "loop",
        "where", "self", "final", "override", "become",
    ];
    if name.is_empty() {
        return format!("a{i}");
    }
    if KW.contains(&name) {
        return format!("{name}_");
    }
    name.to_string()
}

fn env(k: &str) -> String {
    std::env::var(k).unwrap_or_else(|_| panic!("env {k} not set"))
}

/// Entry points hand-implemented in `src/driver.rs` (so the generator skips them to avoid duplicate
/// symbols). Two groups: the **bring-up** set that returns real, sane values for a dlopen smoke test
/// (init / driver-version / device-presence / context lifecycle), and the **IR-wired** set that maps
/// the CUDA compute model onto the shared dd-gpu IR via `dd_gpu::cuda::CudaContext` (memory alloc/copy,
/// PTX module load, kernel launch = compute pipeline + dispatch). Everything else is a generated stub.
const IMPLEMENTED: &[&str] = &[
    // ---- bring-up: init + driver version + error strings ----
    "cuInit",
    "cuDriverGetVersion",
    "cuGetErrorString",
    "cuGetErrorName",
    // ---- bring-up: device presence (values from dd_gpu::cuda::CudaDeviceDesc) ----
    "cuDeviceGetCount",
    "cuDeviceGet",
    "cuDeviceGetName",
    "cuDeviceTotalMem_v2",
    "cuDeviceGetAttribute",
    "cuDeviceComputeCapability",
    "cuDeviceGetUuid",
    "cuDeviceGetUuid_v2",
    // ---- bring-up: context lifecycle ----
    "cuCtxCreate_v2",
    "cuCtxDestroy_v2",
    "cuCtxSetCurrent",
    "cuCtxGetCurrent",
    "cuCtxGetDevice",
    "cuCtxSynchronize",
    // ---- IR-wired: memory (CUDA alloc/copy -> dd-gpu IR through CudaContext) ----
    "cuMemAlloc_v2",
    "cuMemFree_v2",
    "cuMemcpyHtoD_v2",
    "cuMemcpyDtoH_v2",
    // ---- IR-wired: module (PTX) + kernel launch (compute pipeline + dispatch) ----
    "cuModuleLoadData",
    "cuModuleGetFunction",
    "cuLaunchKernel",
    "cuStreamSynchronize",
    // ---- IR-wired: stream + event lifecycle (synchronization tokens) ----
    "cuStreamCreate",
    "cuStreamDestroy_v2",
    "cuEventCreate",
    "cuEventRecord",
    "cuEventSynchronize",
    "cuEventDestroy_v2",
];
