//! Codegen for the guest `libvk_hl.so.1` ICD shim: turn `registry/vk_commands.manifest` into the
//! complete `#[no_mangle] extern "C"` `vk*` export surface (712 commands) plus the name→address
//! dispatch table the loader-facing `vk_icdGetInstanceProcAddr` / `vkGetInstanceProcAddr` resolve
//! against.
//!
//! Every command NOT hand-written in `src/` (`IMPLEMENTED` below) is emitted here as a spec-faithful
//! default stub: correct C-ABI signature (so the loader/app resolves the symbol + links), a
//! `HL_SHIM_DEBUG`-gated once-per-name trace, and a benign, TRUTHFUL return — a `VkResult`-returning
//! command returns `VK_ERROR_FEATURE_NOT_PRESENT` (never a false `VK_SUCCESS`) after nulling any output
//! handle; every other return is the truthful zero/NULL. Real bodies replace stubs without ever
//! changing the exported surface. Ported from `hl-shim-vk/build.rs` (capability-inventory + origins
//! codegen dropped — this is the transport-wired template).
//!
//! Manifest records: `T<TAB>type<TAB>kind` classify by-value types (so a bare param maps without
//! knowing every Vulkan type); `C<TAB>name<TAB>ret<TAB>params` are the commands. A pointer is a
//! pointer — every `*`-suffixed C type lowers to a `c_void` pointer regardless of pointee.
//!
//! Also bakes the shared-object soname `libvk_hl.so.1` (the ICD library the icd.json `library_path`
//! names) on Linux.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::PathBuf;

/// `VkResult` a truthful stub returns instead of a false `VK_SUCCESS` (stable Vulkan ABI, from vk.xml).
const VK_ERROR_FEATURE_NOT_PRESENT: i32 = -8;

fn main() {
    let manifest = PathBuf::from(env("CARGO_MANIFEST_DIR")).join("registry/vk_commands.manifest");
    println!("cargo:rerun-if-changed={}", manifest.display());
    println!("cargo:rerun-if-changed=build.rs");
    // `-Wl,-soname` is a GNU-ld flag (the ICD only ships on the Linux guest); emit it only on Linux.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("linux") {
        println!("cargo:rustc-cdylib-link-arg=-Wl,-soname,libvk_hl.so.1");
    }

    let text = std::fs::read_to_string(&manifest)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest.display()));

    // Pass 1: the by-value type classification table.
    let mut kinds: HashMap<String, String> = HashMap::new();
    for line in text.lines() {
        let line = line.trim_end();
        if !line.starts_with("T\t") {
            continue;
        }
        let mut f = line.split('\t');
        f.next();
        let name = f.next().unwrap_or("");
        let kind = f.next().unwrap_or("");
        kinds.insert(name.to_string(), kind.to_string());
    }

    // Pass 2: emit a C-ABI stub for every non-IMPLEMENTED command, plus a dispatch entry for all.
    let mut out = String::new();
    out.push_str("// @generated by build.rs from registry/vk_commands.manifest — DO NOT EDIT.\n\n");

    let mut cmds = 0usize;
    let mut stubs = 0usize;
    let mut dispatch = String::new();
    let mut names = String::new();
    for (lineno, line) in text.lines().enumerate() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') || line.starts_with("T\t") {
            continue;
        }
        let mut f = line.split('\t');
        let rec = f.next().unwrap_or("");
        if rec != "C" {
            panic!("manifest line {}: unknown record {rec:?}", lineno + 1);
        }
        let name = f.next().unwrap_or("");
        let ret = f.next().unwrap_or("void");
        let params = f.next().unwrap_or("");
        if name.is_empty() {
            panic!("manifest line {}: empty name: {line:?}", lineno + 1);
        }
        cmds += 1;
        // Every exported entry point — hand-written or generated — is resolvable at crate root by its
        // bare name (implemented ones via `use` in lib.rs), so the dispatch resolver references them
        // uniformly. The fn-item→address cast runs at RUNTIME (a `static` fails const-eval), so we emit
        // a match function rather than a table.
        writeln!(dispatch, "        \"{name}\" => Some({name} as *const () as usize),").unwrap();
        writeln!(names, "    \"{name}\",").unwrap();
        if IMPLEMENTED.contains(&name) {
            continue; // hand-written in src/; a generated stub would collide.
        }
        stubs += 1;
        emit_stub(&mut out, name, ret, params, &kinds);
    }

    writeln!(out, "\n/// Total Vulkan `vk*` entry points in the manifest (the exported command surface).").unwrap();
    writeln!(out, "pub const VK_ENTRYPOINTS: usize = {cmds};").unwrap();
    writeln!(out, "/// Entry points emitted as default stubs (not yet hand-implemented).").unwrap();
    writeln!(out, "pub const GENERATED_STUBS: usize = {stubs};").unwrap();
    writeln!(out, "/// Entry points with real hand-written bodies in `src/`.").unwrap();
    writeln!(out, "pub const IMPLEMENTED_ENTRYPOINTS: usize = {};", IMPLEMENTED.len()).unwrap();

    // The name→address resolver the loader-facing proc-addr entries in `crate::icd` consult. A match
    // over the whole exported `vk*` surface; the address cast runs at call time (see above).
    writeln!(out, "\n/// Resolve any exported `vk*` entry point by name to its address. Consulted by the").unwrap();
    writeln!(out, "/// loader-facing proc-addr resolvers in `crate::icd`. Runtime cast (not a const table).").unwrap();
    writeln!(out, "pub fn dispatch_addr(name: &str) -> Option<usize> {{\n    match name {{\n{dispatch}        _ => None,\n    }}\n}}").unwrap();
    // A name-only census the surface tests can iterate without taking any addresses.
    writeln!(out, "\n/// Every exported `vk*` entry-point name (the completeness census list).").unwrap();
    writeln!(out, "pub static DISPATCH_NAMES: &[&str] = &[\n{names}];").unwrap();

    let out_path = PathBuf::from(env("OUT_DIR")).join("generated_entrypoints.rs");
    std::fs::write(&out_path, out).unwrap();
}

fn emit_stub(out: &mut String, name: &str, ret: &str, params: &str, kinds: &HashMap<String, String>) {
    let is_vk_result = ret.trim() == "VkResult";
    let mut sig = String::new();
    let mut argnames: Vec<String> = Vec::new();
    let mut last_out: Option<String> = None; // last param IF it is a single `*mut` output pointer
    if !params.is_empty() {
        let n = params.split(';').count();
        for (i, p) in params.split(';').enumerate() {
            let (ty, pname) = p.split_once('|').unwrap_or_else(|| panic!("bad param {p:?} in {name}"));
            let rty = map_type(ty.trim(), name, kinds);
            let mut pn = sanitize(pname.trim(), i);
            // Guarantee unique parameter identifiers (a manifest can carry repeated names across
            // api-variant params). Names are cosmetic — the ABI is unaffected.
            while argnames.contains(&pn) {
                pn.push_str(&format!("_{i}"));
            }
            if i > 0 {
                sig.push_str(", ");
            }
            write!(sig, "{pn}: {rty}").unwrap();
            // A `vkCreate*`/`vkAllocate*` command's final parameter is its output handle — a single,
            // non-const `*mut` pointer. Record it so a failing stub can null it (VK_NULL_HANDLE) before
            // returning: truthful failure must initialize the output, never leave a caller reading junk.
            if i + 1 == n && rty.starts_with("*mut ") && !rty.starts_with("*mut *mut") {
                last_out = Some(pn.clone());
            }
            argnames.push(pn);
        }
    }
    let rmap = map_ret(ret.trim(), name, kinds);
    let arrow = rmap.as_ref().map(|r| format!(" -> {r}")).unwrap_or_default();
    let touch: String = argnames.iter().map(|a| format!("let _ = {a}; ")).collect();
    let init_out = match &last_out {
        Some(outp) if is_vk_result && (name.starts_with("vkCreate") || name.starts_with("vkAllocate")) => {
            format!("unsafe {{ if !{outp}.is_null() {{ *({outp} as *mut u64) = 0; }} }} ")
        }
        _ => String::new(),
    };
    let body = match &rmap {
        None => format!("{touch}crate::stub::hit(\"{name}\");"),
        Some(r) => {
            let retval = if is_vk_result {
                VK_ERROR_FEATURE_NOT_PRESENT.to_string()
            } else {
                default_for(r).to_string()
            };
            format!("{touch}{init_out}crate::stub::hit(\"{name}\"); {retval}")
        }
    };
    writeln!(out, "#[no_mangle]\npub extern \"C\" fn {name}({sig}){arrow} {{ {body} }}\n").unwrap();
}

/// C return type -> Rust type (None == `void`/unit).
fn map_ret(c: &str, ctx: &str, kinds: &HashMap<String, String>) -> Option<String> {
    if c == "void" {
        return None;
    }
    Some(map_type(c, ctx, kinds))
}

/// C type string -> Rust C-ABI type. Pointers (single/double, const/mut) lower to a `c_void` pointer —
/// a pointer is a pointer at the ABI, so the pointee is irrelevant for a stub's signature. Only a bare
/// by-value type consults the T-table (fail-loud on an unclassified base type).
fn map_type(c: &str, ctx: &str, kinds: &HashMap<String, String>) -> String {
    let c = c.trim();
    if c.ends_with("*const*") || c.ends_with("* const*") {
        return "*const *const core::ffi::c_void".to_string();
    }
    if let Some(rest) = c.strip_suffix("**") {
        let is_const = rest.trim_start().starts_with("const ");
        return if is_const {
            "*const *const core::ffi::c_void".to_string()
        } else {
            "*mut *mut core::ffi::c_void".to_string()
        };
    }
    if let Some(rest) = c.strip_suffix('*') {
        let is_const = rest.trim_start().starts_with("const ");
        return if is_const {
            "*const core::ffi::c_void".to_string()
        } else {
            "*mut core::ffi::c_void".to_string()
        };
    }
    scalar(c, ctx, kinds).to_string()
}

/// A bare (by-value) Vulkan/C type -> its Rust C-ABI representation, via the vk.xml-derived T-table or
/// a concrete scalar token. Fail-loud on anything unclassified so a registry bump surfaces at build
/// time rather than silently mis-typing the ABI.
fn scalar(c: &str, ctx: &str, kinds: &HashMap<String, String>) -> String {
    let base = c.strip_prefix("const ").unwrap_or(c).trim();
    let kind = kinds.get(base).map(String::as_str).unwrap_or(base);
    match kind {
        "disp" | "funcptr" => "*mut core::ffi::c_void".to_string(),
        "nondisp" => "u64".to_string(),
        "enum" => "i32".to_string(),
        "enum64" => "i64".to_string(),
        "bitmask" => "u32".to_string(),
        "bitmask64" => "u64".to_string(),
        "struct" => panic!("by-value struct/union param {base:?} (in {ctx}); needs a real layout"),
        "void" => "core::ffi::c_void".to_string(),
        "char" => "core::ffi::c_char".to_string(),
        "i8" => "i8".to_string(),
        "i16" => "i16".to_string(),
        "i32" | "int" | "int32_t" => "i32".to_string(),
        "i64" | "int64_t" => "i64".to_string(),
        "u8" | "uint8_t" => "u8".to_string(),
        "u16" | "uint16_t" => "u16".to_string(),
        "u32" | "uint32_t" => "u32".to_string(),
        "u64" | "uint64_t" => "u64".to_string(),
        "usize" | "size_t" => "usize".to_string(),
        "f32" | "float" => "f32".to_string(),
        "f64" | "double" => "f64".to_string(),
        other => panic!("unmapped by-value type {other:?} (base {base:?} in {ctx}); extend build.rs"),
    }
}

fn default_for(rust_ty: &str) -> &'static str {
    if rust_ty.starts_with("*const") {
        "core::ptr::null()"
    } else if rust_ty.starts_with("*mut") {
        "core::ptr::null_mut()"
    } else {
        "0" // truthful zero / VK_FALSE / NULL-equivalent for a non-VkResult scalar return.
    }
}

fn sanitize(name: &str, i: usize) -> String {
    const KW: &[&str] = &[
        "type", "ref", "box", "in", "fn", "let", "match", "move", "mut", "as", "impl", "loop",
        "where", "self", "final", "override", "become",
    ];
    if name.is_empty() {
        return format!("a{i}");
    }
    if KW.contains(&name) {
        return format!("{name}_");
    }
    name.to_string()
}

fn env(k: &str) -> String {
    std::env::var(k).unwrap_or_else(|_| panic!("env {k} not set"))
}

/// Entry points hand-implemented in `src/` (so the generator skips them to avoid duplicate symbols):
/// the loader proc-addr resolvers + instance/physical-device/device bring-up (`instance`/`device`), and
/// the IR-wired compute set (memory/buffer/shader/pipeline/descriptor/command-record/dispatch/submit/
/// fence) that marshals the C ABI and calls the `hl_vulkan` lowering services through the process-global
/// RemoteCommandSink (`compute`). The 3 `vk_icd*` loader hooks are hand-written in `icd` but are NOT in
/// the manifest, so they are not listed here. Everything else in the vk.xml surface is a generated stub.
const IMPLEMENTED: &[&str] = &[
    // ---- loader proc-addr dispatch (icd.rs) ----
    "vkGetInstanceProcAddr",
    "vkGetDeviceProcAddr",
    // ---- global / instance / physical-device (instance.rs) ----
    "vkEnumerateInstanceVersion",
    "vkEnumerateInstanceExtensionProperties",
    "vkEnumerateInstanceLayerProperties",
    "vkCreateInstance",
    "vkDestroyInstance",
    "vkEnumeratePhysicalDevices",
    "vkGetPhysicalDeviceProperties",
    "vkGetPhysicalDeviceFeatures",
    "vkGetPhysicalDeviceMemoryProperties",
    "vkGetPhysicalDeviceQueueFamilyProperties",
    "vkGetPhysicalDeviceFormatProperties",
    "vkGetPhysicalDeviceImageFormatProperties",
    "vkEnumerateDeviceExtensionProperties",
    "vkEnumerateDeviceLayerProperties",
    // ---- VK_KHR_get_physical_device_properties2 / core-1.1 `...2` queries (instance.rs) ----
    "vkGetPhysicalDeviceProperties2",
    "vkGetPhysicalDeviceFeatures2",
    "vkGetPhysicalDeviceMemoryProperties2",
    "vkGetPhysicalDeviceQueueFamilyProperties2",
    "vkGetPhysicalDeviceFormatProperties2",
    // ---- device + queue (device.rs) ----
    "vkCreateDevice",
    "vkDestroyDevice",
    "vkGetDeviceQueue",
    // ---- IR-wired compute path (compute.rs) ----
    // memory + buffers
    "vkCreateBuffer",
    "vkDestroyBuffer",
    "vkGetBufferMemoryRequirements",
    "vkAllocateMemory",
    "vkFreeMemory",
    "vkBindBufferMemory",
    "vkMapMemory",
    "vkUnmapMemory",
    // shaders + pipelines
    "vkCreateShaderModule",
    "vkDestroyShaderModule",
    "vkCreatePipelineLayout",
    "vkDestroyPipelineLayout",
    "vkCreateComputePipelines",
    "vkDestroyPipeline",
    // descriptors
    "vkCreateDescriptorSetLayout",
    "vkDestroyDescriptorSetLayout",
    "vkCreateDescriptorPool",
    "vkDestroyDescriptorPool",
    "vkAllocateDescriptorSets",
    "vkUpdateDescriptorSets",
    // command pool + buffers + record + submit
    "vkCreateCommandPool",
    "vkDestroyCommandPool",
    "vkAllocateCommandBuffers",
    "vkBeginCommandBuffer",
    "vkEndCommandBuffer",
    "vkCmdBindPipeline",
    "vkCmdBindDescriptorSets",
    "vkCmdDispatch",
    "vkQueueSubmit",
    "vkQueueWaitIdle",
    "vkDeviceWaitIdle",
    // fences
    "vkCreateFence",
    "vkDestroyFence",
    "vkWaitForFences",
    "vkResetFences",
    "vkGetFenceStatus",
    // ---- IR-wired graphics path (graphics.rs) ----
    // images + views + samplers
    "vkCreateImage",
    "vkDestroyImage",
    "vkGetImageMemoryRequirements",
    "vkBindImageMemory",
    "vkCreateImageView",
    "vkDestroyImageView",
    "vkCreateSampler",
    "vkDestroySampler",
    // render pass + framebuffer
    "vkCreateRenderPass",
    "vkDestroyRenderPass",
    "vkCreateFramebuffer",
    "vkDestroyFramebuffer",
    // graphics pipeline
    "vkCreateGraphicsPipelines",
    // render-pass command recording
    "vkCmdBeginRenderPass",
    "vkCmdEndRenderPass",
    "vkCmdBindVertexBuffers",
    "vkCmdBindIndexBuffer",
    "vkCmdDraw",
    "vkCmdDrawIndexed",
    // WSI: swapchain + present + semaphores
    "vkCreateSwapchainKHR",
    "vkDestroySwapchainKHR",
    "vkGetSwapchainImagesKHR",
    "vkAcquireNextImageKHR",
    "vkQueuePresentKHR",
    // ---- IR-wired transfer path (transfer.rs): copies / blits / clears / fills / barriers ----
    "vkCmdCopyBuffer",
    "vkCmdCopyBufferToImage",
    "vkCmdCopyImageToBuffer",
    "vkCmdCopyImage",
    "vkCmdBlitImage",
    "vkCmdClearColorImage",
    "vkCmdClearAttachments",
    "vkCmdFillBuffer",
    "vkCmdUpdateBuffer",
    "vkCmdPipelineBarrier",
    "vkCmdPipelineBarrier2",
    // ---- sync + query path (sync.rs): semaphores (binary + timeline), events, query pools ----
    "vkCreateSemaphore",
    "vkDestroySemaphore",
    "vkSignalSemaphore",
    "vkWaitSemaphores",
    "vkGetSemaphoreCounterValue",
    "vkCreateEvent",
    "vkDestroyEvent",
    "vkGetEventStatus",
    "vkSetEvent",
    "vkResetEvent",
    "vkCmdSetEvent",
    "vkCmdResetEvent",
    "vkCmdWaitEvents",
    "vkCreateQueryPool",
    "vkDestroyQueryPool",
    "vkGetQueryPoolResults",
    "vkResetQueryPool",
    "vkCmdBeginQuery",
    "vkCmdEndQuery",
    "vkCmdResetQueryPool",
    "vkCmdWriteTimestamp",
    "vkCmdCopyQueryPoolResults",
];
