//! Codegen for the guest `libvk_hl.so.1` ICD shim: turn `registry/vk_commands.manifest` into the
//! complete `#[no_mangle] extern "C"` `vk*` export surface (712 commands) plus the name→address
//! dispatch table the loader-facing `vk_icdGetInstanceProcAddr` / `vkGetInstanceProcAddr` resolve
//! against.
//!
//! Every command NOT hand-written in `src/` (`IMPLEMENTED` below) is emitted here as a spec-faithful
//! default stub: correct C-ABI signature (so the loader/app resolves the symbol + links), a
//! `HL_SHIM_DEBUG`-gated once-per-name trace, and a benign, TRUTHFUL return — a `VkResult`-returning
//! command returns `VK_ERROR_FEATURE_NOT_PRESENT` (never a false `VK_SUCCESS`) after nulling any output
//! handle; every other return is the truthful zero/NULL. Real bodies replace stubs without ever
//! changing the exported surface. Ported from `hl-shim-vk/build.rs` (capability-inventory + origins
//! codegen dropped — this is the transport-wired template).
//!
//! Manifest records: `T<TAB>type<TAB>kind` classify by-value types (so a bare param maps without
//! knowing every Vulkan type); `C<TAB>name<TAB>ret<TAB>params` are the commands. A pointer is a
//! pointer — every `*`-suffixed C type lowers to a `c_void` pointer regardless of pointee.
//!
//! Also bakes the shared-object soname `libvk_hl.so.1` (the ICD library the icd.json `library_path`
//! names) on Linux.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::PathBuf;

/// `VkResult` a truthful stub returns instead of a false `VK_SUCCESS` (stable Vulkan ABI, from vk.xml).
const VK_ERROR_FEATURE_NOT_PRESENT: i32 = -8;

fn main() {
    let manifest =
        PathBuf::from(BuildEnv::read("CARGO_MANIFEST_DIR")).join("registry/vk_commands.manifest");
    println!("cargo:rerun-if-changed={}", manifest.display());
    println!("cargo:rerun-if-changed=build.rs");
    // `-Wl,-soname` is a GNU-ld flag (the ICD only ships on the Linux guest); emit it only on Linux.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("linux") {
        println!("cargo:rustc-cdylib-link-arg=-Wl,-soname,libvk_hl.so.1");
    }

    let text = std::fs::read_to_string(&manifest)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest.display()));

    // Pass 1: the by-value type classification table.
    let mut kinds: HashMap<String, String> = HashMap::new();
    for line in text.lines() {
        let line = line.trim_end();
        if !line.starts_with("T\t") {
            continue;
        }
        let mut f = line.split('\t');
        f.next();
        let name = f.next().unwrap_or("");
        let kind = f.next().unwrap_or("");
        kinds.insert(name.to_string(), kind.to_string());
    }

    // Pass 2: emit a C-ABI stub for every non-IMPLEMENTED command, plus a dispatch entry for all.
    let mut out = String::new();
    out.push_str("// @generated by build.rs from registry/vk_commands.manifest — DO NOT EDIT.\n\n");

    let mut cmds = 0usize;
    let mut stubs = 0usize;
    let mut dispatch = String::new();
    let mut names = String::new();
    for (lineno, line) in text.lines().enumerate() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') || line.starts_with("T\t") {
            continue;
        }
        let mut f = line.split('\t');
        let rec = f.next().unwrap_or("");
        if rec != "C" {
            panic!("manifest line {}: unknown record {rec:?}", lineno + 1);
        }
        let name = f.next().unwrap_or("");
        let ret = f.next().unwrap_or("void");
        let params = f.next().unwrap_or("");
        if name.is_empty() {
            panic!("manifest line {}: empty name: {line:?}", lineno + 1);
        }
        cmds += 1;
        // Every exported entry point — hand-written or generated — is resolvable at crate root by its
        // bare name (implemented ones via `use` in lib.rs), so the dispatch resolver references them
        // uniformly. The fn-item→address cast runs at RUNTIME (a `static` fails const-eval), so we emit
        // a match function rather than a table.
        writeln!(
            dispatch,
            "        \"{name}\" => Some({name} as *const () as usize),"
        )
        .unwrap();
        writeln!(names, "    \"{name}\",").unwrap();
        if IMPLEMENTED.contains(&name) {
            continue; // hand-written in src/; a generated stub would collide.
        }
        stubs += 1;
        emit_stub(&mut out, name, ret, params, &kinds);
    }

    writeln!(
        out,
        "\n/// Total Vulkan `vk*` entry points in the manifest (the exported command surface)."
    )
    .unwrap();
    writeln!(out, "pub const VK_ENTRYPOINTS: usize = {cmds};").unwrap();
    writeln!(
        out,
        "/// Entry points emitted as default stubs (not yet hand-implemented)."
    )
    .unwrap();
    writeln!(out, "pub const GENERATED_STUBS: usize = {stubs};").unwrap();
    writeln!(
        out,
        "/// Entry points with real hand-written bodies in `src/`."
    )
    .unwrap();
    writeln!(
        out,
        "pub const IMPLEMENTED_ENTRYPOINTS: usize = {};",
        IMPLEMENTED.len()
    )
    .unwrap();

    // The name→address resolver the loader-facing proc-addr entries in `crate::icd` consult. A match
    // over the whole exported `vk*` surface; the address cast runs at call time (see above).
    writeln!(
        out,
        "\n/// Resolve any exported `vk*` entry point by name to its address. Consulted by the"
    )
    .unwrap();
    writeln!(
        out,
        "/// loader-facing proc-addr resolvers in `crate::icd`. Runtime cast (not a const table)."
    )
    .unwrap();
    writeln!(out, "pub fn dispatch_addr(name: &str) -> Option<usize> {{\n    match name {{\n{dispatch}        _ => None,\n    }}\n}}").unwrap();
    // A name-only census the surface tests can iterate without taking any addresses.
    writeln!(
        out,
        "\n/// Every exported `vk*` entry-point name (the completeness census list)."
    )
    .unwrap();
    writeln!(out, "pub static DISPATCH_NAMES: &[&str] = &[\n{names}];").unwrap();

    let out_path = PathBuf::from(BuildEnv::read("OUT_DIR")).join("generated_entrypoints.rs");
    std::fs::write(&out_path, out).unwrap();
}

fn emit_stub(
    out: &mut String,
    name: &str,
    ret: &str,
    params: &str,
    kinds: &HashMap<String, String>,
) {
    let is_vk_result = ret.trim() == "VkResult";
    let mut sig = String::new();
    let mut argnames: Vec<String> = Vec::new();
    let mut last_out: Option<String> = None; // last param IF it is a single `*mut` output pointer
    if !params.is_empty() {
        let n = params.split(';').count();
        for (i, p) in params.split(';').enumerate() {
            let (ty, pname) = p
                .split_once('|')
                .unwrap_or_else(|| panic!("bad param {p:?} in {name}"));
            let rty = map_type(ty.trim(), name, kinds);
            let mut pn = ParameterName::sanitize(pname.trim(), i);
            // Guarantee unique parameter identifiers (a manifest can carry repeated names across
            // api-variant params). Names are cosmetic — the ABI is unaffected.
            while argnames.contains(&pn) {
                pn.push_str(&format!("_{i}"));
            }
            if i > 0 {
                sig.push_str(", ");
            }
            write!(sig, "{pn}: {rty}").unwrap();
            // A `vkCreate*`/`vkAllocate*` command's final parameter is its output handle — a single,
            // non-const `*mut` pointer. Record it so a failing stub can null it (VK_NULL_HANDLE) before
            // returning: truthful failure must initialize the output, never leave a caller reading junk.
            if i + 1 == n && rty.starts_with("*mut ") && !rty.starts_with("*mut *mut") {
                last_out = Some(pn.clone());
            }
            argnames.push(pn);
        }
    }
    let rmap = map_ret(ret.trim(), name, kinds);
    let arrow = rmap
        .as_ref()
        .map(|r| format!(" -> {r}"))
        .unwrap_or_default();
    let touch: String = argnames.iter().map(|a| format!("let _ = {a}; ")).collect();
    let init_out = match &last_out {
        Some(outp)
            if is_vk_result && (name.starts_with("vkCreate") || name.starts_with("vkAllocate")) =>
        {
            format!("unsafe {{ if !{outp}.is_null() {{ *({outp} as *mut u64) = 0; }} }} ")
        }
        _ => String::new(),
    };
    let body = match &rmap {
        None => format!("{touch}crate::stub::Stub::hit(\"{name}\");"),
        Some(r) => {
            let retval = if is_vk_result {
                VK_ERROR_FEATURE_NOT_PRESENT.to_string()
            } else {
                RustType::new(r).default_value().to_string()
            };
            format!("{touch}{init_out}crate::stub::Stub::hit(\"{name}\"); {retval}")
        }
    };
    writeln!(
        out,
        "#[no_mangle]\npub extern \"C\" fn {name}({sig}){arrow} {{ {body} }}\n"
    )
    .unwrap();
}

/// C return type -> Rust type (None == `void`/unit).
fn map_ret(c: &str, ctx: &str, kinds: &HashMap<String, String>) -> Option<String> {
    if c == "void" {
        return None;
    }
    Some(map_type(c, ctx, kinds))
}

/// C type string -> Rust C-ABI type. Pointers (single/double, const/mut) lower to a `c_void` pointer —
/// a pointer is a pointer at the ABI, so the pointee is irrelevant for a stub's signature. Only a bare
/// by-value type consults the T-table (fail-loud on an unclassified base type).
fn map_type(c: &str, ctx: &str, kinds: &HashMap<String, String>) -> String {
    let c = c.trim();
    if c.ends_with("*const*") || c.ends_with("* const*") {
        return "*const *const core::ffi::c_void".to_string();
    }
    if let Some(rest) = c.strip_suffix("**") {
        let is_const = rest.trim_start().starts_with("const ");
        return if is_const {
            "*const *const core::ffi::c_void".to_string()
        } else {
            "*mut *mut core::ffi::c_void".to_string()
        };
    }
    if let Some(rest) = c.strip_suffix('*') {
        let is_const = rest.trim_start().starts_with("const ");
        return if is_const {
            "*const core::ffi::c_void".to_string()
        } else {
            "*mut core::ffi::c_void".to_string()
        };
    }
    scalar(c, ctx, kinds).to_string()
}

/// A bare (by-value) Vulkan/C type -> its Rust C-ABI representation, via the vk.xml-derived T-table or
/// a concrete scalar token. Fail-loud on anything unclassified so a registry bump surfaces at build
/// time rather than silently mis-typing the ABI.
fn scalar(c: &str, ctx: &str, kinds: &HashMap<String, String>) -> String {
    let base = c.strip_prefix("const ").unwrap_or(c).trim();
    let kind = kinds.get(base).map(String::as_str).unwrap_or(base);
    match kind {
        "disp" | "funcptr" => "*mut core::ffi::c_void".to_string(),
        "nondisp" => "u64".to_string(),
        "enum" => "i32".to_string(),
        "enum64" => "i64".to_string(),
        "bitmask" => "u32".to_string(),
        "bitmask64" => "u64".to_string(),
        "struct" => panic!("by-value struct/union param {base:?} (in {ctx}); needs a real layout"),
        "void" => "core::ffi::c_void".to_string(),
        "char" => "core::ffi::c_char".to_string(),
        "i8" => "i8".to_string(),
        "i16" => "i16".to_string(),
        "i32" | "int" | "int32_t" => "i32".to_string(),
        "i64" | "int64_t" => "i64".to_string(),
        "u8" | "uint8_t" => "u8".to_string(),
        "u16" | "uint16_t" => "u16".to_string(),
        "u32" | "uint32_t" => "u32".to_string(),
        "u64" | "uint64_t" => "u64".to_string(),
        "usize" | "size_t" => "usize".to_string(),
        "f32" | "float" => "f32".to_string(),
        "f64" | "double" => "f64".to_string(),
        other => {
            panic!("unmapped by-value type {other:?} (base {base:?} in {ctx}); extend build.rs")
        }
    }
}

struct RustType<'a>(&'a str);

impl<'a> RustType<'a> {
    fn new(value: &'a str) -> Self {
        Self(value)
    }

    fn default_value(&self) -> &'static str {
        if self.0.starts_with("*const") {
            "core::ptr::null()"
        } else if self.0.starts_with("*mut") {
            "core::ptr::null_mut()"
        } else {
            "0" // truthful zero / VK_FALSE / NULL-equivalent for a non-VkResult scalar return.
        }
    }
}

struct ParameterName;

impl ParameterName {
    fn sanitize(name: &str, index: usize) -> String {
        const KEYWORDS: &[&str] = &[
            "type", "ref", "box", "in", "fn", "let", "match", "move", "mut", "as", "impl", "loop",
            "where", "self", "final", "override", "become",
        ];
        if name.is_empty() {
            return format!("a{index}");
        }
        if KEYWORDS.contains(&name) {
            return format!("{name}_");
        }
        name.to_string()
    }
}

struct BuildEnv;

impl BuildEnv {
    fn read(key: &str) -> String {
        std::env::var(key).unwrap_or_else(|_| panic!("env {key} not set"))
    }
}

/// Entry points hand-implemented in `src/` (so the generator skips them to avoid duplicate symbols):
/// the loader proc-addr resolvers + instance/physical-device/device bring-up (`instance`/`device`), and
/// the IR-wired compute set (memory/buffer/shader/pipeline/descriptor/command-record/dispatch/submit/
/// fence) that marshals the C ABI and calls the `hl_vulkan` lowering services through the process-global
/// RemoteCommandSink (`compute`). The 3 `vk_icd*` loader hooks are hand-written in `icd` but are NOT in
/// the manifest, so they are not listed here. Everything else in the vk.xml surface is a generated stub.
const IMPLEMENTED: &[&str] = &[
    // ---- loader proc-addr dispatch (icd.rs) ----
    "vkGetInstanceProcAddr",
    "vkGetDeviceProcAddr",
    // ---- global / instance / physical-device (instance.rs) ----
    "vkEnumerateInstanceVersion",
    "vkEnumerateInstanceExtensionProperties",
    "vkEnumerateInstanceLayerProperties",
    "vkCreateInstance",
    "vkDestroyInstance",
    "vkEnumeratePhysicalDevices",
    "vkGetPhysicalDeviceProperties",
    "vkGetPhysicalDeviceFeatures",
    "vkGetPhysicalDeviceMemoryProperties",
    "vkGetPhysicalDeviceQueueFamilyProperties",
    "vkGetPhysicalDeviceFormatProperties",
    "vkGetPhysicalDeviceImageFormatProperties",
    "vkEnumerateDeviceExtensionProperties",
    "vkEnumerateDeviceLayerProperties",
    // ---- VK_KHR_get_physical_device_properties2 / core-1.1 `...2` queries (instance.rs) ----
    "vkGetPhysicalDeviceProperties2",
    "vkGetPhysicalDeviceFeatures2",
    "vkGetPhysicalDeviceMemoryProperties2",
    "vkGetPhysicalDeviceQueueFamilyProperties2",
    "vkGetPhysicalDeviceFormatProperties2",
    // ...2KHR aliases (VK_KHR_get_physical_device_properties2) — delegate to the core bodies above
    "vkGetPhysicalDeviceProperties2KHR",
    "vkGetPhysicalDeviceFeatures2KHR",
    "vkGetPhysicalDeviceMemoryProperties2KHR",
    "vkGetPhysicalDeviceQueueFamilyProperties2KHR",
    "vkGetPhysicalDeviceFormatProperties2KHR",
    // ---- device + queue (device.rs) ----
    "vkCreateDevice",
    "vkDestroyDevice",
    "vkGetDeviceQueue",
    "vkGetDeviceQueue2",
    // ---- IR-wired compute path (compute.rs) ----
    // memory + buffers
    "vkCreateBuffer",
    "vkDestroyBuffer",
    "vkGetBufferMemoryRequirements",
    "vkAllocateMemory",
    "vkFreeMemory",
    "vkBindBufferMemory",
    "vkMapMemory",
    "vkUnmapMemory",
    // bind-memory-2 / get-memory-requirements-2 for buffers (core 1.1 + KHR) — delegate to the v1 bodies
    "vkBindBufferMemory2",
    "vkBindBufferMemory2KHR",
    "vkGetBufferMemoryRequirements2",
    "vkGetBufferMemoryRequirements2KHR",
    // shaders + pipelines
    "vkCreateShaderModule",
    "vkDestroyShaderModule",
    "vkCreatePipelineLayout",
    "vkDestroyPipelineLayout",
    "vkCreateComputePipelines",
    "vkDestroyPipeline",
    // descriptors
    "vkCreateDescriptorSetLayout",
    "vkDestroyDescriptorSetLayout",
    "vkCreateDescriptorPool",
    "vkDestroyDescriptorPool",
    "vkAllocateDescriptorSets",
    "vkUpdateDescriptorSets",
    // descriptor update templates (core 1.1 + VK_KHR_descriptor_update_template)
    "vkCreateDescriptorUpdateTemplate",
    "vkCreateDescriptorUpdateTemplateKHR",
    "vkDestroyDescriptorUpdateTemplate",
    "vkDestroyDescriptorUpdateTemplateKHR",
    "vkUpdateDescriptorSetWithTemplate",
    "vkUpdateDescriptorSetWithTemplateKHR",
    // pipeline cache (modeled no-op-with-valid-data)
    "vkCreatePipelineCache",
    "vkDestroyPipelineCache",
    "vkMergePipelineCaches",
    "vkGetPipelineCacheData",
    // command pool + buffers + record + submit
    "vkCreateCommandPool",
    "vkDestroyCommandPool",
    "vkAllocateCommandBuffers",
    "vkBeginCommandBuffer",
    "vkEndCommandBuffer",
    "vkCmdBindPipeline",
    "vkCmdBindDescriptorSets",
    "vkCmdDispatch",
    "vkCmdDispatchIndirect",
    "vkCmdExecuteCommands",
    "vkQueueSubmit",
    "vkQueueWaitIdle",
    "vkDeviceWaitIdle",
    // fences
    "vkCreateFence",
    "vkDestroyFence",
    "vkWaitForFences",
    "vkResetFences",
    "vkGetFenceStatus",
    // ---- IR-wired graphics path (graphics.rs) ----
    // images + views + samplers
    "vkCreateImage",
    "vkDestroyImage",
    "vkGetImageMemoryRequirements",
    "vkGetImageSubresourceLayout",
    "vkBindImageMemory",
    // bind-memory-2 / get-memory-requirements-2 for images (core 1.1 + KHR) — delegate to the v1 bodies
    "vkBindImageMemory2",
    "vkBindImageMemory2KHR",
    "vkGetImageMemoryRequirements2",
    "vkGetImageMemoryRequirements2KHR",
    "vkCreateImageView",
    "vkDestroyImageView",
    "vkCreateSampler",
    "vkDestroySampler",
    // render pass + framebuffer
    "vkCreateRenderPass",
    "vkDestroyRenderPass",
    "vkCreateFramebuffer",
    "vkDestroyFramebuffer",
    // graphics pipeline
    "vkCreateGraphicsPipelines",
    // render-pass command recording
    "vkCmdBeginRenderPass",
    "vkCmdEndRenderPass",
    // dynamic rendering (VK_KHR_dynamic_rendering / core 1.3) — render-pass-object-free recording
    "vkCmdBeginRendering",
    "vkCmdBeginRenderingKHR",
    "vkCmdEndRendering",
    "vkCmdEndRenderingKHR",
    "vkCmdBindVertexBuffers",
    "vkCmdBindIndexBuffer",
    "vkCmdDraw",
    "vkCmdDrawIndexed",
    "vkCmdDrawIndirect",
    "vkCmdDrawIndexedIndirect",
    // dynamic state (viewport/scissor lower to IR; the rest is recorded command state) + push constants
    "vkCmdSetViewport",
    "vkCmdSetScissor",
    "vkCmdSetLineWidth",
    "vkCmdSetDepthBias",
    "vkCmdSetBlendConstants",
    "vkCmdSetStencilCompareMask",
    "vkCmdSetStencilWriteMask",
    "vkCmdSetStencilReference",
    "vkCmdPushConstants",
    // WSI: swapchain + present + semaphores
    "vkCreateSwapchainKHR",
    "vkDestroySwapchainKHR",
    "vkGetSwapchainImagesKHR",
    "vkAcquireNextImageKHR",
    "vkQueuePresentKHR",
    // ---- WSI surface: VK_KHR_surface + platform constructors + phys-device queries (surface.rs) ----
    "vkCreateXcbSurfaceKHR",
    "vkCreateXlibSurfaceKHR",
    "vkCreateWaylandSurfaceKHR",
    "vkCreateHeadlessSurfaceEXT",
    "vkDestroySurfaceKHR",
    "vkGetPhysicalDeviceSurfaceSupportKHR",
    "vkGetPhysicalDeviceSurfaceCapabilitiesKHR",
    "vkGetPhysicalDeviceSurfaceFormatsKHR",
    "vkGetPhysicalDeviceSurfacePresentModesKHR",
    "vkGetPhysicalDeviceXcbPresentationSupportKHR",
    "vkGetPhysicalDeviceXlibPresentationSupportKHR",
    "vkGetPhysicalDeviceWaylandPresentationSupportKHR",
    // ---- IR-wired transfer path (transfer.rs): copies / blits / clears / fills / barriers ----
    "vkCmdCopyBuffer",
    "vkCmdCopyBufferToImage",
    "vkCmdCopyImageToBuffer",
    "vkCmdCopyImage",
    "vkCmdBlitImage",
    "vkCmdClearColorImage",
    "vkCmdClearAttachments",
    "vkCmdFillBuffer",
    "vkCmdUpdateBuffer",
    "vkCmdPipelineBarrier",
    "vkCmdPipelineBarrier2",
    // ...2 / KHR copy variants (delegate to the v1 lowering)
    "vkCmdCopyBuffer2",
    "vkCmdCopyBuffer2KHR",
    "vkCmdCopyBufferToImage2",
    "vkCmdCopyBufferToImage2KHR",
    "vkCmdBlitImage2",
    "vkCmdBlitImage2KHR",
    // ---- sync + query path (sync.rs): semaphores (binary + timeline), events, query pools ----
    "vkCreateSemaphore",
    "vkDestroySemaphore",
    "vkSignalSemaphore",
    "vkWaitSemaphores",
    "vkGetSemaphoreCounterValue",
    "vkCreateEvent",
    "vkDestroyEvent",
    "vkGetEventStatus",
    "vkSetEvent",
    "vkResetEvent",
    "vkCmdSetEvent",
    "vkCmdResetEvent",
    "vkCmdWaitEvents",
    "vkCreateQueryPool",
    "vkDestroyQueryPool",
    "vkGetQueryPoolResults",
    "vkResetQueryPool",
    "vkCmdBeginQuery",
    "vkCmdEndQuery",
    "vkCmdResetQueryPool",
    "vkCmdWriteTimestamp",
    "vkCmdCopyQueryPoolResults",
    // ---- maintenance1-5 + private-data + ycbcr + calibrated timestamps (maintenance.rs) ----
    "vkTrimCommandPool",
    "vkResetCommandPool",
    "vkResetCommandBuffer",
    "vkFreeCommandBuffers",
    "vkGetDescriptorSetLayoutSupport",
    "vkGetDescriptorSetLayoutSupportKHR",
    "vkGetDeviceBufferMemoryRequirements",
    "vkGetDeviceBufferMemoryRequirementsKHR",
    "vkGetDeviceImageMemoryRequirements",
    "vkGetDeviceImageMemoryRequirementsKHR",
    "vkGetImageSparseMemoryRequirements",
    "vkGetImageSparseMemoryRequirements2",
    "vkGetImageSparseMemoryRequirements2KHR",
    "vkGetDeviceImageSparseMemoryRequirements",
    "vkGetDeviceImageSparseMemoryRequirementsKHR",
    "vkCreatePrivateDataSlot",
    "vkCreatePrivateDataSlotEXT",
    "vkDestroyPrivateDataSlot",
    "vkDestroyPrivateDataSlotEXT",
    "vkGetPrivateData",
    "vkGetPrivateDataEXT",
    "vkSetPrivateData",
    "vkSetPrivateDataEXT",
    "vkCreateSamplerYcbcrConversion",
    "vkCreateSamplerYcbcrConversionKHR",
    "vkDestroySamplerYcbcrConversion",
    "vkDestroySamplerYcbcrConversionKHR",
    "vkGetCalibratedTimestampsKHR",
    "vkGetCalibratedTimestampsEXT",
    "vkGetPhysicalDeviceCalibrateableTimeDomainsKHR",
    "vkGetPhysicalDeviceCalibrateableTimeDomainsEXT",
    // ---- host image copy (honest not-supported) + subresource-layout2 (hostcopy.rs) ----
    "vkCopyMemoryToImage",
    "vkCopyMemoryToImageEXT",
    "vkCopyImageToMemory",
    "vkCopyImageToMemoryEXT",
    "vkCopyImageToImage",
    "vkCopyImageToImageEXT",
    "vkTransitionImageLayout",
    "vkTransitionImageLayoutEXT",
    "vkGetImageSubresourceLayout2",
    "vkGetImageSubresourceLayout2EXT",
    "vkGetImageSubresourceLayout2KHR",
    // ---- promoted `...2` copy variants + sync2 barrier (transfer.rs) ----
    "vkCmdCopyImage2",
    "vkCmdCopyImage2KHR",
    "vkCmdCopyImageToBuffer2",
    "vkCmdCopyImageToBuffer2KHR",
    "vkCmdPipelineBarrier2KHR",
    // ---- timeline/host-query/sync2 aliases (sync.rs) ----
    "vkGetSemaphoreCounterValueKHR",
    "vkSignalSemaphoreKHR",
    "vkWaitSemaphoresKHR",
    "vkResetQueryPoolEXT",
    "vkCmdWriteTimestamp2",
    "vkCmdWriteTimestamp2KHR",
    "vkCmdSetEvent2",
    "vkCmdSetEvent2KHR",
    "vkCmdResetEvent2",
    "vkCmdResetEvent2KHR",
    "vkCmdWaitEvents2",
    "vkCmdWaitEvents2KHR",
    // ---- sync2 submit + maintenance5 map/unmap-2 (compute.rs) ----
    "vkQueueSubmit2",
    "vkQueueSubmit2KHR",
    "vkMapMemory2",
    "vkMapMemory2KHR",
    "vkUnmapMemory2",
    "vkUnmapMemory2KHR",
    // ---- image-format-properties2 (instance.rs) ----
    "vkGetPhysicalDeviceImageFormatProperties2",
    "vkGetPhysicalDeviceImageFormatProperties2KHR",
    // ---- create-renderpass2 family (graphics.rs) ----
    "vkCreateRenderPass2",
    "vkCreateRenderPass2KHR",
    "vkCmdBeginRenderPass2",
    "vkCmdBeginRenderPass2KHR",
    "vkCmdEndRenderPass2",
    "vkCmdEndRenderPass2KHR",
    "vkCmdNextSubpass",
    "vkCmdNextSubpass2",
    "vkCmdNextSubpass2KHR",
    // ---- wholesale-unmodeled extension families: honest not-supported (unsupported.rs) ----
    "vkBindAccelerationStructureMemoryNV",
    "vkBindOpticalFlowSessionImageNV",
    "vkBindVideoSessionMemoryKHR",
    "vkBuildAccelerationStructuresKHR",
    "vkBuildMicromapsEXT",
    "vkCmdBeginVideoCodingKHR",
    "vkCmdBuildAccelerationStructureNV",
    "vkCmdBuildAccelerationStructuresIndirectKHR",
    "vkCmdBuildAccelerationStructuresKHR",
    "vkCmdBuildMicromapsEXT",
    "vkCmdControlVideoCodingKHR",
    "vkCmdCopyAccelerationStructureKHR",
    "vkCmdCopyAccelerationStructureNV",
    "vkCmdCopyAccelerationStructureToMemoryKHR",
    "vkCmdCopyMemoryToAccelerationStructureKHR",
    "vkCmdCopyMemoryToMicromapEXT",
    "vkCmdCopyMicromapEXT",
    "vkCmdCopyMicromapToMemoryEXT",
    "vkCmdDecodeVideoKHR",
    "vkCmdDrawMeshTasksEXT",
    "vkCmdDrawMeshTasksIndirectCountEXT",
    "vkCmdDrawMeshTasksIndirectCountNV",
    "vkCmdDrawMeshTasksIndirectEXT",
    "vkCmdDrawMeshTasksIndirectNV",
    "vkCmdDrawMeshTasksNV",
    "vkCmdEncodeVideoKHR",
    "vkCmdEndVideoCodingKHR",
    "vkCmdOpticalFlowExecuteNV",
    "vkCmdSetRayTracingPipelineStackSizeKHR",
    "vkCmdTraceRaysIndirect2KHR",
    "vkCmdTraceRaysIndirectKHR",
    "vkCmdTraceRaysKHR",
    "vkCmdTraceRaysNV",
    "vkCmdWriteAccelerationStructuresPropertiesKHR",
    "vkCmdWriteAccelerationStructuresPropertiesNV",
    "vkCmdWriteMicromapsPropertiesEXT",
    "vkCopyAccelerationStructureKHR",
    "vkCopyAccelerationStructureToMemoryKHR",
    "vkCopyMemoryToAccelerationStructureKHR",
    "vkCopyMemoryToMicromapEXT",
    "vkCopyMicromapEXT",
    "vkCopyMicromapToMemoryEXT",
    "vkCreateAccelerationStructureKHR",
    "vkCreateAccelerationStructureNV",
    "vkCreateMicromapEXT",
    "vkCreateOpticalFlowSessionNV",
    "vkCreateRayTracingPipelinesKHR",
    "vkCreateRayTracingPipelinesNV",
    "vkCreateVideoSessionKHR",
    "vkCreateVideoSessionParametersKHR",
    "vkDestroyAccelerationStructureKHR",
    "vkDestroyAccelerationStructureNV",
    "vkDestroyMicromapEXT",
    "vkDestroyOpticalFlowSessionNV",
    "vkDestroyVideoSessionKHR",
    "vkDestroyVideoSessionParametersKHR",
    "vkGetAccelerationStructureBuildSizesKHR",
    "vkGetAccelerationStructureDeviceAddressKHR",
    "vkGetAccelerationStructureHandleNV",
    "vkGetAccelerationStructureMemoryRequirementsNV",
    "vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT",
    "vkGetDeviceAccelerationStructureCompatibilityKHR",
    "vkGetDeviceMicromapCompatibilityEXT",
    "vkGetEncodedVideoSessionParametersKHR",
    "vkGetMicromapBuildSizesEXT",
    "vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR",
    "vkGetPhysicalDeviceCooperativeMatrixPropertiesNV",
    "vkGetPhysicalDeviceOpticalFlowImageFormatsNV",
    "vkGetPhysicalDeviceVideoCapabilitiesKHR",
    "vkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR",
    "vkGetPhysicalDeviceVideoFormatPropertiesKHR",
    "vkGetRayTracingCaptureReplayShaderGroupHandlesKHR",
    "vkGetRayTracingShaderGroupHandlesKHR",
    "vkGetRayTracingShaderGroupHandlesNV",
    "vkGetRayTracingShaderGroupStackSizeKHR",
    "vkGetVideoSessionMemoryRequirementsKHR",
    "vkUpdateVideoSessionParametersKHR",
    "vkWriteAccelerationStructuresPropertiesKHR",
    "vkWriteMicromapsPropertiesEXT",
    // ================= converted GENERATED_STUBS -> IMPLEMENTED (this task) =================
    // ---- extended dynamic state 1/2/3 (dynstate.rs) ----
    "vkCmdSetCullMode",
    "vkCmdSetCullModeEXT",
    "vkCmdSetFrontFace",
    "vkCmdSetFrontFaceEXT",
    "vkCmdSetPrimitiveTopology",
    "vkCmdSetPrimitiveTopologyEXT",
    "vkCmdSetViewportWithCount",
    "vkCmdSetViewportWithCountEXT",
    "vkCmdSetScissorWithCount",
    "vkCmdSetScissorWithCountEXT",
    "vkCmdSetDepthTestEnable",
    "vkCmdSetDepthTestEnableEXT",
    "vkCmdSetDepthWriteEnable",
    "vkCmdSetDepthWriteEnableEXT",
    "vkCmdSetDepthCompareOp",
    "vkCmdSetDepthCompareOpEXT",
    "vkCmdSetDepthBoundsTestEnable",
    "vkCmdSetDepthBoundsTestEnableEXT",
    "vkCmdSetStencilTestEnable",
    "vkCmdSetStencilTestEnableEXT",
    "vkCmdSetStencilOp",
    "vkCmdSetStencilOpEXT",
    "vkCmdSetRasterizerDiscardEnable",
    "vkCmdSetRasterizerDiscardEnableEXT",
    "vkCmdSetDepthBiasEnable",
    "vkCmdSetDepthBiasEnableEXT",
    "vkCmdSetPrimitiveRestartEnable",
    "vkCmdSetPrimitiveRestartEnableEXT",
    "vkCmdSetDepthBounds",
    "vkCmdBindVertexBuffers2",
    "vkCmdBindVertexBuffers2EXT",
    "vkCmdSetLineStipple",
    "vkCmdSetLineStippleEXT",
    "vkCmdSetLineStippleEnableEXT",
    "vkCmdSetDepthBias2EXT",
    "vkCmdSetVertexInputEXT",
    "vkCmdSetColorBlendEnableEXT",
    "vkCmdSetColorBlendEquationEXT",
    "vkCmdSetColorWriteMaskEXT",
    "vkCmdSetColorWriteEnableEXT",
    "vkCmdSetRasterizationSamplesEXT",
    "vkCmdSetSampleMaskEXT",
    "vkCmdSetAlphaToCoverageEnableEXT",
    "vkCmdSetAlphaToOneEnableEXT",
    "vkCmdSetLogicOpEnableEXT",
    "vkCmdSetLogicOpEXT",
    "vkCmdSetPolygonModeEXT",
    "vkCmdSetTessellationDomainOriginEXT",
    "vkCmdSetPatchControlPointsEXT",
    "vkCmdSetProvokingVertexModeEXT",
    "vkCmdSetLineRasterizationModeEXT",
    "vkCmdSetDepthClampEnableEXT",
    "vkCmdSetDepthClipEnableEXT",
    "vkCmdSetDepthClipNegativeOneToOneEXT",
    "vkCmdSetConservativeRasterizationModeEXT",
    "vkCmdSetExtraPrimitiveOverestimationSizeEXT",
    "vkCmdSetSampleLocationsEnableEXT",
    "vkCmdSetColorBlendAdvancedEXT",
    "vkCmdSetRasterizationStreamEXT",
    // ---- buffer / memory device address (address.rs) ----
    "vkGetBufferDeviceAddress",
    "vkGetBufferDeviceAddressEXT",
    "vkGetBufferDeviceAddressKHR",
    "vkGetBufferOpaqueCaptureAddress",
    "vkGetBufferOpaqueCaptureAddressKHR",
    "vkGetDeviceMemoryOpaqueCaptureAddress",
    "vkGetDeviceMemoryOpaqueCaptureAddressKHR",
    // ---- debug utils / marker / report — benign no-op success (debug.rs) ----
    "vkSetDebugUtilsObjectNameEXT",
    "vkSetDebugUtilsObjectTagEXT",
    "vkQueueBeginDebugUtilsLabelEXT",
    "vkQueueEndDebugUtilsLabelEXT",
    "vkQueueInsertDebugUtilsLabelEXT",
    "vkCmdBeginDebugUtilsLabelEXT",
    "vkCmdEndDebugUtilsLabelEXT",
    "vkCmdInsertDebugUtilsLabelEXT",
    "vkCreateDebugUtilsMessengerEXT",
    "vkDestroyDebugUtilsMessengerEXT",
    "vkSubmitDebugUtilsMessageEXT",
    "vkDebugMarkerSetObjectNameEXT",
    "vkDebugMarkerSetObjectTagEXT",
    "vkCmdDebugMarkerBeginEXT",
    "vkCmdDebugMarkerEndEXT",
    "vkCmdDebugMarkerInsertEXT",
    "vkCreateDebugReportCallbackEXT",
    "vkDestroyDebugReportCallbackEXT",
    "vkDebugReportMessageEXT",
    // ---- device group + external handle properties (devgroup.rs) ----
    "vkGetDeviceGroupPeerMemoryFeatures",
    "vkGetDeviceGroupPeerMemoryFeaturesKHR",
    "vkCmdSetDeviceMask",
    "vkCmdSetDeviceMaskKHR",
    "vkCmdDispatchBase",
    "vkCmdDispatchBaseKHR",
    "vkGetDeviceGroupPresentCapabilitiesKHR",
    "vkGetDeviceGroupSurfacePresentModesKHR",
    "vkGetDeviceGroupSurfacePresentModes2EXT",
    "vkGetPhysicalDevicePresentRectanglesKHR",
    "vkEnumeratePhysicalDeviceGroups",
    "vkEnumeratePhysicalDeviceGroupsKHR",
    "vkGetPhysicalDeviceExternalBufferProperties",
    "vkGetPhysicalDeviceExternalBufferPropertiesKHR",
    "vkGetPhysicalDeviceExternalFenceProperties",
    "vkGetPhysicalDeviceExternalFencePropertiesKHR",
    "vkGetPhysicalDeviceExternalSemaphoreProperties",
    "vkGetPhysicalDeviceExternalSemaphorePropertiesKHR",
    // ---- core benign real bodies (corebits.rs) ----
    "vkFlushMappedMemoryRanges",
    "vkInvalidateMappedMemoryRanges",
    "vkGetDeviceMemoryCommitment",
    "vkGetRenderAreaGranularity",
    "vkGetRenderingAreaGranularityKHR",
    "vkGetRenderingAreaGranularity",
    "vkGetDeviceImageSubresourceLayout",
    "vkGetDeviceImageSubresourceLayoutKHR",
    "vkCreateBufferView",
    "vkDestroyBufferView",
    "vkFreeDescriptorSets",
    "vkResetDescriptorPool",
    "vkGetPhysicalDeviceSparseImageFormatProperties",
    "vkGetPhysicalDeviceSparseImageFormatProperties2",
    "vkGetPhysicalDeviceSparseImageFormatProperties2KHR",
    "vkGetPhysicalDeviceToolProperties",
    "vkGetPhysicalDeviceToolPropertiesEXT",
    "vkGetPhysicalDeviceMultisamplePropertiesEXT",
    "vkCmdClearDepthStencilImage",
    "vkCmdResolveImage",
    "vkCmdResolveImage2",
    "vkCmdResolveImage2KHR",
    "vkCmdDrawIndirectCount",
    "vkCmdDrawIndirectCountKHR",
    "vkCmdDrawIndirectCountAMD",
    "vkCmdDrawIndexedIndirectCount",
    "vkCmdDrawIndexedIndirectCountKHR",
    "vkCmdDrawIndexedIndirectCountAMD",
    "vkTrimCommandPoolKHR",
    // ---- honest not-supported long tail (unsupported.rs) ----
    "vkAcquireDrmDisplayEXT",
    "vkAcquireFullScreenExclusiveModeEXT",
    "vkAcquireImageANDROID",
    "vkAcquireNextImage2KHR",
    "vkAcquirePerformanceConfigurationINTEL",
    "vkAcquireProfilingLockKHR",
    "vkAcquireWinrtDisplayNV",
    "vkAcquireXlibDisplayEXT",
    "vkCmdBeginConditionalRenderingEXT",
    "vkCmdBeginQueryIndexedEXT",
    "vkCmdBeginTransformFeedbackEXT",
    "vkCmdBindDescriptorBufferEmbeddedSamplers2EXT",
    "vkCmdBindDescriptorBufferEmbeddedSamplersEXT",
    "vkCmdBindDescriptorBuffersEXT",
    "vkCmdBindDescriptorSets2",
    "vkCmdBindDescriptorSets2KHR",
    "vkCmdBindIndexBuffer2",
    "vkCmdBindIndexBuffer2KHR",
    "vkCmdBindInvocationMaskHUAWEI",
    "vkCmdBindPipelineShaderGroupNV",
    "vkCmdBindShadersEXT",
    "vkCmdBindShadingRateImageNV",
    "vkCmdBindTransformFeedbackBuffersEXT",
    "vkCmdCopyMemoryIndirectNV",
    "vkCmdCopyMemoryToImageIndirectNV",
    "vkCmdCuLaunchKernelNVX",
    "vkCmdCudaLaunchKernelNV",
    "vkCmdDecompressMemoryIndirectCountNV",
    "vkCmdDecompressMemoryNV",
    "vkCmdDispatchGraphAMDX",
    "vkCmdDispatchGraphIndirectAMDX",
    "vkCmdDispatchGraphIndirectCountAMDX",
    "vkCmdDrawClusterHUAWEI",
    "vkCmdDrawClusterIndirectHUAWEI",
    "vkCmdDrawIndirectByteCountEXT",
    "vkCmdDrawMultiEXT",
    "vkCmdDrawMultiIndexedEXT",
    "vkCmdEndConditionalRenderingEXT",
    "vkCmdEndQueryIndexedEXT",
    "vkCmdEndTransformFeedbackEXT",
    "vkCmdExecuteGeneratedCommandsNV",
    "vkCmdInitializeGraphScratchMemoryAMDX",
    "vkCmdPreprocessGeneratedCommandsNV",
    "vkCmdPushConstants2",
    "vkCmdPushConstants2KHR",
    "vkCmdPushDescriptorSet",
    "vkCmdPushDescriptorSet2",
    "vkCmdPushDescriptorSet2KHR",
    "vkCmdPushDescriptorSetKHR",
    "vkCmdPushDescriptorSetWithTemplate",
    "vkCmdPushDescriptorSetWithTemplate2",
    "vkCmdPushDescriptorSetWithTemplate2KHR",
    "vkCmdPushDescriptorSetWithTemplateKHR",
    "vkCmdRefreshObjectsKHR",
    "vkCmdSetAttachmentFeedbackLoopEnableEXT",
    "vkCmdSetCheckpointNV",
    "vkCmdSetCoarseSampleOrderNV",
    "vkCmdSetCoverageModulationModeNV",
    "vkCmdSetCoverageModulationTableEnableNV",
    "vkCmdSetCoverageModulationTableNV",
    "vkCmdSetCoverageReductionModeNV",
    "vkCmdSetCoverageToColorEnableNV",
    "vkCmdSetCoverageToColorLocationNV",
    "vkCmdSetDescriptorBufferOffsets2EXT",
    "vkCmdSetDescriptorBufferOffsetsEXT",
    "vkCmdSetDiscardRectangleEXT",
    "vkCmdSetDiscardRectangleEnableEXT",
    "vkCmdSetDiscardRectangleModeEXT",
    "vkCmdSetExclusiveScissorEnableNV",
    "vkCmdSetExclusiveScissorNV",
    "vkCmdSetFragmentShadingRateEnumNV",
    "vkCmdSetFragmentShadingRateKHR",
    "vkCmdSetPerformanceMarkerINTEL",
    "vkCmdSetPerformanceOverrideINTEL",
    "vkCmdSetPerformanceStreamMarkerINTEL",
    "vkCmdSetRenderingAttachmentLocations",
    "vkCmdSetRenderingInputAttachmentIndices",
    "vkCmdSetRepresentativeFragmentTestEnableNV",
    "vkCmdSetSampleLocationsEXT",
    "vkCmdSetShadingRateImageEnableNV",
    "vkCmdSetViewportShadingRatePaletteNV",
    "vkCmdSetViewportSwizzleNV",
    "vkCmdSetViewportWScalingEnableNV",
    "vkCmdSetViewportWScalingNV",
    "vkCmdSubpassShadingHUAWEI",
    "vkCmdUpdatePipelineIndirectBufferNV",
    "vkCmdWriteBufferMarker2AMD",
    "vkCmdWriteBufferMarkerAMD",
    "vkCompileDeferredNV",
    "vkCreateAndroidSurfaceKHR",
    "vkCreateBufferCollectionFUCHSIA",
    "vkCreateCuFunctionNVX",
    "vkCreateCuModuleNVX",
    "vkCreateCudaFunctionNV",
    "vkCreateCudaModuleNV",
    "vkCreateDeferredOperationKHR",
    "vkCreateDirectFBSurfaceEXT",
    "vkCreateDisplayModeKHR",
    "vkCreateDisplayPlaneSurfaceKHR",
    "vkCreateExecutionGraphPipelinesAMDX",
    "vkCreateIOSSurfaceMVK",
    "vkCreateImagePipeSurfaceFUCHSIA",
    "vkCreateIndirectCommandsLayoutNV",
    "vkCreateMacOSSurfaceMVK",
    "vkCreateMetalSurfaceEXT",
    "vkCreateScreenSurfaceQNX",
    "vkCreateSemaphoreSciSyncPoolNV",
    "vkCreateShadersEXT",
    "vkCreateSharedSwapchainsKHR",
    "vkCreateStreamDescriptorSurfaceGGP",
    "vkCreateValidationCacheEXT",
    "vkCreateViSurfaceNN",
    "vkCreateWin32SurfaceKHR",
    "vkDeferredOperationJoinKHR",
    "vkDestroyBufferCollectionFUCHSIA",
    "vkDestroyCuFunctionNVX",
    "vkDestroyCuModuleNVX",
    "vkDestroyCudaFunctionNV",
    "vkDestroyCudaModuleNV",
    "vkDestroyDeferredOperationKHR",
    "vkDestroyIndirectCommandsLayoutNV",
    "vkDestroySemaphoreSciSyncPoolNV",
    "vkDestroyShaderEXT",
    "vkDestroyValidationCacheEXT",
    "vkDisplayPowerControlEXT",
    "vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR",
    "vkExportMetalObjectsEXT",
    "vkGetAndroidHardwareBufferPropertiesANDROID",
    "vkGetBufferCollectionPropertiesFUCHSIA",
    "vkGetBufferOpaqueCaptureDescriptorDataEXT",
    "vkGetCommandPoolMemoryConsumption",
    "vkGetCudaModuleCacheNV",
    "vkGetDeferredOperationMaxConcurrencyKHR",
    "vkGetDeferredOperationResultKHR",
    "vkGetDescriptorEXT",
    "vkGetDescriptorSetHostMappingVALVE",
    "vkGetDescriptorSetLayoutBindingOffsetEXT",
    "vkGetDescriptorSetLayoutHostMappingInfoVALVE",
    "vkGetDescriptorSetLayoutSizeEXT",
    "vkGetDeviceFaultInfoEXT",
    "vkGetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI",
    "vkGetDisplayModeProperties2KHR",
    "vkGetDisplayModePropertiesKHR",
    "vkGetDisplayPlaneCapabilities2KHR",
    "vkGetDisplayPlaneCapabilitiesKHR",
    "vkGetDisplayPlaneSupportedDisplaysKHR",
    "vkGetDrmDisplayEXT",
    "vkGetDynamicRenderingTilePropertiesQCOM",
    "vkGetExecutionGraphPipelineNodeIndexAMDX",
    "vkGetExecutionGraphPipelineScratchSizeAMDX",
    "vkGetFaultData",
    "vkGetFenceFdKHR",
    "vkGetFenceSciSyncFenceNV",
    "vkGetFenceSciSyncObjNV",
    "vkGetFenceWin32HandleKHR",
    "vkGetFramebufferTilePropertiesQCOM",
    "vkGetGeneratedCommandsMemoryRequirementsNV",
    "vkGetImageDrmFormatModifierPropertiesEXT",
    "vkGetImageOpaqueCaptureDescriptorDataEXT",
    "vkGetImageViewAddressNVX",
    "vkGetImageViewHandleNVX",
    "vkGetImageViewOpaqueCaptureDescriptorDataEXT",
    "vkGetLatencyTimingsNV",
    "vkGetMemoryAndroidHardwareBufferANDROID",
    "vkGetMemoryFdKHR",
    "vkGetMemoryFdPropertiesKHR",
    "vkGetMemoryHostPointerPropertiesEXT",
    "vkGetMemoryRemoteAddressNV",
    "vkGetMemorySciBufNV",
    "vkGetMemoryWin32HandleKHR",
    "vkGetMemoryWin32HandleNV",
    "vkGetMemoryZirconHandleFUCHSIA",
    "vkGetMemoryZirconHandlePropertiesFUCHSIA",
    "vkGetPastPresentationTimingGOOGLE",
    "vkGetPerformanceParameterINTEL",
    "vkGetPhysicalDeviceDirectFBPresentationSupportEXT",
    "vkGetPhysicalDeviceDisplayPlaneProperties2KHR",
    "vkGetPhysicalDeviceDisplayPlanePropertiesKHR",
    "vkGetPhysicalDeviceDisplayProperties2KHR",
    "vkGetPhysicalDeviceDisplayPropertiesKHR",
    "vkGetPhysicalDeviceExternalImageFormatPropertiesNV",
    "vkGetPhysicalDeviceFragmentShadingRatesKHR",
    "vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR",
    "vkGetPhysicalDeviceRefreshableObjectTypesKHR",
    "vkGetPhysicalDeviceScreenPresentationSupportQNX",
    "vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV",
    "vkGetPhysicalDeviceSurfaceCapabilities2EXT",
    "vkGetPhysicalDeviceSurfaceCapabilities2KHR",
    "vkGetPhysicalDeviceSurfaceFormats2KHR",
    "vkGetPhysicalDeviceSurfacePresentModes2EXT",
    "vkGetPhysicalDeviceWin32PresentationSupportKHR",
    "vkGetPipelineExecutableInternalRepresentationsKHR",
    "vkGetPipelineExecutablePropertiesKHR",
    "vkGetPipelineExecutableStatisticsKHR",
    "vkGetPipelineIndirectDeviceAddressNV",
    "vkGetPipelineIndirectMemoryRequirementsNV",
    "vkGetPipelinePropertiesEXT",
    "vkGetQueueCheckpointData2NV",
    "vkGetQueueCheckpointDataNV",
    "vkGetRandROutputDisplayEXT",
    "vkGetRefreshCycleDurationGOOGLE",
    "vkGetSamplerOpaqueCaptureDescriptorDataEXT",
    "vkGetScreenBufferPropertiesQNX",
    "vkGetSemaphoreFdKHR",
    "vkGetSemaphoreSciSyncObjNV",
    "vkGetSemaphoreWin32HandleKHR",
    "vkGetSemaphoreZirconHandleFUCHSIA",
    "vkGetShaderBinaryDataEXT",
    "vkGetShaderInfoAMD",
    "vkGetShaderModuleCreateInfoIdentifierEXT",
    "vkGetShaderModuleIdentifierEXT",
    "vkGetSwapchainCounterEXT",
    "vkGetSwapchainGrallocUsage2ANDROID",
    "vkGetSwapchainGrallocUsageANDROID",
    "vkGetSwapchainStatusKHR",
    "vkGetValidationCacheDataEXT",
    "vkGetWinrtDisplayNV",
    "vkImportFenceFdKHR",
    "vkImportFenceSciSyncFenceNV",
    "vkImportFenceSciSyncObjNV",
    "vkImportFenceWin32HandleKHR",
    "vkImportSemaphoreFdKHR",
    "vkImportSemaphoreSciSyncObjNV",
    "vkImportSemaphoreWin32HandleKHR",
    "vkImportSemaphoreZirconHandleFUCHSIA",
    "vkInitializePerformanceApiINTEL",
    "vkLatencySleepNV",
    "vkMergeValidationCachesEXT",
    "vkQueueBindSparse",
    "vkQueueNotifyOutOfBandNV",
    "vkQueueSetPerformanceConfigurationINTEL",
    "vkQueueSignalReleaseImageANDROID",
    "vkRegisterDeviceEventEXT",
    "vkRegisterDisplayEventEXT",
    "vkReleaseDisplayEXT",
    "vkReleaseFullScreenExclusiveModeEXT",
    "vkReleasePerformanceConfigurationINTEL",
    "vkReleaseProfilingLockKHR",
    "vkReleaseSwapchainImagesEXT",
    "vkSetBufferCollectionBufferConstraintsFUCHSIA",
    "vkSetBufferCollectionImageConstraintsFUCHSIA",
    "vkSetDeviceMemoryPriorityEXT",
    "vkSetHdrMetadataEXT",
    "vkSetLatencyMarkerNV",
    "vkSetLatencySleepModeNV",
    "vkSetLocalDimmingAMD",
    "vkUninitializePerformanceApiINTEL",
    "vkWaitForPresentKHR",
];
