#!/usr/bin/env python3
# dd-shim-vk command-origin extractor (Phase 0 capability inventory sidecar).
#
# `extract_vk_manifest.py` produces the ABI export surface (`vk_commands.manifest`). This companion
# produces the *provenance* sidecar `vk_command_origins.manifest` that `build.rs` reads to build the
# machine-checkable capability inventory: for every exported `vk*` command, which Vulkan **core
# version** first promoted it, or which **extension** defines it. That origin is what lets the
# generated inventory (a) print a truthful "supported core version/extension" column and (b) pick the
# correct error a stub returns — `VK_ERROR_EXTENSION_NOT_PRESENT` for a command from an extension the
# ICD does not advertise, `VK_ERROR_FEATURE_NOT_PRESENT` for an unimplemented core command.
#
# The origin sidecar NEVER changes the export surface (that stays pinned by the committed
# `vk_commands.manifest`); a newer vk.xml is a strict superset of provenance, so an origin file
# generated from a newer registry still covers every committed command. build.rs defaults any command
# absent from the sidecar to core:1.0.
#
#   O\t<vkName>\t<origin>   -- origin is `core:1.0`/`core:1.1`/... or `ext:VK_KHR_swapchain`
#
#   usage: extract_vk_origins.py <vk.xml> <out.manifest>
import re
import sys
import xml.etree.ElementTree as ET

# Core-version <feature> names. Older registries used a single `VK_VERSION_1_x`; newer ones decompose
# core into profile sub-features (`VK_BASE_VERSION_1_x`, `VK_COMPUTE_VERSION_1_x`,
# `VK_GRAPHICS_VERSION_1_x`) whose union is the core command set. Match all of them and read the
# `MAJOR_MINOR` suffix as the core version.
CORE_FEATURE_RE = re.compile(r"^VK_(?:[A-Z]+_)?VERSION_(\d+)_(\d+)$")


def is_vulkan_supported(node):
    """Whether a <feature>/<extension> applies to the plain "vulkan" API (not vulkansc-only/disabled)."""
    api = node.get("api")
    if api is not None and "vulkan" not in api.split(","):
        return False
    sup = node.get("supported")
    if sup is not None and "vulkan" not in sup.split(","):
        return False
    return True


def main():
    vk, outp = sys.argv[1], sys.argv[2]
    root = ET.parse(vk).getroot()

    # command name -> origin. Core wins over the originating extension (a promoted command reports the
    # earliest core version it was promoted into); the earliest core version wins among core features.
    origin = {}
    core_ver = {}  # name -> (major, minor) for earliest-core resolution

    # Pass 1: core versions (authoritative — promotion beats the originating extension).
    for feat in root.findall("feature"):
        if not is_vulkan_supported(feat):
            continue
        m = CORE_FEATURE_RE.match(feat.get("name") or "")
        if not m:
            continue
        ver = (int(m.group(1)), int(m.group(2)))
        for req in feat.findall("require"):
            for cmd in req.findall("command"):
                nm = cmd.get("name")
                if not nm:
                    continue
                if nm not in core_ver or ver < core_ver[nm]:
                    core_ver[nm] = ver
    for nm, (mj, mn) in core_ver.items():
        origin[nm] = f"core:{mj}.{mn}"

    # Pass 2: extensions (only fill commands no core version already claimed).
    for ext in root.findall("extensions/extension"):
        if not is_vulkan_supported(ext):
            continue
        ename = ext.get("name") or ""
        for req in ext.findall("require"):
            for cmd in req.findall("command"):
                nm = cmd.get("name")
                if nm and nm not in origin:
                    origin[nm] = "ext:" + ename

    with open(outp, "w") as f:
        f.write("# @generated by extract_vk_origins.py from Khronos vk.xml — DO NOT EDIT.\n")
        f.write("# Format: `O<TAB>vkName<TAB>origin` where origin is `core:MAJOR.MINOR` or `ext:VK_...`.\n")
        f.write("# Provenance sidecar for the Phase-0 capability inventory; does NOT define the ABI surface.\n")
        for nm in sorted(origin):
            f.write(f"O\t{nm}\t{origin[nm]}\n")

    print(f"vk command origins emitted: {len(origin)}")


if __name__ == "__main__":
    main()
