// Variants are named for the ISA's instruction groups.
#![allow(clippy::enum_variant_names)]

use super::address::{LoadExtension, MemoryAddress, SimdCopy, SimdLogic, SimdPermute, SimdShift, SimdUnary};
use crate::{
    Aarch64BranchCondition as BranchCondition, Aarch64Shift, BitfieldOperation, CompareOperand, DivideOperation,
    FpBinaryOperation, FpFormat, FpRoundingMode, FpUnaryOperation, LogicalOperation, MemoryWidth, MoveWideOperation,
    MultiplyOperation, RegisterExtension,
};

#[rustfmt::skip]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Instruction {
    AddSubtractImmediate { subtract: bool, set_flags: bool, source: u8, destination: u8, immediate: u64, },
    AddSubtractShifted { subtract: bool, set_flags: bool, source: u8, operand: u8, destination: u8, shift: Aarch64Shift, amount: u8, },
    AddSubtractExtended { subtract: bool, set_flags: bool, source: u8, operand: u8, destination: u8, extension: RegisterExtension, amount: u8, },
    AddCarry { subtract: bool, set_flags: bool, left: u8, right: u8, destination: u8, },
    LogicalImmediate { operation: LogicalOperation, source: u8, destination: u8, mask: u64, },
    LogicalShifted { operation: LogicalOperation, invert: bool, source: u8, operand: u8, destination: u8, shift: Aarch64Shift, amount: u8, },
    MoveWide { operation: MoveWideOperation, destination: u8, immediate: u16, shift: u8, },
    Bitfield { operation: BitfieldOperation, source: u8, destination: u8, rotate: u8, sign_bit: u8, write_mask: u64, top_mask: u64, },
    Extract { high: u8, low: u8, destination: u8, amount: u8, },
    Multiply { operation: MultiplyOperation, subtract: bool, source: u8, operand: u8, addend: u8, destination: u8, },
    VariableShift { shift: Aarch64Shift, source: u8, amount: u8, destination: u8, },
    Divide { operation: DivideOperation, source: u8, divisor: u8, destination: u8, },
    ByteReverse { source: u8, destination: u8, container_bytes: u8, },
    BitReverse { source: u8, destination: u8, },
    CountLeadingZero { source: u8, destination: u8, },
    Crc32 { polynomial: crate::CrcPolynomial, bytes: u8, checksum: u8, value: u8, destination: u8, },
    ConditionalCompare { subtract: bool, source: u8, operand: CompareOperand, condition: BranchCondition, literal: u8, },
    Address { destination: u8, displacement: i64, page: bool, },
    BranchImmediate { displacement: i64, link: bool, },
    BranchRegister { source: u8, link: bool, },
    Return { source: u8, },
    BranchConditional { condition: BranchCondition, displacement: i64, },
    ConditionalSelect { source: u8, alternate: u8, destination: u8, condition: BranchCondition, invert: bool, increment: bool, },
    CompareBranch { source: u8, nonzero: bool, displacement: i64, },
    TestBranch { source: u8, bit: u8, nonzero: bool, displacement: i64, },
    Load { destination: u8, width: MemoryWidth, extension: LoadExtension, address: MemoryAddress, },
    Store { source: u8, width: MemoryWidth, address: MemoryAddress, },
    VectorLoad { destination: u8, bytes: u8, address: MemoryAddress, },
    VectorStore { source: u8, bytes: u8, address: MemoryAddress, },
    VectorLoadPair { first: u8, second: u8, bytes: u8, address: MemoryAddress, },
    VectorLoadGroup { first: u8, count: u8, bytes: u8, address: MemoryAddress, },
    VectorStorePair { first: u8, second: u8, bytes: u8, address: MemoryAddress, },
    VectorStoreGroup { first: u8, count: u8, bytes: u8, address: MemoryAddress, },
    VectorStructureGroup { first: u8, count: u8, lane_bits: u8, load: bool, wide: bool, address: MemoryAddress, },
    VectorStructureLane { first: u8, count: u8, lane_bits: u8, lane: u8, load: bool, replicate: bool, wide: bool, address: MemoryAddress, },
    LoadPair { first: u8, second: u8, width: MemoryWidth, sign_extend: bool, address: MemoryAddress, },
    StorePair { first: u8, second: u8, width: MemoryWidth, address: MemoryAddress, },
    ExclusiveLoad { base: u8, first: u8, second: Option<u8>, width: MemoryWidth, order: crate::MemoryOrder, },
    OrderedAccess { load: bool, base: u8, transfer: u8, width: MemoryWidth, order: crate::MemoryOrder, },
    ExclusiveStore { base: u8, status: u8, first: u8, second: Option<u8>, width: MemoryWidth, order: crate::MemoryOrder, },
    AtomicCompareExchange { base: u8, expected: u8, replacement: u8, width: MemoryWidth, pair: bool, order: crate::MemoryOrder, },
    AtomicUpdate { base: u8, source: u8, destination: u8, width: MemoryWidth, operation: crate::AtomicOperation, order: crate::MemoryOrder, },
    ClearExclusive,
    Barrier { kind: crate::BarrierKind, option: u8, },
    CacheZero { source: u8, },
    InstructionCache { source: u8, },
    SimdAes { operation: crate::AesOperation, source: u8, destination: u8, },
    SimdSha1 { operation: crate::Sha1Operation, first: u8, second: u8, destination: u8, },
    SimdSha256 { operation: crate::Sha256Operation, first: u8, second: u8, destination: u8, },
    SystemRead { destination: u8, register: crate::SystemRegister, },
    SystemWrite { source: u8, register: crate::SystemRegister, },
    SimdImmediate { destination: u8, pattern: u64, invert: bool, modify: Option<SimdLogic>, wide: bool, },
    SimdLogic { operation: SimdLogic, left: u8, right: u8, destination: u8, wide: bool, },
    SimdAddSubtract { subtract: bool, saturating: bool, unsigned: bool, lane_bits: u8, left: u8, right: u8, destination: u8, wide: bool, },
    SimdCopy { operation: SimdCopy, lane_bits: u8, lane: u8, source: u8, destination: u8, wide: bool, },
    SimdExtract { first: u8, second: u8, destination: u8, position: u8, wide: bool, },
    SimdTable { first_table: u8, table_count: u8, indexes: u8, destination: u8, extend: bool, wide: bool, },
    SimdPermute { operation: SimdPermute, lane_bits: u8, left: u8, right: u8, destination: u8, wide: bool, },
    SimdUnary { operation: SimdUnary, lane_bits: u8, source: u8, destination: u8, wide: bool, },
    SimdSaturatingUnary { negate: bool, lane_bits: u8, source: u8, destination: u8, lanes: u8, },
    SimdSaturatingAccumulate { unsigned_destination: bool, lane_bits: u8, source: u8, destination: u8, lanes: u8, },
    SimdShift { operation: SimdShift, amount: u8, lane_bits: u8, source: u8, destination: u8, wide: bool, },
    SimdVariable { signed: bool, saturating: bool, rounding: bool, lane_bits: u8, source: u8, counts: u8, destination: u8, wide: bool, },
    SimdLane { operation: crate::SimdLaneOperation, lane_bits: u8, left: u8, right: u8, destination: u8, wide: bool, },
    SimdWide { operation: crate::SimdWideOperation, signed: bool, lane_bits: u8, left: u8, right: u8, destination: u8, high: bool, },
    SimdReduce { operation: crate::SimdReduceOperation, lane_bits: u8, source: u8, destination: u8, wide: bool, },
    SimdScalarShift { amount: u8, source: u8, destination: u8, left: bool, },
    SimdScalarMove { lane_bits: u8, lane: u8, source: u8, destination: u8, },
    FpImmediate { format: FpFormat, immediate: u8, destination: u8, },
    FpUnary { operation: FpUnaryOperation, format: FpFormat, source: u8, destination: u8, },
    FpBinary { operation: FpBinaryOperation, format: FpFormat, left: u8, right: u8, destination: u8, },
    FpSelect { format: FpFormat, source: u8, alternate: u8, destination: u8, condition: BranchCondition, },
    FpFused { format: FpFormat, left: u8, right: u8, addend: u8, destination: u8, negate_product: bool, negate_addend: bool, },
    FpRoundIntegral { format: FpFormat, source: u8, destination: u8, rounding: FpRoundingMode, exact: bool, },
    SimdFpUnary { operation: FpUnaryOperation, format: FpFormat, source: u8, destination: u8, lanes: u8, },
    SimdFpRoundIntegral { format: FpFormat, source: u8, destination: u8, lanes: u8, rounding: FpRoundingMode, exact: bool, },
    FpFormatConvert { source_format: FpFormat, destination_format: FpFormat, source: u8, destination: u8, },
    FpCompare { format: FpFormat, left: u8, right: Option<u8>, signaling: bool, condition: Option<BranchCondition>, alternative_nzcv: u8, },
    SimdFpCompare { operation: crate::FpComparison, format: crate::FpFormat, left: u8, right: Option<u8>, destination: u8, lanes: u8, absolute: bool, },
    FpGeneralMove { format: FpFormat, general_to_fp: bool, top_half: bool, general: u8, vector: u8, },
    FpConvert { format: FpFormat, fp_to_integer: bool, signed: bool, integer_wide: bool, rounding: FpRoundingMode, source: u8, destination: u8, },
    Bf16Convert { source: u8, destination: u8, vector: bool, high: bool, },
    SimdFpEstimate { format: crate::FpFormat, reciprocal_sqrt: bool, source: u8, destination: u8, lanes: u8, },
    SimdFpRecipExponent { format: crate::FpFormat, source: u8, destination: u8, },
    SimdUnsignedEstimate { reciprocal_sqrt: bool, source: u8, destination: u8, wide: bool, },
    SimdFpStep { format: crate::FpFormat, reciprocal_sqrt: bool, left: u8, right: u8, destination: u8, lanes: u8, },
    SimdFpNarrowOdd { source: u8, destination: u8, high: bool, scalar: bool, },
    SimdFpConvert { format: crate::FpFormat, source: u8, destination: u8, high: bool, widen: bool, },
    SimdFpInteger { format: crate::FpFormat, lanes: u8, signed: bool, scale: u8, rounding: crate::FpRoundingMode, source: u8, destination: u8, },
    SimdIntegerFp { format: crate::FpFormat, lanes: u8, signed: bool, source: u8, destination: u8, },
    SimdFpBinary { operation: crate::FpBinaryOperation, format: crate::FpFormat, lanes: u8, left: u8, right: u8, destination: u8, },
    SimdFpFused { format: crate::FpFormat, lanes: u8, subtract: bool, left: u8, right: u8, index: Option<u8>, destination: u8, scalar: bool, },
    SimdFpProduct { format: crate::FpFormat, lanes: u8, extended: bool, left: u8, right: u8, index: Option<u8>, destination: u8, scalar: bool, },
    SimdFpReduce { operation: crate::FpBinaryOperation, source: u8, destination: u8, },
    SimdDot { signed: bool, left: u8, right: u8, index: Option<u8>, destination: u8, wide: bool, },
    SimdMatrix { signedness: crate::SimdMatrixSignedness, left: u8, right: u8, destination: u8, },
    SimdElementProduct { operation: crate::SimdLaneOperation, lane_bits: u8, left: u8, right: u8, index: u8, destination: u8, wide: bool, },
    SimdHighProduct { rounding: bool, lane_bits: u8, left: u8, right: u8, index: Option<u8>, destination: u8, wide: bool, scalar: bool, },
    SimdLongElement { operation: crate::SimdWideOperation, signed: bool, narrow_bits: u8, left: u8, right: u8, index: u8, destination: u8, high: bool, },
    SimdSaturatingLong { operation: crate::SimdSaturatingLongOperation, narrow_bits: u8, left: u8, right: u8, index: Option<u8>, destination: u8, high: bool, scalar: bool, },
    Nop,
    SupervisorCall { immediate: u16, },
    Breakpoint { immediate: u16, },
    Undefined,
}
pub type Aarch64Instruction = Instruction;
