[package]
name = "engine"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
autobins = false

[lints]
workspace = true

[dependencies]
clap.workspace = true
hl-engine = { path = "../../containers/hl-engine" }
hl-log = { path = "../../packages/hl-log" }
sha2.workspace = true

[[bin]]
name = "hl-engine"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[[bin]]
name = "hl-aarch64"
path = "src/bin/aarch64.rs"

[[bin]]
name = "hl-x86_64"
path = "src/bin/x86.rs"

[dev-dependencies]
serde_json.workspace = true
