// Generated from Rust hl-extension protocol/v1.json. Do not edit.
export const PROTOCOL_SPECIFICATION_VERSION: 1;
export const PROTOCOL_VERSION: 1;
export const PROTOCOL_BOUNDS: Readonly<{ "extension_job_bytes": number; "extension_reference_bytes": number; "pane_input_bytes": number; "pane_inventory_items": number; "pane_text_bytes": number; "resource_inventory_items": number; "semantic_action_value_bytes": number; "semantic_depth": number; "semantic_nodes": number; "semantic_text_bytes": number; "terminal_command_argument_bytes": number; "terminal_command_bytes": number }>;
export type ExtensionCapability = "workspaces:read" | "workspaces:control" | "workspaces:events" | "containers:read" | "containers:control" | "containers:attach" | "images:read" | "images:write" | "volumes:read" | "volumes:write" | "networks:read" | "networks:write" | "terminals:read" | "terminals:control" | "terminals:output" | "panes:observe" | "panes:semantic-read" | "panes:semantic-control" | "extensions:read" | "extensions:control" | "extensions:install" | "filesystem:read" | "filesystem:write" | "interface:render";
export type Align = "Start" | "Center" | "End" | "Stretch";
export type Bounds = { "minimum"?: Length | null; "maximum"?: Length | null };
export type Capability = "workspaces:read" | "workspaces:control" | "workspaces:events" | "containers:read" | "containers:control" | "containers:attach" | "images:read" | "images:write" | "volumes:read" | "volumes:write" | "networks:read" | "networks:write" | "terminals:read" | "terminals:control" | "terminals:output" | "panes:observe" | "panes:semantic-read" | "panes:semantic-control" | "extensions:read" | "extensions:control" | "extensions:install" | "filesystem:read" | "filesystem:write" | "interface:render";
export type Cell = { "Text": string } | { "Number": number } | { "Bytes": number } | { "Badge": { "label": string; "tone": Tone } } | { "Stamp": number } | "Empty";
export type Choice = { "value": string; "label": string };
export type Column = { "key": string; "title": string; "width": Length; "align": Align; "sortable": boolean; "editable": boolean };
export type ContainerCreateSpec = { "image": string; "name": string; "hostname"?: string | null; "entrypoint"?: Array<string> | null; "command": Array<string>; "environment": Array<[string, string]>; "working_directory"?: string | null; "user"?: string | null; "labels": Array<[string, string]>; "mounts": Array<ContainerVolumeMount>; "network"?: string | null; "ports": Array<ContainerPort>; "memory_mb"?: number | null; "cpus"?: number | null; "pids_limit"?: number | null };
export type ContainerInventory = { "containers": Array<ContainerSummary>; "complete": boolean };
export type ContainerOutput = { "stdout": Array<number>; "stderr": Array<number>; "truncated": boolean; "stdout_truncated"?: boolean; "stderr_truncated"?: boolean; "eof"?: boolean };
export type ContainerPort = { "container": number; "host"?: number | null; "protocol": string };
export type ContainerSummary = { "id": string; "name": string; "image": string; "state": string; "created": number; "generation"?: number };
export type ContainerVolumeMount = { "volume": string; "target": string; "read_only": boolean };
export type Division = "beside" | "below";
export type Edges = { "top": Length; "end": Length; "bottom": Length; "start": Length };
export type Entry = { "path": RelativePath; "directory": boolean; "size": number; "identity"?: string | null };
export type EventId = string;
export type ExecutionList = { "executions": Array<ExecutionSummary>; "truncated": boolean };
export type ExecutionSummary = { "id": string; "container_id": string; "running": boolean; "exit_code": number; "pid": number; "command": Array<string>; "user": string };
export type ExtensionAcquisitionChange = { "job": string; "revision": number; "state": string; "coalesced": number };
export type ExtensionAcquisitionJob = { "job": string };
export type ExtensionAcquisitionProgress = { "status": string; "id"?: string | null; "current"?: number | null; "total"?: number | null };
export type ExtensionAcquisitionStatus = { "job": string; "reference": string; "revision": number; "state": string; "progress"?: ExtensionAcquisitionProgress | null; "candidate"?: ExtensionCandidate | null; "error"?: string | null };
export type ExtensionCandidate = { "name": ExtensionName; "version": string; "image_digest": string; "requested": Grant; "installed_image_digest"?: string | null };
export type ExtensionName = PeerName;
export type ExtensionSummary = { "name": string; "image_digest": string; "status": string; "version"?: string; "enabled"?: boolean; "pane_providers"?: Array<PaneProvider> };
export type FileRange = { "path": RelativePath; "identity": string; "offset": number; "total": number; "contents": Array<number>; "eof": boolean; "truncated": boolean };
export type Frame = { "sequence": number; "patches": Array<Patch> };
export type Grant = Array<Capability>;
export type GridSize = { "columns": number; "rows": number };
export type Handler = { "trigger": Trigger; "id": EventId };
export type ImageDetails = { "id": string; "references": Array<string>; "created": string; "size": number; "os": string; "architecture": string; "entrypoint": Array<string>; "command": Array<string>; "working_directory": string; "user": string };
export type ImageInventory = { "images": Array<ImageSummary>; "truncated": boolean };
export type ImagePruneResult = { "deleted": number; "space_reclaimed": number };
export type ImagePullChange = { "job": string; "revision": number; "state": string; "coalesced": number };
export type ImagePullJob = { "job": string };
export type ImagePullStatus = { "job": string; "reference": string; "revision": number; "state": string; "status"?: string | null; "layer"?: string | null; "current"?: number | null; "total"?: number | null; "image"?: ImageSummary | null; "error"?: string | null };
export type ImageSummary = { "id": string; "reference": string; "size": number; "created": number };
export type InspectablePane = { "slot": string; "generation"?: number; "revision"?: number; "kind": PaneKind; "provider"?: PaneProviderIdentity | null; "tab"?: string | null; "title"?: string | null; "focused": boolean };
export type LayoutNode = { kind: "pane" } & { "pane": PaneSummary; "grid"?: GridSize | null; "focused": boolean } | { kind: "split" } & { "division": Division; "ratio_per_mille": number; "first": LayoutNode; "second": LayoutNode };
export type Length = { "Step": number } | { "Chars": number } | "Fill" | "Content";
export type NetworkInventory = { "networks": Array<NetworkSummary>; "truncated": boolean };
export type NetworkSummary = { "id": string; "name": string; "driver": string; "scope": string };
export type NodeId = number;
export type Occupant = "terminal" | "surface";
export type Orientation = "Horizontal" | "Vertical";
export type PaneChange = { "slot": string; "kind": PaneChangeKind; "revision": number; "generation": number; "coalesced": number };
export type PaneChangeKind = "terminal" | "surface" | "native";
export type PaneInventory = { "panes": Array<InspectablePane>; "truncated": boolean };
export type PaneKind = "terminal" | "surface" | "native";
export type PaneOccupantTarget = { kind: "terminal" } | { kind: "surface" } & { "extension": string; "provider": string };
export type PaneProvider = { "id": ExtensionName; "title": string; "icon"?: string | null };
export type PaneProviderIdentity = { "extension": string; "provider": string };
export type PaneSemanticAction = { "generation": number; "revision": number; "node": number; "action": SemanticActionKind; "value"?: string | null };
export type PaneSemanticTree = { "slot": string; "generation": number; "revision": number; "root": SemanticNode; "truncated": boolean };
export type PaneSummary = { "slot": string; "working_directory"?: string | null; "command"?: string | null; "occupant": Occupant; "provider"?: PaneProviderIdentity | null };
export type PaneText = { "slot": string; "generation"?: number; "revision"?: number; "columns"?: number; "rows"?: number; "lines": Array<string>; "cursor_column"?: number; "cursor_row"?: number; "truncated": boolean };
export type Patch = { "Create": { "id": NodeId; "tag": Tag } } | { "Insert": { "parent": NodeId; "child": NodeId; "before"?: NodeId | null } } | { "Move": { "parent": NodeId; "child": NodeId; "before"?: NodeId | null } } | { "SetProp": { "id": NodeId; "prop": Prop; "value": PropValue } } | { "ClearProp": { "id": NodeId; "prop": Prop } } | { "SetHandler": { "id": NodeId; "handler": Handler } } | { "ClearHandler": { "id": NodeId; "trigger": Trigger } } | { "Remove": { "id": NodeId } };
export type PeerName = string;
export type PointerPhase = "move" | "enter" | "leave" | "press" | "release" | "click" | "context" | "scroll";
export type ProcessList = { "container_id"?: string; "titles": Array<string>; "processes": Array<Array<string>>; "observed_at_ms"?: number; "scope"?: ProcessScope; "pid_identity"?: ProcessPidIdentity; "truncated"?: boolean };
export type ProcessPidIdentity = "snapshot";
export type ProcessScope = "initial" | "namespace";
export type Prop = "Label" | "Detail" | "Value" | "Placeholder" | "Help" | "Icon" | "Tooltip" | "Uri" | "Enabled" | "Visible" | "Selected" | "Checked" | "Expanded" | "Busy" | "Secret" | "Destructive" | "Monospace" | "Wrap" | "Ellipsize" | "Variant" | "Tone" | "Scale" | "Color" | "Gap" | "Pad" | "Grow" | "Width" | "Height" | "Align" | "Justify" | "Columns" | "Span" | "RowSpan" | "Orientation" | "Position" | "Minimum" | "Maximum" | "Step" | "Fraction" | "Schema" | "Source" | "RowHeight" | "Choices";
export type PropValue = { "Text": string } | { "Number": number } | { "Integer": number } | { "Flag": boolean } | { "Token": Token } | { "Length": Length } | { "Edges": Edges } | { "Bounds": Bounds } | { "Variant": Variant } | { "Tone": Tone } | { "Scale": Scale } | { "Align": Align } | { "Orientation": Orientation } | { "Choices": Array<Choice> } | { "Schema": Array<Column> } | { "Source": SourceId } | "Nothing";
export type RelativePath = string;
export type RequestId = number;
export type Row = { "key": number; "cells": Array<Cell> };
export type RowRange = { "start": number; "count": number };
export type RowWindow = { "source": SourceId; "version": Version; "request": RequestId; "range": RowRange; "rows": Array<Row> };
export type Scale = "Caption" | "Body" | "Title" | "Display";
export type SemanticActionKind = "invoke" | "change" | "submit" | "toggle" | "expand" | "focus";
export type SemanticNode = { "id": number; "role": string; "label"?: string | null; "value"?: string | null; "disabled": boolean; "destructive": boolean; "actions": Array<SemanticActionKind>; "children": Array<SemanticNode> };
export type SourceId = number;
export type SourceMutation = { "Open": { "source": SourceId; "columns": Array<Column> } } | { "Length": { "source": SourceId; "version": Version; "rows": number } } | { "Window": RowWindow } | { "Invalidate": { "source": SourceId; "version": Version; "range"?: RowRange | null } } | { "Close": { "source": SourceId } };
export type TabSummary = { "id": string; "title": string; "pinned": boolean; "panes": Array<PaneSummary> };
export type TabTopology = { "id": string; "title": string; "pinned": boolean; "root": LayoutNode };
export type Tag = "Column" | "Row" | "Grid" | "Scroll" | "Splitter" | "Stack" | "Overlay" | "Container" | "Spacer" | "Separator" | "Card" | "CardHeader" | "CardContent" | "CardActions" | "CardMedia" | "CardActionArea" | "Paper" | "Section" | "Toolbar" | "HeaderBar" | "Sidebar" | "Text" | "Heading" | "Code" | "Link" | "Icon" | "Badge" | "Avatar" | "AvatarGroup" | "Chip" | "Image" | "ImageList" | "ImageListItem" | "Progress" | "Spinner" | "Meter" | "Skeleton" | "EmptyState" | "Stat" | "Toast" | "Banner" | "AlertTitle" | "InlineMessage" | "ValidationSummary" | "Button" | "IconButton" | "ToggleButton" | "ButtonGroup" | "ToggleButtonGroup" | "SplitButton" | "Fab" | "SpeedDial" | "SpeedDialAction" | "Overflow" | "Entry" | "Search" | "CommandPalette" | "TagInput" | "NumberEntry" | "TextArea" | "PasswordEntry" | "Autocomplete" | "TextField" | "InputAdornment" | "Slider" | "DatePicker" | "TimePicker" | "ColorPicker" | "FilePicker" | "Rating" | "FormControl" | "FormLabel" | "FormHelperText" | "FormControlLabel" | "FormGroup" | "Switch" | "Checkbox" | "Radio" | "RadioGroup" | "Select" | "List" | "ListRow" | "ListItemText" | "ListItemIcon" | "ListItemAvatar" | "ListItemButton" | "ListItemAction" | "ListItemSecondaryAction" | "ListSubheader" | "Table" | "TableHead" | "TableBody" | "TableFooter" | "TableRow" | "TableCell" | "TableSortLabel" | "DataTable" | "KeyValueTable" | "TreeTable" | "EventStream" | "FileBrowser" | "TablePagination" | "Tree" | "TreeItem" | "Tabs" | "TabPage" | "Breadcrumb" | "Pagination" | "PaginationItem" | "Stepper" | "Step" | "StepLabel" | "StepContent" | "StepConnector" | "StepIcon" | "NavigationRail" | "NavigationRailItem" | "BottomNavigation" | "BottomNavigationAction" | "Accordion" | "AccordionSummary" | "AccordionDetails" | "AccordionActions" | "Expander" | "Dialog" | "DialogTitle" | "DialogContent" | "DialogContentText" | "DialogActions" | "Popover" | "ContextMenu" | "Menu" | "MenuItem" | "Drawer" | "DrawerPanel" | "CodeView" | "HexView" | "MarkdownView" | "JsonView" | "LogView" | "Video" | "Chart" | "Sparkline" | "FlameGraph" | "MemoryMap" | "DisassemblyView" | "TimelineView" | "TestReportView" | "CoverageView" | "NetworkWaterfall" | "NetworkRequest" | "NetworkPhase" | "DependencyGraph" | "DependencyNode" | "DependencyEdge" | "DependencyCycle" | "DependencyCycleMember" | "QueryPlan" | "QueryPlanNode" | "QueryPlanMetric" | "DiffViewer" | "DiffLine" | "StackTrace" | "StackFrame";
export type TerminalTopology = { "active_tab"?: string | null; "tabs": Array<TabTopology> };
export type Token = "Ground" | "Surface" | "Raised" | "Line" | "Text" | "TextDim" | "TextFaint" | "Accent" | "Positive" | "Warning" | "Danger" | "Info";
export type Tone = "Neutral" | "Accent" | "Positive" | "Warning" | "Danger";
export type Topic = "containers" | "container-inventory" | "executions" | "images" | "image-pulls" | "volumes" | "networks" | "terminal" | "pane-changes" | "extensions" | "extension-acquisitions" | "workspace-lifecycle" | "workspace-events";
export type Trigger = "Invoke" | "Change" | "Submit" | "Select" | "Edit" | "Sort" | "Activate" | "Toggle" | "Expand" | "Scroll" | "Close" | "Context" | "Key" | "Focus" | "Pointer" | "Drag" | "Drop";
export type UiCollectionSelection = { "source": number; "version": number; "rows": Array<UiSelectedRow> };
export type UiPointerPhase = "enter" | "motion" | "leave" | "press" | "release";
export type UiSelectedRow = { "index": number; "id": string };
export type Variant = "Plain" | "Filled" | "Outline" | "Ghost";
export type Version = number;
export type VolumeInventory = { "volumes": Array<VolumeSummary>; "truncated": boolean };
export type VolumeSummary = { "name": string; "driver": string; "generation": string };
export type WorkspaceConfiguration = { "generation"?: string; "name": string; "image": string; "architecture": string; "storage"?: string | null; "shell"?: string | null; "cpus"?: number | null; "memory_mb"?: number | null; "environment": Array<[string, string]>; "mounts": Array<WorkspaceMount>; "docker_socket": boolean; "scrollback"?: number | null; "vpn"?: string | null; "execution_lifetime": string; "terminal": WorkspaceTerminal };
export type WorkspaceEvent = { event: "key" } & { "key": string; "modifiers": Array<string>; "pressed": boolean; "slot"?: string | null; "generation"?: number | null } | { event: "focus" } & { "active": boolean; "slot"?: string | null; "generation"?: number | null } | { event: "pointer" } & { "phase": PointerPhase; "slot": string; "generation": number; "x": number; "y": number; "button"?: number | null; "modifiers": Array<string>; "delta_x"?: number | null; "delta_y"?: number | null };
export type WorkspaceEventBatch = { "events": Array<WorkspaceEvent>; "dropped": number };
export type WorkspaceInfo = { "name": string; "architecture": string; "image": string };
export type WorkspaceLifecycleAction = "create" | "update" | "remove" | "start" | "stop" | "restart";
export type WorkspaceLifecycleChange = { "workspace": string; "action": WorkspaceLifecycleAction; "revision": number; "coalesced": number };
export type WorkspaceMount = { "host": string; "container": string; "read_only": boolean };
export type WorkspaceState = { "name": string; "architecture": string; "image": string; "running": boolean; "current": boolean };
export type WorkspaceTerminal = { "font_family"?: string | null; "font_size"?: number | null; "foreground"?: string | null; "background"?: string | null; "cursor_shape"?: string | null; "cursor_blink"?: boolean | null };
export type WireRequest = { call: "workspace_info" } | { call: "workspace_list" } | { call: "workspace_inspect"; with: { "name": string } } | { call: "workspace_create"; with: { "configuration": WorkspaceConfiguration } } | { call: "workspace_adopt"; with: { "configuration": WorkspaceConfiguration } } | { call: "workspace_update"; with: { "name": string; "generation": string; "configuration": WorkspaceConfiguration } } | { call: "workspace_delete"; with: { "name": string; "generation": string } } | { call: "workspace_start"; with: { "name": string } } | { call: "workspace_stop"; with: { "name": string } } | { call: "workspace_restart"; with: { "name": string } } | { call: "extension_list" } | { call: "extension_inspect"; with: { "name": string } } | { call: "extension_enable"; with: { "name": string; "image_digest": string } } | { call: "extension_disable"; with: { "name": string; "image_digest": string } } | { call: "extension_retry"; with: { "name": string; "image_digest": string } } | { call: "extension_remove"; with: { "name": string; "image_digest": string } } | { call: "extension_acquisition_start"; with: { "reference": string } } | { call: "extension_acquisition_status"; with: { "job": string } } | { call: "extension_acquisition_cancel"; with: { "job": string; "revision": number } } | { call: "extension_install"; with: { "job": string; "revision": number; "granted": Grant } } | { call: "extension_update"; with: { "job": string; "revision": number; "granted": Grant } } | { call: "container_list" } | { call: "container_inspect"; with: { "id": string } } | { call: "container_processes"; with: { "id": string } } | { call: "container_logs"; with: { "id": string; "stdout": boolean; "stderr": boolean } } | { call: "execution_inspect"; with: { "id": string } } | { call: "execution_list" } | { call: "execution_logs"; with: { "id": string; "stdout": boolean; "stderr": boolean } } | { call: "execution_wait"; with: { "id": string; "timeout_ms": number } } | { call: "execution_kill"; with: { "id": string; "signal": string } } | { call: "execution_remove"; with: { "id": string } } | { call: "container_create"; with: { "spec": ContainerCreateSpec } } | { call: "container_start"; with: { "id": string } } | { call: "container_stop"; with: { "id": string } } | { call: "container_remove"; with: { "id": string } } | { call: "container_pause"; with: { "id": string } } | { call: "container_unpause"; with: { "id": string } } | { call: "container_restart"; with: { "id": string } } | { call: "container_rename"; with: { "id": string; "name": string } } | { call: "container_kill"; with: { "id": string; "signal": string } } | { call: "container_exec"; with: { "id": string; "command": Array<string>; "user"?: string | null; "working_directory"?: string | null } } | { call: "container_attach_terminal"; with: { "id": string; "command": Array<string> } } | { call: "image_list" } | { call: "image_pull"; with: { "reference": string } } | { call: "image_pull_start"; with: { "reference": string } } | { call: "image_pull_status"; with: { "job": string } } | { call: "image_pull_cancel"; with: { "job": string } } | { call: "image_inspect"; with: { "reference": string } } | { call: "image_remove"; with: { "reference": string } } | { call: "image_prune" } | { call: "volume_list" } | { call: "volume_inspect"; with: { "name": string } } | { call: "volume_create"; with: { "name": string } } | { call: "volume_remove"; with: { "name": string; "generation": string } } | { call: "network_list" } | { call: "network_inspect"; with: { "reference": string } } | { call: "network_create"; with: { "name": string } } | { call: "network_remove"; with: { "reference": string } } | { call: "network_connect"; with: { "reference": string; "container": string; "aliases"?: Array<string> } } | { call: "network_disconnect"; with: { "reference": string; "container": string } } | { call: "terminal_tabs" } | { call: "terminal_topology" } | { call: "pane_list" } | { call: "terminal_open_tab"; with: { "title": string } } | { call: "terminal_pin_tab"; with: { "tab": string; "pinned": boolean } } | { call: "terminal_split"; with: { "slot": string; "division": Division } } | { call: "terminal_split_observed"; with: { "slot": string; "generation": number; "revision": number; "division": Division } } | { call: "terminal_spawn"; with: { "slot": string; "command": Array<string> } } | { call: "terminal_spawn_observed"; with: { "slot": string; "generation": number; "revision": number; "command": Array<string> } } | { call: "terminal_read_pane"; with: { "slot": string; "lines"?: number | null } } | { call: "pane_semantic_read"; with: { "slot": string } } | { call: "pane_semantic_action"; with: { "slot": string; "action": PaneSemanticAction } } | { call: "terminal_write_pane"; with: { "slot": string; "generation": number; "revision": number; "contents": Array<number> } } | { call: "terminal_resize_grid"; with: { "slot": string; "columns": number; "rows": number } } | { call: "terminal_resize_grid_observed"; with: { "slot": string; "generation": number; "revision": number; "columns": number; "rows": number } } | { call: "terminal_close_pane"; with: { "slot": string } } | { call: "terminal_close_pane_observed"; with: { "slot": string; "generation": number; "revision": number } } | { call: "terminal_focus_pane"; with: { "slot": string } } | { call: "terminal_focus_pane_observed"; with: { "slot": string; "generation": number; "revision": number } } | { call: "terminal_retitle_pane"; with: { "slot": string; "title": string } } | { call: "terminal_retitle_pane_observed"; with: { "slot": string; "generation": number; "revision": number; "title": string } } | { call: "terminal_ratio"; with: { "slot": string; "ratio": number } } | { call: "terminal_ratio_observed"; with: { "slot": string; "generation": number; "revision": number; "ratio": number } } | { call: "terminal_switch_occupant"; with: { "slot": string; "generation": number; "target": PaneOccupantTarget } } | { call: "terminal_switch_occupant_observed"; with: { "slot": string; "generation": number; "revision": number; "target": PaneOccupantTarget } } | { call: "filesystem_list"; with: { "path": RelativePath } } | { call: "filesystem_read"; with: { "path": RelativePath } } | { call: "filesystem_read_range"; with: { "path": RelativePath; "offset": number; "limit": number; "observed"?: string | null } } | { call: "filesystem_stat"; with: { "path": RelativePath } } | { call: "filesystem_write"; with: { "path": RelativePath; "contents": Array<number> } } | { call: "filesystem_create_observed"; with: { "path": RelativePath; "contents": Array<number> } } | { call: "filesystem_mkdir"; with: { "path": RelativePath } } | { call: "filesystem_rename"; with: { "from": RelativePath; "to": RelativePath } } | { call: "filesystem_rename_observed"; with: { "from": RelativePath; "to": RelativePath; "observed": string } } | { call: "filesystem_remove"; with: { "path": RelativePath } } | { call: "filesystem_remove_observed"; with: { "path": RelativePath; "observed": string } } | { call: "interface_open_tab"; with: { "title": string } } | { call: "interface_split"; with: { "slot": string; "division": Division } } | { call: "interface_withdraw"; with: { "slot": string } } | { call: "interface_render"; with: { "frame": Frame } } | { call: "interface_render_at"; with: { "slot": string; "frame": Frame } } | { call: "source_resize"; with: { "mutation": SourceMutation } } | { call: "source_resize_at"; with: { "slot": string; "mutation": SourceMutation } } | { call: "event_subscribe"; with: { "topic": Topic } } | { call: "event_unsubscribe"; with: { "topic": Topic } };
export type WireReply = { reply: "workspace"; with: WorkspaceInfo } | { reply: "workspace_configuration"; with: WorkspaceConfiguration } | { reply: "workspaces"; with: Array<WorkspaceState> } | { reply: "extensions"; with: Array<ExtensionSummary> } | { reply: "extension"; with: ExtensionSummary } | { reply: "extension_acquisition_job"; with: ExtensionAcquisitionJob } | { reply: "extension_acquisition"; with: ExtensionAcquisitionStatus } | { reply: "containers"; with: Array<ContainerSummary> } | { reply: "container"; with: ContainerSummary } | { reply: "processes"; with: ProcessList } | { reply: "logs"; with: ContainerOutput } | { reply: "execution"; with: ExecutionSummary } | { reply: "executions"; with: ExecutionList } | { reply: "images"; with: ImageInventory } | { reply: "image"; with: ImageSummary } | { reply: "image_pull_job"; with: ImagePullJob } | { reply: "image_pull"; with: ImagePullStatus } | { reply: "image_details"; with: ImageDetails } | { reply: "image_prune"; with: ImagePruneResult } | { reply: "volumes"; with: VolumeInventory } | { reply: "volume"; with: VolumeSummary } | { reply: "networks"; with: NetworkInventory } | { reply: "network"; with: NetworkSummary } | { reply: "tabs"; with: Array<TabSummary> } | { reply: "topology"; with: TerminalTopology } | { reply: "panes"; with: PaneInventory } | { reply: "text"; with: PaneText } | { reply: "semantics"; with: PaneSemanticTree } | { reply: "entries"; with: Array<Entry> } | { reply: "entry"; with: Entry } | { reply: "contents"; with: Array<number> } | { reply: "file_range"; with: FileRange } | { reply: "identity"; with: string } | { reply: "done" };
export type WireCall = WireRequest['call'];
export type WireRequestFor<C extends WireCall> = Extract<WireRequest, { call: C }>;
export type WireRequestParameters<C extends WireCall> = WireRequestFor<C> extends { with: infer P } ? P : undefined;
export interface WireReplyByCall {
  "workspace_info": Extract<WireReply, { reply: "workspace" }>;
  "workspace_list": Extract<WireReply, { reply: "workspaces" }>;
  "workspace_inspect": Extract<WireReply, { reply: "workspace_configuration" }>;
  "workspace_create": Extract<WireReply, { reply: "workspace_configuration" }>;
  "workspace_adopt": Extract<WireReply, { reply: "workspace_configuration" }>;
  "workspace_update": Extract<WireReply, { reply: "workspace_configuration" }>;
  "workspace_delete": Extract<WireReply, { reply: "done" }>;
  "workspace_start": Extract<WireReply, { reply: "done" }>;
  "workspace_stop": Extract<WireReply, { reply: "done" }>;
  "workspace_restart": Extract<WireReply, { reply: "done" }>;
  "extension_list": Extract<WireReply, { reply: "extensions" }>;
  "extension_inspect": Extract<WireReply, { reply: "extension" }>;
  "extension_enable": Extract<WireReply, { reply: "done" }>;
  "extension_disable": Extract<WireReply, { reply: "done" }>;
  "extension_retry": Extract<WireReply, { reply: "done" }>;
  "extension_remove": Extract<WireReply, { reply: "done" }>;
  "extension_acquisition_start": Extract<WireReply, { reply: "extension_acquisition_job" }>;
  "extension_acquisition_status": Extract<WireReply, { reply: "extension_acquisition" }>;
  "extension_acquisition_cancel": Extract<WireReply, { reply: "done" }>;
  "extension_install": Extract<WireReply, { reply: "extension" }>;
  "extension_update": Extract<WireReply, { reply: "extension" }>;
  "container_list": Extract<WireReply, { reply: "containers" }>;
  "container_inspect": Extract<WireReply, { reply: "container" }>;
  "container_processes": Extract<WireReply, { reply: "processes" }>;
  "container_logs": Extract<WireReply, { reply: "logs" }>;
  "execution_inspect": Extract<WireReply, { reply: "execution" }>;
  "execution_list": Extract<WireReply, { reply: "executions" }>;
  "execution_logs": Extract<WireReply, { reply: "logs" }>;
  "execution_wait": Extract<WireReply, { reply: "execution" }>;
  "execution_kill": Extract<WireReply, { reply: "done" }>;
  "execution_remove": Extract<WireReply, { reply: "done" }>;
  "container_create": Extract<WireReply, { reply: "identity" }>;
  "container_start": Extract<WireReply, { reply: "done" }>;
  "container_stop": Extract<WireReply, { reply: "done" }>;
  "container_remove": Extract<WireReply, { reply: "done" }>;
  "container_pause": Extract<WireReply, { reply: "done" }>;
  "container_unpause": Extract<WireReply, { reply: "done" }>;
  "container_restart": Extract<WireReply, { reply: "done" }>;
  "container_rename": Extract<WireReply, { reply: "done" }>;
  "container_kill": Extract<WireReply, { reply: "done" }>;
  "container_exec": Extract<WireReply, { reply: "identity" }>;
  "container_attach_terminal": Extract<WireReply, { reply: "identity" }>;
  "image_list": Extract<WireReply, { reply: "images" }>;
  "image_pull": Extract<WireReply, { reply: "image" }>;
  "image_pull_start": Extract<WireReply, { reply: "image_pull_job" }>;
  "image_pull_status": Extract<WireReply, { reply: "image_pull" }>;
  "image_pull_cancel": Extract<WireReply, { reply: "done" }>;
  "image_inspect": Extract<WireReply, { reply: "image_details" }>;
  "image_remove": Extract<WireReply, { reply: "done" }>;
  "image_prune": Extract<WireReply, { reply: "image_prune" }>;
  "volume_list": Extract<WireReply, { reply: "volumes" }>;
  "volume_inspect": Extract<WireReply, { reply: "volume" }>;
  "volume_create": Extract<WireReply, { reply: "volume" }>;
  "volume_remove": Extract<WireReply, { reply: "done" }>;
  "network_list": Extract<WireReply, { reply: "networks" }>;
  "network_inspect": Extract<WireReply, { reply: "network" }>;
  "network_create": Extract<WireReply, { reply: "identity" }>;
  "network_remove": Extract<WireReply, { reply: "done" }>;
  "network_connect": Extract<WireReply, { reply: "done" }>;
  "network_disconnect": Extract<WireReply, { reply: "done" }>;
  "terminal_tabs": Extract<WireReply, { reply: "tabs" }>;
  "terminal_topology": Extract<WireReply, { reply: "topology" }>;
  "pane_list": Extract<WireReply, { reply: "panes" }>;
  "terminal_open_tab": Extract<WireReply, { reply: "identity" }>;
  "terminal_pin_tab": Extract<WireReply, { reply: "done" }>;
  "terminal_split": Extract<WireReply, { reply: "identity" }>;
  "terminal_split_observed": Extract<WireReply, { reply: "identity" }>;
  "terminal_spawn": Extract<WireReply, { reply: "done" }>;
  "terminal_spawn_observed": Extract<WireReply, { reply: "done" }>;
  "terminal_read_pane": Extract<WireReply, { reply: "text" }>;
  "pane_semantic_read": Extract<WireReply, { reply: "semantics" }>;
  "pane_semantic_action": Extract<WireReply, { reply: "done" }>;
  "terminal_write_pane": Extract<WireReply, { reply: "done" }>;
  "terminal_resize_grid": Extract<WireReply, { reply: "done" }>;
  "terminal_resize_grid_observed": Extract<WireReply, { reply: "done" }>;
  "terminal_close_pane": Extract<WireReply, { reply: "done" }>;
  "terminal_close_pane_observed": Extract<WireReply, { reply: "done" }>;
  "terminal_focus_pane": Extract<WireReply, { reply: "done" }>;
  "terminal_focus_pane_observed": Extract<WireReply, { reply: "done" }>;
  "terminal_retitle_pane": Extract<WireReply, { reply: "done" }>;
  "terminal_retitle_pane_observed": Extract<WireReply, { reply: "done" }>;
  "terminal_ratio": Extract<WireReply, { reply: "done" }>;
  "terminal_ratio_observed": Extract<WireReply, { reply: "done" }>;
  "terminal_switch_occupant": Extract<WireReply, { reply: "done" }>;
  "terminal_switch_occupant_observed": Extract<WireReply, { reply: "done" }>;
  "filesystem_list": Extract<WireReply, { reply: "entries" }>;
  "filesystem_read": Extract<WireReply, { reply: "contents" }>;
  "filesystem_read_range": Extract<WireReply, { reply: "file_range" }>;
  "filesystem_stat": Extract<WireReply, { reply: "entry" }>;
  "filesystem_write": Extract<WireReply, { reply: "done" }>;
  "filesystem_create_observed": Extract<WireReply, { reply: "identity" }>;
  "filesystem_mkdir": Extract<WireReply, { reply: "done" }>;
  "filesystem_rename": Extract<WireReply, { reply: "done" }>;
  "filesystem_rename_observed": Extract<WireReply, { reply: "identity" }>;
  "filesystem_remove": Extract<WireReply, { reply: "done" }>;
  "filesystem_remove_observed": Extract<WireReply, { reply: "done" }>;
  "interface_open_tab": Extract<WireReply, { reply: "identity" }>;
  "interface_split": Extract<WireReply, { reply: "identity" }>;
  "interface_withdraw": Extract<WireReply, { reply: "done" }>;
  "interface_render": Extract<WireReply, { reply: "done" }>;
  "interface_render_at": Extract<WireReply, { reply: "done" }>;
  "source_resize": Extract<WireReply, { reply: "done" }>;
  "source_resize_at": Extract<WireReply, { reply: "done" }>;
  "event_subscribe": Extract<WireReply, { reply: "done" }>;
  "event_unsubscribe": Extract<WireReply, { reply: "done" }>;
}
export type WireReplyFor<C extends WireCall> = WireReplyByCall[C];
export type WireFailure = { error: "denied" } & { "capability": string; "detail": string } | { error: "absent" } & { "detail": string } | { error: "conflict" } & { "detail": string } | { error: "failed" } & { "detail": string } | { error: "unsupported" } & { "call": string };
export type WireSnapshot = { snapshot: "containers"; of: Array<ContainerSummary> } | { snapshot: "container_inventory"; of: ContainerInventory } | { snapshot: "executions"; of: ExecutionList } | { snapshot: "images"; of: ImageInventory } | { snapshot: "image_pulls"; of: ImagePullChange } | { snapshot: "volumes"; of: VolumeInventory } | { snapshot: "networks"; of: NetworkInventory } | { snapshot: "terminal"; of: Array<TabSummary> } | { snapshot: "pane_changes"; of: PaneChange } | { snapshot: "extensions"; of: Array<ExtensionSummary> } | { snapshot: "extension_acquisitions"; of: ExtensionAcquisitionChange } | { snapshot: "workspace_lifecycle"; of: WorkspaceLifecycleChange } | { snapshot: "workspace_events"; of: WorkspaceEventBatch };
export type WireUiEvent = { interaction: "invoke" } & { "trigger": string; "node": number; "id": string; "slot"?: string | null } | { interaction: "submit" } & { "trigger": string; "node": number; "id": string; "slot"?: string | null } | { interaction: "change" } & { "trigger": string; "node": number; "id": string; "slot"?: string | null; "value": PropValue } | { interaction: "select" } & { "trigger": string; "node": number; "id": string; "slot"?: string | null; "rows": Array<number>; "collection"?: UiCollectionSelection | null } | { interaction: "edit" } & { "trigger": string; "node": number; "id": string; "slot"?: string | null; "source": number; "version": number; "row": UiSelectedRow; "column": string; "value": string } | { interaction: "sort" } & { "trigger": string; "node": number; "id": string; "slot"?: string | null; "source": number; "version": number; "column": string; "descending": boolean } | { interaction: "scroll" } & { "trigger": string; "node": number; "id": string; "slot"?: string | null; "dx": number; "dy": number } | { interaction: "close" } & { "trigger": string; "node": number; "id": string; "slot"?: string | null } | { interaction: "context" } & { "trigger": string; "node": number; "id": string; "slot"?: string | null; "x": number; "y": number } | { interaction: "key" } & { "trigger": string; "node": number; "id": string; "slot"?: string | null; "key": string; "keycode": number; "modifiers": number; "pressed": boolean } | { interaction: "focus" } & { "trigger": string; "node": number; "id": string; "slot"?: string | null; "focused": boolean } | { interaction: "pointer" } & { "trigger": string; "node": number; "id": string; "slot"?: string | null; "phase": UiPointerPhase; "x"?: number | null; "y"?: number | null; "button": number; "modifiers": number } | { interaction: "drag" } & { "trigger": string; "node": number; "id": string; "slot"?: string | null } | { interaction: "drop" } & { "trigger": string; "node": number; "id": string; "slot"?: string | null; "source": number; "x": number; "y": number };
export const PROTOCOL_REPLIES: Readonly<Record<WireRequest['call'], WireReply['reply']>>;
export const PROTOCOL_REQUEST_CAPABILITIES: Readonly<Record<WireRequest['call'], ExtensionCapability | null>>;
export function validateRequest(value: unknown): WireRequest;
export function validateReply(value: unknown): WireReply;
export function validateReplyFor(call: WireRequest['call'], value: unknown): WireReply;
export function validateFailure(value: unknown): WireFailure;
export function validateSnapshot(value: unknown): WireSnapshot;
export function validateUiEvent(value: unknown): WireUiEvent;
export function encodeRequest(call: WireRequest['call'], payload?: unknown): WireRequest;
