/* BR, BLR, default RET and explicit-register RET.  `blr x30` is the aliasing
 * case: the branch target must be read before BLR publishes its return PC. */
__asm__(".global _start\n"
        ".type _start,%function\n"
        "_start:\n"
        "adr x1,br_target\n"
        "br x1\n"
        "br_target:\n"
        "adr x30,blr_target\n"
        "blr x30\n"
        "after_blr:\n"
        "adr x4,after_blr\n"
        "cmp x30,x4\n"
        "b.ne fail\n"
        "adr x5,explicit_ret_target\n"
        "ret x5\n"
        "blr_target:\n"
        "ret\n"
        "explicit_ret_target:\n"
        "movz x0,#42\n"
        "movz x8,#93\n"
        "svc #0\n"
        "fail:\n"
        "movz x0,#1\n"
        "movz x8,#93\n"
        "svc #0\n"
        ".size _start,.-_start\n");
