/* Exact integer-ALU slice. Conditional branches are intentionally left to the
 * interpreter: each preceding generated B makes canonical NZCV externally
 * observable at a dispatcher boundary before the next generated block. */
__asm__(".global _start\n"
        ".type _start,%function\n"
        "_start:\n"
        "adr x2,_start\n"
        "adrp x0,_start\n"
        "sub x0,x0,#0x400,lsl #12\n"
        "add x0,x0,#42\n"
        "add sp,x0,#8\n"
        "sub w0,wsp,#8\n"
        "b 2f\n"
        "movz x0,#1\n"
        "1:\n"
        "movz x3,#0xffff,lsl #32\n"
        "movz xzr,#0x1234\n"
        "movz x8,#93\n"
        "svc #0\n"
        "2:\n"
        "b 3f\n"
        "3:\n"
        "movz x1,#1\n"
        "orr x2,xzr,#0x7fffffffffffffff\n"
        "eor x2,x2,#0xffff\n"
        "eor x2,x2,#0xffff\n"
        "and x2,x2,#0x7fffffffffffffff\n"
        "adds x3,x2,x1\n"
        "b 4f\n"
        "4:\n"
        "b.vs 5f\n"
        "b 99f\n"
        "5:\n"
        "b.mi 6f\n"
        "b 99f\n"
        "6:\n"
        "cmp x1,x1\n"
        "b 7f\n"
        "7:\n"
        "b.eq 8f\n"
        "b 99f\n"
        "8:\n"
        "b.cs 9f\n"
        "b 99f\n"
        "9:\n"
        "sub w4,wzr,w1,lsl #1\n"
        "add w7,wzr,w1,lsl #2\n"
        "adds w5,w4,w1,lsl #1\n"
        "b 90f\n"
        "90:\n"
        "b.eq 91f\n"
        "b 99f\n"
        "91:\n"
        "b.cs 92f\n"
        "b 99f\n"
        "92:\n"
        "tst w5,#0xff\n"
        "b 10f\n"
        "10:\n"
        "b.eq 11f\n"
        "b 99f\n"
        "11:\n"
        "b.cc 12f\n"
        "b 99f\n"
        "12:\n"
        "b.vc 13f\n"
        "b 99f\n"
        "13:\n"
        "mov x6,x1\n"
        "eor x6,x6,x1,lsl #1\n"
        "and x6,x6,x1\n"
        "and sp,xzr,#0xff\n"
        "cmp sp,#0\n"
        "b.eq .Llogical_and_sp\n"
        "b 99f\n"
        ".Llogical_and_sp:\n"
        "orr sp,xzr,#0xff\n"
        "cmp sp,#0xff\n"
        "b.eq .Llogical_orr_sp\n"
        "b 99f\n"
        ".Llogical_orr_sp:\n"
        "eor sp,xzr,#3\n"
        "cmp sp,#3\n"
        "b.eq .Llogical_eor_sp\n"
        "b 99f\n"
        ".Llogical_eor_sp:\n"
        "ands xzr,x1,#1\n"
        "b.ne .Llogical_ands_zr\n"
        "b 99f\n"
        ".Llogical_ands_zr:\n"
        "cmp sp,#3\n"
        "b 14f\n"
        "14:\n"
        "b.eq 15f\n"
        "b 99f\n"
        "15:\n"
        "cmn sp,#0\n"
        "movz x9,#0\n"
        "cbz x9,16f\n"
        "b 99f\n"
        "16:\n"
        "cbnz x1,17f\n"
        "b 99f\n"
        "17:\n"
        "movz x11,#0x8000,lsl #48\n"
        "tbnz x11,#63,18f\n"
        "b 99f\n"
        "18:\n"
        "tbz x11,#31,19f\n"
        "b 99f\n"
        "19:\n"
        "movz w11,#0x8000,lsl #16\n"
        "tbnz x11,#31,20f\n"
        "b 99f\n"
        "20:\n"
        "cmp x1,#0\n"
        "b.hi 21f\n"
        "b 99f\n"
        "21:\n"
        "cmp xzr,x1\n"
        "b.ls 22f\n"
        "b 99f\n"
        "22:\n"
        "b.lt 23f\n"
        "b 99f\n"
        "23:\n"
        "cmp x1,x1\n"
        "b.ge 24f\n"
        "b 99f\n"
        "24:\n"
        "movz x12,#0\n"
        "b 26f\n"
        "25:\n"
        "add x12,x12,#1\n"
        "b 27f\n"
        "26:\n"
        "cbz x12,25b\n"
        "27:\n"
        "movz x0,#42\n"
        "b 1b\n"
        "99:\n"
        "movz x0,#1\n"
        "b 1b\n"
        ".size _start,.-_start\n");
