/* Complete allocated AArch64 data-processing (3 source) family. Each result is
 * checked before the next form so width, signedness, high-half, Ra, ZR, or
 * subtract mistakes cannot cancel in one final checksum. */
__asm__(".global _start\n"
        ".type _start,%function\n"
        "_start:\n"
        "movz x0,#3\n"
        "movz x1,#5\n"
        "movz x2,#7\n"
        "madd x3,x0,x1,x2\n"
        "cmp x3,#22\n"
        "b.ne 99f\n"
        "msub x3,x0,x1,x2\n"
        "movz x4,#8\n"
        "sub x4,xzr,x4\n"
        "cmp x3,x4\n"
        "b.ne 99f\n"

        /* W results wrap at 32 bits and zero their high half. */
        "movz w0,#1\n"
        "sub w0,wzr,w0\n"
        "movz w1,#2\n"
        "movz w2,#3\n"
        "madd w3,w0,w1,w2\n"
        "cmp w3,#1\n"
        "b.ne 99f\n"
        "msub w3,w0,w1,w2\n"
        "cmp w3,#5\n"
        "b.ne 99f\n"

        /* Signed and unsigned widening retain the full 64-bit addend. */
        "movz w0,#2\n"
        "sub w0,wzr,w0\n"
        "movz w1,#3\n"
        "movz x2,#7\n"
        "smaddl x3,w0,w1,x2\n"
        "cmp x3,#1\n"
        "b.ne 99f\n"
        "smsubl x3,w0,w1,x2\n"
        "cmp x3,#13\n"
        "b.ne 99f\n"
        "movz w0,#1\n"
        "sub w0,wzr,w0\n"
        "movz w1,#2\n"
        "movz x2,#3\n"
        "umaddl x3,w0,w1,x2\n"
        "movz x4,#1\n"
        "movk x4,#2,lsl #32\n"
        "cmp x3,x4\n"
        "b.ne 99f\n"
        "umsubl x3,w0,w1,x2\n"
        "movz x4,#5\n"
        "movk x4,#0xfffe,lsl #32\n"
        "movk x4,#0xffff,lsl #48\n"
        "cmp x3,x4\n"
        "b.ne 99f\n"

        /* High-half forms distinguish signed from unsigned multiplication. */
        "movz x0,#2\n"
        "sub x0,xzr,x0\n"
        "movz x1,#0x4000,lsl #48\n"
        "smulh x3,x0,x1\n"
        "movz x4,#1\n"
        "sub x4,xzr,x4\n"
        "cmp x3,x4\n"
        "b.ne 99f\n"
        "movz x0,#1\n"
        "sub x0,xzr,x0\n"
        "movz x1,#2\n"
        "umulh x3,x0,x1\n"
        "cmp x3,#1\n"
        "b.ne 99f\n"

        /* All operand fields name ZR, and a write to Rd==ZR vanishes. */
        "madd x3,xzr,x1,xzr\n"
        "cbnz x3,99f\n"
        "madd xzr,x0,x1,x2\n"

        "movz x0,#42\n"
        "b 1f\n"
        "99:\n"
        "movz x0,#1\n"
        "1:\n"
        "movz x8,#93\n"
        "svc #0\n"
        ".size _start,.-_start\n");
