/* SXTW sign extension, source/destination ZR, wrapping, and NZCV preservation. */
__asm__(".global _start\n"
        ".type _start,%function\n"
        "_start:\n"
        "movz x1,#1\n"
        "movk x1,#0x8000,lsl #16\n"
        "cmp xzr,xzr\n"
        "sxtw x2,w1\n"
        "sxtw x1,w1\n"
        "sxtw x3,wzr\n"
        "sxtw xzr,w1\n"
        "b.ne 99f\n"
        "movz x4,#1\n"
        "movk x4,#0x8000,lsl #16\n"
        "movk x4,#0xffff,lsl #32\n"
        "movk x4,#0xffff,lsl #48\n"
        "cmp x2,x4\n"
        "b.ne 99f\n"
        "cmp x1,x4\n"
        "b.ne 99f\n"
        "cbnz x3,99f\n"
        "mov x0,#42\n"
        "b 1f\n"
        "99:\n"
        "mov x0,#1\n"
        "1:\n"
        "mov x8,#93\n"
        "svc #0\n"
        ".size _start,.-_start\n");
