use hl_linux::{Errno, GuestMemory, LinuxResult, SyscallOperation, TaskSignalTimeSyscalls};

use crate::RuntimeProcessSyscalls;

impl<M: GuestMemory> TaskSignalTimeSyscalls for RuntimeProcessSyscalls<M> {
    fn handle(&mut self, operation: SyscallOperation, arguments: [u64; 6]) -> LinuxResult {
        match operation.name {
            "getpid" => LinuxResult::Value(self.process.number() as u64),
            "ptrace" => self.ptrace(arguments),
            "gettid" => LinuxResult::Value(self.thread.number() as u64),
            "set_tid_address" => self.set_tid_address(arguments[0]),
            "unshare" => self.unshare(arguments[0]),
            "setns" => self.setns(arguments[0] as i32, arguments[1]),
            "getppid" => self.getppid(),
            "getuid" => self.identity_value(0),
            "geteuid" => self.identity_value(1),
            "getgid" => self.identity_value(2),
            "getegid" => self.identity_value(3),
            "capget" => self.capget(arguments[0], arguments[1]),
            "capset" => self.capset(arguments[0], arguments[1]),
            "personality" => self.personality(arguments[0] as u32),
            "pidfd_open" => self.pidfd_open(arguments[0] as u32, arguments[1] as u32),
            "pidfd_send_signal" => self.pidfd_signal(arguments),
            "pidfd_getfd" => self.pidfd_getfd(arguments),
            "uname" => self.uname(arguments[0]),
            "sethostname" => self.set_uts_name(arguments[0], arguments[1] as usize, false),
            "setdomainname" => self.set_uts_name(arguments[0], arguments[1] as usize, true),
            "sysinfo" => self.sysinfo(arguments[0]),
            "sched_yield" => self.sched_yield(),
            "sched_setscheduler" => self.sched_setscheduler(arguments[0] as i32, arguments[1] as u32, arguments[2]),
            "sched_setparam" => self.sched_setparam(arguments[0] as i32, arguments[1]),
            "sched_getscheduler" => self.sched_getscheduler(arguments[0] as i32),
            "sched_getparam" => self.sched_getparam(arguments[0] as i32, arguments[1]),
            "sched_get_priority_max" => self.sched_priority(arguments[0] as u32, true),
            "sched_get_priority_min" => self.sched_priority(arguments[0] as u32, false),
            "sched_rr_get_interval" => self.sched_rr_interval(arguments[0] as i32, arguments[1]),
            "sched_setattr" => self.sched_setattr(arguments[0] as i32, arguments[1], arguments[2]),
            "sched_getattr" => {
                self.sched_getattr(arguments[0] as i32, arguments[1], arguments[2] as usize, arguments[3])
            }
            "setpriority" => self.setpriority(arguments[0] as u32, arguments[1] as i32, arguments[2] as i32),
            "getpriority" => self.getpriority(arguments[0] as u32, arguments[1] as i32),
            "sched_setaffinity" => self.sched_setaffinity(arguments[0] as i32, arguments[1] as usize, arguments[2]),
            "sched_getaffinity" => self.sched_getaffinity(arguments[0] as i32, arguments[1] as usize, arguments[2]),
            "getcpu" => self.getcpu(arguments[0], arguments[1]),
            "getresuid" => self.getres(arguments, true),
            "getresgid" => self.getres(arguments, false),
            "getgroups" => self.getgroups(arguments[0] as usize, arguments[1]),
            "setgroups" => self.setgroups(arguments[0] as usize, arguments[1]),
            "setuid" => self.set_single_id(arguments[0] as u32, true),
            "setgid" => self.set_single_id(arguments[0] as u32, false),
            "setreuid" => self.set_pair([arguments[0] as u32, arguments[1] as u32], true),
            "setregid" => self.set_pair([arguments[0] as u32, arguments[1] as u32], false),
            "setresuid" => self.set_ids([arguments[0] as u32, arguments[1] as u32, arguments[2] as u32], true),
            "setresgid" => self.set_ids([arguments[0] as u32, arguments[1] as u32, arguments[2] as u32], false),
            "setfsuid" => self.set_filesystem(arguments[0] as u32, true),
            "setfsgid" => self.set_filesystem(arguments[0] as u32, false),
            "umask" => self.umask(arguments[0] as u32),
            "exit" => self.exit(arguments[0], false),
            "exit_group" => self.exit(arguments[0], true),
            "getrlimit" => self.getrlimit(arguments[0] as u32, arguments[1]),
            "setrlimit" => self.setrlimit(arguments[0] as u32, arguments[1]),
            "prlimit64" => self.prlimit(arguments),
            "prctl" => self.prctl(arguments),
            "fanotify_init" | "fanotify_mark" => LinuxResult::Error(Errno::EPERM),
            "bpf" | "userfaultfd" | "io_uring_setup" | "io_uring_enter" | "io_uring_register" => {
                LinuxResult::Error(Errno::EPERM)
            }
            "getpgid" => self.getpgid(arguments[0] as i32),
            "getpgrp" => self.getpgid(0),
            "getsid" => self.getsid(arguments[0] as i32),
            "setpgid" => self.setpgid(arguments[0] as i32, arguments[1] as i32),
            "setsid" => self.setsid(),
            "fork" => self.fork_plain(false),
            "vfork" => self.fork_plain(true),
            "clone" => self.clone_legacy(arguments),
            "clone3" => self.clone3(arguments[0], arguments[1] as usize),
            "wait4" => self.wait4(arguments[0] as i32, arguments[1], arguments[2] as u32, arguments[3]),
            "waitid" => self.waitid(arguments),
            "kill" => self.kill(arguments[0] as i32, arguments[1] as u32),
            "tkill" => self.tkill(arguments[0] as i32, arguments[1] as u32),
            "tgkill" => self.tgkill(arguments[0] as i32, arguments[1] as i32, arguments[2] as u32),
            "rt_sigqueueinfo" => self.rt_sigqueueinfo(arguments[0] as i32, arguments[1] as u32, arguments[2]),
            "rt_tgsigqueueinfo" => self.rt_tgsigqueueinfo(
                arguments[0] as i32,
                arguments[1] as i32,
                arguments[2] as u32,
                arguments[3],
            ),
            "rt_sigaction" => self.rt_sigaction(arguments),
            "rt_sigprocmask" => self.rt_sigprocmask(arguments),
            "rt_sigpending" => self.rt_sigpending(arguments[0], arguments[1] as usize),
            "rt_sigtimedwait" => self.rt_sigtimedwait(arguments),
            "rt_sigsuspend" => self.rt_sigsuspend(arguments),
            "pause" => self.pause(),
            "rt_sigreturn" => self.rt_sigreturn(),
            "clock_gettime" => self.clock_gettime(arguments[0] as i32, arguments[1]),
            "clock_settime" => self.clock_settime(arguments[0] as i32),
            "clock_getres" => self.clock_getres(arguments[0] as i32, arguments[1]),
            "clock_adjtime" => self.clock_adjtime(arguments[0] as i32, arguments[1]),
            "adjtimex" => self.adjtimex(arguments[0]),
            "gettimeofday" => self.gettimeofday(arguments[0], arguments[1]),
            "time" => self.time(arguments[0]),
            "getrusage" => self.getrusage(arguments[0] as i32, arguments[1]),
            "times" => self.times(arguments[0]),
            "nanosleep" => self.nanosleep(arguments[0], arguments[1]),
            "clock_nanosleep" => self.clock_nanosleep(arguments),
            "getitimer" => self.getitimer(arguments[0] as i32, arguments[1]),
            "setitimer" => self.setitimer(arguments[0] as i32, arguments[1], arguments[2]),
            "alarm" => self.alarm(arguments[0] as u32),
            "timer_create" => self.timer_create(arguments[0] as i32, arguments[1], arguments[2]),
            "timer_settime" => self.timer_settime(arguments[0] as i32, arguments[1] as u32, arguments[2], arguments[3]),
            "timer_gettime" => self.timer_gettime(arguments[0] as i32, arguments[1]),
            "timer_getoverrun" => self.timer_getoverrun(arguments[0] as i32),
            "timer_delete" => self.timer_delete(arguments[0] as i32),
            "futex" => self.futex(arguments),
            "futex_waitv" => self.futex_waitv(arguments),
            "set_robust_list" => self.set_robust_list(arguments[0], arguments[1]),
            "get_robust_list" => self.get_robust_list(arguments[0] as u32, arguments[1], arguments[2]),
            "sigaltstack" => self.sigaltstack(arguments[0], arguments[1]),
            "execve" => self.execve(arguments[0], arguments[1], arguments[2]),
            "execveat" => self.execveat(
                arguments[0] as i32,
                arguments[1],
                arguments[2],
                arguments[3],
                arguments[4] as u32,
            ),
            _ => LinuxResult::Error(Errno::ENOSYS),
        }
    }
}
