file(GLOB_RECURSE actual RELATIVE "${ROOT}" "${ROOT}/native/exec/src/*.c" "${ROOT}/native/exec/cache/*.c")
list(APPEND actual
 "runtime/native/address_projection.c"
 "runtime/native/executable_authority.c"
 "runtime/native/shim.c")
list(SORT actual)
file(STRINGS "${MANIFEST}" expected)
list(FILTER expected EXCLUDE REGEX "^($|#)")
list(SORT expected)
if(NOT actual STREQUAL expected)
 message(FATAL_ERROR "native C manifest differs from Cargo discovery")
endif()
file(STRINGS "${ROOT}/runtime/native/retained/COMPILED_TUS.tsv" rows)
list(POP_FRONT rows)
foreach(row IN LISTS rows)
 string(REPLACE "\t" ";" columns "${row}")
 list(LENGTH columns column_count)
 if(column_count GREATER 2)
  list(GET columns 2 source)
  if(NOT EXISTS "${ROOT}/runtime/native/retained/${source}")
   message(FATAL_ERROR "retained compiled TU missing: ${source}")
  endif()
 endif()
endforeach()
