file(GLOB_RECURSE actual RELATIVE "${ROOT}" "${ROOT}/runtime/native/exec/src/*.c" "${ROOT}/runtime/native/exec/cache/*.c")
file(GLOB_RECURSE repository_c_sources RELATIVE "${ROOT}"
 "${ROOT}/*.c" "${ROOT}/*.h" "${ROOT}/*.S")
foreach(source IN LISTS repository_c_sources)
 if(NOT source MATCHES "^runtime/native/")
  message(FATAL_ERROR "C source is outside src/runtime/native: ${source}")
 endif()
endforeach()
list(APPEND actual
 "runtime/native/address_projection.c"
 "runtime/native/executable_authority.c"
 "runtime/native/shim.c")
list(SORT actual)
file(STRINGS "${MANIFEST}" expected)
list(FILTER expected EXCLUDE REGEX "^($|#)")
list(SORT expected)
if(NOT actual STREQUAL expected)
 message(FATAL_ERROR "native C manifest differs from Cargo discovery")
endif()
file(STRINGS "${ROOT}/runtime/native/retained/COMPILED_TUS.tsv" rows)
list(POP_FRONT rows)
file(STRINGS "${ROOT}/runtime/native/retained/RUNTIME_SOURCES.manifest" retained_sources)
foreach(row IN LISTS rows)
 string(REPLACE "\t" ";" columns "${row}")
 list(LENGTH columns column_count)
 if(column_count GREATER 2)
  list(GET columns 2 source)
  if(NOT EXISTS "${ROOT}/runtime/native/retained/${source}")
   message(FATAL_ERROR "retained compiled TU missing: ${source}")
  endif()
  if(NOT source IN_LIST retained_sources)
   message(FATAL_ERROR "retained compiled TU is absent from source inventory: ${source}")
  endif()
 endif()
endforeach()
foreach(source IN LISTS retained_sources)
 if(NOT EXISTS "${ROOT}/runtime/native/retained/${source}")
  message(FATAL_ERROR "retained source inventory entry missing: ${source}")
 endif()
endforeach()
