file(GLOB_RECURSE repository_c_sources RELATIVE "${ROOT}"
 "${ROOT}/*.c" "${ROOT}/*.h" "${ROOT}/*.S")
foreach(source IN LISTS repository_c_sources)
 if(NOT source MATCHES "^runtime/native/")
  message(FATAL_ERROR "C source is outside src/runtime/native: ${source}")
 endif()
endforeach()
set(actual ${repository_c_sources})
list(TRANSFORM actual REPLACE "^runtime/native/" "")
list(SORT actual)
file(STRINGS "${MANIFEST}" rows)
set(expected)
foreach(row IN LISTS rows)
 if(row MATCHES "^($|#)")
  continue()
 endif()
 string(REPLACE "\t" ";" columns "${row}")
 list(LENGTH columns column_count)
 if(NOT column_count EQUAL 2)
  message(FATAL_ERROR "invalid native source inventory row: ${row}")
 endif()
 list(GET columns 0 classification)
 list(GET columns 1 source)
 if(NOT classification MATCHES "^(source|fixture|assembly)$")
  message(FATAL_ERROR "invalid native source classification: ${classification}")
 endif()
 if(classification STREQUAL "assembly" AND NOT source MATCHES "[.]S$")
  message(FATAL_ERROR "non-assembly file classified as assembly: ${source}")
 endif()
 if(NOT classification STREQUAL "assembly" AND source MATCHES "[.]S$")
  message(FATAL_ERROR "assembly file lacks assembly classification: ${source}")
 endif()
 list(APPEND expected "${source}")
endforeach()
list(SORT expected)
if(NOT actual STREQUAL expected)
 message(FATAL_ERROR "native C/H/S inventory has omissions or stale entries")
endif()
file(STRINGS "${ROOT}/runtime/native/retained/COMPILED_TUS.tsv" rows)
list(POP_FRONT rows)
file(STRINGS "${ROOT}/runtime/native/retained/RUNTIME_SOURCES.manifest" retained_sources)
foreach(row IN LISTS rows)
 string(REPLACE "\t" ";" columns "${row}")
 list(LENGTH columns column_count)
 if(column_count GREATER 2)
  list(GET columns 2 source)
  if(NOT EXISTS "${ROOT}/runtime/native/retained/${source}")
   message(FATAL_ERROR "retained compiled TU missing: ${source}")
  endif()
  if(NOT source IN_LIST retained_sources)
   message(FATAL_ERROR "retained compiled TU is absent from source inventory: ${source}")
  endif()
 endif()
endforeach()
foreach(source IN LISTS retained_sources)
 if(NOT EXISTS "${ROOT}/runtime/native/retained/${source}")
  message(FATAL_ERROR "retained source inventory entry missing: ${source}")
 endif()
endforeach()
