[package]
name = "hl-ipc"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
hl-descriptor = { path = "../hl-descriptor" }
hl-memory = { path = "../hl-memory" }
hl-sync = { path = "../hl-sync" }
hl-time = { path = "../hl-time" }

[lints]
workspace = true
