//! dd-shim-cudart codegen: turn the CUDA-Runtime-API entry-point manifest into the complete set of
//! `#[no_mangle] extern "C"` `cuda*`/`__cuda*` exports the shim must provide. Mirrors
//! dd-shim-cuda/build.rs exactly, adapted to the runtime API's several return types.
//!
//! Input:  `registry/cudart.manifest` (extracted from dd's clean-room `dd-gpu/cuda/cudart_shim.c`
//!         runtime-API surface + the standard driver-backed tail — see `registry/`).
//! Output: `$OUT_DIR/generated_entrypoints.rs`, `include!`d by `src/lib.rs`.
//!
//! For every entry point NOT hand-implemented in `src/` (`IMPLEMENTED` below), we emit a spec-faithful
//! *default* stub: correct C-ABI signature (so the symbol resolves and the app links + runs), a
//! debug-gated "unimplemented entry point" trace, and a benign default return. Real bodies replace
//! stubs without ever changing the exported surface — the shrinking long tail, exactly like
//! dd-shim-cuda/-gl. The whole runtime surface is hand-implemented, so no stubs are emitted here.
//!
//! Also sets the shared-object soname to `libcudart.so.1` (the CUDA Runtime API drop-in name). The
//! cdylib's exported-symbol set is the crate's own `#[no_mangle]` items (rustc localizes everything
//! pulled from the `dd-shim-cuda` rlib, i.e. the driver's `cu*`), so `libcudart.so.1` exports EXACTLY
//! this manifest's `cuda*`/`__cuda*` surface — matching real libcudart visibility.

use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let dir = PathBuf::from(env("CARGO_MANIFEST_DIR"));
    let manifest = dir.join("registry/cudart.manifest");
    println!("cargo:rerun-if-changed={}", manifest.display());
    println!("cargo:rerun-if-changed=build.rs");

    // Deployed as libcudart.so.1 (the CUDA Runtime API soname a real app `DT_NEEDED`s); bake it.
    // Matches dd-gpu/cuda/build.sh's C shim and dd-shim-cuda's libcuda.so.1 pattern. Since this crate is
    // a self-contained peer over dd-gpu (it does NOT static-link dd-shim-cuda), no foreign `cu*` symbols
    // or competing soname leak in, so the exported surface is exactly this crate's `cuda*`/`__cuda*`.
    println!("cargo:rustc-cdylib-link-arg=-Wl,-soname,libcudart.so.1");

    let text = std::fs::read_to_string(&manifest)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest.display()));

    let mut out = String::new();
    out.push_str("// @generated by build.rs from registry/cudart.manifest — DO NOT EDIT.\n");
    out.push_str("// (crate-level `#![allow(non_snake_case, ...)]` lives in src/lib.rs.)\n\n");

    let mut rt = 0usize;
    let mut stubs = 0usize;
    for (lineno, line) in text.lines().enumerate() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut f = line.split('\t');
        let lib = f.next().unwrap_or("");
        let name = f.next().unwrap_or("");
        let ret = f.next().unwrap_or("void");
        let params = f.next().unwrap_or("");
        if name.is_empty() {
            panic!("manifest line {}: empty name: {line:?}", lineno + 1);
        }
        match lib {
            "RT" => rt += 1,
            other => panic!("manifest line {}: unknown lib {other:?}", lineno + 1),
        }
        if IMPLEMENTED.contains(&name) {
            continue; // hand-written in src/; a generated stub would collide.
        }
        stubs += 1;
        emit_stub(&mut out, name, ret, params);
    }

    // A compile-time census the crate can assert against (the completeness gate).
    writeln!(out, "\n/// Total CUDA Runtime API entry points in the manifest.").unwrap();
    writeln!(out, "pub const CUDART_ENTRYPOINTS: usize = {rt};").unwrap();
    writeln!(out, "/// Entry points emitted as default stubs (not yet hand-implemented).").unwrap();
    writeln!(out, "pub const GENERATED_STUBS: usize = {stubs};").unwrap();

    let out_path = PathBuf::from(env("OUT_DIR")).join("generated_entrypoints.rs");
    std::fs::write(&out_path, out).unwrap();
}

fn emit_stub(out: &mut String, name: &str, ret: &str, params: &str) {
    let mut sig = String::new();
    let mut argnames = Vec::new();
    if !params.is_empty() {
        for (i, p) in params.split(';').enumerate() {
            let (ty, pname) = p.split_once('|').unwrap_or_else(|| panic!("bad param {p:?} in {name}"));
            let rty = map_type(ty.trim(), name);
            let pn = sanitize(pname.trim(), i);
            if i > 0 {
                sig.push_str(", ");
            }
            write!(sig, "{pn}: {rty}").unwrap();
            argnames.push(pn);
        }
    }
    let rmap = map_ret(ret.trim(), name);
    let arrow = rmap.as_ref().map(|r| format!(" -> {r}")).unwrap_or_default();
    let touch: String = argnames.iter().map(|a| format!("let _ = {a}; ")).collect();
    let body = match &rmap {
        None => format!("{touch}crate::stub::hit(\"{name}\");"),
        Some(r) => {
            let dflt = default_for(r);
            format!("{touch}crate::stub::hit(\"{name}\"); {dflt}")
        }
    };
    writeln!(out, "#[no_mangle]\npub extern \"C\" fn {name}({sig}){arrow} {{ {body} }}\n").unwrap();
}

/// C return type -> Rust type (None == `void`/unit). Panics on an unknown type so an API bump surfaces
/// at build time rather than silently mis-typing the ABI.
fn map_ret(c: &str, ctx: &str) -> Option<String> {
    let c = c.trim();
    if c == "void" {
        return None;
    }
    Some(map_type(c, ctx))
}

/// C type string -> Rust C-ABI type. Handles the pointer forms generally (single/double, const/mut) so
/// an API bump only ever surprises us on a genuinely new *base scalar*, which panics (fail-loud ABI
/// generator). Identical structure to dd-shim-cuda's mapper.
fn map_type(c: &str, ctx: &str) -> String {
    let c = c.trim();
    if let Some(base) = c.strip_suffix("**") {
        // outer const-ness of `X **` params is not expressed in the manifest surface; treat as mut.
        return format!("*mut *mut {}", pointee(base, ctx));
    }
    if let Some(base) = c.strip_suffix('*') {
        let is_const = base.trim_start().starts_with("const ");
        let q = if is_const { "*const" } else { "*mut" };
        return format!("{q} {}", pointee(base, ctx));
    }
    scalar(c, ctx).to_string()
}

/// The Rust type of a pointer's pointee (the base with any leading `const` stripped).
fn pointee(base: &str, ctx: &str) -> String {
    let b = base.trim();
    let b = b.strip_prefix("const ").unwrap_or(b).trim();
    scalar(b, ctx).to_string()
}

/// A bare (by-value) scalar / opaque-handle / enum C type -> Rust.
///
/// CUDA runtime types:
///   * **opaque handles** (`cudaStream_t`, `cudaEvent_t`) are `void*`-shaped → `*mut c_void`;
///   * **`cudaError_t` + `enum cudaMemcpyKind`** are `int`-sized enums → `i32`;
///   * **`dim3`** is a by-value `{u32,u32,u32}` struct → `crate::runtime::Dim3` (repr(C));
///   * **opaque structs only seen behind a pointer** (`cudaDeviceProp`, `cudaFuncAttributes`) →
///     `c_void` (so `cudaDeviceProp*` becomes `*mut c_void`), plus the plain C scalars.
fn scalar(c: &str, ctx: &str) -> &'static str {
    let c = c.strip_prefix("struct ").unwrap_or(c).trim();
    let c = c.strip_prefix("enum ").unwrap_or(c).trim();
    match c {
        "void" => "core::ffi::c_void", // only meaningful as a pointee; bare `void` -> map_ret == None
        "char" => "core::ffi::c_char",
        "float" => "f32",
        "int" | "cudaError_t" | "cudaMemcpyKind" => "i32",
        "unsigned char" => "u8",
        "unsigned int" => "u32",
        "unsigned long long" => "u64",
        "size_t" => "usize",
        // opaque runtime handles (all `void*`-shaped)
        "cudaStream_t" | "cudaEvent_t" => "*mut core::ffi::c_void",
        // by-value dim3 (three unsigned ints)
        "dim3" => "crate::runtime::Dim3",
        // opaque structs only ever referenced through a pointer -> treat pointee as c_void
        "cudaDeviceProp" | "cudaFuncAttributes" => "core::ffi::c_void",
        other => panic!("unmapped C base type {other:?} (in {ctx}); extend scalar() in build.rs"),
    }
}

fn default_for(rust_ty: &str) -> &'static str {
    if rust_ty.starts_with("*const") {
        "core::ptr::null()"
    } else if rust_ty.starts_with("*mut") {
        "core::ptr::null_mut()"
    } else {
        // For a `cudaError_t`/`i32`/`u32` return this is 0 (== `cudaSuccess`) — a benign "did nothing,
        // ok" default so an app keeps running while the entry point is still a stub.
        "0"
    }
}

fn sanitize(name: &str, i: usize) -> String {
    const KW: &[&str] = &[
        "type", "ref", "box", "in", "fn", "let", "match", "move", "mut", "as", "impl", "loop",
        "where", "self", "final", "override", "become",
    ];
    if name.is_empty() {
        return format!("a{i}");
    }
    if KW.contains(&name) {
        return format!("{name}_");
    }
    name.to_string()
}

fn env(k: &str) -> String {
    std::env::var(k).unwrap_or_else(|_| panic!("env {k} not set"))
}

/// Entry points hand-implemented in `src/runtime.rs` (so the generator skips them to avoid duplicate
/// symbols). The WHOLE runtime surface has real bodies — each forwards to a `dd-shim-cuda` driver `cu*`
/// (the analogue of the C cudart shim calling into libcuda), so nothing is left as a generated stub.
const IMPLEMENTED: &[&str] = &[
    // ---- device management ----
    "cudaGetDeviceCount",
    "cudaSetDevice",
    "cudaGetDevice",
    "cudaDeviceSynchronize",
    "cudaGetDeviceProperties",
    "cudaGetDeviceProperties_v2",
    "cudaDeviceReset",
    "cudaThreadSynchronize",
    "cudaDeviceGetPCIBusId",
    // ---- error reporting + versions ----
    "cudaGetLastError",
    "cudaPeekAtLastError",
    "cudaGetErrorName",
    "cudaGetErrorString",
    "cudaDriverGetVersion",
    "cudaRuntimeGetVersion",
    // ---- memory ----
    "cudaMalloc",
    "cudaFree",
    "cudaMallocManaged",
    "cudaMallocHost",
    "cudaHostAlloc",
    "cudaFreeHost",
    "cudaHostGetDevicePointer",
    "cudaMemcpy",
    "cudaMemcpyAsync",
    "cudaMemset",
    "cudaMemsetAsync",
    "cudaMemGetInfo",
    // ---- streams ----
    "cudaStreamCreate",
    "cudaStreamCreateWithFlags",
    "cudaStreamDestroy",
    "cudaStreamSynchronize",
    "cudaStreamWaitEvent",
    "cudaStreamQuery",
    // ---- events ----
    "cudaEventCreate",
    "cudaEventCreateWithFlags",
    "cudaEventDestroy",
    "cudaEventRecord",
    "cudaEventSynchronize",
    "cudaEventElapsedTime",
    "cudaEventQuery",
    // ---- launch + function attributes ----
    "cudaLaunchKernel",
    "cudaFuncGetAttributes",
    // ---- nvcc compiler registration glue + <<<>>> call-config stack ----
    "__cudaRegisterFatBinary",
    "__cudaRegisterFatBinaryEnd",
    "__cudaUnregisterFatBinary",
    "__cudaRegisterFunction",
    "__cudaRegisterVar",
    "__cudaPushCallConfiguration",
    "__cudaPopCallConfiguration",
];
