//! Codegen for the guest `libEGL.so.1` shim: turn `registry/gles2_egl.manifest` into the complete
//! `#[no_mangle] extern "C"` `egl*` + `gl*` export surface (402 entry points).
//!
//! Every entry point NOT hand-written in `src/driver.rs` (`IMPLEMENTED` below) is emitted here as a
//! spec-faithful default stub: correct C-ABI signature (so the symbol resolves and the guest app links +
//! runs), a `HL_SHIM_DEBUG`-gated once-per-name trace, and a benign spec-default return (`0` / null).
//! Real bodies replace stubs without ever changing the exported surface. Mirrors the shipping
//! `hl-cuda/shim/cuda/build.rs` (the capability-inventory codegen of `hl-shim-gl` is dropped — this is
//! the transport-wired template).
//!
//! Also bakes the shared-object soname `libEGL.so.1` (the canonical GLES/EGL drop-in name; a GLES app
//! that `DT_NEEDED`s libGLESv2.so.2 resolves every `gl*` symbol here through the forwarding stub).

use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(BuildEnvironment::get("CARGO_MANIFEST_DIR")).join("registry/gles2_egl.manifest");
    println!("cargo:rerun-if-changed={}", manifest.display());
    println!("cargo:rerun-if-changed=build.rs");
    // `gles_client` is set by this script (never by the user) to select the libGLESv2 role; declare it so
    // the `unexpected_cfgs` lint stays quiet.
    println!("cargo:rustc-check-cfg=cfg(gles_client)");

    let text = std::fs::read_to_string(&manifest)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest.display()));

    emit_role_link_args();

    let mut out = String::new();
    out.push_str("// @generated by build.rs from registry/gles2_egl.manifest — DO NOT EDIT.\n\n");

    let mut gl = 0usize;
    let mut egl = 0usize;
    let mut stubs = 0usize;
    for (lineno, line) in text.lines().enumerate() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut f = line.split('\t');
        let lib = f.next().unwrap_or("");
        let name = f.next().unwrap_or("");
        let ret = f.next().unwrap_or("void");
        let params = f.next().unwrap_or("");
        if name.is_empty() {
            panic!("manifest line {}: empty name: {line:?}", lineno + 1);
        }
        match lib {
            "GL" => gl += 1,
            "EGL" => egl += 1,
            other => panic!("manifest line {}: unknown lib {other:?}", lineno + 1),
        }
        if IMPLEMENTED.contains(&name) {
            continue; // hand-written in src/driver.rs; a generated stub would collide.
        }
        stubs += 1;
        emit_stub(&mut out, lib, name, ret, params);
    }

    writeln!(out, "\n/// Total GLES2 entry points in the manifest.").unwrap();
    writeln!(out, "pub const GLES2_ENTRYPOINTS: usize = {gl};").unwrap();
    writeln!(out, "/// Total EGL entry points in the manifest.").unwrap();
    writeln!(out, "pub const EGL_ENTRYPOINTS: usize = {egl};").unwrap();
    writeln!(out, "/// Total exported entry points (the exported surface).").unwrap();
    writeln!(out, "pub const GLES_EGL_ENTRYPOINTS: usize = {};", gl + egl).unwrap();
    writeln!(out, "/// Entry points emitted as default stubs (not yet hand-implemented).").unwrap();
    writeln!(out, "pub const GENERATED_STUBS: usize = {stubs};").unwrap();
    writeln!(out, "/// Entry points with real hand-written bodies in `src/driver.rs`.").unwrap();
    writeln!(out, "pub const IMPLEMENTED_ENTRYPOINTS: usize = {};", IMPLEMENTED.len()).unwrap();

    let out_path = PathBuf::from(BuildEnvironment::get("OUT_DIR")).join("generated_entrypoints.rs");
    std::fs::write(&out_path, out).unwrap();
}

/// Emit the role-specific cdylib link args: this ONE crate is cross-built TWICE by the top-level
/// `hl-gl/build.rs` (once per output object), selected by `$HL_SHIM_ROLE`:
///
///   * `egl`  (default) → `libEGL.so.1`: OWNS the process-global `State` and exports the shared-state
///     accessor `hl_shim_state_ptr` + the `egl*` surface.
///   * `gles`           → `libGLESv2.so.2`: built with `cfg(gles_client)` so it has NO `State` of its own
///     and instead `DT_NEEDED`s `libEGL.so.1` (from `$HL_SHIM_EGL_LIBDIR`) to import `hl_shim_state_ptr`
///     — matching real Mesa's `libGLESv2`/`libEGL` split while keeping ONE shared context. Exports `gl*`.
///
/// Per-object export RESTRICTION is done at the SOURCE, not here: each `gl*`/`egl*` entry point is
/// `#[cfg_attr(<role>, no_mangle)]` (see `emit_stub` + `src/driver.rs`), so rustc's own cdylib export list
/// already contains only this object's half of the surface. Here we set only the soname / cfg / DT_NEEDED.
fn emit_role_link_args() {
    println!("cargo:rerun-if-env-changed=HL_SHIM_ROLE");
    println!("cargo:rerun-if-env-changed=HL_SHIM_EGL_LIBDIR");
    let role = std::env::var("HL_SHIM_ROLE").unwrap_or_else(|_| "egl".to_string());

    let soname = match role.as_str() {
        "gles" => {
            // libGLESv2.so.2: NO `hl_shim_state_ptr` of its own (it is imported from libEGL via DT_NEEDED).
            println!("cargo:rustc-cfg=gles_client");
            let libdir = std::env::var("HL_SHIM_EGL_LIBDIR").unwrap_or_else(|_| {
                panic!("HL_SHIM_ROLE=gles requires HL_SHIM_EGL_LIBDIR (dir holding the staged libEGL.so.1)")
            });
            // DT_NEEDED libEGL.so.1 (kept via --no-as-needed) so the imported shared-state accessor binds.
            println!("cargo:rustc-cdylib-link-arg=-L{libdir}");
            println!("cargo:rustc-cdylib-link-arg=-Wl,--no-as-needed");
            println!("cargo:rustc-cdylib-link-arg=-l:libEGL.so.1");
            println!("cargo:rustc-cdylib-link-arg=-Wl,--as-needed");
            "libGLESv2.so.2"
        }
        "egl" => "libEGL.so.1",
        other => panic!("unknown HL_SHIM_ROLE {other:?} (want `egl` or `gles`)"),
    };
    println!("cargo:rustc-cdylib-link-arg=-Wl,-soname,{soname}");
}

fn emit_stub(out: &mut String, lib: &str, name: &str, ret: &str, params: &str) {
    let mut sig = String::new();
    let mut argnames = Vec::new();
    if !params.is_empty() {
        for (i, p) in params.split(';').enumerate() {
            let (ty, pname) = p.split_once('|').unwrap_or_else(|| panic!("bad param {p:?} in {name}"));
            let rty = Binding::new(ty.trim(), name).rust_type();
            let pn = Signature::parameter(pname.trim(), i);
            if i > 0 {
                sig.push_str(", ");
            }
            write!(sig, "{pn}: {rty}").unwrap();
            argnames.push(pn);
        }
    }
    let rmap = Binding::new(ret.trim(), name).return_type();
    let arrow = rmap.as_ref().map(|r| format!(" -> {r}")).unwrap_or_default();
    let touch: String = argnames.iter().map(|a| format!("let _ = {a}; ")).collect();
    let body = match &rmap {
        None => format!("{touch}crate::stub::hit(\"{name}\");"),
        Some(r) => format!("{touch}crate::stub::hit(\"{name}\"); {}", Binding::default_value(r)),
    };
    // Export the symbol only from the object that OWNS this half of the surface: `gl*` from libGLESv2
    // (`cfg(gles_client)`), `egl*` from libEGL (`cfg(not(gles_client))`). The other object still COMPILES
    // the fn (so `eglGetProcAddress` can return its address) — it is just not `#[no_mangle]` there, so
    // rustc's cdylib export list omits it. This is what pins each `.so`'s exported dynsym set.
    let export_cfg = match lib {
        "GL" => "#[cfg_attr(gles_client, no_mangle)]",
        "EGL" => "#[cfg_attr(not(gles_client), no_mangle)]",
        other => panic!("emit_stub: unknown lib {other:?} for {name}"),
    };
    writeln!(out, "{export_cfg}\npub extern \"C\" fn {name}({sig}){arrow} {{ {body} }}\n").unwrap();
}

struct Binding<'a> {
    c: &'a str,
    context: &'a str,
}

impl<'a> Binding<'a> {
    fn new(c: &'a str, context: &'a str) -> Self {
        Self { c, context }
    }

    fn return_type(&self) -> Option<String> {
        if self.c == "void" {
            return None;
        }
        Some(self.rust_type())
    }

    fn rust_type(&self) -> String {
        let c = self.c.trim();
        if let Some(base) = c.strip_suffix("*const*") {
            return format!("*const *const {}", Self::pointee(base, self.context));
        }
        if let Some(base) = c.strip_suffix("**") {
            return format!("*mut *mut {}", Self::pointee(base, self.context));
        }
        if let Some(base) = c.strip_suffix('*') {
            let is_const = base.trim_start().starts_with("const ");
            let q = if is_const { "*const" } else { "*mut" };
            return format!("{q} {}", Self::pointee(base, self.context));
        }
        Self::scalar(c, self.context).to_string()
    }

    fn pointee(base: &str, context: &str) -> String {
        let b = base.trim();
        let b = b.strip_prefix("const ").unwrap_or(b).trim();
        Self::scalar(b, context).to_string()
    }

    /// A bare (by-value) scalar / opaque-handle C type -> Rust C-ABI type. Opaque handles (`EGLDisplay`,
    /// `GLsync`, `EGLConfig`, …) are `void*`-shaped, so a value-of-that-type is a `*mut c_void`. Panics on an
    /// unknown base type so an API bump surfaces at build time rather than silently mis-typing the ABI.
    fn scalar(c: &str, context: &str) -> &'static str {
        match c {
            "void" => "core::ffi::c_void", // only meaningful as a pointee; bare `void` -> map_ret == None
            "char" | "GLchar" => "core::ffi::c_char",
            "GLbyte" => "i8",
            "GLubyte" | "GLboolean" => "u8",
            "GLshort" => "i16",
            "GLushort" => "u16",
            "GLenum" | "GLbitfield" | "GLuint" | "EGLenum" | "EGLBoolean" => "u32",
            "GLint" | "GLsizei" | "GLfixed" | "EGLint" => "i32",
            "GLfloat" | "GLclampf" => "f32",
            "GLdouble" => "f64",
            "GLint64" => "i64",
            "GLuint64" | "EGLTime" | "EGLTimeKHR" | "EGLuint64KHR" => "u64",
            "GLintptr" | "GLsizeiptr" | "EGLAttrib" => "isize",
            // opaque handles (all `void*`-shaped)
            "GLsync" | "GLDEBUGPROC" | "EGLClientBuffer" | "EGLContext" | "EGLDisplay" | "EGLImage"
            | "EGLImageKHR" | "EGLSurface" | "EGLSync" | "EGLSyncKHR" | "EGLConfig"
            | "EGLNativeDisplayType" | "EGLNativeWindowType" | "EGLNativePixmapType"
            | "__eglMustCastToProperFunctionPointerType" => "*mut core::ffi::c_void",
            other => panic!("unmapped C base type {other:?} (in {context}); extend scalar() in build.rs"),
        }
    }

    fn default_value(rust_ty: &str) -> &'static str {
        if rust_ty.starts_with("*const") {
            "core::ptr::null()"
        } else if rust_ty.starts_with("*mut") {
            "core::ptr::null_mut()"
        } else {
            "0" // spec default: GL_NO_ERROR / EGL_FALSE / 0 handle — a stub performs no work.
        }
    }
}

struct Signature;
impl Signature {
    fn parameter(name: &str, i: usize) -> String {
        const KW: &[&str] = &[
            "type", "ref", "box", "in", "fn", "let", "match", "move", "mut", "as", "impl", "loop",
            "where", "self", "final", "override", "become",
        ];
        if name.is_empty() {
            return format!("a{i}");
        }
        if KW.contains(&name) {
            return format!("{name}_");
        }
        name.to_string()
    }
}

struct BuildEnvironment;
impl BuildEnvironment {
    fn get(k: &str) -> String {
        std::env::var(k).unwrap_or_else(|_| panic!("env {k} not set"))
    }
}

/// Entry points hand-written in `src/driver.rs` (the generator skips them to avoid duplicate symbols):
/// the EGL bring-up/lifecycle (display/config/context/surface + present) and the GLES core render set
/// (buffer/texture/shader/program creation + draw recording + the queries a probe needs) that marshals
/// the C ABI and calls the `hl_gl` lowering services, flushing the frame IR through the process-global
/// RemoteCommandSink at `eglSwapBuffers`.
const IMPLEMENTED: &[&str] = &[
    // ---- EGL: display / config / context / surface lifecycle + present ----
    "eglGetError",
    "eglGetDisplay",
    "eglInitialize",
    "eglTerminate",
    "eglQueryString",
    "eglGetProcAddress",
    "eglBindAPI",
    "eglChooseConfig",
    "eglGetConfigs",
    "eglGetConfigAttrib",
    "eglCreateContext",
    "eglDestroyContext",
    "eglMakeCurrent",
    "eglCreateWindowSurface",
    "eglDestroySurface",
    "eglSwapBuffers",
    "eglSwapInterval",
    "eglGetCurrentDisplay",
    "eglGetCurrentContext",
    "eglGetCurrentSurface",
    // ---- GLES: error / string ----
    "glGetError",
    "glGetString",
    "glGetStringi",
    // ---- GLES: state / capability queries (glGet*) + pixel store ----
    "glGetIntegerv",
    "glGetFloatv",
    "glGetBooleanv",
    "glPixelStorei",
    // ---- GLES: shader / program introspection (status + reflection lookups) ----
    "glGetShaderiv",
    "glGetProgramiv",
    "glGetShaderInfoLog",
    "glGetProgramInfoLog",
    "glGetUniformLocation",
    "glGetAttribLocation",
    "glBindAttribLocation",
    "glGetActiveUniform",
    "glGetActiveAttrib",
    // ---- GLES: buffers ----
    "glGenBuffers",
    "glBindBuffer",
    "glBufferData",
    "glBufferSubData",
    "glDeleteBuffers",
    // ---- GLES: textures ----
    "glGenTextures",
    "glActiveTexture",
    "glBindTexture",
    "glTexImage2D",
    "glTexParameteri",
    "glTexParameterf",
    "glTexParameterfv",
    "glTexParameteriv",
    "glGenerateMipmap",
    "glDeleteTextures",
    // ---- GLES: shaders + programs ----
    "glCreateShader",
    "glShaderSource",
    "glCompileShader",
    "glCreateProgram",
    "glAttachShader",
    "glLinkProgram",
    "glUseProgram",
    // ---- GLES: uniforms (record into the bound program's uniform block, shipped at binding 1) ----
    "glUniform1i",
    "glUniform2i",
    "glUniform3i",
    "glUniform4i",
    "glUniform1iv",
    "glUniform2iv",
    "glUniform3iv",
    "glUniform4iv",
    "glUniform1f",
    "glUniform2f",
    "glUniform3f",
    "glUniform4f",
    "glUniform1fv",
    "glUniform2fv",
    "glUniform3fv",
    "glUniform4fv",
    "glUniformMatrix2fv",
    "glUniformMatrix3fv",
    "glUniformMatrix4fv",
    // ---- GLES: vertex attributes + fixed-function state ----
    "glVertexAttribPointer",
    "glEnableVertexAttribArray",
    "glDisableVertexAttribArray",
    "glVertexAttribDivisor",
    "glClearColor",
    "glClearDepthf",
    "glViewport",
    "glScissor",
    "glEnable",
    "glDisable",
    "glBlendFunc",
    "glBlendFuncSeparate",
    "glDepthFunc",
    "glDepthMask",
    "glCullFace",
    "glFrontFace",
    // ---- GLES: draw recording (frame draw-list; IR lowered at eglSwapBuffers) ----
    "glClear",
    "glDrawArrays",
    "glDrawElements",
    "glDrawArraysInstanced",
    "glDrawElementsInstanced",
    // ---- GLES: vertex array objects (GLES3 requires a bound VAO to draw) ----
    "glGenVertexArrays",
    "glBindVertexArray",
    "glDeleteVertexArrays",
    "glIsVertexArray",
    // ---- GLES: framebuffer + renderbuffer objects (offscreen render targets) ----
    "glGenFramebuffers",
    "glBindFramebuffer",
    "glDeleteFramebuffers",
    "glIsFramebuffer",
    "glCheckFramebufferStatus",
    "glFramebufferTexture2D",
    "glGenRenderbuffers",
    "glBindRenderbuffer",
    "glDeleteRenderbuffers",
    "glIsRenderbuffer",
    "glRenderbufferStorage",
    "glFramebufferRenderbuffer",
    "glBlitFramebuffer",
    // ---- GLES: readback (device→host; render + CopyTextureToBuffer + read_buffer) ----
    "glReadPixels",
    // ---- GLES3.1: compute dispatch (compute program → CreateComputePipeline + Dispatch) ----
    "glDispatchCompute",
    "glDispatchComputeIndirect",
    // ---- GLES3.0: sync objects (GLsync) over the IR fence timeline ----
    "glFenceSync",
    "glClientWaitSync",
    "glWaitSync",
    "glDeleteSync",
    "glIsSync",
    "glGetSynciv",
    // ---- GLES3.0: indexed buffer bindings (UBO/SSBO feeding bind groups) ----
    "glBindBufferBase",
    "glBindBufferRange",
    // ---- GLES3.0: PBO-style buffer mapping (host staging flushed on unmap as WriteBuffer) ----
    "glMapBufferRange",
    "glUnmapBuffer",
    "glFlushMappedBufferRange",
    // ---- GLES3.0: MRT draw/read buffer selection ----
    "glDrawBuffers",
    "glReadBuffer",
    // ---- GLES3.0: sampler objects (client-side sampler state; glGetSamplerParameter* round-trip) ----
    "glGenSamplers",
    "glDeleteSamplers",
    "glBindSampler",
    "glIsSampler",
    "glSamplerParameteri",
    "glSamplerParameterf",
    "glSamplerParameteriv",
    "glSamplerParameterfv",
    "glSamplerParameterIiv",
    "glSamplerParameterIuiv",
    "glGetSamplerParameteriv",
    "glGetSamplerParameterfv",
    "glGetSamplerParameterIiv",
    "glGetSamplerParameterIuiv",
    // ---- GLES3.0: occlusion / transform-feedback query objects (typed begin/end lifecycle) ----
    "glGenQueries",
    "glDeleteQueries",
    "glBeginQuery",
    "glEndQuery",
    "glIsQuery",
    "glGetQueryiv",
    "glGetQueryObjectuiv",
    // ---- GLES3.0: transform-feedback objects (begin/end/pause/resume + varying capture) ----
    "glGenTransformFeedbacks",
    "glDeleteTransformFeedbacks",
    "glBindTransformFeedback",
    "glIsTransformFeedback",
    "glBeginTransformFeedback",
    "glEndTransformFeedback",
    "glPauseTransformFeedback",
    "glResumeTransformFeedback",
    "glTransformFeedbackVaryings",
    "glGetTransformFeedbackVarying",
    // ---- GLES3.1: separate-shader program pipeline objects ----
    "glGenProgramPipelines",
    "glDeleteProgramPipelines",
    "glBindProgramPipeline",
    "glIsProgramPipeline",
    "glUseProgramStages",
    "glActiveShaderProgram",
    "glProgramParameteri",
    "glGetProgramPipelineiv",
    "glGetProgramPipelineInfoLog",
    "glValidateProgramPipeline",
    "glCreateShaderProgramv",
    // ---- GLES3.0: immutable texture storage + 3D / sub-image / copy uploads ----
    "glTexStorage2D",
    "glTexStorage3D",
    "glTexImage3D",
    "glTexSubImage2D",
    "glTexSubImage3D",
    "glCopyTexSubImage2D",
    "glCopyTexSubImage3D",
    "glCopyTexImage2D",
    "glCompressedTexImage2D",
    "glCompressedTexImage3D",
    "glCompressedTexSubImage2D",
    "glCompressedTexSubImage3D",
    // ---- GLES3.0: buffer / texture / vertex-attribute state queries ----
    "glGetBufferParameteriv",
    "glGetBufferParameteri64v",
    "glGetTexParameteriv",
    "glGetTexParameterfv",
    "glGetTexParameterIiv",
    "glGetTexParameterIuiv",
    "glGetVertexAttribfv",
    "glGetVertexAttribiv",
    "glGetVertexAttribIiv",
    "glGetVertexAttribIuiv",
    "glGetVertexAttribPointerv",
    // ---- GLES3.0: buffer-to-buffer copy + bounded readback ----
    "glCopyBufferSubData",
    "glReadnPixels",
    // ---- GLES3.0: constant generic vertex attributes + integer attribute arrays ----
    "glVertexAttrib1f",
    "glVertexAttrib2f",
    "glVertexAttrib3f",
    "glVertexAttrib4f",
    "glVertexAttrib1fv",
    "glVertexAttrib2fv",
    "glVertexAttrib3fv",
    "glVertexAttrib4fv",
    "glVertexAttribI4i",
    "glVertexAttribI4ui",
    "glVertexAttribI4iv",
    "glVertexAttribI4uiv",
    "glVertexAttribIPointer",
    "glVertexAttribIFormat",
    // ---- GLES3.0: framebuffer-attachment invalidation hints + separate-face stencil (IR-free) ----
    "glInvalidateFramebuffer",
    "glInvalidateSubFramebuffer",
    "glStencilFuncSeparate",
    "glStencilMaskSeparate",
    "glStencilOpSeparate",
    // ---- ES3 / GLES3.1 completeness pass (real bodies in driver.rs) ----
    "glBindImageTexture",
    "glBindVertexBuffer",
    "glBlendBarrier",
    "glBlendColor",
    "glBlendEquation",
    "glBlendEquationSeparate",
    "glBlendEquationSeparatei",
    "glBlendEquationi",
    "glBlendFuncSeparatei",
    "glBlendFunci",
    "glClearBufferfi",
    "glClearBufferfv",
    "glClearBufferiv",
    "glClearBufferuiv",
    "glClearStencil",
    "glColorMask",
    "glColorMaski",
    "glCopyImageSubData",
    "glDebugMessageCallback",
    "glDebugMessageControl",
    "glDebugMessageInsert",
    "glDeleteProgram",
    "glDeleteShader",
    "glDepthRangef",
    "glDetachShader",
    "glDisablei",
    "glDrawArraysIndirect",
    "glDrawElementsBaseVertex",
    "glDrawElementsIndirect",
    "glDrawElementsInstancedBaseVertex",
    "glDrawRangeElements",
    "glDrawRangeElementsBaseVertex",
    "glEnablei",
    "glFinish",
    "glFlush",
    "glFramebufferParameteri",
    "glFramebufferTexture",
    "glFramebufferTextureLayer",
    "glGetActiveUniformBlockName",
    "glGetActiveUniformBlockiv",
    "glGetActiveUniformsiv",
    "glGetAttachedShaders",
    "glGetBooleani_v",
    "glGetBufferPointerv",
    "glGetDebugMessageLog",
    "glGetFragDataLocation",
    "glGetFramebufferAttachmentParameteriv",
    "glGetFramebufferParameteriv",
    "glGetGraphicsResetStatus",
    "glGetInteger64i_v",
    "glGetInteger64v",
    "glGetIntegeri_v",
    "glGetInternalformativ",
    "glGetMultisamplefv",
    "glGetObjectLabel",
    "glGetObjectPtrLabel",
    "glGetPointerv",
    "glGetProgramBinary",
    "glGetProgramInterfaceiv",
    "glGetProgramResourceIndex",
    "glGetProgramResourceLocation",
    "glGetProgramResourceName",
    "glGetProgramResourceiv",
    "glGetRenderbufferParameteriv",
    "glGetShaderPrecisionFormat",
    "glGetShaderSource",
    "glGetTexLevelParameterfv",
    "glGetTexLevelParameteriv",
    "glGetUniformBlockIndex",
    "glGetUniformIndices",
    "glGetUniformfv",
    "glGetUniformiv",
    "glGetUniformuiv",
    "glGetnUniformfv",
    "glGetnUniformiv",
    "glGetnUniformuiv",
    "glHint",
    "glIsBuffer",
    "glIsEnabled",
    "glIsEnabledi",
    "glIsProgram",
    "glIsShader",
    "glIsTexture",
    "glLineWidth",
    "glMemoryBarrier",
    "glMemoryBarrierByRegion",
    "glMinSampleShading",
    "glObjectLabel",
    "glObjectPtrLabel",
    "glPatchParameteri",
    "glPolygonOffset",
    "glPopDebugGroup",
    "glPrimitiveBoundingBox",
    "glProgramBinary",
    "glProgramUniform1f",
    "glProgramUniform1fv",
    "glProgramUniform1i",
    "glProgramUniform1iv",
    "glProgramUniform1ui",
    "glProgramUniform1uiv",
    "glProgramUniform2f",
    "glProgramUniform2fv",
    "glProgramUniform2i",
    "glProgramUniform2iv",
    "glProgramUniform2ui",
    "glProgramUniform2uiv",
    "glProgramUniform3f",
    "glProgramUniform3fv",
    "glProgramUniform3i",
    "glProgramUniform3iv",
    "glProgramUniform3ui",
    "glProgramUniform3uiv",
    "glProgramUniform4f",
    "glProgramUniform4fv",
    "glProgramUniform4i",
    "glProgramUniform4iv",
    "glProgramUniform4ui",
    "glProgramUniform4uiv",
    "glProgramUniformMatrix2fv",
    "glProgramUniformMatrix2x3fv",
    "glProgramUniformMatrix2x4fv",
    "glProgramUniformMatrix3fv",
    "glProgramUniformMatrix3x2fv",
    "glProgramUniformMatrix3x4fv",
    "glProgramUniformMatrix4fv",
    "glProgramUniformMatrix4x2fv",
    "glProgramUniformMatrix4x3fv",
    "glPushDebugGroup",
    "glReleaseShaderCompiler",
    "glRenderbufferStorageMultisample",
    "glSampleCoverage",
    "glSampleMaski",
    "glShaderBinary",
    "glStencilFunc",
    "glStencilMask",
    "glStencilOp",
    "glTexBuffer",
    "glTexBufferRange",
    "glTexParameterIiv",
    "glTexParameterIuiv",
    "glTexStorage2DMultisample",
    "glTexStorage3DMultisample",
    "glUniform1ui",
    "glUniform1uiv",
    "glUniform2ui",
    "glUniform2uiv",
    "glUniform3ui",
    "glUniform3uiv",
    "glUniform4ui",
    "glUniform4uiv",
    "glUniformBlockBinding",
    "glUniformMatrix2x3fv",
    "glUniformMatrix2x4fv",
    "glUniformMatrix3x2fv",
    "glUniformMatrix3x4fv",
    "glUniformMatrix4x2fv",
    "glUniformMatrix4x3fv",
    "glValidateProgram",
    "glVertexAttribBinding",
    "glVertexAttribFormat",
    "glVertexBindingDivisor",
    // ---- EGL: remaining lifecycle / query / sync / image / surface creation ----
    "eglBindTexImage",
    "eglClientWaitSync",
    "eglCopyBuffers",
    "eglCreateImage",
    "eglCreatePbufferFromClientBuffer",
    "eglCreatePbufferSurface",
    "eglCreatePixmapSurface",
    "eglCreatePlatformPixmapSurface",
    "eglCreatePlatformWindowSurface",
    "eglCreateSync",
    "eglDestroyImage",
    "eglDestroySync",
    "eglGetPlatformDisplay",
    "eglGetSyncAttrib",
    "eglQueryAPI",
    "eglQueryContext",
    "eglQuerySurface",
    "eglReleaseTexImage",
    "eglReleaseThread",
    "eglSurfaceAttrib",
    "eglWaitClient",
    "eglWaitGL",
    "eglWaitNative",
    "eglWaitSync",
];
