//! dd-shim-vk codegen: turn the Khronos-`vk.xml`-derived entry-point manifest into (a) the complete
//! set of `#[no_mangle] extern "C"` `vk*` exports the ICD must provide, and (b) a name→address
//! dispatch table the loader-facing `vk_icdGetInstanceProcAddr`/`vkGetInstanceProcAddr` resolve
//! against. Mirrors dd-shim-cuda/build.rs and dd-shim-gl/build.rs.
//!
//! Input:  `registry/vk_commands.manifest` (generated from vk.xml — see `registry/`).
//! Output: `$OUT_DIR/generated_entrypoints.rs`, `include!`d by `src/lib.rs`.
//!
//! For every command NOT hand-implemented in `src/` (`IMPLEMENTED` below), we emit a spec-faithful
//! *default* stub: correct C-ABI signature (so the loader/app resolves the symbol), a DD_SHIM_DEBUG
//! "unimplemented entry point" trace, and a benign default return (`VK_SUCCESS` = 0 for the `VkResult`
//! most Vulkan entry points return). Real bodies replace stubs incrementally without ever changing the
//! exported surface — the shrinking long tail, exactly like the GL/CUDA siblings.
//!
//! Manifest records: `T<TAB>type<TAB>kind` classify by-value types (so a bare param maps without
//! knowing every Vulkan type); `C<TAB>name<TAB>ret<TAB>params` are the commands. A pointer is a
//! pointer — every `*`-suffixed C type lowers to a `c_void` pointer regardless of pointee, so only
//! by-value types ever consult the T-table.
//!
//! Also sets the shared-object soname to `libvk_dd.so.1` (the ICD library the icd.json `library_path`
//! names).

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env("CARGO_MANIFEST_DIR")).join("registry/vk_commands.manifest");
    println!("cargo:rerun-if-changed={}", manifest.display());
    println!("cargo:rerun-if-changed=build.rs");
    // The soname is the deployed Linux guest ICD name. `-Wl,-soname` is a GNU-ld flag; macOS `ld`
    // rejects it (it uses `-install_name`). The ICD only ships on the guest (Linux), and the macOS
    // build exists solely for the on-Metal validation tests (which link the rlib), so only emit the
    // soname link-arg on Linux — otherwise the cdylib fails to link on the test host.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("linux") {
        println!("cargo:rustc-cdylib-link-arg=-Wl,-soname,libvk_dd.so.1");
    }

    let text = std::fs::read_to_string(&manifest)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest.display()));

    // Pass 1: the by-value type classification table.
    let mut kinds: HashMap<String, String> = HashMap::new();
    for line in text.lines() {
        let line = line.trim_end();
        if !line.starts_with("T\t") {
            continue;
        }
        let mut f = line.split('\t');
        f.next();
        let name = f.next().unwrap_or("");
        let kind = f.next().unwrap_or("");
        kinds.insert(name.to_string(), kind.to_string());
    }

    // Pass 2: emit the C-ABI stub for every non-IMPLEMENTED command, and a dispatch entry for all.
    let mut out = String::new();
    out.push_str("// @generated by build.rs from registry/vk_commands.manifest — DO NOT EDIT.\n");
    out.push_str("// (crate-level `#![allow(non_snake_case, ...)]` lives in src/lib.rs.)\n\n");

    let mut cmds = 0usize;
    let mut stubs = 0usize;
    let mut dispatch = String::new();
    let mut names = String::new();
    for (lineno, line) in text.lines().enumerate() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') || line.starts_with("T\t") {
            continue;
        }
        let mut f = line.split('\t');
        let rec = f.next().unwrap_or("");
        if rec != "C" {
            panic!("manifest line {}: unknown record {rec:?}", lineno + 1);
        }
        let name = f.next().unwrap_or("");
        let ret = f.next().unwrap_or("void");
        let params = f.next().unwrap_or("");
        if name.is_empty() {
            panic!("manifest line {}: empty name: {line:?}", lineno + 1);
        }
        cmds += 1;
        // Every exported entry point — hand-written or generated — is resolvable at crate root by its
        // bare name (implemented ones via `pub use` in lib.rs), so the dispatch resolver references
        // them uniformly. The fn-item→address cast (`as *const () as usize`) must run at RUNTIME (a
        // `static` of it fails const-eval: pointers have no integer value at compile time), so we emit
        // a match function rather than a table.
        writeln!(dispatch, "        \"{name}\" => Some({name} as *const () as usize),").unwrap();
        writeln!(names, "    \"{name}\",").unwrap();
        if IMPLEMENTED.contains(&name) {
            continue; // hand-written in src/; a generated stub would collide.
        }
        stubs += 1;
        emit_stub(&mut out, name, ret, params, &kinds);
    }

    writeln!(out, "\n/// Total Vulkan entry points in the manifest (the full vk.xml surface).").unwrap();
    writeln!(out, "pub const VK_ENTRYPOINTS: usize = {cmds};").unwrap();
    writeln!(out, "/// Entry points emitted as default stubs (not yet hand-implemented).").unwrap();
    writeln!(out, "pub const GENERATED_STUBS: usize = {stubs};").unwrap();

    // The name→address resolver `vk_icdGetInstanceProcAddr` / `vkGetInstanceProcAddr` scan. A match
    // over the whole exported `vk*` surface; the address cast runs at call time (see above).
    writeln!(out, "\n/// Resolve any exported `vk*` entry point by name to its address. Consulted by the").unwrap();
    writeln!(out, "/// loader-facing proc-addr resolvers in `crate::icd`. Runtime cast (not a const table).").unwrap();
    writeln!(out, "pub fn dispatch_addr(name: &str) -> Option<usize> {{\n    match name {{\n{dispatch}        _ => None,\n    }}\n}}").unwrap();
    // A name-only census the surface tests can iterate without taking any addresses.
    writeln!(out, "\n/// Every exported `vk*` entry-point name (the completeness census list).").unwrap();
    writeln!(out, "pub static DISPATCH_NAMES: &[&str] = &[\n{names}];", names = names).unwrap();

    let out_path = PathBuf::from(env("OUT_DIR")).join("generated_entrypoints.rs");
    std::fs::write(&out_path, out).unwrap();
}

fn emit_stub(out: &mut String, name: &str, ret: &str, params: &str, kinds: &HashMap<String, String>) {
    let mut sig = String::new();
    let mut argnames: Vec<String> = Vec::new();
    if !params.is_empty() {
        for (i, p) in params.split(';').enumerate() {
            let (ty, pname) = p.split_once('|').unwrap_or_else(|| panic!("bad param {p:?} in {name}"));
            let rty = map_type(ty.trim(), name, kinds);
            let mut pn = sanitize(pname.trim(), i);
            // Guarantee unique parameter identifiers (Rust rejects duplicates); a manifest can carry
            // repeated names across api-variant params. Names are cosmetic — the ABI is unaffected.
            while argnames.contains(&pn) {
                pn.push_str(&format!("_{i}"));
            }
            if i > 0 {
                sig.push_str(", ");
            }
            write!(sig, "{pn}: {rty}").unwrap();
            argnames.push(pn);
        }
    }
    let rmap = map_ret(ret.trim(), name, kinds);
    let arrow = rmap.as_ref().map(|r| format!(" -> {r}")).unwrap_or_default();
    let touch: String = argnames.iter().map(|a| format!("let _ = {a}; ")).collect();
    let body = match &rmap {
        None => format!("{touch}crate::stub::hit(\"{name}\");"),
        Some(r) => {
            let dflt = default_for(r);
            format!("{touch}crate::stub::hit(\"{name}\"); {dflt}")
        }
    };
    writeln!(out, "#[no_mangle]\npub extern \"C\" fn {name}({sig}){arrow} {{ {body} }}\n").unwrap();
}

/// C return type -> Rust type (None == `void`/unit). Most Vulkan entry points return `VkResult`
/// (an int-sized enum → `i32`); `vkGet*ProcAddr` return `PFN_vkVoidFunction` (a pointer).
fn map_ret(c: &str, ctx: &str, kinds: &HashMap<String, String>) -> Option<String> {
    if c == "void" {
        return None;
    }
    Some(map_type(c, ctx, kinds))
}

/// C type string -> Rust C-ABI type. Pointers (single/double, const/mut) lower to a `c_void` pointer
/// — a pointer is a pointer at the ABI, so the pointee is irrelevant for a stub's signature. Only a
/// bare by-value type consults the T-table (fail-loud on an unclassified base type). Same structure
/// as the GL/CUDA generators.
fn map_type(c: &str, ctx: &str, kinds: &HashMap<String, String>) -> String {
    let c = c.trim();
    if c.ends_with("*const*") || c.ends_with("* const*") {
        return "*const *const core::ffi::c_void".to_string();
    }
    if let Some(rest) = c.strip_suffix("**") {
        let is_const = rest.trim_start().starts_with("const ");
        return if is_const {
            "*const *const core::ffi::c_void".to_string()
        } else {
            "*mut *mut core::ffi::c_void".to_string()
        };
    }
    if let Some(rest) = c.strip_suffix('*') {
        let is_const = rest.trim_start().starts_with("const ");
        return if is_const {
            "*const core::ffi::c_void".to_string()
        } else {
            "*mut core::ffi::c_void".to_string()
        };
    }
    scalar(c, ctx, kinds).to_string()
}

/// A bare (by-value) Vulkan/C type -> its Rust C-ABI representation, via the vk.xml-derived T-table
/// (dispatchable handle → pointer, non-dispatchable handle → u64, enum → i32, bitmask → u32/u64,
/// funcptr → pointer) or a concrete scalar token. Fail-loud on anything unclassified so a registry
/// bump surfaces at build time rather than silently mis-typing the ABI.
fn scalar(c: &str, ctx: &str, kinds: &HashMap<String, String>) -> String {
    let base = c.strip_prefix("const ").unwrap_or(c).trim();
    let kind = kinds.get(base).map(String::as_str).unwrap_or(base);
    match kind {
        // T-table kinds
        "disp" | "funcptr" => "*mut core::ffi::c_void".to_string(),
        "nondisp" => "u64".to_string(),
        "enum" => "i32".to_string(),
        "enum64" => "i64".to_string(),
        "bitmask" => "u32".to_string(),
        "bitmask64" => "u64".to_string(),
        "struct" => panic!("by-value struct/union param {base:?} (in {ctx}); needs a real layout"),
        // concrete scalar tokens (from the T-table basetype resolution, or a plain C scalar)
        "void" => "core::ffi::c_void".to_string(),
        "char" => "core::ffi::c_char".to_string(),
        "i8" => "i8".to_string(),
        "i16" => "i16".to_string(),
        "i32" | "int" | "int32_t" => "i32".to_string(),
        "i64" | "int64_t" => "i64".to_string(),
        "u8" | "uint8_t" => "u8".to_string(),
        "u16" | "uint16_t" => "u16".to_string(),
        "u32" | "uint32_t" => "u32".to_string(),
        "u64" | "uint64_t" => "u64".to_string(),
        "usize" | "size_t" => "usize".to_string(),
        "f32" | "float" => "f32".to_string(),
        "f64" | "double" => "f64".to_string(),
        other => panic!("unmapped by-value type {other:?} (base {base:?} in {ctx}); extend build.rs"),
    }
}

fn default_for(rust_ty: &str) -> &'static str {
    if rust_ty.starts_with("*const") {
        "core::ptr::null()"
    } else if rust_ty.starts_with("*mut") {
        "core::ptr::null_mut()"
    } else {
        // For the `VkResult`/`i32` return this is `VK_SUCCESS` (0) — a benign "did nothing, ok"
        // default so an app keeps running while the entry point is still a stub (matches the siblings).
        "0"
    }
}

fn sanitize(name: &str, i: usize) -> String {
    const KW: &[&str] = &[
        "type", "ref", "box", "in", "fn", "let", "match", "move", "mut", "as", "impl", "loop",
        "where", "self", "final", "override", "become",
    ];
    if name.is_empty() {
        return format!("a{i}");
    }
    if KW.contains(&name) {
        return format!("{name}_");
    }
    name.to_string()
}

fn env(k: &str) -> String {
    std::env::var(k).unwrap_or_else(|_| panic!("env {k} not set"))
}

/// Entry points hand-implemented in `src/` (so the generator skips them to avoid duplicate symbols).
/// The **bring-up** set: the ICD proc-addr resolvers, instance + physical-device enumeration and
/// property queries (reporting the "dd Metal (Vulkan)" device), device + queue + command-pool
/// creation. Everything else in the vk.xml surface is a generated stub, ported incrementally.
/// Ported from Vulkan-Loader (ICD interface), MoltenVK (object model / property values), ash (types).
const IMPLEMENTED: &[&str] = &[
    // ---- proc-addr dispatch (icd.rs) ----
    "vkGetInstanceProcAddr",
    "vkGetDeviceProcAddr",
    // ---- global / instance-level (instance.rs) ----
    "vkEnumerateInstanceVersion",
    "vkEnumerateInstanceExtensionProperties",
    "vkEnumerateInstanceLayerProperties",
    "vkCreateInstance",
    "vkDestroyInstance",
    "vkEnumeratePhysicalDevices",
    "vkGetPhysicalDeviceProperties",
    "vkGetPhysicalDeviceFeatures",
    "vkGetPhysicalDeviceMemoryProperties",
    "vkGetPhysicalDeviceQueueFamilyProperties",
    "vkGetPhysicalDeviceFormatProperties",
    "vkEnumerateDeviceExtensionProperties",
    "vkEnumerateDeviceLayerProperties",
    // ---- device + queue + command pool (device.rs) ----
    "vkCreateDevice",
    "vkDestroyDevice",
    "vkGetDeviceQueue",
    "vkCreateCommandPool",
    "vkDestroyCommandPool",
    "vkAllocateCommandBuffers",
    "vkFreeCommandBuffers",
    // ---- increment 2: functional execution path (Vulkan -> dd-gpu IR -> host Metal seam) ----
    // memory + buffers + images (memory.rs)
    "vkCreateBuffer",
    "vkDestroyBuffer",
    "vkGetBufferMemoryRequirements",
    "vkGetImageMemoryRequirements",
    "vkAllocateMemory",
    "vkFreeMemory",
    "vkBindBufferMemory",
    "vkMapMemory",
    "vkUnmapMemory",
    "vkFlushMappedMemoryRanges",
    "vkInvalidateMappedMemoryRanges",
    "vkCreateImage",
    "vkDestroyImage",
    "vkBindImageMemory",
    "vkCreateImageView",
    "vkDestroyImageView",
    // shaders + pipelines + render pass (pipeline.rs)
    "vkCreateShaderModule",
    "vkDestroyShaderModule",
    "vkCreatePipelineLayout",
    "vkDestroyPipelineLayout",
    "vkCreateComputePipelines",
    "vkCreateGraphicsPipelines",
    "vkDestroyPipeline",
    "vkCreateRenderPass",
    "vkDestroyRenderPass",
    "vkCreateFramebuffer",
    "vkDestroyFramebuffer",
    // descriptors (descriptor.rs)
    "vkCreateDescriptorSetLayout",
    "vkDestroyDescriptorSetLayout",
    "vkCreateDescriptorPool",
    "vkDestroyDescriptorPool",
    "vkAllocateDescriptorSets",
    "vkFreeDescriptorSets",
    "vkUpdateDescriptorSets",
    // command buffers + submit + sync (command.rs)
    "vkBeginCommandBuffer",
    "vkEndCommandBuffer",
    "vkResetCommandBuffer",
    "vkResetCommandPool",
    "vkCmdBindPipeline",
    "vkCmdBindDescriptorSets",
    "vkCmdBindVertexBuffers",
    "vkCmdBindIndexBuffer",
    "vkCmdSetViewport",
    "vkCmdSetScissor",
    "vkCmdDispatch",
    "vkCmdBeginRenderPass",
    "vkCmdEndRenderPass",
    "vkCmdDraw",
    "vkCmdDrawIndexed",
    "vkCmdCopyBuffer",
    "vkQueueSubmit",
    "vkQueueWaitIdle",
    "vkDeviceWaitIdle",
    "vkCreateFence",
    "vkDestroyFence",
    "vkWaitForFences",
    "vkResetFences",
    "vkGetFenceStatus",
    "vkCreateSemaphore",
    "vkDestroySemaphore",
    // ---- increment 3: WSI + present (wsi.rs) — the vkcube-through-dd-shim-vk path ----
    "vkCreateWaylandSurfaceKHR",
    "vkDestroySurfaceKHR",
    "vkGetPhysicalDeviceWaylandPresentationSupportKHR",
    "vkGetPhysicalDeviceSurfaceSupportKHR",
    "vkGetPhysicalDeviceSurfaceCapabilitiesKHR",
    "vkGetPhysicalDeviceSurfaceFormatsKHR",
    "vkGetPhysicalDeviceSurfacePresentModesKHR",
    "vkCreateSwapchainKHR",
    "vkDestroySwapchainKHR",
    "vkGetSwapchainImagesKHR",
    "vkAcquireNextImageKHR",
    "vkQueuePresentKHR",
];
