file(STRINGS "${MANIFEST}" _rows)
foreach(_row IN LISTS _rows)
  if(_row MATCHES "^#")
    continue()
  endif()
  string(REPLACE "\t" ";" _fields "${_row}")
  list(GET _fields 2 _artifact)
  list(GET _fields 3 _expected_hash)
  list(GET _fields 4 _expected_size)
  list(GET _fields 6 _source_hash)
  list(GET _fields 7 _abi_hash)
  list(GET _fields 8 _recipe_hash)
  set(_path "${ROOT}/${_artifact}")
  if(NOT EXISTS "${_path}")
    message(FATAL_ERROR "missing prebuilt: ${_path}")
  endif()
  file(SHA256 "${_path}" _actual_hash)
  file(SIZE "${_path}" _actual_size)
  if(NOT _actual_hash STREQUAL _expected_hash OR NOT _actual_size EQUAL _expected_size)
    message(FATAL_ERROR "prebuilt drift: ${_artifact}")
  endif()
  list(GET _fields 0 _case)
  file(SHA256 "${ROOT}/source/${_case}.c" _actual_source)
  file(SHA256 "${ROOT}/source/abi.h" _actual_abi)
  file(SHA256 "${ROOT}/recipe.tsv" _actual_recipe)
  if(NOT _actual_source STREQUAL _source_hash
      OR NOT _actual_abi STREQUAL _abi_hash
      OR NOT _actual_recipe STREQUAL _recipe_hash)
    message(FATAL_ERROR "source or recipe drift: ${_case}")
  endif()
endforeach()
