import assert from 'node:assert/strict';
import fs from 'node:fs';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { CONTROL, KIND, Reader, encode } from '../../react/src/wire.js';

test('packaged CLI binds extension consent to ready identity before provider discovery', async (context) => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'husklet-mcp-extension-')); const socketPath = path.join(directory, 'host.sock');
  const digest = `sha256:${'d'.repeat(64)}`; const calls = []; let mismatch = false;
  const candidate = { name: 'workspace-manager', version: '1.0.0', image_digest: digest, requested: ['interface', 'container-read'], installed_image_digest: null };
  const host = net.createServer((socket) => { const reader = new Reader();
    socket.write(encode({ channel: CONTROL, kind: KIND.request, payload: { protocol: 1, extension: 'installer-agent', granted: ['workspace-read', 'extension-read', 'extension-control', 'extension-install', 'pane-observe'] } }));
    socket.on('data', (chunk) => { for (const frame of reader.take(chunk)) {
      if (frame.kind !== KIND.request || frame.channel === CONTROL) continue;
      calls.push(frame.payload); const call = frame.payload.call; let payload;
      if (call === 'workspace_info') payload = { reply: 'workspace', with: { name: 'dev' } };
      else if (call === 'extension_acquisition_start') payload = { reply: 'extension_acquisition_job', with: { job: 'job-1' } };
      else if (call === 'extension_acquisition_status') payload = { reply: 'extension_acquisition', with: { job: 'job-1', reference: 'registry.example/manager:latest', revision: 7, state: 'ready', progress: null, candidate, error: null } };
      else if (call === 'extension_install' || call === 'extension_update') payload = { reply: 'extension', with: { name: 'workspace-manager', image_digest: mismatch ? `sha256:${'e'.repeat(64)}` : digest, status: 'standby' } };
      else if (call === 'extension_enable') payload = { reply: 'done' };
      else if (call === 'pane_list') payload = { reply: 'panes', with: { panes: [{ slot: 'manager-pane', generation: 2, revision: 1, kind: 'surface', provider: { extension: 'workspace-manager', provider: 'main' }, tab: 'tools', title: 'Manager', focused: false }], truncated: false } };
      else throw new Error(`unexpected host call ${call}`);
      socket.write(encode({ channel: frame.channel, kind: KIND.response, payload }));
    } });
  });
  await new Promise((resolve, reject) => host.listen(socketPath, resolve).once('error', reject));
  const transport = new StdioClientTransport({ command: process.execPath, args: [path.resolve(import.meta.dirname, '../src/cli.js'), '--socket', socketPath, '--workspace', 'dev'], cwd: path.resolve(import.meta.dirname, '..'), stderr: 'pipe' });
  const client = new Client({ name: 'extension-lifecycle-test', version: '1' });
  context.after(async () => { await client.close(); await new Promise((resolve) => host.close(resolve)); fs.rmSync(directory, { recursive: true, force: true }); });
  await client.connect(transport);
  await client.callTool({ name: 'husklet_extension_acquire', arguments: { reference: 'registry.example/manager:latest', confirm: true } });
  const widened = await client.callTool({ name: 'husklet_extension_install', arguments: { job: 'job-1', revision: 7, granted: ['network-write'], confirm: true } });
  assert.equal(widened.isError, true); assert(!calls.some(({ call }) => call === 'extension_install'));
  const installed = JSON.parse((await client.callTool({ name: 'husklet_extension_install', arguments: { job: 'job-1', revision: 7, granted: ['interface'], confirm: true } })).content[0].text);
  assert.deepEqual({ name: installed.name, digest: installed.image_digest, job: installed.job, revision: installed.revision, grants: installed.consented_grants }, { name: 'workspace-manager', digest, job: 'job-1', revision: 7, grants: ['interface'] });
  mismatch = true;
  const bad = await client.callTool({ name: 'husklet_extension_update', arguments: { job: 'job-1', revision: 7, granted: ['interface'], confirm: true } });
  assert.equal(bad.isError, true); assert.match(bad.content[0].text, /does not match the observed candidate/);
  await client.callTool({ name: 'husklet_extension_enable', arguments: { name: installed.name, image_digest: installed.image_digest, confirm: true } });
  const inventory = JSON.parse((await client.callTool({ name: 'husklet_pane_list', arguments: {} })).content[0].text);
  assert.deepEqual(inventory.panes[0].provider, { extension: installed.name, provider: 'main' });
  assert.equal(calls.filter(({ call }) => call === 'extension_acquisition_status').length, 3);
});
