import assert from 'node:assert/strict';
import fs from 'node:fs';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { CONTROL, KIND, Reader, encode } from '../../react/src/wire.js';

test('packaged CLI promotes structured truncation and fails closed for unmarked inventories', async (context) => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'husklet-mcp-inventory-'));
  const socketPath = path.join(directory, 'host.sock');
  const executions = Array.from({ length: 205 }, (_, index) => ({ id: index.toString(16).padStart(32, '0'), container_id: 'c'.repeat(64), running: false, exit_code: 0, pid: 0, command: ['true'], user: 'root' }));
  const panes = Array.from({ length: 201 }, (_, index) => ({ slot: `pane-${index}`, generation: index, revision: 0, kind: 'terminal', provider: null, tab: 'tab', title: `Pane ${index}`, focused: index === 0 }));
  const host = net.createServer((socket) => { const reader = new Reader();
    socket.write(encode({ channel: CONTROL, kind: KIND.request, payload: { protocol: 1, extension: 'inventory-agent', granted: ['workspace-read', 'container-read', 'terminal-read', 'pane-observe'] } }));
    socket.on('data', (chunk) => { for (const frame of reader.take(chunk)) {
      if (frame.kind !== KIND.request || frame.channel === CONTROL) continue;
      let payload;
      if (frame.payload.call === 'workspace_info') payload = { reply: 'workspace', with: { name: 'dev' } };
      else if (frame.payload.call === 'workspace_list') payload = { reply: 'workspaces', with: Array.from({ length: 201 }, (_, index) => ({ name: `workspace-${index}`, status: 'stopped' })) };
      else if (frame.payload.call === 'execution_list') payload = { reply: 'executions', with: { executions, truncated: false } };
      else if (frame.payload.call === 'pane_list') payload = { reply: 'panes', with: { panes, truncated: false } };
      else throw new Error(`unexpected host call ${frame.payload.call}`);
      socket.write(encode({ channel: frame.channel, kind: KIND.response, payload }));
    } });
  });
  await new Promise((resolve, reject) => host.listen(socketPath, resolve).once('error', reject));
  const transport = new StdioClientTransport({ command: process.execPath, args: [path.resolve(import.meta.dirname, '../src/cli.js'), '--socket', socketPath, '--workspace', 'dev'], cwd: path.resolve(import.meta.dirname, '..'), stderr: 'pipe' });
  const client = new Client({ name: 'inventory-bounds-test', version: '1' });
  context.after(async () => { await client.close(); await new Promise((resolve) => host.close(resolve)); fs.rmSync(directory, { recursive: true, force: true }); });
  await client.connect(transport);
  const workspace = await client.callTool({ name: 'husklet_workspace_list', arguments: {} });
  assert.equal(workspace.isError, true); assert.match(workspace.content[0].text, /has no truncation metadata/);
  const execution = JSON.parse((await client.callTool({ name: 'husklet_execution_list', arguments: {} })).content[0].text);
  assert.equal(execution.executions.length, 200); assert.equal(execution.truncated, true);
  assert.equal(execution.executions[199].id, (199).toString(16).padStart(32, '0'));
  const pane = JSON.parse((await client.callTool({ name: 'husklet_pane_list', arguments: {} })).content[0].text);
  assert.equal(pane.panes.length, 200); assert.equal(pane.truncated, true); assert.equal(pane.panes[0].slot, 'pane-0');
});
