// hl/linux_abi/container -- virtual filesystem assembled from cohesive capability fragments.
#include "vfs/path_compose.h"
#include "vfs/namespace_transaction.c"
#include "vfs/path_runtime.c"
#include "vfs/namespace_transaction.c"
#include "vfs/mounts.c"
#include "vfs/process_maps.c"
#include "vfs/process_registry.c"
#include "vfs/process_directories.c"
#include "vfs/process_content.c"
#include "vfs/devices.c"
