//! Codegen for the guest `libnvidia-ml.so.1` shim: turn `registry/nvml.manifest` into the complete
//! `#[no_mangle] extern "C"` `nvml*` export surface (62 entry points), extracted from the clean-room
//! NVML oracle `hl-gpu/nvml/nvml_shim.c`.
//!
//! Every entry point NOT hand-written in `src/nvml.rs` (`IMPLEMENTED`) is emitted as a benign default
//! stub: correct C-ABI signature so the symbol resolves, a `HL_SHIM_DEBUG`-gated trace, and a benign
//! `NVML_SUCCESS` (0) return. Bakes the soname `libnvidia-ml.so.1`.

use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env("CARGO_MANIFEST_DIR")).join("registry/nvml.manifest");
    println!("cargo:rerun-if-changed={}", manifest.display());
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rustc-cdylib-link-arg=-Wl,-soname,libnvidia-ml.so.1");

    let text = std::fs::read_to_string(&manifest)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest.display()));

    let mut out = String::new();
    out.push_str("// @generated by build.rs from registry/nvml.manifest — DO NOT EDIT.\n\n");

    let mut nv = 0usize;
    let mut stubs = 0usize;
    for (lineno, line) in text.lines().enumerate() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut f = line.split('\t');
        let lib = f.next().unwrap_or("");
        let name = f.next().unwrap_or("");
        let ret = f.next().unwrap_or("void");
        let params = f.next().unwrap_or("");
        if name.is_empty() {
            panic!("manifest line {}: empty name: {line:?}", lineno + 1);
        }
        match lib {
            "NVML" => nv += 1,
            other => panic!("manifest line {}: unknown lib {other:?}", lineno + 1),
        }
        if IMPLEMENTED.contains(&name) {
            continue;
        }
        stubs += 1;
        emit_stub(&mut out, name, ret, params);
    }

    writeln!(out, "\n/// Total NVML entry points in the manifest (the exported surface).").unwrap();
    writeln!(out, "pub const NVML_ENTRYPOINTS: usize = {nv};").unwrap();
    writeln!(out, "/// Entry points emitted as default stubs (not yet hand-implemented).").unwrap();
    writeln!(out, "pub const GENERATED_STUBS: usize = {stubs};").unwrap();
    writeln!(out, "/// Entry points with real hand-written bodies in `src/nvml.rs`.").unwrap();
    writeln!(out, "pub const IMPLEMENTED_ENTRYPOINTS: usize = {};", IMPLEMENTED.len()).unwrap();

    let out_path = PathBuf::from(env("OUT_DIR")).join("generated_entrypoints.rs");
    std::fs::write(&out_path, out).unwrap();
}

fn emit_stub(out: &mut String, name: &str, ret: &str, params: &str) {
    let mut sig = String::new();
    let mut argnames = Vec::new();
    if !params.is_empty() {
        for (i, p) in params.split(';').enumerate() {
            let (ty, pname) = p.split_once('|').unwrap_or_else(|| panic!("bad param {p:?} in {name}"));
            let rty = map_type(ty.trim(), name);
            let pn = sanitize(pname.trim(), i);
            if i > 0 {
                sig.push_str(", ");
            }
            write!(sig, "{pn}: {rty}").unwrap();
            argnames.push(pn);
        }
    }
    let rmap = map_ret(ret.trim(), name);
    let arrow = rmap.as_ref().map(|r| format!(" -> {r}")).unwrap_or_default();
    let touch: String = argnames.iter().map(|a| format!("let _ = {a}; ")).collect();
    let body = match &rmap {
        None => format!("{touch}crate::stub::hit(\"{name}\");"),
        Some(r) => format!("{touch}crate::stub::hit(\"{name}\"); {}", default_for(r)),
    };
    writeln!(out, "#[no_mangle]\npub extern \"C\" fn {name}({sig}){arrow} {{ {body} }}\n").unwrap();
}

fn map_ret(c: &str, ctx: &str) -> Option<String> {
    if c == "void" {
        return None;
    }
    Some(map_type(c, ctx))
}

fn map_type(c: &str, ctx: &str) -> String {
    let c = c.trim();
    if let Some(base) = c.strip_suffix("**") {
        return format!("*mut *mut {}", pointee(base, ctx));
    }
    if let Some(base) = c.strip_suffix('*') {
        let is_const = base.trim_start().starts_with("const ");
        let q = if is_const { "*const" } else { "*mut" };
        return format!("{q} {}", pointee(base, ctx));
    }
    scalar(c, ctx).to_string()
}

fn pointee(base: &str, ctx: &str) -> String {
    let b = base.trim();
    let b = b.strip_prefix("const ").unwrap_or(b).trim();
    scalar(b, ctx).to_string()
}

fn scalar(c: &str, ctx: &str) -> &'static str {
    match c {
        "void" => "core::ffi::c_void",
        "char" => "core::ffi::c_char",
        "int" => "i32",
        "unsigned int" => "u32",
        "unsigned long long" => "u64",
        // nvmlReturn_t + the int-sized NVML enums.
        "nvmlReturn_t" | "nvmlTemperatureSensors_t" | "nvmlClockType_t" | "nvmlComputeMode_t"
        | "nvmlEnableState_t" | "nvmlBrandType_t" | "nvmlPstates_t" => "i32",
        // the opaque device handle (void*-shaped).
        "nvmlDevice_t" => "*mut core::ffi::c_void",
        // opaque info structs only ever referenced through a pointer.
        "nvmlMemory_t" | "nvmlMemory_v2_t" | "nvmlUtilization_t" | "nvmlPciInfo_t"
        | "nvmlProcessInfo_t" => "core::ffi::c_void",
        other => panic!("unmapped C base type {other:?} (in {ctx}); extend scalar() in nvml build.rs"),
    }
}

fn default_for(rust_ty: &str) -> &'static str {
    if rust_ty.starts_with("*const") {
        "core::ptr::null()"
    } else if rust_ty.starts_with("*mut") {
        "core::ptr::null_mut()"
    } else {
        "0" // NVML_SUCCESS for the nvmlReturn_t all entry points return.
    }
}

fn sanitize(name: &str, i: usize) -> String {
    const KW: &[&str] = &[
        "type", "ref", "box", "in", "fn", "let", "match", "move", "mut", "as", "impl", "loop",
        "where", "self", "final", "override", "become",
    ];
    if name.is_empty() {
        return format!("a{i}");
    }
    if KW.contains(&name) {
        return format!("{name}_");
    }
    name.to_string()
}

fn env(k: &str) -> String {
    std::env::var(k).unwrap_or_else(|_| panic!("env {k} not set"))
}

/// Every entry point is hand-written in `src/nvml.rs` (`GENERATED_STUBS == 0`): init/shutdown/error, the
/// system version queries, device enumeration + identity (name/uuid/serial/index/brand/arch/cc), memory +
/// utilization (from `HL_CUDA_VRAM*`), PCI info, sensors/clocks/power (modeled sane values), modes/states,
/// running-process queries (none), and the private `nvmlInternalGetExportTable` handshake. Genuinely
/// hardware-specific queries (fan speed, MIG, ext PCI info) return an honest `NVML_ERROR_NOT_SUPPORTED`.
const IMPLEMENTED: &[&str] = &[
    // init / shutdown / error
    "nvmlInit_v2",
    "nvmlInit",
    "nvmlInitWithFlags",
    "nvmlShutdown",
    "nvmlErrorString",
    // system version queries
    "nvmlSystemGetDriverVersion",
    "nvmlSystemGetNVMLVersion",
    "nvmlSystemGetCudaDriverVersion",
    "nvmlSystemGetCudaDriverVersion_v2",
    "nvmlSystemGetProcessName",
    // enumeration + handles
    "nvmlDeviceGetCount",
    "nvmlDeviceGetCount_v2",
    "nvmlDeviceGetHandleByIndex",
    "nvmlDeviceGetHandleByIndex_v2",
    "nvmlDeviceGetHandleByUUID",
    "nvmlDeviceGetHandleByPciBusId",
    "nvmlDeviceGetHandleByPciBusId_v2",
    // identity
    "nvmlDeviceGetName",
    "nvmlDeviceGetUUID",
    "nvmlDeviceGetSerial",
    "nvmlDeviceGetIndex",
    "nvmlDeviceGetMinorNumber",
    "nvmlDeviceGetBrand",
    "nvmlDeviceGetCudaComputeCapability",
    "nvmlDeviceGetArchitecture",
    "nvmlDeviceGetVbiosVersion",
    // memory + utilization
    "nvmlDeviceGetMemoryInfo",
    "nvmlDeviceGetMemoryInfo_v2",
    "nvmlDeviceGetUtilizationRates",
    "nvmlDeviceGetEncoderUtilization",
    "nvmlDeviceGetDecoderUtilization",
    // PCI info + link
    "nvmlDeviceGetPciInfo",
    "nvmlDeviceGetPciInfo_v2",
    "nvmlDeviceGetPciInfo_v3",
    "nvmlDeviceGetPciInfoExt",
    "nvmlDeviceGetCurrPcieLinkGeneration",
    "nvmlDeviceGetMaxPcieLinkGeneration",
    "nvmlDeviceGetCurrPcieLinkWidth",
    "nvmlDeviceGetMaxPcieLinkWidth",
    "nvmlDeviceGetMemoryBusWidth",
    "nvmlDeviceGetNumGpuCores",
    // sensors / clocks / power
    "nvmlDeviceGetTemperature",
    "nvmlDeviceGetTemperatureThreshold",
    "nvmlDeviceGetPowerUsage",
    "nvmlDeviceGetPowerManagementLimit",
    "nvmlDeviceGetEnforcedPowerLimit",
    "nvmlDeviceGetClockInfo",
    "nvmlDeviceGetMaxClockInfo",
    "nvmlDeviceGetFanSpeed",
    // modes / states
    "nvmlDeviceGetPersistenceMode",
    "nvmlDeviceGetDisplayMode",
    "nvmlDeviceGetComputeMode",
    "nvmlDeviceGetPerformanceState",
    "nvmlDeviceGetPowerState",
    "nvmlDeviceGetMigMode",
    // running processes
    "nvmlDeviceGetComputeRunningProcesses",
    "nvmlDeviceGetComputeRunningProcesses_v2",
    "nvmlDeviceGetComputeRunningProcesses_v3",
    "nvmlDeviceGetGraphicsRunningProcesses",
    "nvmlDeviceGetGraphicsRunningProcesses_v2",
    "nvmlDeviceGetGraphicsRunningProcesses_v3",
    // private export table
    "nvmlInternalGetExportTable",
];
