use super::*;

/// `maxVertexInputBindings`. Named because the pipeline path must refuse a binding number past what this
/// device advertises before it uses that number to place a vertex layout, and a second literal would
/// drift away from the advertised limit silently.
pub const MAX_VERTEX_INPUT_BINDINGS: u32 = 31;

pub(super) fn metal_limits() -> VkPhysicalDeviceLimits {
    let dim = 16384u32;
    // Keep the formatted-view ceiling conservative for the largest packed format (RGBA32 = 16 bytes)
    // under the checked 1-GiB host buffer cap. The executor binds the original packed buffer directly.
    let max_texel_buffer_elements = u32::try_from((1u64 << 30) / 16)
        .expect("the host texel-buffer ceiling fits VkPhysicalDeviceLimits");
    let per_stage_buffers = 31u32;
    let per_stage_samplers = 16u32;
    let per_stage_textures = 128u32;
    let per_stage_storage_images = 128u32;
    let per_stage_resources = per_stage_buffers + per_stage_textures; // 159
    let color_samples: VkFlags = 0x1 | 0x4; // TYPE_1 | TYPE_4
    let one_sample: VkFlags = 0x1;
    VkPhysicalDeviceLimits {
        max_image_dimension_1d: dim,
        max_image_dimension_2d: dim,
        max_image_dimension_3d: 2048,
        max_image_dimension_cube: dim,
        max_image_array_layers: 2048,
        max_texel_buffer_elements,
        max_uniform_buffer_range: 65536,
        max_storage_buffer_range: u32::MAX,
        max_push_constants_size: 4096,
        max_memory_allocation_count: 4096,
        max_sampler_allocation_count: 4096,
        buffer_image_granularity: 1,
        sparse_address_space_size: 0,
        max_bound_descriptor_sets: 8,
        max_per_stage_descriptor_samplers: per_stage_samplers,
        max_per_stage_descriptor_uniform_buffers: per_stage_buffers,
        max_per_stage_descriptor_storage_buffers: per_stage_buffers,
        max_per_stage_descriptor_sampled_images: per_stage_textures,
        max_per_stage_descriptor_storage_images: per_stage_storage_images,
        max_per_stage_descriptor_input_attachments: per_stage_textures,
        max_per_stage_resources: per_stage_resources,
        max_descriptor_set_samplers: per_stage_samplers * 5,
        max_descriptor_set_uniform_buffers: per_stage_buffers * 5,
        max_descriptor_set_uniform_buffers_dynamic: per_stage_buffers * 5,
        max_descriptor_set_storage_buffers: per_stage_buffers * 5,
        max_descriptor_set_storage_buffers_dynamic: per_stage_buffers * 5,
        max_descriptor_set_sampled_images: per_stage_textures * 5,
        max_descriptor_set_storage_images: per_stage_storage_images * 5,
        max_descriptor_set_input_attachments: per_stage_textures * 5,
        max_vertex_input_attributes: 31,
        max_vertex_input_bindings: MAX_VERTEX_INPUT_BINDINGS,
        max_vertex_input_attribute_offset: 4095,
        max_vertex_input_binding_stride: 4096,
        max_vertex_output_components: 124,
        max_tessellation_generation_level: 0,
        max_tessellation_patch_size: 0,
        max_tessellation_control_per_vertex_input_components: 0,
        max_tessellation_control_per_vertex_output_components: 0,
        max_tessellation_control_per_patch_output_components: 0,
        max_tessellation_control_total_output_components: 0,
        max_tessellation_evaluation_input_components: 0,
        max_tessellation_evaluation_output_components: 0,
        max_geometry_shader_invocations: 0,
        max_geometry_input_components: 0,
        max_geometry_output_components: 0,
        max_geometry_output_vertices: 0,
        max_geometry_total_output_components: 0,
        max_fragment_input_components: 124,
        max_fragment_output_attachments: 8,
        max_fragment_dual_src_attachments: 1,
        max_fragment_combined_output_resources: per_stage_resources,
        max_compute_shared_memory_size: 32768,
        max_compute_work_group_count: [65535, 65535, 65535],
        max_compute_work_group_invocations: 1024,
        max_compute_work_group_size: [1024, 1024, 1024],
        sub_pixel_precision_bits: 4,
        sub_texel_precision_bits: 4,
        mipmap_precision_bits: 4,
        max_draw_indexed_index_value: u32::MAX,
        max_draw_indirect_count: u32::MAX,
        max_sampler_lod_bias: 15.999,
        max_sampler_anisotropy: 16.0,
        max_viewports: 16,
        max_viewport_dimensions: [dim, dim],
        viewport_bounds_range: [-(2.0 * dim as f32), 2.0 * dim as f32 - 1.0],
        viewport_sub_pixel_bits: 0,
        min_memory_map_alignment: 256,
        min_texel_buffer_offset_alignment: 16,
        min_uniform_buffer_offset_alignment: 256,
        min_storage_buffer_offset_alignment: 16,
        min_texel_offset: -8,
        max_texel_offset: 7,
        min_texel_gather_offset: -8,
        max_texel_gather_offset: 7,
        min_interpolation_offset: -0.5,
        max_interpolation_offset: 0.5,
        sub_pixel_interpolation_offset_bits: 4,
        max_framebuffer_width: dim,
        max_framebuffer_height: dim,
        max_framebuffer_layers: 2048,
        framebuffer_color_sample_counts: color_samples,
        framebuffer_depth_sample_counts: color_samples,
        framebuffer_stencil_sample_counts: color_samples,
        framebuffer_no_attachments_sample_counts: color_samples,
        max_color_attachments: 8,
        sampled_image_color_sample_counts: color_samples,
        sampled_image_integer_sample_counts: one_sample,
        sampled_image_depth_sample_counts: color_samples,
        sampled_image_stencil_sample_counts: color_samples,
        storage_image_sample_counts: one_sample,
        max_sample_mask_words: 1,
        timestamp_compute_and_graphics: VK_TRUE,
        timestamp_period: 1.0,
        max_clip_distances: 8,
        max_cull_distances: 8,
        max_combined_clip_and_cull_distances: 8,
        discrete_queue_priorities: 2,
        point_size_range: [1.0, 511.0],
        line_width_range: [1.0, 1.0],
        point_size_granularity: 0.0,
        line_width_granularity: 0.0,
        strict_lines: VK_FALSE,
        standard_sample_locations: VK_TRUE,
        optimal_buffer_copy_offset_alignment: 256,
        optimal_buffer_copy_row_pitch_alignment: 1,
        non_coherent_atom_size: 256,
    }
}
