[package]
name = "hl-fake-host"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
hl-descriptor = { path = "../hl-descriptor" }
hl-isa = { path = "../hl-isa" }
hl-linux = { path = "../hl-linux" }
hl-memory = { path = "../hl-memory" }
hl-network = { path = "../hl-network" }
hl-provider = { path = "../hl-provider" }
hl-time = { path = "../hl-time" }
hl-vfs = { path = "../hl-vfs" }
