[package]
name = "hl-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
hl-aio = { path = "../hl-aio" }
hl-checkpoint = { path = "../hl-checkpoint" }
hl-descriptor = { path = "../hl-descriptor" }
hl-event = { path = "../hl-event" }
hl-linux = { path = "../hl-linux" }
hl-log = { path = "../../packages/hl-log" }
hl-loader = { path = "../hl-loader" }
hl-task = { path = "../hl-task" }
hl-memory = { path = "../hl-memory" }
hl-provider = { path = "../hl-provider" }
hl-network = { path = "../hl-network" }
hl-ipc = { path = "../hl-ipc" }
hl-vfs = { path = "../hl-vfs" }
hl-isa = { path = "../hl-isa" }
hl-time = { path = "../hl-time" }
hl-sync = { path = "../hl-sync" }
hl-terminal = { path = "../hl-terminal" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
hl-memory = { path = "../hl-memory", features = ["test-support"] }
